### ISSUE TITLE
CocoonJS and touch weirdness

### ISSUE THREAD

**Issue by wojciak** [GoodBoyDigital/pixi.js#1001]
Hi guys,

Wrapped into cocoonJS and the touch positions had wrong offsets (I had to click below-right a target sprite to click the actual sprite). So I went into pixi's code and found this repeating block:

if(navigator.isCocoonJS) {
     touchData.global.x = touchEvent.clientX;
     touchData.global.y = touchEvent.clientY;
}

After commenting these blocks out everything works as it should. 

Now is there a bigger picture behind this or can I create a pull request removing these lines (which look a bit hacky ;]).

Cheers!

**Comment by englercj** [comment]
This is pretty old, was this fixed in dev?

**Comment by heavymery** [comment]
Hey guys, `dev` seems to change significantly from `master`.
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/InteractionManager.js#L738-L798
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/interaction/InteractionManager.js#L575-L599

I'm using Pixi.js 2.1.7 with CocoonJS 2.1.1.1 (iOS 8.1.3).
But, it need to work around like below.

```js
//Support for CocoonJS fullscreen scale modes
touchData.global.x = touchEvent.clientX / this.resolution;
touchData.global.y = touchEvent.clientY / this.resolution;
```
This works fine for me :smiling_imp:

**Comment by JiDW** [comment]
Hello there,

I disagree with this commit, I reported this issue here :

https://github.com/GoodBoyDigital/pixi.js/issues/1374

This is a bug on CocoonJS side, they are aware of it and they will correct it.

The "fix" works for people who do not use a scale mode in cocoonjs but will break every code using a scale mode.

**Comment by englercj** [comment]
Oops reverted.

**Comment by JiDW** [comment]
Thanks ! :)

**Comment by heavymery** [comment]
>The "fix" works for people who use a scale mode in cocoonjs but will break every code not using a scale mode.

Oh, I didn't know that ! 
So that means, my workaround is useful only for people who use CocoonJS scale mode....
Thank you for pointing it out.

>This is a bug on CocoonJS side, they are aware of it and they will correct it.

I wish they can fix that, as soon as possible :smile:
