### ISSUE TITLE
RenderTexture ping-pong

### ISSUE THREAD

**Issue by ichitaro** [GoodBoyDigital/pixi.js#1022]
When accumulate any graphics over time while swapping double buffer of RenderTexture, the output image becomes yellow incrementally. This issue occurs when using WebGLRenderer.

http://codepen.io/ichitaro/pen/gifkw

**Comment by GoodBoyDigital** [comment]
Fixed in v3. We now upload a 32uint as the color so no more color degradation. Noice! :+1:
