### ISSUE TITLE
No way to know if AssetLoader completed if downloading any asset errors out

### ISSUE THREAD

**Issue by dprentis** [GoodBoyDigital/pixi.js#1033]
In a recent project we used pixi.js for rendering and ran into a problem with AssetLoader - namely, if not all of the preloaded assets are available for any reason and any request errors out, no event is triggered. It is therefore very difficult to handle this situation gracefully.

In the end we worked around the problem by first preloading with preload.js and then feeding only accessible assets into the AssetLoader.

Would be great to add some error handling though - I could try a PR, if you like.

**Comment by englercj** [comment]
Pretty sure this was fixed by merging #1274.
