### ISSUE TITLE
Some suggestions on adding children...

### ISSUE THREAD

**Issue by agamemnus** [GoodBoyDigital/pixi.js#1065]
I think it would be better if pixi just had the same naming and interface for adding and removing children as the DOM: insertBefore, appendChild, removeChild. addChildAt isn't very useful at all imo, and makes code very prone to breakdown... insertBefore is much more useful and makes less prone to breakdown.

Naming: I have enough things to remember without having to remember that pixi.js uses addChild and removeChild instead of appendChild and removeChild.

**Comment by englercj** [comment]
Closing, this is unproductive.
