### ISSUE TITLE
Maximum Graphics drawCircle() calls

### ISSUE THREAD

**Issue by aurbano** [GoodBoyDigital/pixi.js#1076]
I can't find the exact cause of this problem. When I render > ~850 circles on a Graphics object with `drawCircle()`, the next ones overlap the first ones and get joined by a strange line.

You can see an example here: http://urbanoalvarez.es/Nebula/pixi-circles.html

With `drawRect()` this **doesn't happen** though: http://urbanoalvarez.es/Nebula/index.html

Those circles are added here, on the file [`nebula-pixi.js`](https://github.com/aurbano/Nebula/blob/63a31991014a6cbbd0b51a76ac82722d7fc58d1c/src/nebula-pixi.js): 

* [`Line 207`](https://github.com/aurbano/Nebula/blob/63a31991014a6cbbd0b51a76ac82722d7fc58d1c/src/nebula-pixi.js#L207): Calling the function that adds the new circle
* [`Line 474`](https://github.com/aurbano/Nebula/blob/63a31991014a6cbbd0b51a76ac82722d7fc58d1c/src/nebula-pixi.js#L474): Drawing the actual circle

The strange part is that this only happens, as I said at the beginning, with more than ~850 nodes, when there are less everything works perfectly.

**Comment by bulkan** [comment]
I've hit this error too. 

Interestingly using webGL renderer with `drawRect` causes the browser to crash after ~5500 `drawRect` calls.

**Comment by luk-bertrand** [comment]
I observed the same issue here : http://jsfiddle.net/83w5m3xd/
Each tile create a graphicData. About 13108 entries, coordinates still correct but the shape come back to origin in a linear way (like for color).

**Comment by luk-bertrand** [comment]
ok, it's not a problem about length of array. We can see here the same issue with just some line of code : http://jsfiddle.net/bkzchuqc/

**Comment by GoodBoyDigital** [comment]
This has been address in v3. Should work like a champ as the batch's now get split if they are too large.
