### ISSUE TITLE
Guards against the texture crop?

### ISSUE THREAD

**Issue by Y08** [GoodBoyDigital/pixi.js#1082]
I found this change in dev-branch: 5029abd30dfb6004ab5bd481f6bf400ba3ffb615

This changes the behaviour when the sprite has visible children though its texture size is 0. It makes difference against _renderWebGL().

**Comment by englercj** [comment]
That is actually a good point, hadn't thought of it.

**Comment by GoodBoyDigital** [comment]
closing for now as this should be ok. cheers!
