### ISSUE TITLE
BlurFilter doesn't work when applied as a sprite shader

### ISSUE THREAD

**Issue by gordyr** [GoodBoyDigital/pixi.js#1089]
The BlurFilter doesn't work when applied as a sprite shader.  I assume this is because the BlurFilter fires off two passes (blurX, blurY)which if I am understanding correctly is not currently supported.

On a related note, is it not possible to allow multiple shaders to be run in this fashion?

I have switched everything over to the new shaders model quite simply because they are applied in a local coordinate space to the sprite.  Which for my purposes is exactly what I need.  However I also need to on occasion, apply several convolutions and a blur, also applied in the local coordinate space, which of course I currently cannot do with filters, leaving me a little stuck.

**Comment by englercj** [comment]
shaders do not have passes, they are a single shader that draws the object. BlurFilter actually has no shader code that runs, it is only those two passes so nothing shows up.

If you want local coord-space shaders there is another issue open for that: #1092
