### ISSUE TITLE
render.resize()  in webkit browsers when the height exceeds 3100px, the view gets distorted ( projection perhaps )

### ISSUE THREAD

**Issue by ourvice** [GoodBoyDigital/pixi.js#1091]
render.resize()  in webkit browsers when the height exceeds 3100px, the view gets distorted ( projection perhaps )

http://instrumentspeaks.weareinstrument.com/temp/

hit the link and resize browser from 2 up wide to mobile size on up width.

Thanks for your help, screams on mobile!~

Cheers

Destin

**Comment by englercj** [comment]
Closing since this isn't a pixi issue
