### ISSUE TITLE
I hope to add an interaction priority.

### ISSUE THREAD

**Issue by mrsions** [GoodBoyDigital/pixi.js#1096]
Sometimes certain objects to be the highest priority.

Have you ever could be added to the full version?

// Define Interactive Prioirty
PIXI.DisplayObject.prototype.priority = 0;

// Change rebuildInteractiveGraph
PIXI.InteractionManager.prototype.rebuildInteractiveGraph = function()
{
    this.dirty = false;

    var len = this.interactiveItems.length;

    for (var i = 0; i < len; i++) {
        this.interactiveItems[i].interactiveChildren = false;
    }

    this.interactiveItems = [];

    if(this.stage.interactive)this.interactiveItems.push(this.stage);
    // go through and collect all the objects that are interactive..
    this.collectInteractiveSprite(this.stage, this.stage);
    
    //-- This
    this.interactiveItems.sort(function(a,b){
    	return b.priority-a.priority;
    });
    
};

**Comment by GoodBoyDigital** [comment]
Hi @mrsions ,

We have just finished building the interactionManager for v3. We will not be adding priorities as we aiming to keep the API similar to the DOM. If enough people request this we can take another look. 

Cheers! :+1:
