### ISSUE TITLE
PIXI.blendModes.ADD not working correctly in WebGL with transparent background

### ISSUE THREAD

**Issue by D-Hartley** [GoodBoyDigital/pixi.js#1104]
Using v2.0 but also had this problem when using v1.6.

This applies if you have a transparent canvas with no solid display objects between the webpage and the blended children. (The children have transparent backgrounds).

If you alter the alpha of a display object while its blend mode is set to ADD you can see the objects bounds over the top of other children, as can be seen in the following image:
![add bug](https://cloud.githubusercontent.com/assets/9450160/4830062/f4a2c938-5f8a-11e4-9192-69b7572939de.jpg)

I have also made a pen to demonstrate the behaviour:
http://codepen.io/davidhartley/pen/oFbiL

This behaviour only applies to WebGL and not canvas and only seems to affect the ADD blend mode which makes me believe it is something to do with the destination alpha used in the WebGL render.

I am currently using PIXI.blendModes.SCREEN instead for the time being as this produces a similar effect to ADD but without this bug.

**Comment by GoodBoyDigital** [comment]
Hey there! Been looking into this and seems that theres not much that can be done with the ADD blend mode working correctly with transparency :/

Hopefully SCREEN will be good enough for you needs ?
