### ISSUE TITLE
"there are only 2 changes" ?

### ISSUE THREAD

**Issue by whizzkid** [GoodBoyDigital/pixi.js#1111]
There's more than 2 changes that might be worth a mention... (a 'whats new' doc would be nice by the way)

Polygon.points is no longer an array of points, but an array of numbers...  
Font rendering has changed, so your font positioning might be off (I had to move all my text down a few pixels)

there might be more, haven't encountered em yet.

**Comment by englercj** [comment]
README will be rewritten in v3
