### ISSUE TITLE
PIXI v 2.0 -  arc not drawing - & mouse event on button-2 (right button) not firing

### ISSUE THREAD

**Issue by AndreNel7** [GoodBoyDigital/pixi.js#1119]
1. The following code needs to be added - so drawing an arc won't throw an error:
pixi.dev.js line: 11500

PIXI.Graphics.prototype.arc = function(cx, cy, radius, startAngle, endAngle, anticlockwise)
{
    // line: 11500: Code to add ->
    if (this.currentPath)
    {
        if (this.currentPath.shape.points.length === 0) this.currentPath.shape.points = [0, 0];
    }
    else
    {
        this.moveTo(0, 0);
    }
    // <- Code to add

    var startX = cx + Math.cos(startAngle) * radius;
    var startY = cy + Math.sin(startAngle) * radius;
...

2. mouse event on button-2 not firing
-> "stage.mousedown" isn't even triggered on mouse-2 (right click) (but is triggered on mouse 1 & 3 - left & center buttons)

**Comment by englercj** [comment]
I can't seem to reproduce the error you describe. Do you have a test-case that shows this happening? I am able to call `.arc` without this code and it works fine.

**Comment by englercj** [comment]
Closing this since it has been 30 days with no response.
