### ISSUE TITLE
v2.0.0 displacementFilter multiple canvases

### ISSUE THREAD

**Issue by glafarge** [GoodBoyDigital/pixi.js#1122]
Unexpected result with DisplacementFilter when I have more than one canvas in page.

[![v1.6.1](https://cloud.githubusercontent.com/assets/670645/4919688/5a4a3660-64fc-11e4-8d29-2142884c5fad.jpg)](http://jsfiddle.net/glafarge/6h84bpnk/)

[![v2 0 0](https://cloud.githubusercontent.com/assets/670645/4919693/604b9446-64fc-11e4-8c31-c61bef59bf90.jpg)](http://jsfiddle.net/glafarge/6h84bpnk/1)

Two fiddles to compare : 
v1.6.1 : http://jsfiddle.net/glafarge/6h84bpnk/
v2.0.0 : http://jsfiddle.net/glafarge/6h84bpnk/1

**Comment by englercj** [comment]
This issue may be caused by #1238, hopefully this will be fixed in v3

**Comment by GoodBoyDigital** [comment]
Boom! works like a champ in v3!

**Comment by glafarge** [comment]
Thank you !! :)
