### ISSUE TITLE
It is not possible to crop a RenderTexture

### ISSUE THREAD

**Issue by GenericString** [GoodBoyDigital/pixi.js#1124]
new PIXI.Texture(rendertexture, new PIXI.Rectangle(0,0,100,100));
and
new PIXI.Texture(rendertexture.baseTexture, new PIXI.Rectangle(0,0,100,100));

both return a blank texture. I tried and the RenderTextures can be placed through a sprite on the canvas just fine. But trying to crop them with Texture() doesnt work at all.

Ive been on this for more than i'd like to admit, i didnt find a single way around this, even with the 1000 Pixi functions had (.trim, .crop, .setframe(), .frame, etc,..)

the only hack i found is
var texture = PIXI.Texture.fromCanvas(rendertexture.getCanvas());
But that doesnt work either since it tints the image full #fff white.

Am i missing something? Could someone else try to clip a renderTexture?

Thanks in Advance!

**Comment by GoodBoyDigital** [comment]
Just fixed this in v3. Got there in the end :)
