### ISSUE TITLE
VideoTexture not working in firefox 

### ISSUE THREAD

**Issue by ddennis** [GoodBoyDigital/pixi.js#1148]
It seems like the video texture is not working correctly.in Firefox, because the 
PIXI.VideoTexture.prototype.onCanPlay = function() { ... } is missing the event parameter:

This seems to fix it PIXI.VideoTexture.prototype.onCanPlay = function(event) {   ...... };

Thank you for a great library.
/Dennis

**Comment by tobireif** [comment]
After Pixi 3.0, this issue can probably be closed as soon as the following tests succeed:

Test the video example online (not locally). In each browser after browser-start/-restart & clear-cache. (and again after reload). Check presence of sound, video, and filtering. All this in each of Mac FF, Mac Chrome, Windows FF, and Windows Chrome.

**Comment by englercj** [comment]
Marked as a 3.0 milestone issue and closing.

**Comment by tobireif** [comment]
But doesn't "closed" mean that no one will ever look at it again? (neither before nor after 3.0)

I wouldn't close it before the descibed tests haven't succeeded. (BTW, they did succeed with my code).

**Comment by englercj** [comment]
I'm saying this is fixed in v3, so I closed it. There will be examples/tests for all the code written which will include this case regardless of the issue being opened.

I'm not sure I follow what you mean?
