### ISSUE TITLE
Contribute to WebGL Stats

### ISSUE THREAD

**Issue by englercj** [GoodBoyDigital/pixi.js#1166]
It would be pretty cool to help contribute to the stats on http://webglstats.com/ by including there small script on the pixi/GoodBoyDigital pages:

```html
<script src="//cdn.webglstats.com/stat.js" defer="defer" async="async"></script>
```

The script measures a couple WebGL params and reports it to their aggregator so devs can use those stats when building their projects. It doesn't send any PII as you can see in the script source.

**Comment by englercj** [comment]
Then do it! lol

**Comment by englercj** [comment]
Added these stats to the new v3 examples, still be cool to put this on the .com

**Comment by GoodBoyDigital** [comment]
closing this for now as we have it in the examples

**Comment by h3rb** [comment]
where in the examples?

**Comment by englercj** [comment]
I had added it in pixijs/examples@5a9aaad729a716b543c54d3d07ffbee2af21e3f0, then it was removed in pixijs/examples@99d8d31af409ce19b731178a38893da888a298ea (when they did v2).
