### ISSUE TITLE
In WebGLSpriteBatch.js max size why just 2000

### ISSUE THREAD

**Issue by nextht** [GoodBoyDigital/pixi.js#1168]
In WebGLSpriteBatch.js this.size i think should be 65536/6, so max size could reach to 10000.

    PIXI.WebGLSpriteBatch = function()
    {
         /**
         * @property vertSize
         * @type Number
         */
        this.vertSize = 6;
    
        /**
         * The number of images in the SpriteBatch before it flushes
         * @property size
         * @type Number
         */
        this.size = 2000;//Math.pow(2, 16) /  this.vertSize;

From my knowledge the limit is gl.drawElements method's gl.UNSIGNED_SHORT param, so i don't think "//Math.pow(2, 16) /  this.vertSize;" the comment is reasonable, should be  Math.pow(2, 16) / 6, the "6" represent the indices for every sprite. 

Below code look like has the same issue:

	PIXI.WebGLFastSpriteBatch = function(gl)
	{
		/**
		 * @property vertSize
		 * @type Number
		 */
		this.vertSize = 10;

		/**
		 * @property maxSize
		 * @type Number
		 */
		this.maxSize = 6000;//Math.pow(2, 16) /  this.vertSize;

**Comment by GoodBoyDigital** [comment]
Added a SPRITE_BATCH_SIZE to the constants to v3. Enjoy!
