### ISSUE TITLE
RenderTexture (renderWebGL/renderCanvas) unexpectedly mutates DisplayObject.worldTransform

### ISSUE THREAD

**Issue by pnstickne** [GoodBoyDigital/pixi.js#1174]
https://github.com/GoodBoyDigital/pixi.js/commit/90038284a3afd1fff8d83a6c6551c7e9857a3191 appears to introduce a change where the worldTransform of the object being rendered is itself modified. The is problematic behavior because the unexpectedly mutates the DisplayObject and it's position/effect in the scene-graph.

The previous version appears to have used a temporary worldTransform object - I am not sure if there was a particular reason for it's removal (`render` does not appear to be usable in a re-entrant manner so a single temp. matrix as before should work well, unless there is something else that I am unaware of).

Side-effects of this change have been reported in https://github.com/photonstorm/phaser/issues/1310 and http://www.html5gamedevs.com/topic/10015-phaser-213-and-state-transition-plugin/ from usage in Phaser.

If this mutation is absolutely required and cannot be restored, then it should be _very clearly documented_. I would opt for simply avoiding permanent mutations to the DisplayObjects supplied as arguments, as mutating them so is just confusing and unexpected.

**Comment by englercj** [comment]
This PR has been merged.
