### ISSUE TITLE
YUIDoc type refinement: {Number} -> {Integer}

### ISSUE THREAD

**Issue by pnstickne** [GoodBoyDigital/pixi.js#1178]
Hi, I've submitted some PRs dealing the YUIDoc additions. Currently (well, after a secondary commit) the PR changes only use {Number} for numeric parameters.

However, one thing that I prefer in other projects is to refine types from {Number} to {Integer} where such is appropriate. I know that there is no "int" type in JavaScript, but I personally feel that adding such a type "hint" to the documentation increases the overall clarity when such is valid to require or can be guaranteed.

As pointed out (on my now-not-head-changes), it would be inconsistent if {Integer} was used only in a limited fashion and not applied to all the YUIDoc type annotations where such a "hint" holds. Thus I am looking for 'guidance' on the top.

Should/must {Number} to be used exclusively for all numeric types, even those with a finite set of fixed values, "Scale Modes" and "Blend Modes"? Or can the types be refined as {Integer}? Or would it be even more appropriate to use {ScaleMode}?

I would like to go to at least {Integer} type "hints" - I don't know how to get YUIDoc to create a new type without it also being a "class", and that makes me feel uncomfortable about {ScaleMode} even though is absolutely the most precise/accurate.

I would be willing to spend a little bit of time updating the documentation for consistency and carefully apply {Integer} to types that are currently annotated as {Number}, where such a change is prudent. (I would also hope that, if done, such a documentation-oriented PR without any feature changes could be hurried through a merge!)

But since I'm just :swimmer: around in here and have very little say on The PIXI Way, or any _consistency guidelines_ about the YUIDoc comments/annotations, it is appropriate that relevant blessings are obtained before such a proposal is implemented - or it would just be another loved, but lonely, backlogged PR.

**Comment by englercj** [comment]
@pnstickne I have gone through the englercj/pixi.js#dev-rewrite branch and rewritten the docs as jsdoc. If you want to convert all the `{number}` spots to `{integer}` or `{double}` feel free to throw in a PR!
