### ISSUE TITLE
WebGLFilterManager dosen't restore WebGLRenderer's offset correctly

### ISSUE THREAD

**Issue by nextht** [GoodBoyDigital/pixi.js#1180]
I found  that when i use filter on sprite, the renderer's offset will be reset to original.
Try the code below, if uncomment  //sprite.filters = [blurFilter];  the screen will not move.

    stage = new PIXI.Stage(0x66FF99);    
    renderer = PIXI.autoDetectRenderer(400, 400);   
    document.body.appendChild(renderer.view);

    loader = new PIXI.AssetLoader(["fullscreen.png"]);       
    loader.onComplete = function(){        
        texture = PIXI.Texture.fromImage("fullscreen.png");        
        var blurFilter = new PIXI.BlurXFilter();        
        sprite = new PIXI.Sprite(texture);
        sprite.anchor.x = 0;
        sprite.anchor.y = 0;   
        sprite.position.x = 5;
        sprite.position.y = 5;        
        //sprite.filters = [blurFilter];      
        stage.addChild(sprite);           
        renderer.offset.x = 5;                        
        animate();
    }; 
    loader.load();

    function animate() {
        requestAnimFrame(animate);
        renderer.render(stage);        
        renderer.offset.x += 1;
        renderer.offset.y += 1;
    }
Or am i mistaking using renderer.offset? Can it be modified by user?

**Comment by GoodBoyDigital** [comment]
Hey guys, this should be sorted in v3 now. Thanks!
