### ISSUE TITLE
Filters broken on any masked object

### ISSUE THREAD

**Issue by ourvice** [GoodBoyDigital/pixi.js#1187]
Hello!

The filters seem to be broken on any object that is masked ( masked displayObjectContainer children filters are not applied and the children object disappears  )  the sprite does not render visually.

Any ideas?

Thanks!

Destin

**Comment by GoodBoyDigital** [comment]
this has been fixed in v3. Boo ya!

**Comment by ourvice** [comment]
awesome :)
