### ISSUE TITLE
DisplayObject.renderable no longer used

### ISSUE THREAD

**Issue by photonstorm** [GoodBoyDigital/pixi.js#1190]
This property no longer does anything. It probably ought to either be removed to keep the docs clean, or added to the _renderCanvas / _renderWebgl checks:

`if (this.visible === false || this.alpha === 0 || this.texture.crop.width <= 0 || this.texture.crop.height <= 0) return;`

**Comment by englercj** [comment]
I think we should add renderable back in as a working property.
