### ISSUE TITLE
Sprite.filters not working in CocoonJS ?

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1194]
Hello,

I have a working demo app on my Nexus 4 with CocoonJS 2.1 and PixiJS 2.1. I run my app in "Canvas+" mode. Everything works fine except if I try to put a filter on a sprite. I tried GrayFilter and ColorMatrixFilter, and for both, the sprite become invisible. It works fine in Chrome.

Regards.

**Comment by englercj** [comment]
Closing this since it isn't a pixi issue. Thanks!
