### ISSUE TITLE
Travis CI warning 'function closure expressions is only available in Mozilla JavaScript extensions (use moz option)."

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#1195]
Before having created a pull request I ran all tests and JSHint. (locally)

But on https://github.com/GoodBoyDigital/pixi.js/pull/1186 there are little red crosses saying "Failure: The Travis CI build failed".
For commit https://github.com/tobireif/pixi.js/commit/a04a3380c0c8f487699e10270b2c6b7b1293175b Travis CI says on https://travis-ci.org/GoodBoyDigital/pixi.js/builds/41255912 :
```
Running "jshint:source" (jshint) task

Linting src/pixi/textures/VideoTexture.js ...ERROR

[L72:C50] W118: 'function closure expressions' is only available in
  Mozilla JavaScript extensions (use moz option).

PIXI.VideoTexture.prototype.onCanPlay = function()

Warning: Task "jshint:source" failed.
Use --force to continue.

Aborted due to warnings.
```

Overall, for the whole pull request, it says

    "All is well — The Travis CI build passed"

https://travis-ci.org/GoodBoyDigital/pixi.js/builds/41276600
    "Done, without errors."
    "Done. Your build exited with 0 [no errors]."

Perhaps the issue is
https://github.com/jshint/jshint/issues/1192
and this one here can be closed.

**Comment by englercj** [comment]
I saw this spot in the dev-rewrite branch and fixed it. It was a missing open brace (`{`) that still worked due to that syntax being valid ES6 :P

Picked it up with jshint and fixed it!
