### ISSUE TITLE
Canvas Filters

### ISSUE THREAD

**Issue by austinh** [GoodBoyDigital/pixi.js#1198]
Is there any chance that certain WebGL filters can be supported by canvasRenderer? I understand that performance will not be as great, but perhaps there are some cheap ones where the filters can apply without WebGL. EaselJS uses it.

An example of this would be greyscale and sepia. Per-pixel manipulation on that level is pretty cheap. It's not a crazy blur or anything, but it's something. These are relatively inexpensive canvas operations. Perhaps you could even cache them similar to Tint.

Here are some examples.
http://www.html5rocks.com/en/tutorials/canvas/imagefilters/
https://github.com/CreateJS/EaselJS/tree/master/src/easeljs/filters
https://github.com/kangax/fabric.js/tree/master/src/filters
https://github.com/kig/canvasfilters/blob/master/filters.js

**Comment by englercj** [comment]
This can be built as a v3 plugin, but we don't plan to support it anytime soon.
