### ISSUE TITLE
CanvasRenderer doesn't mask stroke correctly 

### ISSUE THREAD

**Issue by nextht** [GoodBoyDigital/pixi.js#1199]
I change example 14 - Masking index.html code to "var renderer = new PIXI.WebGLRenderer(620, 380);" and also change "thing.beginFill(0x8bc5ff, 0.4);" to "thing.lineStyle(25, 0x16f1ff, 1);"
I found that WebGLRenderer can mask the stroke and cull the fill part, but CanvasRenderer still display fill part.

**Comment by GoodBoyDigital** [comment]
this should be cool in v3 now. ta!

**Comment by hjujah** [comment]
+1 
Any progress on this one? We are still having the same issue on 3.07...
