### ISSUE TITLE
IE11 issue

### ISSUE THREAD

**Issue by brejep** [GoodBoyDigital/pixi.js#1201]
I'm developing a game with Phaser and, when testing in IE11, I get a constant flickering between the stage's background colour and black. I also don't get any interactions from buttons in Phaser.

While no errors are thrown, there is a warning in the console:
EBGL11135: getContext: Context attribute premultipliedAlpha:false is not currently supported

I can confirm that if I remove the premultipliedAlpha option from the webgl context options in Pixi (src/pixi/renderers/webgl/WebGLRenderer.js line 150), the buttons and interactions do then work in Phaser. However, the flickering continues.

I think this may be a graphics card specific issue.

The PIXI examples on the GoodBoy website seem to use version 1.5.2 and the problem is not evident there. Are there any using version 2 that I could test against?

There are no issues if I render in canvas mode.

Technical details:
Phaser version: v2.1.3 "Ravinda" - Built: Thu Oct 23 2014 12:33:04
PIXI version v2.0.0
Windows 8.1 with Internet Explorer 11.0.9600.17416 - IE compatibility mode set to Edge.
Graphics: NVIDIA GeForce GT 640M

**Comment by JiDW** [comment]
It happens on Windows Phone too

**Comment by GoodBoyDigital** [comment]
closing this for now as I'm pretty sure this has been fixed in v3. Let me know if im wrong! Cheers! :+1:

**Comment by spleennooname** [comment]
i have the same problem here: http://codepen.io/spleen666/pen/ZGYPbW - looks fine in chrome & FF -

**Comment by englercj** [comment]
Have you tried passing `{ transparent: true }` to autoDetectRenderer, so that `premultipliedAlpha` is `true` on context creation?

**Comment by patrickfabrizius** [comment]
Just had this bug in IE11 with PIXI 4.5.1 even when forcing the CanvasRenderer, but @englercj 's suggestion using transparent: true seems to fix the issue.

**Comment by digitaloranges** [comment]
I've just had the exact same issue in IE11 and indeed, setting transparent:true does fix the problem.
