### ISSUE TITLE
Swap Texture cause exception in examples 23

### ISSUE THREAD

**Issue by nextht** [GoodBoyDigital/pixi.js#1211]
/examples/example\ 23\ -\ Texture\ Swap/index.html
In the demo when i click to swap texture, encounter error from Texture.js PIXI.Texture.prototype.setFrame method

    if (!this.trim && (frame.x + frame.width > this.baseTexture.width || frame.y + frame.height > this.baseTexture.height))
    {
        throw new Error('Texture Error: frame does not fit inside the base Texture dimensions ' + this);
    }

**Comment by englercj** [comment]
We are rewriting the examples and will make sure this is fixed in the new ones.
