### ISSUE TITLE
Filters and Custom Renderer Resolution Bug

### ISSUE THREAD

**Issue by amadeus** [GoodBoyDigital/pixi.js#1215]
Hello, so I've found a rather weird issue concerning filters and custom resolutions with Pixi.

See [here](http://jsfiddle.net/amadeus/j5c5wtq5/) for a quick example - click to toggle the filter on and off.

Essentially it seems like the entire scene gets scaled back down to 1x resolution, and attached to the bottom left corner. I've tried it with a couple other filters so it's not specific to the invert filter.

It's rather simple code - the only thing perhaps out of the ordinary is how I am instantiating my renderer:

```js
renderer = new PIXI.WebGLRenderer(
	446,
	250,
	{
		view: document.getElementById('canvas'),
		resolution: 3
	}
);
```

If I change resolution to 1, no problems at all.

**Comment by marcusstenbeck** [comment]
@GoodBoyDigital @englercj Should I take a look at this?

**Comment by gre** [comment]
I was about to file this bug too, but found this issue.

Here is another jsfiddle showing this bug: http://jsfiddle.net/zuvbkzee/2/

this makes filters unusable for retina devices but i'm glad this will be part of v3.0.

**Comment by GoodBoyDigital** [comment]
This works as expected in v3 now :+1: 

![screen shot 2015-02-16 at 11 05 29 am](https://cloud.githubusercontent.com/assets/3112434/6210858/d18dec9c-b5cb-11e4-87d8-25dc141cab9f.png)

**Comment by gre** [comment]
Awesome
