### ISSUE TITLE
Text.destroy crashes Chrome tab

### ISSUE THREAD

**Issue by kichooo** [GoodBoyDigital/pixi.js#1219]
I try to clean memory after removing a text objects. I call:

textObject.destroy(true);

but it crashes the Chrome tab if I call it on many text objects at once.

Maybe I do that incorrectly? After reading PIXI source I see that PIXI creates a html canvas object for every text instance, is it necessary? Looks like it creates a massive impact on memory.

Do you destroy your text objects after they are no longer needed?

**Comment by GoodBoyDigital** [comment]
Hello! Just tested this demo on v3. Seemed to work fine now :+1: 
I would suggest that if you use that much text it may be best to reuse the texture if the text is the same. Alternatively using bitmap text would also be a good path. thanks!
