### ISSUE TITLE
How to create effect like Photoshop eraser

### ISSUE THREAD

**Issue by weepy** [GoodBoyDigital/pixi.js#1225]
Heya

I'm making a mobile game where you have to do some cleaning and I want the user to clean up by wiping away the dirt. The effect I'm looking to achieve is like the Photoshop eraser, but I'm not quite sure how best to achieve this --- it's quite easy in canvas api. But ideally i'd like to not have to upload a new texture every frame as it could be quite big.

Any ideas ?!

J

**Comment by englercj** [comment]
You may get better responses for "What is a good technique for X" on [the forums](http://www.html5gamedevs.com/forum/15-pixijs/).
