### ISSUE TITLE
android and chrome with pixie using assetloader with crossorigin set to true cannot pass basic authentication with delayed loading initialisation

### ISSUE THREAD

**Issue by baslentfert** [GoodBoyDigital/pixi.js#1234]
i came across the following: on android chrome browser loading a page with basic authentication.
after authentication the loading starts with a user click using the assetloader. The assets failed to load, this due to crossbrowser origin is set to true standard. 
maybe someone ran into this as well?
all assets and resources come from the same domain.
FIX : i set crossorigin to standard false, the loading acts correctly within same domain.

**Comment by englercj** [comment]
I think this is related to #1269

**Comment by GoodBoyDigital** [comment]
this should be fine in v3 as crossorigin is determined automatically. We cool to close this @englercj ? thanks!

**Comment by englercj** [comment]
Should be fine with the new loader, cross origin is automagically detected.
