### ISSUE TITLE
Instantiating more than 4 WebGLRenderers causes black textures

### ISSUE THREAD

**Issue by erd0s** [GoodBoyDigital/pixi.js#1238]
If I instantiate and destroy more than 4 WebGLRenderers on a single page I get a black canvas, this behavior is consistent across chrome/ff/safari, I've included a minimal example, any ideas why this would be happening?

I'm in an "mvc" type page where the page is rarely refreshed, changing pages just swaps out content on the page, and my pages have a pixi instances on them.

```javascript
var stage, renderer, container, redText, blueText, keepGoing;

var animate = function() {
	if (keepGoing) {
        requestAnimFrame(animate);
        renderer.render(stage);
    }
};

var startPixi = function() {
	stage = new PIXI.Stage();
    renderer = PIXI.autoDetectRenderer(1080, 393, {transparent: true});
    document.querySelector('body').appendChild(renderer.view);
    
    redText = PIXI.Sprite.fromImage("img/red-text.png");

    stage.addChild(redText);

    lastTime = new Date().getTime() / 1000;
    keepGoing = true;
    requestAnimFrame(animate);
};

var endPixi = function() {

    stage.removeChild(redText);

    redText.texture.destroy(true);
    keepGoing = false;
    renderer.destroy();

	var c = document.querySelector('canvas');
	document.querySelector('body').removeChild(c);
};

```

So calling startPixi() then endPixi() more than 4 times causes this behavior

**Comment by noseglid** [comment]
I've run into this as well now. Is there a workaround for 2.x? I can't go back to 1.6.1 since I need features from 2.x.

**Comment by mattdesl** [comment]
@noseglid 
you can just add a few more `true` statements to the [problematic code](https://github.com/GoodBoyDigital/pixi.js/blob/2dfd58b3757e16fad4b26a1fb9edf944f38aa5b8/src/pixi/textures/BaseTexture.js#L110)

:neutral_face:

**Comment by noseglid** [comment]
Won't really help me.. I don't know how many I need.

**Comment by mattdesl** [comment]
Well most browsers aren't capable of handling more than a couple dozen, so that's a starting point. Why do you need so many?

**Comment by noseglid** [comment]
It's not that I have many at the same time. I create and destroy them as I go along.

**Comment by mattdesl** [comment]
In previous projects I've used a singleton to re-use canvas contexts, but that can arguably get annoying to test and also isn't easily supported by some frameworks. 

I suspect even if this bug is fixed you will find other issues with Pixi not cleaning up resources from earlier renderers (just off the top of my head: the texture cache). :sad:

**Comment by englercj** [comment]
This should be fixed now in v3. Using events from the texture that any number of renderers can listen for to update/destroy that texture.
