### ISSUE TITLE
Very slow rendering of my "big" (not really) stage. Please help me figure it out.

### ISSUE THREAD

**Issue by RubrikBonnier** [GoodBoyDigital/pixi.js#1246]
(Sorry for asking this here, but the forum is as annoying as most forums and doesn't let me post. Why doesn't Github have an exact copy of "issues" but for tech support anyway?)

For the last week, I've been trying to move from Canvas 2D to WebGL for my game due to the fascinating sluggishness of the former, and the amazing speediness of the latter. To make a long story short, I've arrived at a final solution that *should* work for me, but currently doesn't.

***Important: what I have technically works exactly as intended, in every regard, except for the rendering speed. It's even slower than Canvas 2D currently, which can only mean that I have done something horribly, HORRIBLY wrong.***

I've looked through my code 10 times now and can't find anything obvious. It seems to me that it should be very fast.

**Note: I'm well aware of the fact that I have no "culling" routine yet. However, the entire world map is so small, that it barely covers a few screens. Also, I'm gonna have a feature where the user can zoom out to see the whole world at once anyway, so I can't really do culling most of the time.**

Either case, the culling is not the problem here. The problem must be something I'm confused about, because again, this is even slower than Canvas 2D. I'm 100% convinced that this is not due to WebGL or Pixi.js, but due to some error of mine. Can you help me find and fix it?

I cannot make a working example due to the complexity of my project, but I did spend significant time creating this minimal example with real code but which doesn't actually run as a program. It contains all the relevant parts and shows exactly what I'm doing for all the relevant parts.

CPU usage: 24-33%. GPU usage: 14-33%. OS: Windows 8.1 Update 1. Latest stable Chromium. WebGL confirmed to work. Very fast and beefy computer. *Very* slow perceived rendering of my world. As in, Mario Paint on the SNES kind of rendering. Almost.

The code:

```js
var renderer = new PIXI.WebGLRenderer(800, 600); // This is set the size of the screen when resized.

var stage = new PIXI.Stage(); // Important note to self: Stage objects are for some reason special and cannot be modified! Only use for a "wrapper" of sorts, and remember to render() it, but otherwise, do everything to "root" instead of stage!
var root = new PIXI.DisplayObjectContainer(); // root is the real stage, which can be modified in all kinds of ways, unlike stupid Stage.
stage.addChild(root);

function doThisOnceToSetTheGameUp()
{
	for (var i = 0; i < mapLayers.length; i++)
	{
		var theLayer = new PIXI.DisplayObjectContainer();

		for (var x = 0; x < (WORLD_WIDTH_IN_TILES * TILE_SIZE); x += TILE_SIZE)
		{
			for (var y = 0; y < (WORLD_HEIGHT_IN_TILES * TILE_SIZE); y += TILE_SIZE)
			{
				var theTileSprite = new PIXI.Sprite(/* complicated calculation that works; it just grabs the correct texture from the world map */);
				theTileSprite.position.x = x;
				theTileSprite.position.y = y;
				theTileSprite.layer = i;
				theLayer.addChild(theTileSprite);
				screenTiles.push(theTileSprite);
			}
		}

		root.addChild(theLayer);
	}
}

function drawStuffWhenAnimationFrameIsGiven()
{
	root.position.x = -cameraX;
	root.position.y = -cameraY;

	renderer.render(stage); // Since stage is rendered, root is rendered, thus each of the layers, thus all the sprites in each layer.
	requestAnimationFrame(drawStuffWhenAnimationFrameIsGiven);
}
```

**Edit**: Added code markdown styles.

**Comment by steffomix** [comment]
Have a similar Problem, but depends on the Browser. Chrome x64 on Ubuntu 16.04 runs like silk with +30fps.
Firefox on same Machine behaves like a total failure and displays nothing with far below 1fps.

http://jsfiddle.net/nikkikoole/tq13caus/3/

**Comment by staff0rd** [comment]
@steffomix possibly Ubuntu related - firefox & chrome both +30fps on my win10 box

**Comment by olejka91** [comment]
@NikkiKoole ,

Could you suggest me a good lib to visualize a large amount of data as a network in browser with binding events for nodes, edges and a view ( like rightclick, drag node, drag view, zoom, multiple select and text labels for nodes and edges).

I`ve tested cytoscape.js, vis.js, sigma.js.

Cytoscape.js animate smoothly up to 3k nodes and 5k edges.

Vis a little bit less than Cytoscape.js

Sigma visualize and animate smoothly up to 5k nodes and 8k edges.

(10k * 10k is too laggy for Sigma)
Sigma is the best choice but it`s still not enough performance for such large network.

Need more or equal to 10k nodes and 10k edges to animate them smoothly on changing layout from random position to circle for example or other type of layout

Does it a good idea to use PIXI for example?

Thanks in advance
