### ISSUE TITLE
TiltShiftFilter

### ISSUE THREAD

**Issue by mladenjacket** [GoodBoyDigital/pixi.js#1247]
Hi all,

Im using Intel Xdk with crosswalk and pixi and when i use tiltshiftfilter i get this error:
Uncaught TypeError: undefined is not a function 

this is my code

filter = new PIXI.TiltShiftFilter();
sprite.filters = [filter];

BlurFilter() seems to be working fine

any suggestions ?

**Comment by englercj** [comment]
I think this had to do with some inheritance missing in the TiltShiftFilter class. If you can show an example of this not working feel free to reopen this.
