### ISSUE TITLE
Blurry rendering on Safari with retina using webgl

### ISSUE THREAD

**Issue by Wiles** [GoodBoyDigital/pixi.js#1249]
When I run the included example in Safari on a retina display the text is significantly more blurry when webgl is enabled. Disabling webgl and reloading the page immediately improves the visuals.

This was on Yosemite 10.10.1 and Safari 8.0.

http://jsfiddle.net/Wiles/uqu1aygv/

**Comment by GoodBoyDigital** [comment]
this should work correctly in v3 now! Thanks for sharing :+1:
