### ISSUE TITLE
InteractionData bubbling?

### ISSUE THREAD

**Issue by mustyoshi** [GoodBoyDigital/pixi.js#1252]
Perhaps add a way to stop the mouse event from continuing after it triggers a callback, and perhaps let the user specify what direction they want the events to propagate (descendants first, or ancestors first)

I almost achieved what I wanted by reversing the InteractionManager loops, except it ends after one iteration because the sprite doesn't have any interactive children. Hopefully that won't bite me, eh?

Idk how to add labels or I would have labeled it feature-request

**Comment by GoodBoyDigital** [comment]
This should work now in v3. enjoy :) :+1:
