### ISSUE TITLE
Sprites with filters don't render in RenderTexture (dev 2.2)

### ISSUE THREAD

**Issue by serprex** [GoodBoyDigital/pixi.js#1255]
https://github.com/serprex/openEtG/blob/master/gfx.js#L56 <- If I remove this line, the card art is rendered (without filter ofc). I tried a different filter, same result. I lifted filter to be applied to the sprite that the RenderTexture is used by, & the filter is applied to the whole Sprite (as it should be)

Worked before update to 2.2

"fixed Y-flipped mask issue on render texture" does not solve the issue

**Comment by GoodBoyDigital** [comment]
fixed for v3. woop!
