### ISSUE TITLE
Canvas Texture vs Loaded Texture... I think it might be a bug...

### ISSUE THREAD

**Issue by rolyataylor2** [GoodBoyDigital/pixi.js#1263]
Here is my Graphics Sprite thing

    SomeOtherSprite  = new PIXI.Graphics();
    SomeOtherSprite .beginFill(0xFFFFFF);
    SomeOtherSprite .drawRect(0,0,game.camera.viewWidth(),game.camera.viewHeight());
    SomeOtherSprite .endFill();

This works great!

    var texture = PIXI.Texture.fromImage('mask.png'); // Image from a the canvas element saved and turned into a png
    SomeOtherSprite.filters = [new PIXI.AlphaMaskFilter(texture)];

The problem happens when I try to use a canvas texture as a alpha mask for another sprite.

    var canvas = document.createElement('canvas');
    canvas.width = 256; canvas.height = 256;
    var ctx = canvas.getContext('2d');
    var gradient = ctx.createLinearGradient(0,0,170,0);
    gradient.addColorStop(0,"black");
    gradient.addColorStop(1,"white");
    
    ctx.fillStyle = gradient;
    ctx.fillRect(20,20,150,100);
    
    var texture = PIXI.Texture.fromCanvas(canvas));
    SomeOtherSprite.filters = [new PIXI.AlphaMaskFilter(texture)];

**Comment by GoodBoyDigital** [comment]
Hey there! this should be all good now in v3. cheers!
