### ISSUE TITLE
stage.setInteractionDelegate doesn't work

### ISSUE THREAD

**Issue by beeglebug** [GoodBoyDigital/pixi.js#1264]
It looks like there area few problems with it:

It doesn't set `stage._interactiveEventsAdded`, so when the renderer runs, it calls `stage.interactionManager.setTarget(this)`, which wipes out the newly added delegate.

Also, because it calls `interactionManager.setTargetDomElement` directly, rather than `setTarget`, the `target` and `resolution` properties are not set.

I have an idea of how to fix it, and potentially add some functionality at the same time, i'll do a PR later.

**Comment by GoodBoyDigital** [comment]
This should work correctly in v3 now ->
```renderer.plugins.interactiveManager.setTargetElement( element )```
cheers! :+1:
