### ISSUE TITLE
Can I enter some sort of "debug mode"?

### ISSUE THREAD

**Issue by RubrikBonnier** [GoodBoyDigital/pixi.js#1268]
Whatever I do, I can't get my PIXI-based JS program back to working after some changes. There is no output whatsoever to the error log. No "can't load image due to permission errors" or anything. Nothing. I've tried to uncomment large parts of my program but I simply can't figure out what's wrong.

Is there some "PIXI debug mode" where I can actually learn what is the problem?

I use pixi.dev.js, if that matters.

**Comment by karaliunas** [comment]
You can give a try to [PixiJS devtool Chrome addon](https://chrome.google.com/webstore/detail/pixijs-devtools/aamddddknhcagpehecnhphigffljadon?hl=en)
