### ISSUE TITLE
AssetLoader.onComplete is never called if assetURLs is empty.

### ISSUE THREAD

**Issue by martin-stone** [GoodBoyDigital/pixi.js#1270]
A minor irritation that's caught us out a few times when writing automated tests where the test fixtures don't need any assets. We have to add a dummy image to the list to get the rest of our game initialising.

**Comment by GoodBoyDigital** [comment]
Hey @englercj this looking good in v3? Can we close? cheers!

**Comment by englercj** [comment]
Close it up! New loader that operates totally differently now, and doesn't experience this bug.
