### ISSUE TITLE
BitmapText cacheAsBitmap issues

### ISSUE THREAD

**Issue by kambing86** [GoodBoyDigital/pixi.js#1276]
Please check this test page for more details.
I'm using latest chrome to view this.
https://www.googledrive.com/host/0B31if-IJ9CXbQlFSQU1WcFc5Szg/

key:
1 set sprite as cacheAsBitmap = true
2 set text as cacheAsBitmap = true
3 change text to "123"
4 change text to "456"

setup
a sprite is created, and one bitmaptext is created and placed in the sprite.

there are 2 issues here

1) default situation without pressing any key
the sprite is cacheAsBitmap = true before the actual rendering occur, the text is inverted.

2) in first situation without changing cacheAsBitmap properties, the text is inverted, change the text by clicking 3 & 4 will update the cache correctly. after changing the properties settings by pressing 2, press 3 & 4 will not update the cache immediately.
click 2, open console and type in the code below line by line
```
text.setText("789");
```
```
text.updateCache();
```
will show the result correctly.

**Comment by GoodBoyDigital** [comment]
This should work like a champ in v3 now. :+1:
