### ISSUE TITLE
Dev build kinda broken

### ISSUE THREAD

**Issue by whizzkid** [GoodBoyDigital/pixi.js#1279]
I downloaded the dev build because I was having problems with Spine. Ran the examples and noticed that example 12 - Spine  and example 14 - Masking  aren't working properly.

The Spine example shows a white screen and the masking example doesn't draw a rectangle anymore but a weird shape.

The Spine problems wrecked my project, so unfortunately I'm forced to revert to an earlier version.

STR: download the dev build and run the examples

**Comment by englercj** [comment]
We will be rewriting the examples and spine code, so this shouldn't be an issue when that happens.
