### ISSUE TITLE
SpineLoaded forces you to use Spine generated atlas files

### ISSUE THREAD

**Issue by whizzkid** [GoodBoyDigital/pixi.js#1280]
With the last few updates Spineloader now forces you to use the atlas files that Spine generates.

pros: 
 - more convenient for generating assets, since all you need is the Spine Export.

cons:
- Texturepacker makes better atlases. but you can't load them now.
- PIXI does not handle the stripping of whitespaces (x and y) well with Spine exports, it has no trouble with TexturePacker trims.

Instead of forcing the user to solely rely on Spine generated files, I believe it would be better to offer the option to load your own Atlas files as well.

**Comment by aholla** [comment]
I too need this :) 

Without it I wont be able to update to a new version of pixi. :(

**Comment by englercj** [comment]
Now tracking this at pixijs/pixi-spine#11.
