### ISSUE TITLE
What about FontLoader?

### ISSUE THREAD

**Issue by jagi** [GoodBoyDigital/pixi.js#1282]
Hi,
Now, to load fonts we have to use libraries like font.js but wouldn't it be better to create FontLoader class that would make it possible to add path to font with other assets and make whole process more transparent? It could use font.js internally or we could create our own implementation. I could help with creating such class.

**Comment by GoodBoyDigital** [comment]
Hey @englercj  could use this to the loader to nail fonts? -> https://github.com/typekit/webfontloader

**Comment by englercj** [comment]
Is the desire here "I want to load a font file and do stuff with it (as a raw file)" or "I want to know when my `@font-face` declaration in my css has loaded" or "I want to load a font file and make it available for use in PIXI.Text"?

**Comment by GoodBoyDigital** [comment]
For me it would be so I could use a pixi text object and know the font is ready when it generates the canvas texture.

**Comment by NikkiKoole** [comment]
I was just going to open an issue/ feature request for this too, I've tried a few options in http://www.html5gamedevs.com/topic/2385-how-to-make-sure-that-a-font-is-loaded/ including the font.js OP mentions but I ended up with setTimeout, global variables and prayer.  there are finnicky differences between tablet/chrome/firefox I don't understand and it would be very nice if pixi would *just* load it so I can use it with PIXI.Text and be sure it works (and not show another default font for example)

**Comment by englercj** [comment]
@NikkiKoole I'm still asking the question, are you talking about using `@font-face {}` and then the loader notifying you when it is done, or are you talking about loading a font via pixi and using it that way?

**Comment by NikkiKoole** [comment]
I mean I prefer loading a font via pixi assetloader if that would be possible.

**Comment by tobireif** [comment]
I'm using https://developers.google.com/webfonts/docs/webfont_loader , see https://github.com/tobireif/boomchat/blob/565fe873b06a271a9d90a632ca8b0166af8ddaa6/web/js/main.js#L186 .

Now when I want to track the progress of the loading of the assets (incl. images and fonts), it would useful if Pixi's loader could handle everything the Google/Typekit Web Font Loader handles. That would mean I wouldn't have to use two loaders, and I could use the Pixi loader to count to 100% regarding images and fonts, and I could still kick off font related stuff when the fonts got loaded (as I do in the linked code).

**Comment by englercj** [comment]
englercj/resource-loader#5

This is a non-trivial thing to do, the web font loader library is larger than the resource-loader and all it does is fonts. It probably won't be anytime soon but it is on my radar.

**Comment by englercj** [comment]
Closing to track on resource loader instead.

**Comment by tobireif** [comment]
Perhaps you could link the new issue page here?

**Comment by davidfig** [comment]
For others who ran into this problem, I'm using https://github.com/bramstein/fontfaceobserver in my preload check to ensure that @font-face is properly loaded. Probably wouldn't be too hard to include in the loader.

**Comment by SlavMFM** [comment]
@davidfig I don't know why but in my case when using **fontfaceobserver** nothing being rendered at all (the whole game disappears) - really weird. When getting back to **webfontloader** everything appears back but it has race conditions (sometimes first line of text having Arial font).
