### ISSUE TITLE
Stage transformation doesn't affect children

### ISSUE THREAD

**Issue by YopSolo** [GoodBoyDigital/pixi.js#1285]
cannot do stuff like rotate the stage, translate the stage or scale it.
values are modified but childrens are unaffected.

a workaround is to create a DisplayObjectContainer and use it as a stage but...

using pixi 2.1.0

**Comment by pnstickne** [comment]
(As long as a Stage documents that the behavior differs, and hopefully provides a nice hint..)

**Comment by GoodBoyDigital** [comment]
Pooof! Stage is gone. So no more transform issues :)
