### ISSUE TITLE
Issues with TexturePacker and AtlasLoader

### ISSUE THREAD

**Issue by gre** [GoodBoyDigital/pixi.js#1290]
I'm getting a `Cannot read property 'replace' of undefined` when trying to use a json atlas exported from TexturePacker and I've tried both the *JSON (Array)* and *JSON (Hash)*.

When looking at the code of AtlasLoader, it seems it fails in parsing the JSON – when [splitting on a `" "`](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/loaders/AtlasLoader.js#L91).

It seems [this code](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/loaders/AtlasLoader.js#L91-L98) is **very** specific and error prone, you have absolutely no guarantee that the JSON generated from TexturePacker (or any other software BTW) have the exact indentation/spacing/key-ordering you expect it have (and what if I want to minimize my JSON).
**I suggest to rely on a real JSON parser like `JSON.parse`** and just use the resulting object as the altas data, code would be much more small and more reliable.
Not sure to have 100% the time, but tell me if you want me to help you on refactoring that.

Thanks

**Comment by GoodBoyDigital** [comment]
Think that this should be all good in v3. Pixi uses the standard JSON hash format. Let me know if this issue still exists! :+1:
