### ISSUE TITLE
Stop click event propagation

### ISSUE THREAD

**Issue by jagi** [GoodBoyDigital/pixi.js#1291]
Hi, I know that there was several topics about event bubbling and stoping its propagation but I have not found solution for my problem. Here is an example scene http://jsfiddle.net/Jagi/2az8rgr4/6/ with Box child added to the Stage. Both Box and Stage have `click` event assigned. When I click Box the click event is triggered first on the Stage and later on the Box. This is totally confusing. Event bubbling should work different way: `Box -> Stage -> Box`. Now it's `Stage -> Box`. More over I can't stop propagation. I've read about InteractionManager and maybe it's a way of solving my problem. But I haven't found any example of using it in proper way with Pixi 2.2. Could anyone help?

**Comment by GoodBoyDigital** [comment]
Hi there! pixi v3 now has ```event.stopPropegation()``` that should do just what you need :+1: enjoy!

**Comment by perara** [comment]
Would this also work with events like mousemove?

```coffeescript
x.mousemove =  (e) ->
    e.stopPropegation()
```
Does not seem to work in v3rc4 (undefined)

**Comment by jagi** [comment]
@GoodBoyDigital great to here!

**Comment by englercj** [comment]
@perara It wasn't added in rc4, was added to the latest dev.

**Comment by perara** [comment]
@englercj Thanks. Works fine!

**Comment by Shadowstep33** [comment]
Does stopPropagation() work between events? For example, if I have stage and box (box being a child of stage), and stage allows you to drag using mouseup, mousedown, and mousemove while box just has a click on it. If i use stopPropagation in the box click method, will it prevent all three events on stage? Or will it just prevent everything that would happen after the click fires (i.e. mouseup on stage)?

**Comment by englercj** [comment]
It should only prevent the `click` event, if it is stopping other events I would consider that a bug.

**Comment by Shadowstep33** [comment]
Cool thanks, that's what I thought but just wanted to make sure. Cheers!

**Comment by allenliao** [comment]
should be 
x.mousemove =  (e) ->
    e.stopPropagation()
not 
x.mousemove =  (e) ->
    e.stopPropegation()

**Comment by KosGrillis** [comment]
Is there a way to stop propagation of other events, specifically mouseover?
