### ISSUE TITLE
Wrong text height calculation

### ISSUE THREAD

**Issue by jagi** [GoodBoyDigital/pixi.js#1292]
I'm working with text and some letters are cut. It this example http://jsfiddle.net/Jagi/2az8rgr4/7/ letters `Ń` and `Ś` have their accent cut. The same with the letter `y`. However in my different project letters `Ń` and `Ś` display correctly but `y` is worse. Moreover I have the same font style in both situations but displaying letters differs. Why is that?

**Comment by jagi** [comment]
@motiz88 have you thought about implementing this polyfill with different approach then second parameter to `measureText` function? I think that to make it real poly fill it should behave exactly as original. I know that developer may not want all the properties of measure text but i JS we have getters on objects. So we could return object without any values calculated and only when developer tries to access some property it could be calculated. What about that?

**Comment by IridiumMaster** [comment]
Text display has cosmetically broken for me from 2.0 to 2.25 (latest version). The bottom of letters is getting chopped off in Chrome w/ canvas renderer. Here is a visual example:
![screen shot 2015-01-31 at 3 36 59 pm](https://cloud.githubusercontent.com/assets/4607679/5989933/26ac4864-a95f-11e4-9270-601da4569d3a.png)
Compare to -
![screen shot 2015-01-31 at 3 36 42 pm](https://cloud.githubusercontent.com/assets/4607679/5989936/3686ac52-a95f-11e4-8064-3d9d7ff605b7.png)

**Comment by GoodBoyDigital** [comment]
Howdy! I just added a padding property to style that should fix these issues if they pop up. The padding won't affect the position of the text itself it will simply give a bit more rendering room.
