### ISSUE TITLE
Sprite cacheAsBitmap inverted issue in WebGL

### ISSUE THREAD

**Issue by kambing86** [GoodBoyDigital/pixi.js#1293]
I found out this issue when tackling the BitmapText cacheAsBitmap issue, refer back to #1276

Any child inside a sprite are inverted if the sprite's cacheAsBitmap = true.

https://www.googledrive.com/host/0B31if-IJ9CXbQlFSQU1WcFc5Szg/index3.html

There is no issue in Canvas renderer.

I found the codes below look suspicious and replaced them like this

PIXI.RenderTexture.prototype.renderWebGL
```
//Lets create a nice matrix to apply to our display object. Frame buffers come in upside down so we need to flip the matrix 
    /*var wt = displayObject.worldTransform;
    wt.identity();
    wt.translate(0, this.projection.y * 2);
    if(matrix)wt.append(matrix);
    wt.scale(1,-1);*/
    var wt = displayObject.worldTransform;
    wt.identity();
    if(matrix)wt.append(matrix);
```
Then the sprite looks ok. But then if I set BitmapText.cacheAsBitmap = true, the texts got inverted.
Check the link below for the result
https://www.googledrive.com/host/0B31if-IJ9CXbQlFSQU1WcFc5Szg/index4.html

**Comment by lodr** [comment]
I've found a similar issue while masking. The mask is rendered with inverted Y. I was debugging pixi and I've found that inverting `renderSession.flipY` in [line 146](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/renderers/webgl/utils/WebGLStencilManager.js#L146) of `WebGLStencilManager.js` makes the trick.

**Comment by GoodBoyDigital** [comment]
All fixed now in v3 :+1: cheers all!
