### ISSUE TITLE
Calculate scaled width using getBounds()

### ISSUE THREAD

**Issue by jagi** [GoodBoyDigital/pixi.js#1297]
Hi,
is it normal (I seem that not) that scaled display object's width isn't equal width from `getLocalBounds` and `getBounds`? Let's take that example

```js
object.width; // 100
object.scale.set(0.5, 0.5);
object.width; // 50
var bounds = object.getBounds();
bounds; // width: 100
var localBounds = object.getLocalBounds();
localBounds; // width: 100
```

Width of the object takes into account scale property but `getBounds` and `getLocalBounds` doesn't.

**Comment by GoodBoyDigital** [comment]
Hi there @jagi 
Yes this is correct - 
getBounds will return the bounds of the object within the global scene graph 
getLocalBounds will return the bounds of the object as if it had no transform applied (its true bounds)

hope that makes sense! thanks !
