### ISSUE TITLE
Text width and height on high density screens

### ISSUE THREAD

**Issue by jagi** [GoodBoyDigital/pixi.js#1298]
Hi, I've noticed error in the `PIXI.Text` when resolution is set to 2. It creates two times bigger canvas than it should. When I force text resolution to be 1 it gives correct width and height of the text.

From what I was able to determine the problem is that display object's width is already multiplied by resolution (2) and it's multiplied again in `updateText()` function so the canvas is 4 times bigger than it would be if resolution was 1. And it should actually be only 2 times bigger, because resolution is 2.

To make it work properly I've wrote following code:
```js
var text = new PIXI.Text('test', {
  font: '100px Arial'
});
text.width; // 2 times to wide.
text.resolution = 1;
text.updateText();
text.width; // Correct width.
```

**Comment by shabanovd** [comment]
Hi, I'm experience problem in same area, but solution is opposite to your one. I have to set text.resolution = 2 manually, because it set properly only if text have dirty flag and rendered. Only then resolution set to required value from renderSession.

Resolution = 1 is not an option because text is blurry.

**Comment by jagi** [comment]
Have you initialised `Renderer` like this?

```js
var renderer = new PIXI.WebGLRenderer(width, height, {
  resolution: window.devicePixelRatio || 1
});
```

**Comment by shabanovd** [comment]
Yes, I do. The problem that texture's resolution variable is wrong till first rendering (and texture.baseTexture.resolution too). So, to solve I did manually set "resolution" on text and width & height divide by that resolution before use it value.

**Comment by jagi** [comment]
I've tried to investigate PIXI code if it goes about `resolution` property and I found following points in which error can be present.

There is `generateTexture` function that is called manually by programmer (it's not called by PIXI itself) when he/she want it to be cached as an image and not be rerendered each time http://www.goodboydigital.com/pixijs/docs/files/src_pixi_display_DisplayObject.js.html#l555. As you can see in line 569 there is following code:

```js
var renderTexture = new PIXI.RenderTexture(bounds.width | 0, bounds.height | 0, renderer, scaleMode, resolution);
```

It creates `RenderTexture` and is not only passing texture bounds but also information about resolution. So if we render texture manually everything should work but when we render sprite, text etc. on canvas using PIXI without using `generateTexture` function it looks as follows.

Cached sprite is generated using `_generateCachedSprite ` function in this line http://www.goodboydigital.com/pixijs/docs/files/src_pixi_display_DisplayObject.js.html#l639. As you can see if cache does not exist yet the following code is called.

```js
var renderTexture = new PIXI.RenderTexture(bounds.width | 0, bounds.height | 0);//, renderSession.renderer);
```

There is no information about resolution passed to `RenderTexture` constructor. So I assume that this is a point where we should look for error. But it was just quick investigation. I hope that someone from PIXI team will refer to this problem and my suggestion.

**Comment by jagi** [comment]
It strange that it doesn't work for you. It appears that in your situation `dirty` property of `PIXI.Text` is set to `false` at the text creation. And it should be `true` at the beginning because it's not rendered yet. Then it copies `resolution` property from `renderSession` and renders text sharp.

It if goes about my problem, text is rendered to texture with two times bigger resolution which is ok because I want to draw text on high density screen. Text is drawn correctly to canvas but information about width and height of `DisplayObject` are invalid.

**Comment by JiDW** [comment]
@jagi wow great ! Does your solution create a text with a pixel ratio of 2 or just put the correct size with a pixel ratio of 1 ?

I'm trying for months to display high density texts with PIXI but nobody answer to me : 

http://www.html5gamedevs.com/topic/10580-how-to-deal-with-pixel-ratio-and-pixitext/

**Comment by jagi** [comment]
Changing `resolution` to `1` only affects `width` calculation. It's change to `2` by PIXI whenever text needs updating. So you don't have to bother that you will break something. `PIXI.Text` width calculation is just made wrong. I don't know precisely how it works so I don't want to create pull request because it could break something else. However if you just want to get correct width of text you can set resolution to 1 just before taking width.

**Comment by JiDW** [comment]
Oh, I see. Well, aren't every displayobject width/height affected by resolution anyway ?

What I'm trying to do is to create a Text affected by current pixel ratio. There should be some way to tell pixi to create a PIXI.Text with a texture resolution different from 1.

**Comment by jagi** [comment]
The `resolution` is property on the level of texture. `PIXI.Text` is probably the only object that also contains `resolution` property. And unfortunately I was wrong in previous post. When you change `resolution` of `PIXI.Text` then it rerenders texture with resolution `1` so the width is correct then. However `width` calculation should take `resolution` into account and it isn't doing so right now.

In the `PIXI.Sprite` there is something like this:

```js
Object.defineProperty(PIXI.Sprite.prototype, 'width', {
    get: function() {
        return this.scale.x * this.texture.frame.width;
    }
});
```

But in `PIXI.Text` it's a little bit different however it still takes texture width without taking resolution into account.

```js
Object.defineProperty(PIXI.Text.prototype, 'width', {
    get: function() {
        if(this.dirty)
        {
            this.updateText();
            this.dirty = false;
        }

        return this.scale.x * this.texture.frame.width;
    }
});
```

To answer your question. When you set `resolution` to 2 on `PIXI.Text` it will create texture with higher density. The same as taking image with double resolution.

**Comment by JiDW** [comment]
I didn't realise PIXI.Text have a resolution property. I will toy with that, thanks for pointing it out !

However I do not get what difference you see between text width and sprite width ?

If you have a sprite with a texture resolution of 2, your width will be equal to the pixel width of your texture, not divided by a resolution.

**Comment by GoodBoyDigital** [comment]
This should be all good now in v3. Dimensions now remain the same regardless of resolution. cheers :+1:
