### ISSUE TITLE
Using renderTextures on more than one stage causes an error

### ISSUE THREAD

**Issue by positlabs** [GoodBoyDigital/pixi.js#1299]
I would think that renderer instances would be completely sandboxed from each other, but this bug only happens when I try to use renderTexture in multiple renderers.

The bug can be seen here: http://lightpaintlive.com/dist/

I can provide some code snippets if needed.

![screen shot 2014-12-27 at 10 59 05 am](https://cloud.githubusercontent.com/assets/1918844/5561693/aeced176-8db7-11e4-9a1b-dbf2f94d664f.png)

**Comment by positlabs** [comment]
Hmm.. I'm not going to have time to look into this any time soon. :(

**Comment by GoodBoyDigital** [comment]
You are now forced to pass a renderer to a renderTexture in v3. This should stop this error from occurring. cheers! :+1:

**Comment by positlabs** [comment]
Awesome, thanks! I will be using renderTextures everywhere now!
