### ISSUE TITLE
TilingSprite canvas rendering bug if using tileScale (fix proposed)

### ISSUE THREAD

**Issue by jounii** [GoodBoyDigital/pixi.js#1302]
If you use tileScale to draw tile in different size, on WebGL it works properly, but with Canvas rendering the sprite is positioned incorrectly. I tracked down and it seems the problem is incorrect order of context.scale() and context.translate() calls. Swapping the scale() to happen after translate() fixes this. However I'm not that familiar with PIXI internals or context draws how it order should be.

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/extras/TilingSprite.js#L255-L256

I'm using tiling sprite through PhaserJS, so I have to make a patch to the used PhaserJS version (PIXI bundled), however it would be nice if this fix would falldown to Phaser from PIXI.

**Comment by englercj** [comment]
Fixed by #1338
