### ISSUE TITLE
What is the difference between pixi.js and pixi.dev.js?

### ISSUE THREAD

**Issue by RubrikBonnier** [GoodBoyDigital/pixi.js#1304]
https://github.com/GoodBoyDigital/pixi.js/tree/master/bin

My first assumption was that pixi.dev.js is the "bleeding edge" dev version, while pixi.js is the latest stable and tested one. But it looks like it's more like pixi.js is the minified, for-distribution version and pixi.dev.js is the "for human reading" version of the same basic file.

But then... are both of them the latest stable or the latest "bleeding edge"? I want the latest stable.

**Comment by serprex** [comment]
https://www.atlassian.com/git/tutorials/using-branches

master is "stable", other branches with commits ahead of it could be deemed "bleeding edge". Particularly "dev"

**Comment by englercj** [comment]
`pixi.js` is minified, and to be used in production
`pixi.dev.js` is not, and to be used when developing you app.

`pixi.dev.js` is easier to debug since it is not minified. Both contain the same runtime code.

**Comment by gre** [comment]
I have a related question, I hope it is ok if I ask it here:

is pixi.dev.js accessible from browserify (and the npm published pixi's) ?
Also I think the general convention in npm / browserify world is to publish the unminified version as entry point and let the final user minify the whole thing.

Thanks

**Comment by englercj** [comment]
Feel free to put in a PR and change it :)

**Comment by gre** [comment]
PR sent :-)
Also I've taken a look at your current WIP of refactoring with commonjs, very promising work! :-)
I guess the issue I raised is already fixed out there ;-)
Cheers

**Comment by englercj** [comment]
yup!
