### ISSUE TITLE
Issue wite lineTo rendering strangely using WebGL

### ISSUE THREAD

**Issue by GBagley** [GoodBoyDigital/pixi.js#1306]
Add this question to StackOverflow:
http://stackoverflow.com/questions/27737165/issue-with-pixi-js-lineto-using-webgl

Thought I should file an issue here as well. Having an issue using where the lineTo method seems to draw lines that aren't specified. The bad lines aren't uniform width (seem to taper off towards the ends) and are much longer than they should be. Example jsfiddle showing the problem here:
http://jsfiddle.net/b1e48upd/1/

Using the canvas renderer gives correct results.

Trying to search for this problem, I've gathered that the WebGL renderer may have an issue with non-integer values (shown in the question here: http://stackoverflow.com/questions/23872565/pixi-js-lines-are-rendered-outside-dedicated-area), and I've also seen that sending consecutive lineTo commands to the same coordinates will cause issues, but my example doesn't have either of those. Same issue trying multiple browsers as well (Chrome and Firefox).

**Comment by edcarstens** [comment]
This is the same problem as a former ticket that was just reopened (ticket #1075)

**Comment by englercj** [comment]
Closing as a duplciate of #1075.
