### ISSUE TITLE
Shaders with more textures - wrong order of binding

### ISSUE THREAD

**Issue by TomTomson** [GoodBoyDigital/pixi.js#1308]
Although some issues regarding similar problems have been already closed, this problem still persists and I have managed to find out what is wrong (but not how to fix it).

When using filters (`sprite.filters`), everything works as expected. However when you use the filter as a shader directly (`sprite.shader`), the shaders which use **additional textures get broken**.

One of those examples is a `PIXI.DisplacementFilter` (but others which use textures are broken as well, including my own shaders). When you have a sprite with a `[stonewall]` texture and apply a shader with a `[displacement]` texture:

    var sprite = new PIXI.Sprite(stonewall);
    sprite.shader = new PIXI.DisplacementFilter(displacement);
    
The shader is broken because the order of applied textures is wrong. I used a WebGL Inspector extension for Chrome and found this:

![Shader](http://s28.postimg.org/veklhk6sd/pixijsshader.png)

What is going on?

    ...
    bindTexture(TEXTURE_2D, [displacement]) // mapped to 0
    uniform1i("displacementMap", 1)
    ...
    bindTexture(TEXTURE_2D, [stonewall]) // mapped to 1
    ...
    
What is the **correct order**:

    ...
    bindTexture(TEXTURE_2D, [stonewall]) // mapped to 0
    ...
    bindTexture(TEXTURE_2D, [displacement]) // mapped to 1
    uniform1i("displacementMap", 1)
    ...

**Comment by GoodBoyDigital** [comment]
All fixed in v3 now! :+1:

**Comment by merixstudio** [comment]
Hey, @GoodBoyDigital can you help us backport this fix to v2? Can this be done easily? Any guidance appreciated.

**Comment by englercj** [comment]
Hey @merixstudio, what is blocking you from upgrading to v3? The API is really similar, and upgrading is easy due to the [`deprecation`](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/deprecation.js) file that helps tell you in real time how to upgrade your app.

**Comment by merixstudio** [comment]
Main concern is stability. We have very big project, lots of custom stuff on top of PIXI (own Spine implementation, various shaders).

**Comment by englercj** [comment]
@merixstudio Right now the maintenance strategy for v2 is to implement fixes ad-hoc if they are critical and absolutely necessary. v2 is not organized in a way that makes it easy to make changes.

v3 has a lot less bugs than v2 had, and I would say more stable than v2. I recommend trying out an upgrade and seeing how that works for you. It sounds more scary than it actually is :) I was able to upgrade the Phaser game engine in less than an hour, and that is no small project.
