### ISSUE TITLE
A Closure Compiler issue related to Pixi.js that you might be interested in. (It fails to remove the exotic Pixi.js comments)

### ISSUE THREAD

**Issue by RubrikBonnier** [GoodBoyDigital/pixi.js#1312]
https://github.com/google/closure-compiler/issues/769

**Comment by NikkiKoole** [comment]
but the "exotic" pixi.js comments you want to remove is the license info !
In that info it for example states that the pixi.js is under a MIT License, which in itself states that:

`Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.`

So you can do almost everything with this opensource code under exactly one condition: include the license info. Which is the thing you  want to remove ;)

**Comment by englercj** [comment]
This is a closure compile bug, doesn't have anything to do with pixi. Thanks for the heads up though.
