### ISSUE TITLE
Very confused about contradicting code examples.

### ISSUE THREAD

**Issue by RubrikBonnier** [GoodBoyDigital/pixi.js#1314]
In the official sample code, I see this:

var bunnyTexture = PIXI.Texture.fromImage("bunny.png");

Why is there no new after the =? Isn't that required? If not, is this some special case? Is it needed in all other situations? I don't get it.

**Comment by drkibitz** [comment]
PIXI.Texture is a constructor, `fromImage` is a static factory method. e.g. `new PIXI.Texture()` vs `PIXI.Texture.fromImage()`

**Comment by TomTomson** [comment]
The `new PIXI.Texture()` is called *inside* the `PIXI.Texture.fromImage(...)`.

The `fromImage(...)` function creates a `new PIXI.Texture()`, puts the image from the file to that texture and then `return`s it.

*Is it needed in all other situations?* Depends. Usually not, but always consult [the docs](http://www.goodboydigital.com/pixijs/docs/classes/Texture.html). If it says `static` next to a function, it means that it works without the `new`.

**Comment by englercj** [comment]
I recommend reading about the [`new` keyword][new], as others have said it is used to create an instance of a constructor. The other is a static factory method that invokes it for you with some preset params.

Closing this as answered.

[new]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new
