### ISSUE TITLE
Small trouble with sprites

### ISSUE THREAD

**Issue by ceraroger** [GoodBoyDigital/pixi.js#1317]
Hi!
I'm new to pixi and my question may look stupid, sorry for it and for my bad English.
I'm trying to perform some simple operations, like in examples. And there I faced a little problem.
I'm trying add sprite to the stage, like this:
```
var texture = PIXI.Texture.fromImage(imgName),
sprite = new PIXI.Sprite(texture);
sprite.position.x = x;
sprite.position.y = y;
sprite.alpha = 0.5;
stage.addChild(sprite);
```
Animation loop already exists and theoretically sprite must appear at (x, y) whith alpha = 0.5, but it appears at (0, 0) with alpha = 1 for a moment and then disappears and appears again at defined position whith alpha = 0.5.
Not a big problem, but I can see it and I think something is wrong here.
Could you give me an advice, please?
Thanks.

**Comment by englercj** [comment]
Interesting, can you show a running example on jsFiddle or the like? Also what version are you using (latest dev, latest release)?

**Comment by ceraroger** [comment]
Thanks for the reply.
It's something like this:
http://jsfiddle.net/2r8o686w/3/
Need to press 'run', or image won't load. I couldn't use external images, so I just took jsfiddle logo :)
You can reproduce the effect by pressing the 'add sprite' button repeatedly, it won't happen on every click. Well, I hope you can. I can see it on Chrome 39, Firefox 34 and Opera 26.

I think i know what causes the problem. It occurs in jsfiddle only when the I'm using ```setTimeout```
I know this is bad practice, but in my case I'm working in local environment and images aren't loaded yet when I'm trying to add them.

I'm using bin/pixi.js from master branch.

**Comment by TomTomson** [comment]
It's because the default sprite position is `0,0` and you're adding the sprite to the stage *before* setting its position to the values you want.

So either do `stage.addChild(sprite)` *after* the texture is loaded (inside the timeout function), or temporarily set `sprite.visible = false` before you set the correct position.

**Comment by englercj** [comment]
@ceraroger, @TomTomson has the right of it. The code you linked as a sprite to the stage with position 0,0, then later comes back and changes the position. So you will see that flicker because it actually was at 0,0 for 10 ms while the setTimeout was waiting.

**Comment by ceraroger** [comment]
Oh...my bad, such a stupid mistake...
Thanks a lot!
