### ISSUE TITLE
Drawing a rounded rectangle in mask graphic produces an error in the canvas renderer

### ISSUE THREAD

**Issue by ianbjorndilling** [GoodBoyDigital/pixi.js#1321]
When drawing a rounded rectangle to a graphics object, **Uncaught TypeError: Cannot read property '0' of undefined** is produced when the graphics object is used as a mask. Here's a [fiddle](http://jsfiddle.net/3g772q1y/) reproducing the problem. 

It looks like the shape.points array is undefined when it is passed into CanvasGraphics.renderGraphicsMask.

**Comment by englercj** [comment]
I believe we fixed this issue in the dev-rewrite branch.
