### ISSUE TITLE
Resolution + RenderTexture Bug

### ISSUE THREAD

**Issue by amadeus** [GoodBoyDigital/pixi.js#1322]
I have found yet another issue when using the resolution property with RenderTexture class. I believe this issue may be somewhat related to issue #1215 since the results are somewhat the same (some botched transformations).

The premise is quite simple. I created a two sprites. One from an image, the other based on a RenderTexture that was rendered from the sprite.

If I leave the RenderTexture resolution to the default of 1, everything works as expected:

![working example - resolution @ 1](https://dl.dropboxusercontent.com/s/o2ekfk7fb0f7no0/PIXI_ResolutionRenderTexture_Bug_2015-01-04_22-35-51.png?dl=0)

However, if I change the resolution to 2 when I instantiate the RenderTexture, I get this result:

![broken example - resolution @ 2](https://dl.dropboxusercontent.com/s/al916mok2ys61jv/PIXI_ResolutionRenderTexture_Bug_2015-01-04_22-39-25.png?dl=0)

Here is the example fiddle, I left a comment on the line that can be played with:

http://jsfiddle.net/amadeus/s87s1c3w/

**Comment by GoodBoyDigital** [comment]
hi! Just tested this code with v3 and works like a champ in now. :+1:
