### ISSUE TITLE
question about pixilights (normal map generation)

### ISSUE THREAD

**Issue by NikkiKoole** [GoodBoyDigital/pixi.js#1323]
Hi, I was looking at @GoodBoyDigital 's new year's greet and I have a question about it, 

![png-1](https://cloud.githubusercontent.com/assets/453055/5612203/46eaf172-94d1-11e4-94d4-25c7562c069e.png)
![png](https://cloud.githubusercontent.com/assets/453055/5612204/484da0d2-94d1-11e4-9762-bb2f5baa283e.png)

The same question applies to the example in teh example folder:
How does one generate these bump map images?

![jpeg-1](https://cloud.githubusercontent.com/assets/453055/5612192/2e11928c-94d1-11e4-8113-1e0343d82adb.jpg)
![jpeg](https://cloud.githubusercontent.com/assets/453055/5612193/352e3282-94d1-11e4-9a90-abcbf8b3114d.jpg)

I've played around with a piece of software called CrazyBump, I remember  reading about it somewhere pixi related, but I cannot achieve the same results, am I right in thinking these images arre actually built using 3d software like blender and then rendering a top view or something ?

**Comment by englercj** [comment]
@NikkiKoole That is one way to do it (exporting the normals from a 3D object), there is also a tool coming out soon that will generate normals for 2D art:

http://www.html5gamedevs.com/topic/10950-dynamic-lighting-with-normal-maps-of-sprite-dlight/

**Comment by NikkiKoole** [comment]
I found out about that tool too, it looks wonderful, but somehow I don't think it can generate the same thing as those present boxes. When I use crazybump for this image : 
![untitled](https://cloud.githubusercontent.com/assets/453055/5616630/b920d0b0-9506-11e4-8afd-0f78cf27c5c9.png)

it creates:
![untitled_nrm](https://cloud.githubusercontent.com/assets/453055/5616636/bf48119c-9506-11e4-95aa-8647641370d8.png)

while actually I don't care at all about those dots and how they would be bumping the light, because they won't, the desired result is:
![untitled2](https://cloud.githubusercontent.com/assets/453055/5616641/d3796350-9506-11e4-8158-f251b75cd742.png)

So that does mean there is no way around installing blender and getting into that for such things I guess ;)

The example file in the examples folder I can achieve though with crazy bump:
![2e11928c-94d1-11e4-8113-1e0343d82adb](https://cloud.githubusercontent.com/assets/453055/5616664/2f90a4aa-9507-11e4-86e3-0b43badb437e.jpg)

turns to 
![2e11928c-94d1-11e4-8113-1e0343d82adb_nrm](https://cloud.githubusercontent.com/assets/453055/5616688/4e295ec0-9507-11e4-977a-52b9c2fd6ca6.png)
not an exact fit, but there are many tweaking possibilities for that, but I am just wondering about the boxes really, and how they are done.

**Comment by englercj** [comment]
In the case you are talking about you would need to model the object in 3D and export the normals.

**Comment by NikkiKoole** [comment]
Thanks for the clearance!, off to study 3d modelling, will be back in a decade ;)
