### ISSUE TITLE
TilingSprite._renderWebGL still calls updateWebGLTexture

### ISSUE THREAD

**Issue by photonstorm** [GoodBoyDigital/pixi.js#1324]
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/pixi/extras/TilingSprite.js#L171

`updateWebGLTexture` no longer exists as a function, which causes this to crash.

**Comment by englercj** [comment]
That should be `renderer.updateTexture()`, I'll release a hotfix real fast.
