### ISSUE TITLE
Wont render

### ISSUE THREAD

**Issue by Lord-Ford** [GoodBoyDigital/pixi.js#1330]
Hi.  I am following along with a tutorial (http://www.yeahbutisitflash.com/?p=5226) and when I try to render on google chrome the dev tools console shows this:

    Pixi.js v2.2.3 - webGL      http://www.pixijs.com/    ♥♥♥     pixi.dev.is:224    

referring to line# 224: console.log.apply(console, args);

this is my code: 
function init(){
	//console.log("It worked!");
	stage = new PIXI.Stage(0x66FF99);
	renderer = PIXI.autoDetectRenderer(
	512,
	384,
	document.getElementById("game-canvas")
	);
	renderer.render(stage);
	}

**Comment by englercj** [comment]
What is the issue you are having? You didn't post any errors and you added nothing to your stage so there isn't anything to render. What is the problem? 

The log you posted it just letting you know that pixi is running and with what renderer.

**Comment by Lord-Ford** [comment]
Nothing wrong with the program, user error.  I didn't set up a server
