### ISSUE TITLE
Missing feature: dash line

### ISSUE THREAD

**Issue by hmilyyang** [GoodBoyDigital/pixi.js#1333]
Can not draw dashed line?

**Comment by stbaer** [comment]
+1 for this feature. Would be very nice to have.

**Comment by mattdesl** [comment]
A function that does a lot of lineTo + moveTo operations could achieve a dashed line.

Internally, this is probably how it would be done in canvas2D. In WebGL you could do the same, or you could apply the dash in the fragment shader. The latter is more complicated and also leads to some unnecessary fill-rate, but costs less in terms of vertex bandwidth. Another approach is to use a repeating texture pattern to create the stippling.

IMHO this doesn't need to be part of Pixi, since there's so many ways that it can be implemented and exactly which solution you choose may heavily depend on your application.

**Comment by stbaer** [comment]
I can understand @mattdesl point of view and it's not too hard to implement a dash line for e.g. a straight line. But as I'm working on a project with pretty complex graphics including curves and splines it would be very nice to have this feature included in pixi. 

After the announcement of primitives for pixi @GoodBoyDigital said that  it's on the todo list (here in a comment: http://www.goodboydigital.com/pixi-webgl-primitives/). So I really hoped for it to arrive soon. 

And I also think that it would be nice for pixi to support at least the drawing operations that are available for canvas.

**Comment by GoodBoyDigital** [comment]
closing this for now as we have no plans to implement dotted lines just yet. Thanks!

**Comment by jeensshi** [comment]
i also met this problem,and solved it by simple way. here is the code:

    function drawdash(x0,y0,x1,y1,linewidth){
         var dashed = new PIXI.Graphics();
              dashed.lineStyle(1, 0x59e3e8, 1);    // linewidth,color,alpha
                dashed.moveTo(0, 0);
                dashed.lineTo(linewidth,0);
                dashed.moveTo(linewidth*1.5,0);
                dashed.lineTo(linewidth*2.5,0);
         var dashedtexture = dashed.generateCanvasTexture(1,1);
        var linelength=Math.pow(Math.pow(x1-x0,2)  + Math.pow(y1-y0,2) , 0.5);
        var tilingSprite = new PIXI.extras.TilingSprite(
            dashedtexture, linelength, linewidth
        );
        tilingSprite.x=x0;
        tilingSprite.y=y0;
        tilingSprite.rotation = angle(x0,y0,x1,y1)*Math.PI/180;
        tilingSprite.pivot.set(linewidth/2, linewidth/2);
        return tilingSprite;
        
        function angle(x0,y0,x1,y1){
            var diff_x = x1 - x0,
                diff_y = y1 - y0;
            return 360*Math.atan(diff_y/diff_x)/(2*Math.PI);
        }
    }

**Comment by jeensshi** [comment]
i also met this problem,and solved it by simple way.
here is the code:

function drawdash(x0,y0,x1,y1,linewidth){
     var dashed = new PIXI.Graphics();
          dashed.lineStyle(1, 0x59e3e8, 1);    // linewidth,color,alpha
            dashed.moveTo(0, 0);
            dashed.lineTo(linewidth,0);
            dashed.moveTo(linewidth*1.5,0);
            dashed.lineTo(linewidth*2.5,0);
     var dashedtexture = dashed.generateCanvasTexture(1,1);
    var linelength=Math.pow(Math.pow(x1-x0,2)  + Math.pow(y1-y0,2) , 0.5);
    var tilingSprite = new PIXI.extras.TilingSprite(
        dashedtexture, linelength, linewidth
    );
    tilingSprite.x=x0;
    tilingSprite.y=y0;
    tilingSprite.rotation = angle(x0,y0,x1,y1)*Math.PI/180;
    tilingSprite.pivot.set(linewidth/2, linewidth/2);
    return tilingSprite;
    
            function angle(x0,y0,x1,y1){
            var diff_x = Math.abs(x1 - x0),
                diff_y = Math.abs(y1 - y0);
            var cita;
            
            if(x1>x0){
                if(y1>y0){
                    
                    cita= 360*Math.atan(diff_y/diff_x)/(2*Math.PI);
                }else
                {
                    if(y1<y0){ 
                        cita=-360*Math.atan(diff_y/diff_x)/(2*Math.PI);
                    }else{  
                        cita=0;
                    }
                }
            }else
            {
                if(x1<x0){
                    if(y1>y0){
                        
                        cita=180-360*Math.atan(diff_y/diff_x)/(2*Math.PI);
                    }else
                    {
                        if(y1<y0){ 
                            cita=180+360*Math.atan(diff_y/diff_x)/(2*Math.PI);
                        }else{  
                            cita=180;
                        }
                    } 
                }else{  
                    
                    if(y1>y0){ 
                        cita=90;
                    }else
                    {
                        if(y1<y0){ 
                            cita=-90;
                        }else{  
                            cita=0;
                        }
                    }
                }
            }
            
            
            return cita;
        }
}
usage:

    var linewidth=5;
    var tilingSprite = drawdash(100,100,100,400,linewidth);
    app.stage.addChild(tilingSprite);
    app.ticker.add(function(delta) {
        tilingSprite.tilePosition.x += 0.5*delta;
    });
can it help?

**Comment by jeensshi** [comment]
i also met this problem,and solved it by simple way.
here is the code:

function drawdash(x0,y0,x1,y1,linewidth){
        var dashed = new PIXI.Graphics();
        dashed.lineStyle(1, 0x59e3e8, 1); // linewidth,color,alpha
        dashed.moveTo(0, 0);
        dashed.lineTo(linewidth,0);
        dashed.moveTo(linewidth1.5,0);
        dashed.lineTo(linewidth2.5,0);
        var dashedtexture = dashed.generateCanvasTexture(1,1);
        var linelength=Math.pow(Math.pow(x1-x0,2) + Math.pow(y1-y0,2) , 0.5);
        var tilingSprite = new PIXI.extras.TilingSprite(dashedtexture, linelength, linewidth);
        tilingSprite.x=x0;
        tilingSprite.y=y0;
        tilingSprite.rotation = angle(x0,y0,x1,y1)*Math.PI/180;
        tilingSprite.pivot.set(linewidth/2, linewidth/2);
        return tilingSprite;
        function angle(x0,y0,x1,y1){
        var diff_x = Math.abs(x1 - x0),
            diff_y = Math.abs(y1 - y0);
        var cita;
        if(x1>x0){
            if(y1>y0){
                cita= 360*Math.atan(diff_y/diff_x)/(2*Math.PI);
            }else
            {
                if(y1<y0){ 
                    cita=-360*Math.atan(diff_y/diff_x)/(2*Math.PI);
                }else{  
                    cita=0;
                }
            }
        }else
        {
            if(x1<x0){
                if(y1>y0){
                    cita=180-360*Math.atan(diff_y/diff_x)/(2*Math.PI);
                }else
                {
                    if(y1<y0){ 
                        cita=180+360*Math.atan(diff_y/diff_x)/(2*Math.PI);
                    }else{  
                        cita=180;
                    }
                } 
            }else{ 
                if(y1>y0){ 
                    cita=90;
                }else
                {
                    if(y1<y0){ 
                        cita=-90;
                    }else{  
                        cita=0;
                    }
                }
            }
        }
        return cita;
    }
}

usage:

var linewidth=5;
var tilingSprite = drawdash(100,100,100,400,linewidth);
app.stage.addChild(tilingSprite);
app.ticker.add(function(delta) {
    tilingSprite.tilePosition.x += 0.5*delta;
});

can it help?

**Comment by josephmcasey** [comment]
Is there any plan of revisiting this feature? It would be nice to have the functional parity with the CanvasRenderingContext2D.

**Comment by ErikSom** [comment]
If anyone is looking for this feature, here is my dashed-line implementation for drawing polygons.
https://codepen.io/unrealnl/pen/aYaxBW

**Comment by Bokos-** [comment]
Another simple example:

https://codepen.io/bokos/pen/EeBXgR?editors=0010

```javascript
PIXI.Graphics.prototype.drawDashLine = function(toX, toY, dash = 16, gap = 8) {
 const lastPosition = this.currentPath.shape.points;

  const currentPosition = {
    x: lastPosition[lastPosition.length - 2] || 0,
    y: lastPosition[lastPosition.length - 1] || 0
  };

  for (
    let iteration = 1;
    Math.abs(currentPosition.x) < Math.abs(toX) ||
    Math.abs(currentPosition.y) < Math.abs(toY);
    iteration += 1
  ) {
    if (iteration % 2 === 1) {
      currentPosition.x =
        currentPosition.x + dash < toX ? currentPosition.x + dash : toX;
      currentPosition.y =
        currentPosition.y + dash < toY ? currentPosition.y + dash : toY;

      this.lineTo(currentPosition.x, currentPosition.y);
    } else {
      currentPosition.x =
        currentPosition.x + gap < toX ? currentPosition.x + gap : toX;
      currentPosition.y =
        currentPosition.y + gap < toY ? currentPosition.y + gap : toY;
      this.moveTo(currentPosition.x, currentPosition.y);
    }
  }
};
```
