### ISSUE TITLE
PixiJS doesn't handle rotated img whereas TexturePacker use them

### ISSUE THREAD

**Issue by alamboley** [GoodBoyDigital/pixi.js#1335]
Hey guys,

With an update (don't know the specific one), TexturePacker auto-enables the rotation in the JSONHash format, and we can't remove it (via an option in TexturePacker).

Since PixiJS doesn't handle it, I get this error: `Error: Texture Error: frame does not fit inside the base Texture dimensions [object Object]`.

My solution is to use Phaser template which prevent rotation.

It's sad that TexturePacker don't show this checkbox... :(

**Comment by CodeAndWeb** [comment]
The checkbox is available - it's in the **advanced settings** of **Layout**:
![ember](https://cloud.githubusercontent.com/assets/716009/5665738/c4c5a192-975a-11e4-9af3-67608ffc9d48.png)

But I am of course happy to see support for rotated sprites added to PixiJS.

Btw: I would also like to add an "official" exporter for PixiJS to the framework selector during start.
Is there somebody to contact for icon and some questions? Please contact => support at codeandweb.com

**Comment by alamboley** [comment]
Wow, feeling like a noob right now! But we must admit that the issue reported by PixiJS wasn't easy to link ;)

**Comment by englercj** [comment]
You can email Mat (mat@goodboydigital.com) and CC me (chad@pantherdev.com).

We still should support rotation in the lib, which we haven't for a long time and it bugs me!

**Comment by GoodBoyDigital** [comment]
Me and @englercj banged our heads together and have come up with a neat way of handling this using the uvs in webGL. 

So yup, this is now supported in v3. Its currently only in webGL though so keeping this open until we nail canvas too.

**Comment by GoodBoyDigital** [comment]
All done in now! v3 handles rotated textures in both the webGL and Canvas renderer. Boom! :+1:
