### ISSUE TITLE
ColorMatrixFilter not multiplying RGB on A

### ISSUE THREAD

**Issue by MishaAmashukeli** [GoodBoyDigital/pixi.js#1342]
http://codepen.io/mishaa/pen/pvRLGJ
        var filter = new PIXI.ColorMatrixFilter();
        filter.matrix = [
            1, 0, 0, 0,
            0, 1, 0, 0,
            0, 0, 1, 0,
            0, 0, 0, 0
        ];
It's all zeroes in the alpha row but the sprite is still visible. The culprit is the blend mode.
From WebGLRenderer.js:
`PIXI.blendModesWebGL[PIXI.blendModes.NORMAL]        = [gl.ONE,       gl.ONE_MINUS_SRC_ALPHA];`

With this blend mode, if you set pixel's alpha to 0 in a shader, the pixel won't get fully transparent. You should multiply the RGB value to alpha value to get the correct transparency. But that's not intuitive and not all PIXI filters do that. 
So, should not it be `[gl.SRC_ALPHA,       gl.ONE_MINUS_SRC_ALPHA]` ?

**Comment by MishaAmashukeli** [comment]
Ok I read some more about this and appearantly this approach is called premultiplied alpha and it's a good thing. So it's the filters that need fixing, not blending.

**Comment by GoodBoyDigital** [comment]
Should be all good now in v3 I believe! :+1:

**Comment by mattlima** [comment]
Sorry to jump in on a closed issue, I've done a lot of research before posting here. I'm working on some recursive filtering in a project and I'm having a similar issue with alpha; There's not a ton of material on the behavior of the alpha channel in the color matrix filter; I've looked at the source and it seems very straightforward in that the alpha channel of pixels resulting from a matrix filter where indexes 15-19 are zero should be zero, i.e., the result should be a transparent sprite. This isn't the case.  I've updated the original codepen to pixi v3: http://codepen.io/mattlima/pen/LGOBmv – I'm sure you're insane busy but if you could point me in the right direction I'd really appreciate it.
