### ISSUE TITLE
Spine Skeleton Scale.

### ISSUE THREAD

**Issue by aholla** [GoodBoyDigital/pixi.js#1344]
Hi, I would like to be able to scale my Spine Skeletons but he data is parsed during the load process and the scale needs to be set before the parsing.

The simplest solution would be to use a global scale e.g. 
```
PIXI.SpineAnimScale = 1.0;
```
Then the user can adjust this before loading in the assets. Then just before the spine data is parsed, the scale is applied:
```javascript
// in JsonLoader.js Line 189.

// create a new instance of a spine texture loader for this spine object //
var textureLoader = new PIXI.SpineTextureLoader(this.url.substring(0, this.url.lastIndexOf('/')));
// create a spine atlas using the loaded text and a spine texture loader instance //
var spineAtlas = new spine.Atlas(this.ajaxRequest.responseText, textureLoader);
// now we use an atlas attachment loader //
var attachmentLoader = new spine.AtlasAttachmentLoader(spineAtlas);
// spine animation
var spineJsonParser = new spine.SkeletonJson(attachmentLoader);

// new -----------------
spineJsonParser.scale = PIXI.SpineAnimScale;
// --------------------

var skeletonData = spineJsonParser.readSkeletonData(originalLoader.json);

```

This is for changing the skeleton at runtime for using different sized texture atlases. For more info : http://esotericsoftware.com/spine-using-runtimes#Scaling

Thanks,

Adam

p.s. I have tested this and it works :)

**Comment by aholla** [comment]
Hi just to revisit this. I know spine how has it own repo but the "skeletonData" is created in the loader so this "scale" could be applied in the loader or moved and added somewhere in the new repo.

**Comment by englercj** [comment]
Tracking on pixi-spine.
