### ISSUE TITLE
Setting texture with Canvas on Sprite

### ISSUE THREAD

**Issue by shanemccartney** [GoodBoyDigital/pixi.js#1345]
Changing a texture at runtime with the texture property does not work with Canvas i.e.

if(this.isSelected){
		this.icon.texture = PIXI.Texture.fromImage("ui_sound_off_icon.png");
} else {
		this.icon.texture = PIXI.Texture.fromImage("ui_sound_on_icon.png");
}

This works as expected with WebGL

**Comment by GoodBoyDigital** [comment]
Hi @shanemccartney ! Hows it going man? 

Set texture should do the trick..

```
this.icon.setTexture( PIXI.Texture.fromImage("ui_sound_off_icon.png") );
```

The below will work correctly for version 3 when it is ready ( we are hard at work on it at the moment )
```
this.icon.texture = PIXI.Texture.fromImage("ui_sound_off_icon.png")
```

Cheers!

**Comment by shanemccartney** [comment]
Thanks was just about to remove this comment realising the bug was the method I was using. I looked into how you updated a Sprite with a MovieClip and went ahhh-huh!

Yes all is good bro its ben ages hey!

Look forward to version 3! Might post a few more issues I noticed hopefully simple to fix :)

**Comment by GoodBoyDigital** [comment]
Please do man! Helps us keep things improving at a decent pace :)
And yes it has been a while huh? Hope all is well over in Aussie land!

**Comment by englercj** [comment]
Closing this since it is fixed in v3, thanks for bringing this up! Never feel like you shouldn't post an issue, never a waste of our time!
