### ISSUE TITLE
Pixi is encapsulated in a 'Self Invoking Anonymous Function'...

### ISSUE THREAD

**Issue by aholla** [GoodBoyDigital/pixi.js#1348]
Hi, I was just trying to write a patch for my own project that would allow me to scale my spine data but I have found I cant overwrite stuff because it is all hidden within a function. See #1344

With the PIXI namespace this should not be necessary as the global scope would not be polluted.

Perhaps this is just related to the "spine" class. Because it is hidden within the function there is no way to reference it and therefore if I was to try and change how it is parsed, I have no reference to it.

Perhaps to use Spine, users should be required to load the library themselves rather than PIXI have a nested version.

Thanks.

**Comment by englercj** [comment]
You mean you can't override the spine implementation (not PIXI's but Esoteric's)? I'm confused as to what "stuff" you are referring to.

**Comment by aholla** [comment]
I want to change the function "PIXI.JsonLoader.prototype.onJSONLoaded" so that I can change what happens when spine data is loaded.

I want to have an external script called "pixi.patches.js" that I load after pixi and therefore overwriting this method.

The prolem is in my "patches" file, I have no reference to "spine" because it is being deglared inside the PIXI annon function.

When i run:

```javascript
        // spine animation
        var spineJsonParser = new spine.SkeletonJson();
        spineJsonParser.scale = 0.5;
        var skeletonData = spineJsonParser.readSkeletonData(this.json);
        PIXI.AnimCache[this.url] = skeletonData;
        this.onLoaded();
```

I get an error because spine is not in the global scope.

Either I could load the esotericsoftware version externally (is it the same?) so it is in the global scope or it needs to be accessible through the PIXI namespace.

Does that make sense?

**Comment by englercj** [comment]
Yes, so you are trying to access the internal spine runtime. We don't expose that in v2, but we can talk about doing it for v3.

The runtime is not the same as what you load from Esoteric directly, so that wouldn't work.

**Comment by aholla** [comment]
Yeah, I it might be a good idea because there are features that can be used (such as scaling) but it is not accessible. Would be good to have more control over this in V3 or perhaps make necessary modifications so that it can use the Esoteric version directly rather than having a custom version.

**Comment by alexh00** [comment]
Ha, I just ran into exactly the same problem! For now I'm working around it in my project by removing the self invoking function that wraps pixi since I don't need to use pixi that way. Glad to see somebody has already logged this as an issue.

**Comment by englercj** [comment]
Pixi's spine runtime is now exposed in v3.
