### ISSUE TITLE
NuGet package for pixi.js v2

### ISSUE THREAD

**Issue by nmehlei** [GoodBoyDigital/pixi.js#1354]
I am new to pixi.js and as such I may not understand the version tree correctly, but shouldn't there be a NuGet-accessible version of pixi.js v2? The only NuGet package I can find is for 1.4.1 (though updated just a few days ago).

**Comment by englercj** [comment]
We don't have an officially supported NuGet package. If there is one, it wasn't us who published it.

**Comment by englercj** [comment]
I don't think we will officially support one in the near future, but feel free to create a community supported one.
