### ISSUE TITLE
Putting a filter like displacementFilter on a group with many sub groups and sprites renders it white/transparent

### ISSUE THREAD

**Issue by bitplanets** [GoodBoyDigital/pixi.js#1356]
Putting a filter like displacementFilter on a group with many sub groups and sprites renders it white/transparent

    var displacementTexture = PIXI.Texture.fromImage(require("assets/images/displacementMAP.jpg"));
    displacementFilter = new PIXI.DisplacementFilter(displacementTexture);
    rootGroup.filters = [displacementFilter]

I've tried several filters and none works.

I've also put on phaser, but one of you can close this issue. https://github.com/photonstorm/phaser/issues/1546

Phaser 2.2.2; PIXI: 2.2.0; webgl

**Comment by GoodBoyDigital** [comment]
this should be licked for v3. Cheers for sharing your issue! :+1:
