### ISSUE TITLE
Explosion and shake filter? Or something similar?

### ISSUE THREAD

**Issue by bitplanets** [GoodBoyDigital/pixi.js#1357]

**Comment by englercj** [comment]
Does just moving position not work for you?

**Comment by bitplanets** [comment]
I was thinking of something that reshapes the world. Like a depth effect. Take a look at this game effect: http://www.indiedb.com/games/plannet
I know is more than a filter involved, but a filter could make the morph effect

**Comment by englercj** [comment]
Pretty sure you can accomplish that with the DisplacementFilter and some position manipulation.

http://www.goodboydigital.com/pixijs/examples/15/indexAll.html

**Comment by bitplanets** [comment]
I already do that:
https://www.youtube.com/watch?v=lwniWeeOBYo&index=1&list=PLXtZbf7h4-ubSEJWCrIrMems9lq3Sha8t

but will never look like an explosion

**Comment by englercj** [comment]
You can play around with something like this: http://www.geeks3d.com/20091116/shader-library-2d-shockwave-post-processing-filter-glsl/

**Comment by bitplanets** [comment]
This was what I've been talking about, thanks! The hard part will be to integrate this into a pixi filter...

**Comment by englercj** [comment]
@bitplanets Shouldn't be too bad, the frag shader is pretty much there which is most of the work. Just need to translate some of their uniforms to our uniforms/attributes that are passed in.

**Comment by bitplanets** [comment]
Ok, then you might accept a pull request for a filter like this

**Comment by englercj** [comment]
@bitplanets Sure if they go to the v3 (`dev-rewrite`) branch, I probably won't be merging any non-critical PRs to v2.

**Comment by bitplanets** [comment]
I have a question: but what about scaling the effect based on camera zoom is possible?

**Comment by englercj** [comment]
@bitplanets Anything is possible, its just software :)

**Comment by bitplanets** [comment]
The fragment source requires the vertex shader too. But there is no property in the AbstractFilter with vertexSrc for example. Where should I add that?

**Comment by englercj** [comment]
There isn't a way to specify a vertex shader in a filter in v2, in v3 you will be able to do that.

**Comment by bitplanets** [comment]
Thanks! Then until v3 this can't be done :-(

**Comment by englercj** [comment]
@bitplanets I'm curious why, the vertex shaders in those examples don't do anything custom. What do you need a custom vertex shader for in this filter?

**Comment by bitplanets** [comment]
Because the pixel shader uses this:

    vec2 uv = gl_TexCoord[0].xy;

Which is set in the vertex shader:

    gl_TexCoord[0] = gl_MultiTexCoord0;

**Comment by englercj** [comment]
That is sent to the fragment shader as a varying in pixi: `vTextureCoord`.

Like I said you won't be able to copy/paste these shaders, they need to be translated to pixi.

**Comment by englercj** [comment]
I've written this as a filter in v3 using this fragment shader:

```glsl
precision lowp float;

varying vec2 vTextureCoord;

uniform sampler2D uSampler;

uniform vec2 center;
uniform vec3 params; // 10.0, 0.8, 0.1
uniform float time;

void main()
{
  vec2 uv = vTextureCoord;
  vec2 texCoord = uv;

  float dist = distance(uv, center);

  if ( (dist <= (time + params.z)) && (dist >= (time - params.z)) )
  {
    float diff = (dist - time);
    float powDiff = 1.0 - pow(abs(diff*params.x), params.y);

    float diffTime = diff  * powDiff;
    vec2 diffUV = normalize(uv - center);
    texCoord = uv + (diffUV * diffTime);
  }

  gl_FragColor = texture2D(uSampler, texCoord);
}
```

You can find the full filter code at:

https://github.com/GoodBoyDigital/pixi.js/tree/dev-rewrite/src/filters/shockwave

It should be pretty easy to port to v2 if you need it now.

**Comment by bitplanets** [comment]
Thanks @englercj I really appreciate your work (: thanks a lot!

**Comment by englercj** [comment]
@bitplanets Anytime! I hope this effect works out for you, you can see it in action in the v3 [filter examples][ex].

[ex]: http://pixijs.github.io/examples/filters/#N4IgDgTgpgzlAuIBcIAiUBmBDArgG0QBoQBjPAezgBNls85joBbKJgIymhqVHW30Q8QABmShRSOgxABGWlnpRiAJnmLiAZjXSALNqUgArPuIA2EyADsFgBwWAnBZkSpBmXMkLpM1Z/WytJHgIHDc9P29jCLdzaOIZa2iAX3ixEBgASwAvKGQbFJBfUDY8HAhkGQ0AOlNLGRtLHXtmlub8zTSSsoANCura+sbW1ptiLogATT6auoam4baC8NAYeCgwZEMCqNAAD2RLQ2IATwOtszSsADsAczxcpCP0kgUHmQLE0BuILFOkd+IdiEGSuADdOIIASBHEIruQMnBkMIqudZBI9hVhCdMQV3Gl9khkU8/kTcUUQATnNjCVVRiAskiqlDKmk4GAMlgKrjliBxpisSBvlgqBkoFd4AAhUrlJCmYTCXE7EDXO4PJ4/EU4GCM1EyWIYmnEnVJE3EDDkPBUTjaoQAQRgJAyGQAYhkCJw0pBYAhkGhMLgCCBiGRKFBuMFQmaLVaIDbgKaQFLyOQmK73TLQF64II/fxA8GKNRkBGDObLdaxAmpWU02sM+BoNnfXwA0RSIWw8WQqXoxWeAmAMIW8gQADKazAtY9QizPpQLYEQfbofD3aj5djlYKQ7BFpw8Ay5CuU/rs5zC/zy6LQTXIDLMbjg4glBgAAksPASAALE+extz3NWyXENrxLdcHy3YhUARMA8CwEhWDFeBfxnf9z39RcCxXLtIzvXtN37ApUHIeBRxIaAxRQzM0ObDDLxAzsb1w+8+3jAoAHEfmOKiG29dC8zbBjV2Y/DHwKABJMEIR4s9aIE4CO2EnsNzE4gADl4TgGSaPnOjBMUnDlIgwjiAABQyXYoDgtZtL4uSgKw0DbxYgi2OIAAldiJVHWCMmQt06z/OzdPkxzGLAvCVMgkBRy/cgSAAawAdywcFbKbEKHKvRjXHA1iE1HdYOXSgCL307CmKM/KClHJgsAgSVpRK/isqEwy8tchMABUAtijIMH89MgoywDMOypSOtUkAuqShFBsC1DgtG+iDMqyatxNIAAA

**Comment by bitplanets** [comment]
Thanks, amazing! I will put in my game as soon as I will end my current back end and testing stuff (:

**Comment by bitplanets** [comment]
I think it could have a curve parameter too, what do you think?

**Comment by englercj** [comment]
@bitplanets The `time` uniform controls the expansion speed, just update the `time` slower and it will move slower. The `params` vector will control the shape of the wave.

**Comment by bitplanets** [comment]
Ok, thanks (:
