### ISSUE TITLE
[Fix] Error in Multiply blend mode in WebGL

### ISSUE THREAD

**Issue by X-Ryl669** [GoodBoyDigital/pixi.js#1361]
Current Multiply blend mode should be "out.[rgba] = inA.[rgb] * inB.[rgb], 1" (from the Multiply layer blend mode formula)

So the code should read:
    // FIX PIXIJS bug, multiply is: out = src * dst, alpha = 1.0
    PIXI.blendModesWebGL[PIXI.blendModes.MULTIPLY] = [renderer.gl.SRC_COLOR, renderer.gl.ONE];

So the out color is dst*src, alpha = 1 as expected.

**Comment by GoodBoyDigital** [comment]
Hi @X-Ryl669, the webGL multiply works pretty much identically ( from a visual point of view at least! ) as the canvas multiply blendMode so we will be keeping it as is for now. Thanks for sharing :+1:

**Comment by X-Ryl669** [comment]
Actually, it's wrong, please recheck. In canvas, multiply compositing is source*dest (check canvas specifications). If you want the same in WebGL, you must set SRC_COLOR * DST_COLOR (and 1 for alpha, since WebGL expect pre-multiplied alpha already).

**Comment by GoodBoyDigital** [comment]
cool - maybe I set the blendmode incorrectly when I tested, when you say:

you must set SRC_COLOR * DST_COLOR (and 1 for alpha, since WebGL expect pre-multiplied alpha already)

do you mean:

```this.blendModes[CONST.blendModes.MULTIPLY]      = [gl. SRC_COLOR, gl. DST_COLOR];``` ?

Thanks!

**Comment by X-Ryl669** [comment]
Actually, it seems that:
```
this.blendModes[CONST.blendModes.MULTIPLY] = [gl.DST_COLOR, gl.ZERO];
```
is what we need. 
WebGL blend functions are confusing because source and destination is swapped compared to PixiJS's role (you blend destination over a source in PixiJS while in WebGL you blend a source over a destination), but this is what I've found:

>      gl.blendFunc(gl.SRC_ALPHA, gl.ONE);
>The parameters to this function define how the blending is done. This is fiddly, but not difficult. Firstly, let’s define two terms: the source fragment is the one that we’re drawing right now, and the destination fragment is the one that’s already in the frame buffer. The first parameter to the gl.blendFunc determines the source factor, and the second the destination factor; these factors are numbers used in the blending function. In this case, we’re saying that the source factor is the source fragment’s alpha value, and the destination factor is a constant value of one. There are other possibilities; for example, if you use SRC_COLOR to specify the source colour, you wind up with separate source factors for the red, green, blue and alpha values, each of which is equal to the original RGBA components.

>Now, let’s imagine that WebGL is trying to work out the colour of a fragment when it has a destination with RGBA values of (Rd, Gd, Bd, Ad) and an incoming source fragment with values (Rs, Gs, Bs, As).

>In addition, let’s say that we’ve got RGBA source factors of (Sr, Sg, Sb, Sa) and destination factors of (Dr, Dg, Db, Da)

>For each colour component WebGL will calculate as follows:
```
Rresult = Rs * Sr + Rd * Dr
Gresult = Gs * Sg + Gd * Dg
Bresult = Bs * Sb + Bd * Db
Aresult = As * Sa + Ad * Da
```

So, in our case, we want:
```
Rresult = Rs * Rd + Rd * 0
Gresult = Gs * Gd + Gd * 0
Bresult = Bs * Bd + Bd * 0
Aresult = As * Ad + Ad * 0
```
But I tested this in PixiJS, and it does not give correct result. It seems something is doing bad thing afterward, and I can't figure out. Right now, I get the expected output when setting SRC_COLOR for both parameters, which does not make any sense at all.

**Comment by ivanpopelyshev** [comment]
This shit is still not fixed. Reopen?
