### ISSUE TITLE
Shouldn't blendMode.NORMAL be [gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA]??

### ISSUE THREAD

**Issue by edankwan** [GoodBoyDigital/pixi.js#1362]
fragment shader:
color.a = vTextureCoord.x;

Fixed preview:
http://jsfiddle.net/fkuxvywa/

**Comment by MishaAmashukeli** [comment]
Is this really a bug? This seems to be the correct approach actually - http://blogs.msdn.com/b/shawnhar/archive/2009/11/06/premultiplied-alpha.aspx

You can modify your shader this way:
http://jsfiddle.net/gk8vs9a1/

```
    color.rgb = color.rgb / (color.a + 0.0000000001);
    color.a = vTextureCoord.x;
    color.rgb = color.rgb  * color.a;

**Comment by edankwan** [comment]
Yes and no I think. The current one is more flexible but the blendmode "normal" should behave just like in Photoshop normal. Maybe use "none" for the current one and "normal" be the I suggested seems more appropriate.
