### ISSUE TITLE
TypeError when crop a Texture

### ISSUE THREAD

**Issue by Icemic** [GoodBoyDigital/pixi.js#1367]
my codes:

    var bg2Texture = PIXI.Texture.fromImage('./res/BG25a_1280.jpg');
    var bg2Texture_ = PIXI.Texture(bg2Texture,new PIXI.Rectangle(0,0,15,30));
    var bg2 = new PIXI.Sprite(bg2Texture_);

It says: 

    Uncaught TypeError: Cannot call method 'bind' of undefined

But when i try to run  *var bg2Texture_ = PIXI.Texture(bg2Texture,new PIXI.Rectangle(0,0,15,30));* in console, it says: 

    TypeError: Object #<Object> has no method 'setFrame'

What should i do?

**Comment by englercj** [comment]
```js
var bg2Texture_ = PIXI.Texture(bg2Texture,new PIXI.Rectangle(0,0,15,30));
```

This line is incorrect, you forgot to use the `new` keyword:

```js
var bg2Texture_ = new PIXI.Texture(bg2Texture,new PIXI.Rectangle(0,0,15,30));
```

Without it you are running the ctor with a bad context and will get errors.
