### ISSUE TITLE
TilingSprite doesn't use texture resolution

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1371]
Hi,

When creating a tilingsprite from a texture with a resolution different from 1, you expect to get a tilingsprite with the same resolution.

At this time, it is always 1.

generateTilingTexture should use the resolution of its source texture or provide a way to specify the resolution, like PIXI.Text

**Comment by englercj** [comment]
I'm pretty sure this has been fixed in v3, @GoodBoyDigital can you confirm?

**Comment by GoodBoyDigital** [comment]
yup - licked this in v3. :+1:
