### ISSUE TITLE
DisplayObjectContainer getBounds doesn't return the correct height when resolution != 1

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1372]
Hi,

Here is a fiddle (from our game, pardon my french) : http://jsfiddle.net/n0n6jLs2/2/

When resolution is set to 2, I get incorrect value for the height of my DOC.
I thought it was because of the tilingsprites (see #1371 ) but I have the same issue when I remove them.

say 640*354 with res = 2
say 320*327 with res = 1

Regards.

**Comment by GoodBoyDigital** [comment]
this has been sorted for v3! thanks for sharing :+1:
