### ISSUE TITLE
Displacement filter y value is incorrect.

### ISSUE THREAD

**Issue by aholla** [GoodBoyDigital/pixi.js#1373]
I was just doing a test with the displacement filter, creating a magnifying glass. I found the x scale worked correctly, expanded the view but the y worked in the opposite direction, pinching the view.

Using the following texture, it should create a bubble effect but the y is wrong.

To fix this the material.y has to be subtracted from the textureCoor instead of added. Change:

```javascript
gl_FragColor = texture2D(uSampler, vec2(vTextureCoord.x + matSample.x, vTextureCoord.y + matSample.y));',
```

to:

```javascript
gl_FragColor = texture2D(uSampler, vec2(vTextureCoord.x + matSample.x, vTextureCoord.y - matSample.y));', // the "matSample.y" is now subtracted from the "TextureCoord.y" instead of added.
```

**Comment by GoodBoyDigital** [comment]
Displacement map now working in v3!
its now super easy to use as you now pass a sprite in as the source. enjoy! :+1:
