### ISSUE TITLE
Events with PIXI+Cocoonjs returns incorrect values when resolution >1

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1374]
Hello,

This is a PIXI bug as PIXI use a if-test for cocoonjs where this bug happens

```javascript
if (navigator.isCocoonJS && !rect.left && !rect.top && !event.target.style.width && !event.target.style.height)
        {
            //Support for CocoonJS fullscreen scale modes
            touchData.global.x = touchEvent.clientX;
            touchData.global.y = touchEvent.clientY;
        }
```

These values should be divided by this.resolution.

**Comment by JiDW** [comment]
Update : This bug occurs with the official cocoonjs launcher but not once the code is compiled in an APK.

The behaviors of both should be the same so I'm writing to Ludei to know what behavior is correct and on what side will they update the behavior of the event.

**Comment by JiDW** [comment]
Update : The behavior isn't the same because of the cocoonjs scale mode.

No scale = no need to divide by the resolution. PIXI works.
Any type of scale = need to divide by resolution.

So it may be a cocoonjs bug, depending on what values are correct. Still waiting for their answer before   this issue can be closed or confirmed.

**Comment by GoodBoyDigital** [comment]
Hi @JiDW I think this may have been a pixi issue - should be fixed in v3 now. Let me know if this is not the case. Thanks!
