### ISSUE TITLE
hitTest returns incorrect values when resolution > 1

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1375]
The width and height of Sprite is not divided by the resolution (this is normal) and hitTest doesn't know it (this is not).
So when you have a resolution > 1, the hitBox of sprites are larger than the displayed sprite.

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/InteractionManager.js#L623

```javascript
 else if(item instanceof PIXI.Sprite)
    {
        var width = item.texture.frame.width;
        var height = item.texture.frame.height;
        var x1 = -width * item.anchor.x;
        var y1;

        if (x > x1 && x < x1 + width)
        {
            y1 = -height * item.anchor.y;

            if (y > y1 && y < y1 + height)
            {
                // set the target property if a hit is true!
                return true;
            }
        }
    }
```

width and height should be divided by the resolution..

**Comment by GoodBoyDigital** [comment]
should be all good for v3 now! :+1:
