### ISSUE TITLE
Is this me or MovieClip is broken?

### ISSUE THREAD

**Issue by Hypher** [GoodBoyDigital/pixi.js#1376]
MovieClip uses updateTransform to add a constant to currentFrame each frame. This is discussed here #471 and I agree it should rely on delta time. (milestone 1.6?)

Second problem, updateTransform is called by DisplayObjectContainer::getLocalBounds (which is called when accessing width or height accessors). So when accessing them, it artificially speeds up the animation!

And third problem: why does it rounds currentFrame? It should floor it!
With a 3 textures animation and suppose each frame take 1 second.
Texture 0 is shown 0.5 seconds, texture 1 is shown 1 second, and texture 2 is shown 1 second, then the animation loops.

**Comment by GoodBoyDigital** [comment]
all valid points! thanks for sharing @Hypher :+1: 
this will get looked at for v3.

**Comment by GoodBoyDigital** [comment]
All in addressed for v3 :+1: thanks again for sharing!
