### ISSUE TITLE
TilingSprite with mask crashes in Canvas renderer

### ISSUE THREAD

**Issue by richpixel** [GoodBoyDigital/pixi.js#1378]
I'm using Phaser 2.2.1, that uses PIXI 2.2.0 

PIXI is crashing when attempting to render a TilingSprite that has a mask, in the canvas renderer.

The call stack winds up here:

PIXI.CanvasMaskManager.prototype.pushMask = function(maskData, renderSession)

and the line that fails:

var context = renderSession.context;
context.save(); // crash

After a quick glance of the code, it appears that the param 'renderSesstion' is actually passed a 'context'  (CanvasRenderingContext2D) so it fails to get a context out of a context :(

So it seems its just passing the wrong param to here and an easy fix.

**Comment by englercj** [comment]
Looks line the line that is broken is:

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/pixi/extras/TilingSprite.js#L209

I can hotfix this, but it is not an issue in v3 anymore.
