### ISSUE TITLE
Chrome Mobile crash with TileSprites & WebGL (memory leak)

### ISSUE THREAD

**Issue by chacal** [GoodBoyDigital/pixi.js#1381]
I'm using TileSprites in my Phaser project to create parallax scrolling background. My game crashes the Chrome Mobile on Nexus 7 when re-creating them. Crashes do not occur when rendering mode is changed from WebGL to Canvas.

I created a small sample project that highlights the issue: https://github.com/chacal/phaser_nexus_test
Project is live at: http://chacal.github.io/phaser_nexus_test/

I think the problem has something to do with releasing memory/textures as I get out of memory errors in Android logs:

    W/Adreno-GSL(25812): <sharedmem_gpumem_alloc_id:1431>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
    E/Adreno-GSL(25812): <ioctl_kgsl_sharedmem_alloc:1532>: ioctl_kgsl_sharedmem_alloc: FATAL ERROR : (null)

If I remove the TileSprites from the sample project, the problem goes away. Also using fewer TileSprites increases the time before crashing (probably because the memory is not exhausted as quickly?).

I opened a Phaser issue about this as well: https://github.com/photonstorm/phaser/issues/1563

**Comment by englercj** [comment]
I profiled the code a bit and seems like baseTextures are leaking into the cache. If you click to reset a few times then open the dev console and run `PIXI.BaseTextureCache` and inspect that object you will see there are a bunch of base textures created from a canvas.

Basically the way tiling sprite works for WebGL is by drawing the tiled texture to a canvas buffer and using that as the single texture to draw. The destroy function of `PIXI.TilingSprite` is not cleaning up that texture, but even if it was Phaser isn't calling the parent destroy for it's `Phaser.TileSprite`. To fix this we need to fix our destroy method, and @photonstorm needs to make `Phaser.TileSprite` call the parent destroy function so resources are cleaned properly.

I'll hotfix pixi's portion of this now.

**Comment by englercj** [comment]
Published v2.2.5 with these fixes in it.

**Comment by AdrianDroid** [comment]
Still happening in all browser and all device. 

 http://chacal.github.io/phaser_nexus_test/
multiple click on canvas will crash ALL the mobile browser i have tested.

**Comment by englercj** [comment]
The demo you gave is using pixi v2, which is no longer supported and most of the leaks I see in the heap allocations profile are phaser/p2 related.

**Comment by photonstorm** [comment]
It's a very out-dated version of Phaser (and P2) at that.

**Comment by englercj** [comment]
Exactly.
