### ISSUE TITLE
WebGL rendering artifacts

### ISSUE THREAD

**Issue by bulkan** [GoodBoyDigital/pixi.js#1382]
Hi there,

When I use `autoDetectRenderer` which gives me a webgl renderer I get artifacts (lines across dots). I've recorded a [video](https://www.youtube.com/watch?v=CchHjChL058&feature=youtu.be) to demonstrate the problem.

The code can be found [here](github.com/bulkan/mira) and a demo using `CanvasRenderer` [here](http://bulkan-evcimen.com/mira.html).

I am not sure what I am doing wrong and any help will be appreciated.

**Comment by NikkiKoole** [comment]
ikt looks like the same issue as mentioned : https://github.com/GoodBoyDigital/pixi.js/issues/1076

**Comment by bulkan** [comment]
Interestingly using webGL renderer with `drawRect` causes the browser to crash after ~5500 `drawRect` calls

**Comment by englercj** [comment]
Closing to trac in #1076.
