### ISSUE TITLE
Rectangle.contains is using incorrect width.height comparison

### ISSUE THREAD

**Issue by beeglebug** [GoodBoyDigital/pixi.js#1384]
`Rectangle.contains` is currently testing that `x <= x1 + this.width`, where `x1` is the rectangle position, and the same for y/height.

This means that a Rectangle at position 0,0, with a width and height of 8, will return true for a point at 8,8, which is actually outside the rectangle. 

Basically, the test should just be `<`, not `<=`.

**Comment by englercj** [comment]
Actually it means the point is on the edge of the rectangle, which we consider "contained" in the rectangle.

**Comment by beeglebug** [comment]
I don't think it is though. This is easier to picture if you think of a
very small rectangle in pure pixel terms.

A 1x4 rectangle drawn at 0,0 will fill pixels 0,0 0,1 0,2 and 0,3. So a hit
test against 0,4 should return false, but in the above mentioned code it
would return true, as 4 is less than or equal to 0 + 4.

I'm on my phone at the moment, but as soon as I get on my PC in the morning
I can make a test to show what I mean.

**Comment by englercj** [comment]
I get what you are saying, we will probably be switching to an external lib for geom in v3 hopefully that will not have the same issue.

**Comment by beeglebug** [comment]
What's the ETA on v3? Would you open to a quick PR for this in the meantime?

**Comment by englercj** [comment]
v3 is slated for mid-february (hopefully in time for Valentines Day). I'll fix this in v3 for now.
