### ISSUE TITLE
Pixi 2 Maintanence Release, Is This Possible?

### ISSUE THREAD

**Issue by amadeus** [GoodBoyDigital/pixi.js#1385]
This is sort of a general post since I am not sure where the appropriate place to put it would be, given that it is sort of inter-related to both Pixi and Phaser. Also, I may be the only person with these concerns, but I figured I would post here in case there are others in a similar boat.

It seems that both Pixi and Phaser are both essentially being re-written for their impending 3.0 releases. Obviously Pixi v3 is much sooner on the horizon and the work underway I think is great and important to the future of Pixi.

Phaser on the other hand, is also incurring a rewrite, but it is still very early in development. They are of course also building their own renderer (moving away from Pixi), and going to be re-architecting quite a bit based on their learnings over the last couple years. I think this is also important and inevitable for the sustained future of Phaser. Phaser's release however, is much further in the future (probably at minimum, a summer release if all goes well.)

Where all this gets complicated is in the current version of Phaser. And while this is in some ways a Phaser issue, all the bugs I have discovered recently have been on the Pixi side of things. The two issues I have reported are #1322 and #1215. I also today discovered another issue with RenderTexture and Safari/iOS browers (which I will report soon with a reproducible test case.)

All of these issues are pretty important for a project I am working on. In fact, nearly show-stoppers. I may have a couple creative work arounds, but getting these issues fixed are pretty important to me. Of course however, I understand this is an open source project, and you guys owe me nothing, so I don't want to come across as self-centered or ungrateful. I am very thankful for all the incredible work you guys have done to make these projects as great as they are.

However, given the nature of both of these combined projects impending major updates/rewrites, I was wondering if you guys would consider at least few maintenance updates for Pixi 2. Obviously no new features should be expected, but I do think it could help greatly for Phaser users in the upcoming months.

/cc @photonstorm

**Comment by englercj** [comment]
I will be branching master into a `v2.x` branch when we release v3, and maint will continue on that branch. Support will be minimal, but we will try to help people not have a terrible time with it.

Features in v3 will almost certainly not be back-ported and many bug fixes we got from our refactor will not either. Keep in mind as well that even Phaser 2 uses a fork of pixi and not our main-line. Our maintenance policy won't effect that project very much.

**Comment by photonstorm** [comment]
FWIW I haven't totally ruled out merging Pixi 3 with Phaser 2. It all just depends on how much of a ballache it is vs. quantity of issues it will resolve. Lots of the Pixi issues v3 currently fixes aren't areas Phaser even uses (geom, loader, interactions, etc) and some of the more obscure rendering issues v2 has are as-yet un-fixed in v3 anyway, although I guess the chance of them being fixed longer-term is much greater.

Unlike with previous Pixi releases were we've nearly always been *ahead* of Pixi main line, I'll give v3 a good period of time to bake-in first before exploring merging with Phaser 2.

I would expect it would be in everyones interest if Pixi v2 remains maintained, for a while at least anyway, as there must be plenty of projects in flight for it that won't be trivial or cost-effective to port to Pixi v3. However, there are only so many hours in the day.

**Comment by englercj** [comment]
> I would expect it would be in everyones interest if Pixi v2 remains maintained, for a while at least anyway, as there must be plenty of projects in flight for it that won't be trivial or cost-effective to port to Pixi v3. 

That is my current thinking, that we will try to tackle roadblocking issues for people. But I can't imagine we will be fixing the 150 issues in the backlog in v2. We will try to hit a lot of them for the v3 release (and eventually all of them).

**Comment by amadeus** [comment]
Thanks so much for the detailed replies! It's a daunting task to manage open source projects at these scales.

I have a strong knowledge of JavaScript and Canvas 2D, but I am still just starting to learn WebGL. I will certainly experiment and see if I can contribute to fixing these more outstanding issues. 

Is it safe to assume you guys won't be accepting any 2.x fixes until v3 is out?

**Comment by englercj** [comment]
@amadeus No I'm going to move the branches around right now, so we have a maint branch that you can pull to. Give me a few minutes.

**Comment by englercj** [comment]
OK:

- `master` is the release branch (as usual)
- `v2.x` is the v2 maintenance branch
- `dev` is the latest development (v3) branch

**Comment by amadeus** [comment]
@englercj You rock, thanks so much!
