### ISSUE TITLE
PIXI.graphics vs PIXI.sprite application ?

### ISSUE THREAD

**Issue by SebKaine** [GoodBoyDigital/pixi.js#1390]
Hi guys,

I am working on building a **complete GUI with PIXI**. The goal to achieve is to Build:
* Button
* Menu
* Panels
* Sliders
* Tab ....

Initially i was planning to do everything with **PIXI.graphics**. In fact as it is the tool for basic 2D drawing i thought it was the **lightest/fastest** tool to draw thing with WebGL. Basically to me when you do something like this :

```
// draw rectangle
var rectangle = new PIXI.Graphics();
rectangle.beginFill( 0xffffff );
rectangle.moveTo( 0, 0 );
rectangle.lineTo( 0, 10);
rectangle.lineTo( 10, 10);
rectangle.lineTo( 10, 0 );
rectangle.endFill();
```

I thought that something like this was done in the back

```
squareVertexPositionBuffer = gl.createBuffer();
gl.bindBuffer(gl.ARRAY_BUFFER, squareVertexPositionBuffer);
vertices = [
     0.0,   0.0,   0.0,
     0.0,  10.0,  0.0,
    10.0, 10.0,  0.0,
    10.0,   0.0,  0.0
];
gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(vertices), gl.STATIC_DRAW);
squareVertexPositionBuffer.itemSize = 3;
squareVertexPositionBuffer.numItems = 4;

squareVertexColorBuffer = gl.createBuffer();
gl.bindBuffer(gl.ARRAY_BUFFER, squareVertexColorBuffer);
colors = []
for (var i=0; i < 4; i++) {
  colors = colors.concat([1.0, 1.0, 1.0, 1.0]);
}
gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(colors), gl.STATIC_DRAW);
squareVertexColorBuffer.itemSize = 4;
squareVertexColorBuffer.numItems = 4;
```

But the more i dive in the **Exemples** and the **Topics** about **Interactivity**, the more i see people tend to use **sprite** for nearly everything. 

So would it be possible to have some advise on what is **best choice beetween Graphics and Sprite to draw UI element**. The most important point are :
- Lightest as possible
- fastest as possible
- lowest bandwidth consumption

Intuitively i see no reason why sprite would be faster than **direct gl.draw call** as you can't be as low level as saying to your GPU put me a rectangle here  ... :)

Thanks for your time !

Cheers

Emmanuel

**Comment by SebKaine** [comment]
This answer pretty well my question
http://www.html5gamedevs.com/topic/2851-sprites-or-graphics/

so intuition is sometime bad ... :) Sprite looks to be the way to go for fast graphics rendering. What i don't like with texture is that it scale bad, it destroy any flexibility to modify the color of the UI by the users.

**Comment by englercj** [comment]
Hope you got the infos you needed! :)
