### ISSUE TITLE
PIXI.Text doesn't update gl textures when text changes

### ISSUE THREAD

**Issue by serprex** [GoodBoyDigital/pixi.js#1391]
Instead dimensions would change & stretch previous texture to dimensions

I've personally been able to fix with "this.texture.baseTexture._glTextures = {};" at the end of Text.updateTexture, but I'm sure someone else knows the more correct way to handle this

**Comment by englercj** [comment]
Just so you are aware: text, spine, and interactions are the 3 remaining features we have not yet refactored. They are expected to be broken right now.

**Comment by serprex** [comment]
My primary concern is whether assigning _glTextures to {} causes a memory leak, as I've been trying to port oetg to v3 & fixing issues I run into along the way

**Comment by GoodBoyDigital** [comment]
@serprex yes - this would cause a big of a memory leak! As all textures would still exist on the GPU..

**Comment by englercj** [comment]
@serprex You will leak using that code, you should use the `needsUpdate` property I mentioned before.

**Comment by serprex** [comment]
Setting needsUpdate didn't work, it was what I tried first. Will look into having needsUpdate clear _glTextures properly

**Comment by englercj** [comment]
it doesn't clear _glTextures, it doesn't need to. It needs to update them, which is what it does.

**Comment by GoodBoyDigital** [comment]
all good in v3 now :+1:
