### ISSUE TITLE
baseTexture.source is undefined with WebGLRenderer

### ISSUE THREAD

**Issue by smakinson** [GoodBoyDigital/pixi.js#1393]
I am trying to use a RenderTexture for a TilingSprite's texture. If I use a CanvasRender it shows up fine, but if I let auto detect pick the WebGLRenderer I see this error:

Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': No function was found that matched the signature provided.

If I dig in a bit I see that texture.baseTexture.source is undefined for this line:

canvasBuffer.context.drawImage(texture.baseTexture.source,
                               texture.crop.x,
                               texture.crop.y,
                               texture.crop.width,
                               texture.crop.height,
                               0,
                               0,
                               targetWidth,
                               targetHeight);

**Comment by englercj** [comment]
Do you have a running example that shows this error so i can track it down?

**Comment by smakinson** [comment]
I see the error if I run this at localhost.

https://www.dropbox.com/s/tnefd7wq2tz7gaf/pixi-rendertexture-bug.zip?dl=0

**Comment by englercj** [comment]
Looks like in WebGL a RenderTexture uses a framebuffer instead of a baseTexture source. That is causing the error, I will look into it more soon.

**Comment by smakinson** [comment]
Great, thanks!!

**Comment by englercj** [comment]
@GoodBoyDigital Is gonna fix this up here soon.

**Comment by smakinson** [comment]
Awesome! Would you say its pretty safe to use the files in the dist on the dev branch?

**Comment by englercj** [comment]
Safe as in to play around with, or safe as in to ship with? The first yes, the later no.

**Comment by smakinson** [comment]
Ok, good to know. Thanks.

**Comment by GoodBoyDigital** [comment]
haha! yeah, depends how brave you are feeling!

On Thu, Feb 5, 2015 at 3:58 PM, Chad Engler <notifications@github.com>
wrote:

> Safe as in to play around with, or safe as in to ship with? The first yes,
> the later no.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoodBoyDigital/pixi.js/issues/1393#issuecomment-73070549>
> .
>



-- 
Mat Groves

*Technical Partner*


 Telephone: 07708 114496 :: www.goodboydigital.com
 First Floor, Unit 9B, Queens Yard, White Post Lane, London, E9 5EN
 goodboy©. All Rights Reserved.

**Comment by smakinson** [comment]
I'm not scared!  :)

**Comment by GoodBoyDigital** [comment]
All fixed in v3 :+1:

**Comment by smakinson** [comment]
Awesome, thanks!!
