### ISSUE TITLE
bindBuffer error causing graphics glitches

### ISSUE THREAD

**Issue by alexmahan** [GoodBoyDigital/pixi.js#1394]
We're currently working on a WebGL/Web Audio experiment that has up to 5 WebGL contexts running at once. Intermittently - sometimes a few seconds in, sometimes several minutes in - we receive the following error:
`WebGL: INVALID_OPERATION: bindBuffer: object not from this context`

This causes graphical glitches to occur in one or more of the WebGL renderers. In the attached, you can see a glitched-out parallelogram in the top left of the panel.

Any insight you have into this error is welcomed. Thanks!

![bindbuffer-error](https://cloud.githubusercontent.com/assets/140830/5968356/5e14624a-a7cb-11e4-9437-b6b676f09fee.png)
![webgl-artifact](https://cloud.githubusercontent.com/assets/140830/5968357/5e2c068e-a7cb-11e4-8881-f29237f90853.png)

**Comment by englercj** [comment]
Very weird, not sure why this would happen just looking at the code. Anyway you could share a running example? Feel free to email me if you want to keep it private.

**Comment by tdreyno** [comment]
What's your email? I'm thomas@instrument.com

**Comment by englercj** [comment]
chad@pantherdev.com (you can view it on my github profile :smiley:)

**Comment by englercj** [comment]
Updating this with info from our email thread:

------

Seems like the second time we try to use the following, we get weird vertex issues on any other Graphics objects:


      arcCircle.lineStyle(10, color);
      arcCircle.moveTo(CIRCLE_RADIUS + 2, CIRCLE_RADIUS + 2);
      arcCircle.arc(CIRCLE_RADIUS + 2, CIRCLE_RADIUS + 2, CIRCLE_RADIUS - 8, 0, targetRadians, false);

It seems like drawing a path, which is not a polygon, that is, it doesn’t close. Is generating or losing some vertexes. Or maybe it’s trying to autocomplete the path in WebGL and losing track.

Maybe that massive vertex array in WebGL becomes off by one?

No idea. I can get you a reproducible case later this week. For now, we’re just going to make an animated bitmap sprite sheet to work around it.

**Comment by alexmahan** [comment]
Thanks, Chad. That's interesting. We also tracked it down to the circle, and are now using a sprite sheet workaround rather than drawing an arc. :)

Thanks again for looking into it!

**Comment by englercj** [comment]
@alexmahan Just so we are clear, that was a copy-paste of what @tdreyno sent me the other day. Not my words :)

**Comment by englercj** [comment]
Bump for a repro case :D

**Comment by tdreyno** [comment]
Still cleaning up after our launch (https://events.google.com/io2015/?experiment), will post this when we get a free moment.

**Comment by englercj** [comment]
I'm curious if you try this with the new v3 stuff if you still get that issue? Graphics got an overhaul in that branch and I'm curious if this issue is still happening there or if it can be closed.

**Comment by tdreyno** [comment]
We'll be open sourcing the code soon. But won't be able to spend time porting it to v3. Feel free to close this ticket.

**Comment by pwolfert** [comment]
I'm getting that same error in v3.0.7.  It mostly happens when I leave the tab alone for a while and come back to it.  I use drawCircle a lot.
