### ISSUE TITLE
Why  blendMode > 3 not working?

### ISSUE THREAD

**Issue by acopalipsis** [GoodBoyDigital/pixi.js#1401]
Hello! sorry for broken English I'm using Google translator.
Why overlay blendMode value constants PIXI.blendModes > 3 not working?
Method PIXI.autoDetectRenderer returns WebGLRenderingContext.
If this information is not enough, I have found in the Internet example,
which illustrates my problem http://codepen.io/ianmcgregor/pen/CtjeI
In this example, I do not work overlay after SCREEN.
If all sixteen blendMode work, then tell me, what am I doing wrong? Thank you!

**Comment by englercj** [comment]
The WebGLRenderer only supports a few blendModes, the others are not implmented as of WebGL 1.0 so we default them back to normal.

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/renderers/webgl/WebGLRenderer.js#L534-L550
