### ISSUE TITLE
InteractionManager throws 'cannot read property click of undefined' after removeChild

### ISSUE THREAD

**Issue by NikkiKoole** [GoodBoyDigital/pixi.js#1407]
It's hard to make some very small selfcontained example showing this, I can try though, but what I do is calling removeChild in batches, then I always get the error as described in the title:
on this line =
```
if (item[clickFunction] || item[upFunction] || item[upOutsideFunction])
```
in 
```
PIXI.InteractionManager.prototype.onMouseUp
```

I've fixed it by just putting a little escape plan in place
```
var item = this.interactiveItems[i];
	if (! item){
	    continue;
	}
        if (item[clickFunction] || item[upFunction] || item[upOutsideFunction])
```

**Comment by GoodBoyDigital** [comment]
Yo! this should be sweet on v3 now :+1:
