### ISSUE TITLE
PIXI.canUseNewCanvasBlendModes false positives

### ISSUE THREAD

**Issue by photonstorm** [GoodBoyDigital/pixi.js#1408]
Just a heads-up on this one for the v3 re-write, because this cost me hours and hours of debugging on a recent project.

The current test to see if the browser supports the multiply blend mode (and by definition any of the other new blend modes) doesn't take into account browsers who support multiply for *Canvas paths only*. The Samsung S5 stock browser is a brilliant example of this.

It supports multiply on Canvas operations such as fill, stroke and fillRect. But it doesn't support it *at all* for drawImage, which is how Pixi uses it for tinting.

This test needs to be made more robust, ideally by using 2 tiny images and comparing the pixel results from those.

(Thanks again Samsung.. really)

**Comment by GoodBoyDigital** [comment]
thanks for sharing dude! Will make sure to address in v3

**Comment by englercj** [comment]
Wow, crazy...thanks for the heads up Rich.

**Comment by adelciotto** [comment]
fixed in https://github.com/GoodBoyDigital/pixi.js/commit/36c900686deb4a1b0bc1e3b0087a2a710d249dc3
