### ISSUE TITLE
Graphics tinting not working with canvas

### ISSUE THREAD

**Issue by smakinson** [GoodBoyDigital/pixi.js#1410]
Since filing bug 1393 I am using the canvas renderer and I am seeing some troubles with the tint property. I have a graphic and it will tint one time and then not again. Here is an example with the auto detect renderer commented out.

On a side note there is also a commented out bit for the TweenMax ColorPropsPlugin incase it interests you. 

http://codepen.io/anon/pen/RNLJaM?editors=101

**Comment by anthdeldev** [comment]
Fixed in [PR-1461](https://github.com/GoodBoyDigital/pixi.js/pull/1461)

**Comment by logan503k** [comment]
25 февр. 2015 г. 9:49 пользователь "Anthony Del Ciotto" <
notifications@github.com> написал:

**Comment by GoodBoyDigital** [comment]
closing this as seems all fixed :+1: thanks all!
