### ISSUE TITLE
getChildByName

### ISSUE THREAD

**Issue by adireddy** [GoodBoyDigital/pixi.js#1413]
Hi Guys, Is there any reason why `getChildByName` is not available in Pixi.

I quickly added it in v3 and want to check with you guys before raising any pull request.

**Comment by GoodBoyDigital** [comment]
This sounds like i could be a nice little plugin feature for v3 - as
currently no objects have the concept of names.

On Thu, Feb 5, 2015 at 3:27 PM, Adi <notifications@github.com> wrote:

> Hi Guys, Is there any reason why getChildByName is not available in Pixi.
>
> I quickly added it in v3 and want to check with you guys before raising
> any pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoodBoyDigital/pixi.js/issues/1413>.
>



-- 
Mat Groves

*Technical Partner*


 Telephone: 07708 114496 :: www.goodboydigital.com
 First Floor, Unit 9B, Queens Yard, White Post Lane, London, E9 5EN
 goodboy©. All Rights Reserved.

**Comment by englercj** [comment]
Yeah feel free to make any plugin you want, it doesn't have to be put into the main repo.

**Comment by adireddy** [comment]
cool thx guys.
