### ISSUE TITLE
Pixi Polymer components

### ISSUE THREAD

**Issue by positlabs** [GoodBoyDigital/pixi.js#1415]
I've been learning [Polymer](http://polymer-project.org) recently and thought it might be cool to make some pixi components. I'm not totally sure if this is a great idea yet. There might be some performance issues that I'm not aware of.

It might look something like this
```html
<pixi-stage width="800" height="600" autodetect>
    <pixi-sprite texture="path/to/img.jpg" x="10" y="10"></pixi-sprite>
</pixi-stage>
```

The main advantage would be that the dom is much easier to read and understand than the imperative way of creating pixi objects. It will also allow devs to use polymer's data binding and other web component sugar.

Anyway, I'm not an expert with pixi or polymer. Just wanted to hear what you all though about it.

**Comment by englercj** [comment]
I don't know anything about Polymer so I can't comment :)

**Comment by positlabs** [comment]
There is an empty repo here: https://github.com/positlabs/pixi-poly

I might try polymerizing a smaller library (seriouslyjs) first, to understand the process better.

**Comment by englercj** [comment]
Closing this for now, if this happens it should be in userland.
