### ISSUE TITLE
Publish examples to website

### ISSUE THREAD

**Issue by abesto** [GoodBoyDigital/pixi.js#1416]
As discussed in https://github.com/GoodBoyDigital/pixi.js/issues/1005, the examples under http://www.goodboydigital.com/pixijs/examples/ are quite outdated. Both in using old versions of Pixi.js, and in not being up to date with the examples in the repo.

**Comment by englercj** [comment]
The v3 examples are being built and hosted on github:

https://github.com/pixijs/examples

**Comment by logan503k** [comment]
englercj

**Comment by englercj** [comment]
Closing this in favor of the new pixi examples being built on github.
