### ISSUE TITLE
Add a color class for ease of use

### ISSUE THREAD

**Issue by ala53** [GoodBoyDigital/pixi.js#1417]
Adding a color class to PIXI, much like the current matrix, rectangle, etc. classes would be quite useful. Instead of calling `new PIXI.Stage(0x01070304)`, you could call `new PIXI.Stage(PIXI.Color.red)` or `new PIXI.Stage(new PIXI.Color(0.5, 0.7, 0.3, 0.5))`

For an example implementation: https://gist.github.com/ala53/077481918f25bb97958b#file-gistfile1-js

**Comment by GoodBoyDigital** [comment]
Sounds like a great idea for a v3 plugin!

**Comment by englercj** [comment]
There are tons of utility modules in the npm ecosystem, are they not what you are looking for?

**Comment by ala53** [comment]
I know that there are many other color modules, but I feel that including one would be within the scope of a rendering engine. While it is portable to use numbers, it is no more portable than a color utility that resolves to numbers and is not as intuitive to write #F3CA19 as to write new Color(0.95, 0.75, 0.05). RGB codes and unexplained hex codes are typically a bad idea. 

In fact, the color utility could just return a number E.g.

```
PIXI.Color = function(r,g,b) {
     return <bitshifting r,g,b to a number here>
```

**Comment by englercj** [comment]
We have that right now :)

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/utils/index.js#L57-L66

**Comment by ala53** [comment]
Well then, thanks for letting me know. I thought that the lack of color functions was an oversight in design, but it seems that I merely missed the existing function.
