### ISSUE TITLE
Canvas renderer (in Safari 7), flickering

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#1422]
In Safari 7 (which uses the Canvas renderer) I see flickering sprites.

**Comment by tobireif** [comment]
To reproduce:

Load http://tobireif.com/boomchat_copy_3_for_bugreport/ in Firefox or Chrome.
Click on a button, eg the smiley on the left. What you see is probably what I see and what is intended.
Now load the same web app in Safari 7 (on Mac OS eg 10.9.5) (Pixi uses Canvas in Safari 7). The issues are:
    * the text above the form field flickers before it disappears.
    * each ball also flickers before it disappears.
    * one ball remains visible.
None of these issues happen in Firefox or Chrome - the text and the balls fade out as intended, and no ball remains visible. The issues happen in desktop Safari and on an actual iPhone (an older one).

**Comment by GoodBoyDigital** [comment]
hi @tobireif is this still present on the current dev version of pixi? thanks!

**Comment by tobireif** [comment]
Trying to update the example to the latest Pixi from the dev branch, in order to answer you question / in order to test whether it works now in Safari 7.

The code is at
http://tobireif.com/boomchat_copy_3_for_bugreport_uses_pixi_dev_branch_2015-03-23/

The buttons don't appear on load (they only appear after load and resize). With the loader from Pixi 2 it works http://tobireif.com/boomchat/  . Does the func onAssetsLoaded in http://tobireif.com/boomchat_copy_3_for_bugreport_uses_pixi_dev_branch_2015-03-23/ get called after the assets got fully loaded?

**Comment by englercj** [comment]
@tobireif What you are experiencing is a bug related to the fix made for englercj/resource-loader#7.

I am looking into the best way to solve this now.

**Comment by englercj** [comment]
@tobireif Can you try again now with the latest builds on dev? I've updated the loader and it should fix this issue now.

**Comment by tobireif** [comment]
@englercj I tried it again, with the latest from the dev branch: works now!

http://tobireif.com/boomchat_copy_3_for_bugreport_uses_pixi_dev_branch_2015-03-23/

Thanks!

**Comment by englercj** [comment]
Awesome, glad to hear it!

**Comment by tobireif** [comment]
@GoodBoyDigital
> is this still present on the current dev version of pixi? thanks!

Tested the issue #1422 itself (flickering sprites etc, see report @ top of page), including on an iPhone 4.
Works!

Thanks @GoodBoyDigital :+1:
