### ISSUE TITLE
[QUESTION] Using a new vertex shader

### ISSUE THREAD

**Issue by JairoCA** [GoodBoyDigital/pixi.js#1425]
After experimenting a bit with pixi, I have found no way to use my own vertex shader inside my project.

Among the different experiments I have used, I realised that even though the sprites now have a "shader" parameter, it has to be an AbstractFilter, and therefore only contain a fragment shader.

I managed to see also that the shaders that are in use in my case when rendering sprites are the default ones (default vertex in PIXI.PixiShader.defaultVertexSrc , default fragment in PIXI.WebGLSpriteBatch.defaultShader).

Could you please tell me if there is any way of using my own vertex shader without making my dirty hands modify my version of pixi?

Thanks :)

**Comment by englercj** [comment]
Not really in v2, but it is trivial in v3. Filters can have both custom vertex and fragment shaders.

For examples checkout the v3 filter library:

https://github.com/GoodBoyDigital/pixi.js/tree/dev/src/filters

**Comment by JairoCA** [comment]
Thank you for your answer :)

I have just investigated into the AbstractFilter in the v3 and saw a beautiful vertexSrc. However, I could not manage to build on my own the version. If I can not manage to build it tomorrow I will open another issue. Meanwhile, would it be possible to get a "compiled" version from anyone?

Thanks again

**Comment by JairoCA** [comment]
At the end I was able to build the library. It is the first time I use a JavaScript library builder, and it was hard for me to notice that Gulp was used instead of Grunt for this version.
