### ISSUE TITLE
Extending PIXI.Graphics

### ISSUE THREAD

**Issue by perara** [GoodBoyDigital/pixi.js#1426]
Hello, I'm trying to extend PIXI.Graphics but it seems like something is bugging out, ive done it successfully with PIXI.Text.

Im using coffeescript and it is done the following way:

```javascript
class Craphics extends PIXI.Graphics

  constructor: ->
    super

module.exports = Craphics
```

I try to initialize the object like i normally do, seems to work fine, but it fails when i add it as a child in my stage:

Error:
```
Uncaught TypeError: Cannot read property '0' of undefined                 pixi.dev.js:12199 
PIXI.Graphics._renderWebGL                                                               pixi.dev.js:2238 
PIXI.DisplayObjectContainer._renderWebGL                                         main.js:9410 
PIXI.WebGLRenderer.renderDisplayObject                                            main.js:9376 
PIXI.WebGLRenderer.render                                                                  main.js:21735 
(anonymous function)                                                                  main.js:21540 GameLoop.update
```
Failing at These lines in PIXI:

http://www.goodboydigital.com/pixijs/docs/files/src_pixi_primitives_Graphics.js.html line 689

Anyone know what this problem can be?

**Comment by englercj** [comment]
No way to know without viewing the JS, I have no idea what coffee script is doing.

**Comment by perara** [comment]
Hello, Will this help?
http://84.48.44.106:9001

I figured out that it seems to be only the drawing the fails.
I added hitArea with the polygon i use for drawing, and adding some mouseOver events. These seems to fire fine.

**Comment by englercj** [comment]
I'm super confused, it looks like you are including `pixi.dev.js` on the page, but you `main.js` also has pixi.js included. It looks like it is making some calls to one, some to the other (somehow). Try deduping that first, and that will probably fix your issue.

**Comment by perara** [comment]
Wow That is embarrasing. And yes you are correct. having two pixi.js does not work very well!

Thanks alot!

**Comment by englercj** [comment]
Anytime
