### ISSUE TITLE
hitArea and childIndex

### ISSUE THREAD

**Issue by Abais** [GoodBoyDigital/pixi.js#1428]
Hi everyone,

Firstly, please forgive my english !

So, I don't know if it's an issue or something i missed, but i have a problem with hit areas.

When i swap child index of 2 half-overlayed sprites, the sprite which go in background will continue to receive mouse interaction when i hover the one which go in front !

Some help is welcome :)

**Comment by GoodBoyDigital** [comment]
Hi @Abais thanks for sharing this issue. It has been addressed for v3! :+1:
