### ISSUE TITLE
AssetLoader::onProgress - additional event data

### ISSUE THREAD

**Issue by aleroy** [GoodBoyDigital/pixi.js#1429]
I have a suggestion to add a little convenience to PIXI.AssetLoader's onProgress event: It would be helpful to pass the index of asset that was just loaded (and possibly---for extra convenience---the length of the assetURLs array).

<dl>
  <dt>Request:</dt>
  <dd>Modify AssetLoader::onProgress event object
     <ul><li>+ nth (index of the asset in AssetLoader.assetURLs)</li><li>+ of (AssetLoader.assetURLs.length) *unnecessary, but convenient*</ul>
  </dd>
</dl>
 
Here is a diff of the changes needed:
```javascript
--- AssetLoader.js	2015-02-11 09:33:14.000000000 -0600
+++ AssetLoader.js	2015-02-11 09:36:55.000000000 -0600
@@ -112,11 +112,12 @@
 PIXI.AssetLoader.prototype.load = function()
 {
     var scope = this;
-
-    function onLoad(evt) {
-        scope.onAssetLoaded(evt.data.content);
+    
+    function setLoadHandler(loader, nth) {
+        loader.on('loaded', function(evt) {
+            scope.onAssetLoaded(evt.data.content, nth);
+        });
     }
-
     this.loadCount = this.assetURLs.length;
 
     for (var i=0; i < this.assetURLs.length; i++)
@@ -135,7 +136,7 @@
 
         var loader = new Constructor(fileName, this.crossorigin);
 
-        loader.on('loaded', onLoad);
+        setLoadHandler(loader, i );
         loader.load();
     }
 };
@@ -146,10 +147,14 @@
  * @method onAssetLoaded
  * @private
  */
-PIXI.AssetLoader.prototype.onAssetLoaded = function(loader)
+PIXI.AssetLoader.prototype.onAssetLoaded = function(loader, nth)
 {
     this.loadCount--;
-    this.emit('onProgress', { content: this, loader: loader });
+    this.emit('onProgress', { content : this
+                            , loader  : loader
+                            , nth     : nth
+                            , of      : this.assetURLs.length
+                            });
     if (this.onProgress) this.onProgress(loader);
 
     if (!this.loadCount)
```
... and here is an example usage (with bootstrap & jquery for ui elements):
```javascript
function init()
{
    var self   = this;
    var assets = [
                 // ...
                 ];
    var loader = new PIXI.AssetLoader(assets);

    function onProgress( e )
    {
        var percent = Math.round(e.data.nth / e.data.of) * 100;
        var value = percent + "%";
        // 'pb_loader' is a bootstrap progress bar nested in a modal dialog
        $('#pb_loader').width(value).text(value);
    }
    function onComplete( e )
    {
        // 'myModal' is bootstrap modal dialog
        $('#myModal').modal('hide');
    }
    loader.on('onProgress', onProgress);
    loader.on('onComplete', onComplete);

    $("#myModal").modal('hide');
    loader.load();
}
```

**Comment by englercj** [comment]
If you want this in v2, feel free to send a PR to the maint branch (`v2.x`). As for v3 this information is already passed in to progress events. It sends the entire state of the loader (including the calculated progress), and the specific resource that just completed loading.

**Comment by aleroy** [comment]
Awesome, thanks!
I look forward to v3...sounds like an even better change.

**Comment by englercj** [comment]
I'm adding this to the v2 maintenance branch, and realized that you can't use the index to know how much is loaded. The loads are async parallel, not serial so you could get indexes in random orders. Instead I'm sending back the number of loaded resources and the total number of resources that will be loaded.
