### ISSUE TITLE
"properties.descent += 6" "throws off all the text formatting"

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#1430]
Please see the code at https://github.com/GoodBoyDigital/pixi.js/commit/fa5ba164055d3b3ee17c8490831e7031f5b9357e and the bug report by @whizzkid (on the same page).

I think the descent should come from font metrics measuring instead of being hardcoded.

**Comment by serprex** [comment]
https://github.com/GoodBoyDigital/pixi.js/pull/1420

**Comment by englercj** [comment]
@tobireif Does #1420 fix you issue?

**Comment by smujzee** [comment]
Checked the bug report by @whizzkid, unfortunately; the test sample did not show pomising result on safari browser. Could it be a browser issue? (or it is compatible with all browsers.)

**Comment by smujzee** [comment]
I think it has to come from the measurements in the font metrics too.

**Comment by tobireif** [comment]
@englercj 

> Does #1420 fix you issue?

Do you want me to try it with Pixi 2 or using the latest from the dev branch?

I'm trying to create a quick test page ( current URL is http://codepen.io/anon/pen/qEoErJ?editors=101 ) using the latest Pixi build, but it seems that Pixi 3 requires a build step? (I had compiled a "pixi.js" file using Gulp, but it seems I can't simply and directly use that build on Codepen.)

**Comment by tobireif** [comment]
(Nevermind, got the build to work (with Mat's help), will try to post an additional test page for text positioning soon.)

**Comment by tobireif** [comment]
@englercj 
> Does #1420 fix you issue?

I tested something and noticed that a descender was cut off. Since I applied PR https://github.com/GoodBoyDigital/pixi.js/pull/1420  that specific descender doesn't get cut off anymore, so I think you should merge the fix.

But there still are things that get cut off, I'll submit a separate issue ticket.

(Regarding this issue page here, I hope to provide a test page soon.)

**Comment by tobireif** [comment]
Working on two test pages, but I can't seem to make an image appear using Pixi 3. Any idea?
On http://codepen.io/TobiReif/full/MYVaJY/ see "new PIXI.Sprite.fromImage" etc.

**Comment by englercj** [comment]
`fromImage` is a function, not a constructor. Don't use the `new` keyword.

**Comment by tobireif** [comment]
Thanks, I fixed that, but the image still doesn't get rendered. Any idea? (Feel free to fork the codepen to play with it.)
BTW, the cross-origin request errors in the console seem to be related to other requests.
It's probably caused by something simple, but I can't make Pixi 3 render the image. It's an olive colored rectangle that should appear anywhere, I'd adjust the position then.

**Comment by tobireif** [comment]
I copied all the code from the codepen to local files. I'm not getting any console errors, but the graphic doesn't get rendered (as in the codepen). Any idea?

**Comment by GoodBoyDigital** [comment]
Howdy! I just added a padding property to style that should fix these issues if they pop up. The padding won't affect the position of the text itself it will simply give a bit more rendering room.
