### ISSUE TITLE
WebGL stencil buffer is not supported by some Android stock browsers

### ISSUE THREAD

**Issue by darkwhite** [GoodBoyDigital/pixi.js#1431]
PIXI.autoDetectRenderer returns WebGL renderer in some cases while Stencil buffer is not supported by the browser. This leads to some weird behaviors based on the usage scenarios.

**Comment by darkwhite** [comment]
Can handle this situation in "PIXI.autoDetectRenderer" by replacing:

    var canvas = document.createElement( 'canvas' );
    return !! window.WebGLRenderingContext && ( canvas.getContext( 'webgl' ) || canvas.getContext( 'experimental-webgl' ) );

by:

    var canvas = document.createElement( 'canvas' );
    var gl_tmp = canvas.getContext( 'webgl', {stencil:true}) || canvas.getContext( 'experimental-webgl' , {stencil:true});
    var contextAttributes = gl_tmp.getContextAttributes();
    var haveStencilBuffer = contextAttributes.stencil;
    return !! window.WebGLRenderingContext && (haveStencilBuffer);

I do this check always but perhaps make it optional will be a better way for PIXI library.

**Comment by englercj** [comment]
https://github.com/GoodBoyDigital/pixi.js/blob/88661f02228f03e1698bbe2e16f4fc47a1948e71/src/pixi/utils/Detector.js#L46-L66

**Comment by darkwhite** [comment]
I don't see that "autoDetectRecommendedRenderer" as a good solution because it just simply forces all Android browsers to use canvas renderer while many of them (actually most of them) work perfectly in WebGL mode. Using that even Chrome browser in Android Lollipop will be forced to use canvas renderer.
