### ISSUE TITLE
Scaling and rotating children Error

### ISSUE THREAD

**Issue by aholla** [GoodBoyDigital/pixi.js#1433]
If you scale a child either by setting its scale or by changing its width and then rotate the parent container, the child becomes distorted.

It looks like the rotations are being applied to the container/parent and then the width of the child is set. The child's width needs to be set first and then the parent rotated.

**Comment by englercj** [comment]
Is this with any renderer? Any specific type of objects?

Do you have a running test case for this?

**Comment by aholla** [comment]
Hmmm, I just coded up a test in codepen but it works fine there so it is only in my project...

All i can say is there are multiple Container all with anchor points set to 0.5 and then the container that i am rotating would be in negative space. Here are a few screen shots of what I am seeing:

https://dl.dropboxusercontent.com/u/698268/bugs/01.jpg
https://dl.dropboxusercontent.com/u/698268/bugs/02.jpg
https://dl.dropboxusercontent.com/u/698268/bugs/03.jpg

**Comment by englercj** [comment]
I unfortunately have no idea what is happening without seeing it happen. My test cases do not reproduce this either.

**Comment by GoodBoyDigital** [comment]
Hey @aholla is this still an issue? cheers matey!

**Comment by aholla** [comment]
I don't have the code to test any more, I had to change how I was build the animation to get around the issue. 

I too was unable to replicate it with a simple test so I would say this is a real edge case but it is there; somehow when nested within multiple containers with various positions and rotations my child objects because skewed.

It may be fixed in the latest version, perhaps somewhere the order in which a matrix is being process could be the cause.

**Comment by GoodBoyDigital** [comment]
nice. thanks for the heads up. Lets assume its fixed in v3 but keep a vigilant eye on the issue in case it pops up again. closing for now. cheers dude.
