### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by ponychicken** [GoodBoyDigital/pixi.js#1434]
It would be nice to have an officially published package on npm. Why npm, if pixi is not made for node, you might ask? If you use a loader like browserify you can then require('pixi') to load pixi in your client side scripts.

Right now the pixi package is unfortunately occupied by an outdated fork, but it would be also possible to publish it to pixi.js

**Comment by englercj** [comment]
We already have an official package that I maintain:

https://www.npmjs.com/package/pixi.js

Is this not what you were looking for?

**Comment by ponychicken** [comment]
Oh, weird, I failed to find this! Thanks. (But maybe it would be a good idea to contact the guy who owns the pixi package. Since he's not actively maintaining it, he might be willing to hand over the name)

**Comment by englercj** [comment]
Well, we wouldn't switch over because we would lose people who have been using this package, and we don't want to take up 2 names on npm.
