### ISSUE TITLE
WebGLFastSpriteBatch context is not being restored on context lost

### ISSUE THREAD

**Issue by cixzhang** [GoodBoyDigital/pixi.js#1435]
PIXI.WebGLFastSpriteBatch.prototype.setContext is never called when handling context lost. This leads to this error (plus a bunch of other errors resulting from this) when PIXI.WebGLFastSpriteBatch.prototype.start is called:

    WebGL: INVALID_OPERATION: bindBuffer: object not from this context

**Comment by englercj** [comment]
This is no longer an issue for v3.
