### ISSUE TITLE
question: is it ok to use pixi.js as a scene graph including non-renderables?

### ISSUE THREAD

**Issue by mreinstein** [GoodBoyDigital/pixi.js#1438]
pixi has a hierarchical scene graph, and I'd prefer to have one hierarchy rather than replicating that structure elsewhere. Can I use that tree to attach my own nodes (including stuff that isnt renderable like scripts/sounds?)

e.g., I have a character class that extends PIXI.Spine, and I want to attach a sound class using `.addChild(sound)` is that reasonable to do? Will pixi ignore inert/unrenderable nodes?

**Comment by englercj** [comment]
As long as it extends `DisplayObject` and is set `visible=false` it should be innocuous to put it in the scene graph.

**Comment by mreinstein** [comment]
thanks! Are there any gotchas/performance implications that I should be aware of with this approach? 

Also, would you guys be willing to accept pull request(s) that add more traversal functions? I would love to add `find(fn)` and `filter(fn)` methods which get references to nodes that match some criteria.

**Comment by englercj** [comment]
Keep in mind that we iterate every child in the tree, even when `visible=false` the node is still visited. We just don't perform any work on non-visible nodes. Keeping you tree shallow and wide is more performant than deep and narrow.
