### ISSUE TITLE
Using Pixi without a build step

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#1440]
Does this
https://github.com/pixijs/examples/blob/master/src/basic/index.js
mean that projects using Pixi 3 will always require a build step?
Or can a Pixi build be used directly, without compiling the JS that uses it? (as with Pixi 2)

**Comment by photonstorm** [comment]
It will always need a build step *unless* you use one of the pre-packaged builds provided. So if you're just sticking pixi.js into your script tag then nothing much will change for you. If you've a more complex set-up, fiddling will be required.

**Comment by GoodBoyDigital** [comment]
Hey buddy! Yes we will have a compiled version before we launch v3. As its still under development this has not been added yet.

**Comment by tobireif** [comment]
@photonstorm and @GoodBoyDigital : Thanks for your reply!

I'm trying to create a quick test page ( current URL is http://codepen.io/anon/pen/qEoErJ?editors=101 ) for https://github.com/GoodBoyDigital/pixi.js/issues/1430 , using the latest Pixi dev branch.

I had built Pixi using "npm install && gulp",  and tried using it in a Codepen
http://codepen.io/anon/pen/qEoErJ?editors=101 ,
but it doesn't seem to work: "PIXI.Text is not a constructor".

Or perhaps I should use Pixi 2 for testing https://github.com/GoodBoyDigital/pixi.js/issues/1430 ?

**Comment by GoodBoyDigital** [comment]
I its PIXI.text.Text at the moment

**Comment by tobireif** [comment]
That works
http://codepen.io/anon/pen/qEoErJ?editors=101
- thanks!

I wasn't sure whether my build is supposed to work, good to know it's usable. Will consult the source regarding any additional related API changes :)

**Comment by englercj** [comment]
v2 also required a build step, unless you used the prepackaged solution. There is no difference except that we haven't committed working builds yet since we are still working on it.
