### ISSUE TITLE
Pixi Text: É and ' are cut off. (eg in Mac FF)

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#1442]
In the below codepen, the É and 'are cut off in the Pixi text. (eg in Mac FF)

http://codepen.io/TobiReif/pen/qEoONr

**Comment by GoodBoyDigital** [comment]
Howdy! I just added a padding property to style that should fix these issues if they pop up. The padding won't affect the position of the text itself it will simply give a bit more rendering room.
