### ISSUE TITLE
Typo from recent isMask commit

### ISSUE THREAD

**Issue by serprex** [GoodBoyDigital/pixi.js#1445]
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/graphics/Graphics.js#L819

Should be !this.renderable

Also stray isMask references @ https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/graphics/Graphics.js#L694 & https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/graphics/Graphics.js#L744

**Comment by GoodBoyDigital** [comment]
Thanks for letting me know @serprex . Should be all good now :+1:
