### ISSUE TITLE
Set pixi.dev.js as value for 'main' within package.json

### ISSUE THREAD

**Issue by munkychop** [GoodBoyDigital/pixi.js#1449]
When using build tools, such as Grunt, alongside Browserify or Uglify it is preferable to target a non-minified PIXI file in order to avoid double minification, since this should be left to an individual's build implementation. So it would be better if the path to the non-minified version of PIXI was set as the value for the 'main' field within the package.json.

Current:
```JSON
"main": "bin/pixi.js"
```

Proposed:
```JSON
"main": "bin/pixi.dev.js"
```

Is there really any reason to use the minified file?

**Comment by englercj** [comment]
Nope, and we don't in v3: https://github.com/GoodBoyDigital/pixi.js/blob/dev/package.json#L10

**Comment by munkychop** [comment]
Cool, yeah I noticed it in v3, but you guys have been doing tons of work there, so I thought I'd ask before submitting a pull request.

**Comment by englercj** [comment]
Yes, to get things into a v2 maintenance release pull them to `v2.x`, `dev` is the next release (v3).
