### ISSUE TITLE
Delay on events?

### ISSUE THREAD

**Issue by perara** [GoodBoyDigital/pixi.js#1450]
Hello, Im fiddling around with events in pixi, But to me, it seems like the reaction on the callback is abit slow.
Demo: http://128.39.148.43:9001/
(Hovering a country is slow for example)
(And sluggish when moving the parent container of all the graphics elements)

What you see in the demo is a container with about 1000 Graphics elements generated from a list of Polygons. THese polygons have quite a few points, but reducing point count did not make any noticable difference.

The function for hovering a country is the following: 
 # Hovering the graphics object
```
      graphics.mouseover =  (e) ->
        this.clear()
        this.lineStyle(5, 0x0000FF, 1);
        this.blendMode = PIXI.blendModes.ADD
        this.drawPolygon(this.polygon.points)


      # leave hovering the graphics object
      graphics.mouseout =  (e) ->
        this.clear()
        this.lineStyle(1, 0x0000FF, 1);
        this.beginFill(0xffffff, 0.5);
        this.blendMode = 0
        this.drawPolygon(this.polygon.points)
```

And for the movement (Panning)
```
  parent.mousedown = (moveData) ->
    pos = moveData.global
    prevX = pos.x
    prevY = pos.y
    isDragging = true

  parent.mouseup = (moveDate) ->
    isDragging = false


  parent.mousemove = (moveData) ->
    if !isDragging
      return
    pos = moveData.global
    dx = pos.x - prevX
    dy = pos.y - prevY

    that._dx += dx
    that._dy += dy

    that.position.x += dx
    that.position.y += dy
    prevX = pos.x
    prevY = pos.y
```

I was told that these callbacks should be faster than having this in the gameloop. Maybe im doing something wrong tho?

I could not notice anything that would cause this in PIXI... :/

**Comment by englercj** [comment]
The callbacks for interaction events *are* in the render loop (in v2).

**Comment by GoodBoyDigital** [comment]
I think I know what this is! we only check mouse over/out events at 30fps. which is half the speed of the actual rendering. Add this line:

```PIXI.INTERACTION_FREQUENCY = 60;```

It should speed up the reaction!

cheers!

**Comment by perara** [comment]
Seems to work way better!
 
Thanks!
