### ISSUE TITLE
[PIXI 2.2.5, Bug] TilingSprite from atlas texture (not file) with messy borders (all but Safari)

### ISSUE THREAD

**Issue by georgiee** [GoodBoyDigital/pixi.js#1457]
The Tiles generated from an atlas have visible seams. Affected browsers: Chrome, Firefox, Firefox DevEdition not Safari.

See here: http://jsfiddle.net/georgie/e5oL623g/
![screen shot 2015-02-24 at 07 05 35](https://cloud.githubusercontent.com/assets/1701755/6344086/a1945caa-bbf3-11e4-9b8a-1836529fc904.png)

The generated texture from the atlas (TexturePacker) seems to be identical to the one from the image file- BUT I can see a very very thin transparent line on both sides. See my looping GIF for this. So the generated texture might be wrong.

![textures](https://cloud.githubusercontent.com/assets/1701755/6344193/955b3600-bbf5-11e4-92f6-ed5ba2d91e15.gif)

Is this a known error? This seems to be too obvious to get missed. I couldn't find a related issue or a commit after 2.2.5 related to this. I tried several texture formats, changing the generated json to shift the texture, tried tileScaling just to get another output. The problem persisted.

Are you guys busy with v3 or could you look into this ? 

Here the source image files:
http://2vc.org/temp/files.zip

Thanks
George

**Comment by englercj** [comment]
Does this happen in webgl only, or canvas as well?

**Comment by georgiee** [comment]
Oh sorry, I totally forgot about canvas. I just verified this and it only happens in webgl.

**Comment by GoodBoyDigital** [comment]
he there! this has been sorted in v3 now. :+1:
