### ISSUE TITLE
[PIXI 2.2.5, Bug] TilingSprite#generateTilingTexture generates a stretched texture for trimmed sources.

### ISSUE THREAD

**Issue by georgiee** [GoodBoyDigital/pixi.js#1458]
I have a trimmed sprite
Untrimmed width of the sprite is 500px, it's trimmed down to 20px. There is a lot of space to the right to generate a very wide tiling pattern.

See here:
http://jsfiddle.net/georgie/gesz8bkr/

Looks like this:
![screen shot 2015-02-24 at 17 02 05](https://cloud.githubusercontent.com/assets/1701755/6353014/e774552e-bc46-11e4-9bd8-6881b16066c2.png)

This affects Canvas & WebGL.

You can see the same trimmed frame is used in a sprite and in a tiling sprite.  The single sprite is fine.
The tiled texture is strechted to the full untrimmed size when tiled. I found that TilingSprite#generateTilingTexture is not acting correctly. See here: 
https://github.com/GoodBoyDigital/pixi.js/blob/2a5afb857328b1e28152499bce8e8560a6563caf/src/pixi/extras/TilingSprite.js#L439

```
//targetWidth & targetHeight will hold the frame size not the cropped size for trimmed textures- this will stretch the image
canvasBuffer.context.drawImage(texture.baseTexture.source,
                               texture.crop.x,
                               texture.crop.y,
                               texture.crop.width,
                               texture.crop.height,
                               0,
                               0,
                               targetWidth, 
                               targetHeight);
```

In my fiddle the targetWidth should be 20px not 500px (the untrimmed size).
I tried to monkey patch pixi with a version of generateTilingTexture which uses the trimmed dimensions of a sprite. This worked, but the scaling of the sprite was not incorporated correctly. So I dropped my idea and posting this issue instead of a solution :)

I found that rich sponsored these changes some time ago-  see https://github.com/GoodBoyDigital/pixi.js/pull/579
and I wonder if this bug is present since then ?

Thanks George

**Comment by englercj** [comment]
Thanks @georgiee for the detailed bug reports. I will try to have something for you by tomorrow!

**Comment by photonstorm** [comment]
> I found that rich sponsored these changes some time ago- see #579
and I wonder if this bug is present since then ?

Nope, it worked back then. If you look at the few lines I added:

https://github.com/photonstorm/pixi.js/blob/661c5bc13727314c7a46b831dda317437cf76eab/src/pixi/extras/TilingSprite.js#L374 

You'll see they are *no longer present* in the current code.

**Comment by photonstorm** [comment]
This is why it doesn't work in WebGL: https://github.com/GoodBoyDigital/pixi.js/blob/v2.x/src/pixi/renderers/webgl/utils/WebGLSpriteBatch.js#L384

**Comment by GoodBoyDigital** [comment]
thanks for pointing out @photonstorm :+1:

**Comment by georgiee** [comment]
Sorry Rich, you're right. I assumed that it worked back in the days and just wondered what happend to it in the meanwhile. Anyway, I'm glad that this should be easy to fix now it's pointed out.

In the meanwhile I looked at the working commit https://github.com/GoodBoyDigital/pixi.js/commit/661c5bc13727314c7a46b831dda317437cf76eab and it's parent https://github.com/GoodBoyDigital/pixi.js/commit/49c2ce1ca09cb92354a6a37b1b3adc0850665263.
to find where it disappeared but there wasn't any related commit in the current file history of https://github.com/GoodBoyDigital/pixi.js/commits/master/src/pixi/extras/TilingSprite.js.

Might this regression be caused by a failed manual merge? I'm just curious as this is one of my fears when I have to tidy up a failed merge.

**Comment by photonstorm** [comment]
I applied my original fix (adjusted for the crop property) and it fixes it for Canvas. But WebGL is still whacked. To be honest I can't remember if even the original fix worked on WebGL either. I'd suspect not.

**Comment by englercj** [comment]
Added the fix back into v2.x with 5cb6b42. That should fix it up for canvas.

**Comment by GoodBoyDigital** [comment]
morning! this works like a champ in v3 so closing for now. :+1: 
thanks all!
