### ISSUE TITLE
Feature request: Clever shader based edge/distance antialiasing

### ISSUE THREAD

**Issue by gordyr** [GoodBoyDigital/pixi.js#1464]
Currently antialising of any kind is only performed when setting the ```antialias``` property to ```true```.  This of course uses native webGL multisampling antialising and only if the users hardware supports it.  Not only that but it is rather a slow and unnecessary method for a 2d library like pixi.

Without any antialiasing at all, rotated sprites and shapes become very jagged.

There are several methods which provide far better results and are faster than native multisampling but having done a bit of research recently the best fit for pixi in my opinion would be the method described and demonstrated here.

http://abandonedwig.info/blog/2013/02/24/edge-distance-anti-aliasing.html

As you can see the author is simply altering the opacity of shape edges using a fragment shader.

![Image of Yaktocat](http://abandonedwig.info/edge-distance-anti-aliasing/demo.png)

Here is a live WebGL version, complete with source code for the method.

http://abandonedwig.info/edge-distance-anti-aliasing/demo.html

I think this would be an excellent addition to pixi and would reduce the need to convert shapes into sprites in order to get decent edges.  Not only that but it appears reasonably quick and easy to implement.

Perhaps a simple ```object.edgeAntialias = true``` property for shapes and rectangular sprites?

If I was familiar enough with pixi's internal I would attempt a PR myself, unfortunately I am not.

**Comment by GoodBoyDigital** [comment]
check out v3 - we have an FXAA shader built in :)

**Comment by gordyr** [comment]
You sir.... are a god. :)

**Comment by englercj** [comment]
Right now it only is used when the environment doesn't support native antialiasing, but the user enabled antialiasing. We can make a param to force the use of FXAA if you know for your case it would be faster.

**Comment by GoodBoyDigital** [comment]
I was thinking the same! FXAA is much faster. We could also expose the filter itself in the filters index.js for easy access?

**Comment by englercj** [comment]
@GoodBoyDigital Sure, sounds good to me.

**Comment by GoodBoyDigital** [comment]
sorted init!
