### ISSUE TITLE
Filters not built ?

### ISSUE THREAD

**Issue by OwlyCode** [GoodBoyDigital/pixi.js#1465]
Hello !

While browsing pixi.js sources, I found out that an AsciiFilter and a NoiseFilter were added by #981 but when I look into the minified pixi.js in the bin dir, they are missing.

Is it intended to load them separately ?

**Comment by englercj** [comment]
If you are talking about in v2, then yes they were never packaged with pixi:

https://github.com/GoodBoyDigital/pixi.js/blob/master/Gruntfile.js#L75-L90

Don't remember if that was on purpose, or just an oversight. Those are all shipped in the `filter` package of v3 though.
