### ISSUE TITLE
Vertex shader null in Pixi v3?

### ISSUE THREAD

**Issue by oal** [GoodBoyDigital/pixi.js#1467]
I'm trying to port a project to Pixi v3, but for some reason I couldn't get shaders working. Setting a filter on a Sprite's .shader attribute, I got this, even though I set both a vertex source and fragment shader source.

```Uncaught Error: Pixi.js Error. Shader requires vertexSrc and fragmentSrc```

Then I found this:
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js#L393

```js
shader = new Shader(this.renderer.shaderManager, null, currentShader.fragmentSrc, currentShader.uniforms);
```

It seems to never get passed on to the shader initialization. Am I supposed to set this up in some other way, or is shader support in Pixi v3 not done yet?

**Comment by englercj** [comment]
Nice catch, that needs to be fixed. We haven't done much (any?) testing on v3 yet so you are likely to encounter a *lot* of bugs if you are trying to use it right now!

I'll fix this promptly.

**Comment by englercj** [comment]
Just added a commit that should fix your issue. Try with the latest dev branch and let me know how that works (you will need to rebuild locally).

**Comment by oal** [comment]
Thanks for the quick reply. Yes, I'm aware that v3 isn't quite ready yet, but I wanted to give it a try anyway.

Now I get: ```Uncaught TypeError: Cannot read property '_location' of undefined```

Looks like `projectionMatrix` isn't set here: https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/sprites/webgl/SpriteRenderer.js#L407

**Comment by GoodBoyDigital** [comment]
Yeah - defo gonna be some bugs in v3 as its still sort of under construction. But glad to hear you are using it as it will help us nail issues a lot quicker!

**Comment by GoodBoyDigital** [comment]
@oal does your shader have a projectionMatrix uniform?

**Comment by oal** [comment]
No, I assumed it'd be passed in/created automatically, like when using it as a .filter, isn't that the case?

**Comment by englercj** [comment]
@oal You still need to have it in the vertex source code, we don't modify your shader source (filters don't either).

**Comment by GoodBoyDigital** [comment]
What does your shader look like? It should be a TextureShader possibly?

**Comment by oal** [comment]
@englercj Adding projectionMatrix to the vertex shader source didn't help. I'm currently just extending the AbstractFilter with my own fragment shader (neither leaving the vertex shader to null/default nor adding my own vertex shader with the projectionMatrix helped)

@GoodBoyDigital hmm, possibly, but TextureShader isn't available on the PIXI object that I'm importing. Where can I find it?

**Comment by englercj** [comment]
That's a good point @GoodBoyDigital, shouldn't the sprite renderer be using texture shader instead of the base shader?

**Comment by GoodBoyDigital** [comment]
I see! Leave it with me, I will take a look tonight :+1:

**Comment by GoodBoyDigital** [comment]
Abstract filter has a function called ```getShader``` we should be calling that. Will tweak laters.. good catch guys!

**Comment by GoodBoyDigital** [comment]
all updated and stuff now. should be good to go!
