### ISSUE TITLE
shader.attributes.aColor === -1 in v3

### ISSUE THREAD

**Issue by oal** [GoodBoyDigital/pixi.js#1472]
Using filters in v3, I get a lot of `WebGL: INVALID_VALUE: vertexAttribPointer: index out of range` in Chrome (Firefox works fine). It turns out `attributes.aColor` on the shader that's created from the filter is `-1`, and it seems like this is a known issue (from v2?)

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/renderers/webgl/shaders/Shader.js#L128

It has a `TODO: Check if this is needed anymore`, and yes, I think it's still needed. :-)

![aColor](https://cloud.githubusercontent.com/assets/371103/6418966/911682fe-beb9-11e4-8343-8771013edad9.png)

**Comment by englercj** [comment]
@oal I would be suprised if this has to do with that hack I commented out, it was specifically for a certain version of chromebook hardware.

What filter are you using? Most likely the filter manager expects `aColor` to exist so it can set it, but the filter doesn't actually have that attribute in the vertex shader. Most context (like a stack trace and sample code) will help us track this down.

Honestly, the filter manager should ensure attributes have a position before setting them to ensure the shader actually uses it.

**Comment by oal** [comment]
@englercj I see. It happens when `vColor` isn't used inside the fragment shader. I use the default vertex shader, and pass inn no additional uniforms. So this will not give any warnings (defaultFragmentSrc from TextureShader.js):
```js
var defaultFragmentSrc = [
	'precision lowp float;',

	'varying vec2 vTextureCoord;',
	'varying vec4 vColor;',
	'uniform sampler2D uSampler;',

	'void main(void){',
	'   gl_FragColor = texture2D(uSampler, vTextureCoord) * vColor ;',
	'}'
].join('\n');
```
But this will:
```js
var defaultFragmentSrc = [
	'precision lowp float;',

	'varying vec2 vTextureCoord;',
	'varying vec4 vColor;',
	'uniform sampler2D uSampler;',

	'void main(void){',
	'   gl_FragColor = texture2D(uSampler, vTextureCoord);',
	'}'
].join('\n');
```
This may very well be the expected behavior, and feel free to close the issue if so. I ran into this while debugging the other issue I reported earlier.

**Comment by englercj** [comment]
hmmm, The `vColor` varying will be optimized out if you don't use it. But I am surprised that causes the error you describe...

Maybe since vColor is optimized out of the fragment shader it also removes it from the vertex shader, which then makes aColor unused so it is also optimized out? Seems like an impressive optimization, but it could be happening.

This is why we should change places that assume an attribute/uniform exists to check first if it does before assigning it.

**Comment by oal** [comment]
That sounds like a reasonable explanation. I get a warning about this in Firefox as well (don't know why I didn't notice it earlier): `Error: WebGL: vertexAttribPointer: index -1 is invalid. That probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program.`

**Comment by englercj** [comment]
@GoodBoyDigital How do you feel about changing attribute/uniform assumptions like:

```js
gl.vertexAttribPointer(shader.attributes.aColor, ...);
```

into:

```js
if (shader.attributes.aColor !== -1) {
    gl.vertexAttribPointer(shader.attributes.aColor, ...);
}
```

And the same for uniforms to check `._location` is not `-1` so we don't try to set something on a filter/shader made by the user doesn't actually exist.

**Comment by GoodBoyDigital** [comment]
@englercj this is a dangerous path - I think keeping a standard frame for shaders is important as this would open up complexity when uploading data. Its definitely good to use vColor too as it ensures alpha is respected.

**Comment by GoodBoyDigital** [comment]
seems like this has run its course. Closing for now :+1:
