### ISSUE TITLE
Error on build: Cannot start Firefox

### ISSUE THREAD

**Issue by DannyBen** [GoodBoyDigital/pixi.js#1473]
I followed the build instructions and did `npm install` then `grunt`.
The grunt process stopped with this error

```
Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser Firefox
ERROR [launcher]: Cannot start Firefox
        Can not find the binary C:\Program Files\Mozilla Firefox\firefox.exe
        Please set env variable FIREFOX_BIN
```
        
I am running on Windows, with no Firefox.
Do I have to install firefox, or is there a way around this?

EDIT:
I edited the Gruntfile and uncommented the kindly provided `browsers: ['Chrome'],` line which was commented out. Is that the correct way? Is my build process done now?

**Comment by oal** [comment]
Karma is the test runner, which is run by default when just calling `grunt`. It needs a browser to run the tests in. If you just want to build PIXI, you can use `grunt build` (or build-debug) which doesn't run any unit tests.

See: https://github.com/GoodBoyDigital/pixi.js/blob/master/Gruntfile.js#L214

**Comment by DannyBen** [comment]
Yeah, I am not using grunt on a regular basis, so was not sure.
In fact, I think I do not need to build at all... I was under the impression that I need to build in order to start developing in Pixl, but I then realized I just need the bin folder, and start with one of the examples. Correct me if otherwise please.

If I am correct, perhaps this should be mentioned somewhere prominent both in the main README and on the pixljs.com site.

**Comment by oal** [comment]
You really only need to build if you make changes to Pixi itself. If you're just going to use it in a project, you can simply grab the prebuilt JS file in the `bin` directory, or under "Releases". :smile: 

@GoodBoyDigital As @DannyBen suggests, maybe there should be a "Note: You do not have to build Pixi yourself to start using it. Just use one of the prebuilt files in `bin`" under "Build" in the readme?

**Comment by DannyBen** [comment]
Thanks, I will now have tinted bunnies rotating on my screen in no time :)

**Comment by englercj** [comment]
We will update the v3 readme to make it much more clear to get and use pixi. Right now, you have to build v3 so we haven't added those docs yet.

**Comment by englercj** [comment]
This should be good to go now.
