### ISSUE TITLE
Should I calculate deltaTime to ensure same speed on varying FPS

### ISSUE THREAD

**Issue by DannyBen** [GoodBoyDigital/pixi.js#1474]
I am not sure what is the recommended practice with Pixi. 
All the examples I saw are not calculating / using delta time in their animate loop. Is this just for simplicity? or is delta time calculation not needed in Pixi?

In other words, should I just use `sprite.position.x += speed` or `sprite.position.x += speed*selfCalculatedDeltaTime`

**Comment by englercj** [comment]
How you decide to move around your objects doesn't really have anything to do with Pixi. This is just the rendering engine, the decision of how to simulate movement or physics is up to you in your game/engine.

Commonly people will use a simple fixed step size, or a straight delta time calculation. More advanced engines generally use a fixed step time (~16ms) for simulation, and may run multiple simulations based on frame time. It really just depends on your specific case what works best.

**Comment by DannyBen** [comment]
Well, how I choose to do things is definitely not pixi related, but my question was is pixi provides a facility or a recommended design pattern to handle this.

Since pixi provides the `requestAnimFrame(animate)` function, I was wondering if it also provides some deltaTime variable that I can call in this loop.

Where can I find documentation about `requestAnimFrame(animate)` and possibly other "global" functions that are available (if any)?

**Comment by oal** [comment]
I believe `requestAnimFrame` was just a polyfill from before most browsers shipped with `requestAnimationFrame`. A custom `requestAnimFrame` is no longer needed, and seems to have been removed completely from the Pixi dev branch (v3), as well as just being an alias for `requestAnimationFrame` in the current version.

See also: http://caniuse.com/#search=requestAnimationFrame

**Comment by DannyBen** [comment]
@oal this is a very helpful comment, now things make sense to me. With [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) there is a timestamp parameter that I can use. This is what I needed, thanks a lot.
