### ISSUE TITLE
Error touchmove

### ISSUE THREAD

**Issue by Manu33** [GoodBoyDigital/pixi.js#1477]
I have an error with 2.2.7 version of pixi.js with occur on Android tablet

*Cannot set property 'originalEvent' of undefined

Détail
TypeError: Cannot set property 'originalEvent' of undefined
at b.InteractionManager.onTouchMove (...pixi_227.js:13:6159)
at HTMLCanvasElement.l.wrapAndCatch.d.util.hasFunction.a.(anonymous function).d.util.hasFunction.f.(anonymous function) (http://d2zah9y47r7bi2.cloudfront.net/releases/current/tracker.js:3:492)

Browser : Mozilla/5.0 (Linux; U; Android 4.2.1; fr-fr; AT10-A Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30*

Regards,

**Comment by englercj** [comment]
Do you have this issue if you use v3? I think it is fixed there. If you still have problems with v3, feel free to post another issue.

**Comment by Manu33** [comment]
hi, i try this morning to go to the V3 but i have some others issues following the doc…

I have open one in github

Regards,
