### ISSUE TITLE
WebGLRenderer flips Y when masking into a render texture

### ISSUE THREAD

**Issue by davidfig** [GoodBoyDigital/pixi.js#1493]
This was a comment to the closed issue #1258 by NikkiKoole:

> Since f3730f1 that change I have some problems with renderTextures (without using masks) It only appears in one of the DisplayObjectContainer's children, but the fix is just to set this.renderSession.flipY = 1; in WebGLRenderer.renderDisplayObject, I'll try to make a self contained example because atm I am seeing this in a very large project of mine... (nearing deadline ;))

I ran into the same issue, where a DisplayObjectContainer's children were flipped during a renderTexture.render() call. The fix is what NikkiKoole mentioned: 

In the following line of PIXI.WebGLRenderer.prototype.renderDisplayObject()

    // make sure to flip the Y if using a render texture..
    this.renderSession.flipY = buffer ? -1 : 1;

becomes

    // make sure to flip the Y if using a render texture..
    this.renderSession.flipY = 1;

change it so flipY to be always 1.

I'm sure there's a reason for this check, but removing it fixes the issue.

**Comment by GoodBoyDigital** [comment]
All fixed in v3 :)

**Comment by davidfig** [comment]
Can't wait to get my grubby hands on v. 3.
