### ISSUE TITLE
Typed array

### ISSUE THREAD

**Issue by drkibitz** [GoodBoyDigital/pixi.js#1494]
*Before going any further, although this is mainly in regards to progress of v3 (dev branch). This is also not really an issue but a question.*

I've seen a few places where @englercj and @GoodBoyDigital have each mentioned usage and the testing of typed arrays around this repo, but I thought I would open this up to see if full understanding could be shared.

- What are the findings in perf when using typed vs regular arrays?
- Why are typed arrays used and why not, for example why are many matrix arrays in color filters regular arrays?

**Comment by GoodBoyDigital** [comment]
Good question sir!

As a general rule typed arrays seem to be a little faster. But this tends to manifest itself when working with big arrays. The reason they are not used for the colorMatrix is a bit of an oversight. We could change them to be float32Arrays to keep things consistent but I doubt it would have an effect on the perf..

**Comment by englercj** [comment]
That is pretty much it, large arrays are generally faster with typed arrays. But normal arrays that have only ints (or floats) are optimized anyway so they are close perf on smaller arrays. Honestly it doesn't matter all that much unless you need to count bytes, or want to ensure a certain type (such as ints and no floats) or something of that nature.
