### ISSUE TITLE
hitArea (Polygon) on Sprite is incorrect, Bug?

### ISSUE THREAD

**Issue by perara** [GoodBoyDigital/pixi.js#1500]
Using the same hitArea on Graphics and Sprite seems to yield different results, 
Shown below is a demonstration where i did the following:

*Edit*: The reason this is happening is because it does not handle absolute position, as the hitArea is relative to the sprite. Any way to fix this on a sprite level?

# Creating the Graphics object
1. Create Graphics from an Polygon array
2. Setting hitArea with the Polygon Array

# Creating the Sprite object
1. Convert Graphics element to an Texutre (.generateTexture)
2. Create an sprite with the texture generated
3. Position the Sprite with the further left coordinate of the polygon (To get same positioning as the graphics object)
4. Set hitArea of the Sprite with the Polygon Array (Same as Step 2 in Graphics)

The results are as following: 
![alt text](http://i.gyazo.com/9965cc37d7162f4acb4f311904f6d1cb.gif "Bug")

First i hover the object, which triggers the graphics mouseEvent (OK), but it does not however trigger the sprite mouseevent.

Investigating further, it seems like the hitArea is misplaced below the Sprite.
I'm not sure what i'm missing here, i have fiddled some with anchoring, but it did not make any difference. 

Worth to mention that the hitArea i try to use is absolute coordinates, not relative to the Sprite. May this be the reason, Any way to avoid if so?

This was also posted here
http://www.html5gamedevs.com/topic/12937-hitarea-on-sprite-not-positioned-correctly/

**Comment by englercj** [comment]
The hitArea is relative to the sprite, not absolute coords. Adjust your shape accordingly.

**Comment by perara** [comment]
OK, Thanks :+1:
