### ISSUE TITLE
"npm install" does not create a ready to use include

### ISSUE THREAD

**Issue by rygine** [GoodBoyDigital/pixi.js#1501]
I'm just getting started with this lib and simply added it to my package.json. After running `npm install` and trying to build my app, I get the following message:

`Error: Cannot find module 'brfs' from '.../node_modules/pixi.js'`

If I run `npm install` from within the pixi.js folder, all is well. Is `brfs` a dependency and not a devDependency? Am I missing something?

BTW, I'm using `var PIXI = require('pixi.js');` in my app.

**Comment by englercj** [comment]
Ah, thats because `brfs` should be in normal dependencies so the transform works when you browserify your app. Good catch!

**Comment by englercj** [comment]
Try now with the latest dev:

```
npm install  git+ssh://git@github.com:GoodBoyDigital/pixi.js.git#dev
```

**Comment by englercj** [comment]
This should be good in the latest dev, I'll put it in the next RC.
