### ISSUE TITLE
Polygon.points should be an array of Points or a flat array of coordinates ?

### ISSUE THREAD

**Issue by ayamflow** [GoodBoyDigital/pixi.js#1504]
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/math/shapes/Polygon.js#L22

Comment says `//if this is a flat array of numbers, convert it to points` but it actually does the opposite, tests if the first argument is a point, and then create a flat array of coordinates such as [x0, y0, x1, y1...].

I feel that it is a brain fart but correct me if I missed something :)

(I'm trying to create a polygonal hitArea and stumbled upon this - maybe why this hitArea behaves in a funky way?)

**Comment by englercj** [comment]
It used to be an array of points, someone (cough, [right here][0]) updated the code, but not the docs. The code looks correct, just has the wrong docs on them. Feel free to update them.

[0]: https://github.com/GoodBoyDigital/pixi.js/commit/f6dbc80a0c4649dfccee83befae801adf27eddf0#diff-629b48508ccf711d0682abd0f0e016edL20

**Comment by ayamflow** [comment]
Great, thanks for the precision! Makes sense now.
