### ISSUE TITLE
Sprite.prototype.destroy is overwritten

### ISSUE THREAD

**Issue by ayamflow** [GoodBoyDigital/pixi.js#1505]
by `Sprite.prototype = Object.create(...)` 2 lines after. So `Sprite.prototype.destroy` is `undefined`.

EDIT: and btw `Container.prototype.destroy.call(this);` also fail because Container doesn't have a `destroy` method.

**Comment by alvinsight** [comment]
Thanks, all fixed now :)

**Comment by ayamflow** [comment]
You rock!
