### ISSUE TITLE
Sprite sheets don't work with Data URIs

### ISSUE THREAD

**Issue by sfentress** [GoodBoyDigital/pixi.js#1509]
If I try and load a sprite sheet JSON file, and in my image path I use a Data URI, the JSONLoader incorrectly prepends that Data URI with the url path, creating an invalid uri.

For example, if my spritesheet is hosted at /images/sprites/, and it contains

    {
         ...
         "meta": {
               "image": "data:image/png;base64,iVBO..."
         }
    }

Then the ImageLoader will make a request for "**/images/sprites/**data:image/png;base64,iVBO..."

This can be seen at [JSONLoader:117](http://www.goodboydigital.com/pixijs/docs/files/src_pixi_loaders_JsonLoader.js.html#l117).

    // sprite sheet
    var textureUrl = this.baseUrl + this.json.meta.image;          // <------
    var image = new PIXI.ImageLoader(textureUrl, this.crossorigin);

I think it would be a simple fix to first check if it's a Data URI, and, if it is, pass it through unchanged. Do you want me to create a PR for this?

**Comment by englercj** [comment]
Merged into v2.x, will go out with the next v2 maintenance release.
