### ISSUE TITLE
EventEmitter2

### ISSUE THREAD

**Issue by drkibitz** [GoodBoyDigital/pixi.js#1511]
I finally got around to trying to get a couple of PRs done and building things.

I noticed resouce-loader depends on EventEmitter2 which is included in the bundle, and wondering if we can just use that as the emitter pattern. Similarly to how pixi.js now shares a dependency on async with resource-loader. I know this may be unwanted for perf concerns, but I was concerned about having both `src/core/utils/eventTarget.js` and eventemitter2.js lingering around in the bundle.

**Comment by englercj** [comment]
:+1: Do want.

**Comment by ivw** [comment]
Maybe consider [EventEmitter3](https://github.com/primus/eventemitter3), it has better performance and the same API, but without some unnecessary functions.

**Comment by drkibitz** [comment]
@ivw this issue is really more about code duplication, but if that's truly the case, maybe @englercj would consider using it here:
https://github.com/englercj/resource-loader/blob/master/package.json#L24

**Comment by englercj** [comment]
@drkibitz Updated resource loader to use ee3 in v1.3.0, and bumped pixi in `dev` to use v1.3.0.

**Comment by drkibitz** [comment]
@englercj that was fast ;)

**Comment by englercj** [comment]
Closed by #1532

**Comment by drkibitz** [comment]
@englercj I was actually working on this :( oh well, my bad not saying anything.

I did a take a different approach though. I kept eventTarget.js and pull in EventEmitter proto methods, but still implemented a different emit method to keep bubble prevention. So how is bubbling going to work with EE3?

**Comment by englercj** [comment]
@drkibitz We took bubbling out of the eventTarget anyway. We decided we didn't want it to happen for arbitrary events, just for the interaction stuff. So the interaction manager actually does the bubbling of events, other events are normal observer pattern.

Sorry to rip it out from under you like that!

**Comment by drkibitz** [comment]
@englercj got it, thanks
