### ISSUE TITLE
Error: Cannot find module 'brfs' from ./node_modules/pixi.js

### ISSUE THREAD

**Issue by nylira** [GoodBoyDigital/pixi.js#1512]
I just downloaded the latest version of pixi.js from npm, and was surprised (but delighted) to see the version updated to 3.0.0-rc1. I'm trying to use it with browserify right now. Unfortunately it seems like `brfs` is required in `dependencies`, not just `devDependencies` in `package.json`.

*Test case*
1. Create a new project with browserify set up.
2. Get pixi.js `npm install pixi.js`
3. Put `var PIXI = require('pixi.js')` in your main JS file.
4. Run `browserify` to compile the main JS file into a bundle.
5. Receive the error about `brfs` missing.

Looking at the dev branch it seems like `brfs` is in `dependencies` already, but it moved to the `devDependencies` section some where between there and publishing it to npm.

I'm working around this right now by simply running `npm install brfs --save` in my project directory. It's not a big deal, just thought I'd give a heads up.

**Comment by englercj** [comment]
Actually it was the other way around, we published to npm with it in "devDependencies" then it was recently fixed and we have not released a new RC.

The fix was for #1501 which was fixed after the RC1 release. I'll see if we can get RC2 out soon and alleviate this.

**Comment by englercj** [comment]
https://www.npmjs.com/package/pixi.js

Just released RC2.

**Comment by nylira** [comment]
Thanks for your hard work!
