### ISSUE TITLE
Sprite width always return 1

### ISSUE THREAD

**Issue by PierBover** [GoodBoyDigital/pixi.js#1517]
I'm using both 2.2.7 and the dev branch and I get the same result.

I create an empty sprite, I add some children to it, and it's width is never updated. The children are sprites that use the same image. I've waited for the image load using PIXI.AssetLoader and a callback, and then even waited 5 seconds more with a setTimeout and I get 1 anyway (and I'm developing in local).

If I use getBounds I get this object `PIXI.Rectangle {x: 20, y: 20, width: 1, height: 1, clone: function…}`

I'm using Chrome on OSX btw

**Comment by alvinsight** [comment]
The fact that you get 1 as width and height is the normal behaviour when the texture is not loaded.
However, if you did create the sprite and the texture inside a loading callback, there is a problem, can you provide us with a test case on jsfiddle/codepen/jsbin ?

**Comment by PierBover** [comment]
Here it is

http://pastebin.com/Qg7CsXEN

**Comment by englercj** [comment]
```js
loader.onComplete = init();
```

I'm almost positive that is not what you want. That is running the init function and assigning the return value (`undefined`) to the loader.onComplete property. You want:

```js
loader.onComplete = init;
```

**Comment by PierBover** [comment]
I?ve changed it to `loader.onComplete = init` and it makes no difference. Also the scene is already rendered when the timeout kicks in.

**Comment by englercj** [comment]
Look like the Sprite doesn't take children into account when calculating its bounds. Why is grid a Sprite and not a DisplayObjectContainer?

**Comment by PierBover** [comment]
It's the first time I'm using Pixi and since I read  it's based on the Flash API I thought that was the way to go.

DisplayObjectContainer returns the correct width and height.

So Sprite cannot be used as a container?

**Comment by englercj** [comment]
IT can, have children that render, but its main purpose is to render a texture. If you just need a container use DOC (Which sprite inherits from).

**Comment by PierBover** [comment]
Thanks for the help @englercj

**Comment by PierBover** [comment]
Is there some event that is triggered when the DOC and it's children have been initialized?

I'm using PIXI.AssetLoader but I still have to wait using a setTimeout to get the real size of the DOC.

**Comment by englercj** [comment]
You should only have to wait until the assets are loaded, that is why we recommend not creating the objects until all assets are loaded.

**Comment by PierBover** [comment]
Isn't that what PIXI.AssetLoader does?

**Comment by englercj** [comment]
Should be, and has been. If it isn't for you I'd like to see a running example of it broken, because that is exactly what it should do.

Also keep in mind that atleast one `updateTransform` walk has to happen or getBounds will be wrong. So that may what you are experiencing.

**Comment by PierBover** [comment]
You are absolutely right, after the first render pass it works perfectly
