### ISSUE TITLE
Stage Interactivity.. click callback Bug?

### ISSUE THREAD

**Issue by perara** [GoodBoyDigital/pixi.js#1523]
I'm having issues with the click callback ignoring the interactive flag:
https://jsfiddle.net/g1a6yj4t/2/

.mouseover and .mouseout seems to use the interactive flag correctly however.

The example is forked from: http://www.goodboydigital.com/pixijs/examples/6/
The only difference is that i set interactive = false in the click callback.
It does not work to set interactive on the stage, or the sprite itself. (Located at "//HERE" comment)

Seeing as starting with the interactive = false gives the expected behavior i wonder if this is a bug.

Edit:
Added all callbacks to check which one fired: https://jsfiddle.net/g1a6yj4t/4/
*mousedown
*mouseup
*click

**Comment by perara** [comment]
How would i go about a temporary fix for this?

**Comment by alvinsight** [comment]
Thank you for the test case,
Is it possible for you to null all the input callbacks inside the click function ? Like : 
button.mousedown = null,;
button.mouseup = null; 
button.click = null;
Obviously it would only work If you're building a very basic thing...

**Comment by perara** [comment]
Yes i ended up with something like that.
I'm reusing the old setInterval function implementing it like this:

    PIXI.DisplayObjectContainer.prototype.setInteractive = (state) ->
      queue = []
      queue.push(@)
  
      while queue.length > 0
        item = queue.pop()
        queue.push.apply queue, item.children
  
        item.interactive = state
        if !state
          item.__click = item.click
          item.__mousedown = item.mousedown
          item.__mouseup = item.mouseup
          item.click = null
          item.mousedown = null
          item.mouseup = null
        else
          item.click = item.__click
          item.mousedown = item.__mousedown
          item.mouseup = item.__mouseup
          item.__click = null
          item.__mousedown = null
          item.__mouseup = null

I'll just update setInterval when its fixed with:

        PIXI.DisplayObjectContainer.prototype.setInteractive = (state) ->
          @interactive = state

**Comment by GoodBoyDigital** [comment]
hi there! this looks the example is working like a champ in v3. 
There was a little scoping issue in your example that was also causing the issue:

```button.interactive = false // OR here??!?!?```
should be:
```this.interactive = false // OR here??!?!?```

Closing for now. Thanks for sharing and providing the fiddle, always handy for debugging :+1:
