### ISSUE TITLE
container boundaries cause issues with filters that increase the spatial size

### ISSUE THREAD

**Issue by CodeRect** [GoodBoyDigital/pixi.js#1535]
Preface - I have only tried this with `v3.0.0-rc2` but this is probably a general issue.

Description - The boundaries of a container are currently calculated by iterating over the contained children (see [1]). This is usually perfectly fine, but leads to issues with filters that increase the spatial size of the content. A common Gaussian blur for example is cut of on the said boundaries (see [2]).

Suggestion - add a padding attribute to containers, such that backwards compatibility is still guaranteed but someone who runs into this issue can easily fix it. 

[1] https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/display/Container.js#L337
[2] https://imgur.com/O2WkLfz

**Comment by englercj** [comment]
Ah I see, that is interesting. I think a padding attribute makes sense as we did that with Text as well, I'll add that in if you are cool with it @GoodBoyDigital?

**Comment by CodeRect** [comment]
I just figured out that there is already such an attribute (see [1]). I guess that the issue can therefore be closed, in case there is no further discussion about it. Thanks for this great library!

[1] https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/renderers/webgl/filters/AbstractFilter.js#L27

**Comment by englercj** [comment]
Oh, I actually forgot about that. Now I remember we added it for basically this same case before. Sorry about that!
