### ISSUE TITLE
boundary issues when rendering a DisplayObject to a RenderTexture

### ISSUE THREAD

**Issue by CodeRect** [GoodBoyDigital/pixi.js#1537]
Preface - I have only tried this with `v3.0.0-rc2` but this is probably a general issue.

Description - When the size of a `DisplayObject` that is being rendered to a `RenderTexture` is being changed, the boundaries are not updated accordingly. This is because the `RenderTexture` updates the boundaries according to the children of the passed `DisplayObject`, which however has none (see [1]).

Suggestion - This can be fixed by any user by embedding the `DisplayObject` into a `Container` and rendering the `Container` instead. It should however be fixed internally by introducing a check within the `renderWebGL` function.

[1] https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/textures/RenderTexture.js#L271

**Comment by englercj** [comment]
Does this issue still happen on the latest v3 release?

**Comment by CodeRect** [comment]
Does seem to work now, thank you!

The referenced pull request however does not seem to be the one that solved the problem though. I assume that @GoodBoyDigital solved this issue, so I would highly appreciate it if he would leave a quick comment and reference the commit that solved this issue.
