### ISSUE TITLE
texture.render(), when "clear" parameter is set to true, doesn't clear the texture

### ISSUE THREAD

**Issue by clementchenebault** [GoodBoyDigital/pixi.js#1543]
in pixi.js, 
RenderTexture.prototype.renderWebGL = function (displayObject, matrix, clear, updateTransform)
this.textureBuffer.clear();
should be : 
this.textureBuffer.clear(true);

@GoodBoyDigital

**Comment by GoodBoyDigital** [comment]
:+1:

**Comment by adelciotto** [comment]
fixed in https://github.com/GoodBoyDigital/pixi.js/commit/f337c75c7cb4afff66d3ea4afb5e8b67bdcc8958
