### ISSUE TITLE
Spine image scaling ignored

### ISSUE THREAD

**Issue by oarmstrong** [GoodBoyDigital/pixi.js#1544]
Following on from my previous issue, #1539, which I closed due to a lack of information, I've narrowed the issue down.

A [test animation](http://www.filedropper.com/broken) that my animator has created exhibits the problem.

![2015-03-17-152024_365x193_scrot](https://cloud.githubusercontent.com/assets/187195/6691501/d527e376-ccbe-11e4-882b-d9c39f91e20f.png)

He says that PIXI is ignoring the scaling on the images in the initial setup, and when he [changed it](http://www.filedropper.com/working) such that the initial scaling is on the bones instead, it works fine.

![2015-03-17-154130_341x157_scrot](https://cloud.githubusercontent.com/assets/187195/6691493/c9054458-ccbe-11e4-9bb8-2e9d52e23890.png)

For the first test animation, it displays fine in both Spine and the [Skeleton Viewer](http://esotericsoftware.com/spine-skeleton-viewer), so this is a bug somewhere in either PIXI or the spine.js runtime.

**Comment by oarmstrong** [comment]
If you can point me into the general area this bug may be in, then I can take a whack at fixing it myself?  I wouldn't know where to look to get started.

**Comment by englercj** [comment]
All the spine code in v3 is in the spine plugin:

https://github.com/GoodBoyDigital/pixi.js/tree/dev/src/spine

And in v2 it is in the extras:

https://github.com/GoodBoyDigital/pixi.js/tree/v2.x/src/pixi/extras

I know very little about our implementation of spine since I don't ever use it.

**Comment by englercj** [comment]
Tracking this at pixijs/pixi-spine#12
