### ISSUE TITLE
DisplayObjects using filters cause WebGL errors when moved off screen in v3.0.0-rc2

### ISSUE THREAD

**Issue by baseten** [GoodBoyDigital/pixi.js#1547]
See this fiddle: http://jsfiddle.net/arxx5zxj/3/

Appears to be because `this.frame` inside `RenderTarget` contains negative dimensions when attempting to render a `DisplayObject` that has been moved outside of canvas bounds, when using a filter on it (and obviously using `WebGLRenderer`).

Error is: `WebGL: INVALID_VALUE: viewport: size < 0`

Everything still renders correctly but the error causes a slower framerate.

**Comment by GoodBoyDigital** [comment]
nice catch!

**Comment by GoodBoyDigital** [comment]
all fixed now. Thanks for sharing! :+1:
