### ISSUE TITLE
 [v3] Canvas from RenderTexture can not be retrieved

### ISSUE THREAD

**Issue by CodeRect** [GoodBoyDigital/pixi.js#1552]
Description - The current implementation is accessing an invalid attribute (see [1]). What currently is `this.textureBuffer.width / height` should be `this.textureBuffer.size.width / height` instead.

Additional suggestion - It is currently not possible to get access to the raw pixel data of a texture directly. An additional interface that returns a three dimensional array would therefore be a nice feature that should be straightforward to integrate into the library. A `getPixel(x, y)` would likewise be a nice addition.

[1] https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/textures/RenderTexture.js#L406

**Comment by englercj** [comment]
Neat feature, we would implement it by drawing to a canvas and doing `getImageData` which you can do now. Feel free to put in a PR for this as a plugin in extras.

**Comment by CodeRect** [comment]
oh snap - i did not read the 'as a plugin in extras' part - the issued pull requests are hopefully still usable

**Comment by englercj** [comment]
Closing since the related PRs have been merged.
