### ISSUE TITLE
[v3] Resource Loader on iPad 2 Canvas

### ISSUE THREAD

**Issue by adireddy** [GoodBoyDigital/pixi.js#1557]
Just noticed an issue with loader on iPad 2 Canvas.

It's in middlewares/parsing/blob.js line 12 where `resource.data` is used.

When I debugged it I have seen the data being a long string as shown below instead of an object.
`"�PNG
↵↵
IHDR���>a�	pHYs��↵OiCCPPhotoshop ICC profilexڝSgTS�=���BK���KoR RB���&*!......`

Which results in
`TypeError: 'undefined' is not an object (evaluating 'resource.data.type.indexOf')`

Test URL: http://adireddy.github.io/demos/haxe-pixi/v3/loader.html

**Comment by adireddy** [comment]
Found another issue with the loader on the same device (iPad 2).

It fails when loading spritesheet (json) file with the following error.
`SYNTAX_ERR: DOM Exception 12: An invalid or illegal string was specified.`

Resource.js line 277.

It's failing on json even if I hardcode xhr.responseType value to 'json'

Test URL: http://adireddy.github.io/demos/haxe-pixi/v3/spritesheet.html

**Comment by englercj** [comment]
This is a resource loader bug, tracking in englercj/resource-loader#6.
