### ISSUE TITLE
mousemoveoutside event

### ISSUE THREAD

**Issue by ivw** [GoodBoyDigital/pixi.js#1564]
It would be useful to have a `mousemoveoutside` event.
Just like you have both a `mouseup` and `mouseupoutside` event.

One use case is when you have a map that can be dragged around, like in Google Maps. Without mousemoveoutside the dragging will stop when you're over any overlay element or outside the map element.

**Comment by englercj** [comment]
Good idea!

**Comment by GoodBoyDigital** [comment]
hello! could you keep track of if the curser is over or not over to achieve this? the mouse moved event is dispatched ell the time (even if the mouse is not over the current element)

**Comment by ivw** [comment]
The mousemove event is not dispatched if the mouse is not over the DOM canvas element

**Comment by GoodBoyDigital** [comment]
mouse move is now on the window so it gets called even if you mouse off the renderer view :+1:

**Comment by patrickfabrizius** [comment]
The "outside" events are very useful, but why aren't they mentioned in the API docs on http://pixijs.github.io/docs/PIXI.interaction.InteractionManager.html ?

**Comment by englercj** [comment]
Because that documentation is generated from comments in the source, if there are no comments in the source to document them it won't be in the documentation. Feel free to put in a PR to correct it.
