### ISSUE TITLE
WebGLRenderer not scaling graphics correctly at small sizes.

### ISSUE THREAD

**Issue by redheringe** [GoodBoyDigital/pixi.js#1566]
WebGLRenderer does not appear to be scaling Pixi.Graphics objects when graphics objects get very small.
-issue not observed with CanvasRenderer
-issue observed in dev branch, v3, v2 etc

WebGLRenderer: http://jsfiddle.net/zku04sm9/5/
CanvasRenderer: http://jsfiddle.net/zku04sm9/6/

any ideas?

thanks!

**Comment by englercj** [comment]
The stencil buffer in webgl is used to draw graphics, it has no antialiasing. This is what causes the edges to be sharp when drawing with webgl.

**Comment by redheringe** [comment]
is that a fundamental limitation, or within the realm of potentially fixable?

**Comment by englercj** [comment]
You can work around it by drawing your shapes with something other than the Graphics class. For example, drawing to a canvas and using that as a sprite texture. Or using FXAA for antialiasing instead of native.

**Comment by redheringe** [comment]
clever workaround idea on the canvas to sprite workaround,

as for fxaa, wouldn't that still be run with webgl/stencil and thus still have problems?
http://jsfiddle.net/zku04sm9/7/  used webgl and fxaa=true, same issue

grattitude!

**Comment by englercj** [comment]
Yeah I don't think you can make that look very good with just antialiasing anyway. Even on native canvas it doesn't look great. With native antialias it looks better:

http://jsfiddle.net/zku04sm9/8/

By the way to use antialiasing you need `{ antialias: true }` and for fxaa you need `{ antialias: true, forceFXAA: true }`.

**Comment by redheringe** [comment]
good to know, thanks for the pointers-
