### ISSUE TITLE
[V3-RC2] xhr.responseType JSON unsupported with cocoonJS

### ISSUE THREAD

**Issue by Greewi** [GoodBoyDigital/pixi.js#1570]
When loading a json with PIXI.Loader, Cocoon JS says that the XHR response type json is not implemented.

By commenting the following line in **Resource.prototype._loadXhr**, the loading work in Cocoon (and in other navigators) :
```javascript
// set the responseType
xhr.responseType = this.xhrType;
```

**Comment by Greewi** [comment]
(Note that Cocoon seem to hate any response type set, including blob.)

**Comment by englercj** [comment]
Tracking this in englercj/resource-loader#6, was going to look at these this weekend.
