### ISSUE TITLE
Is there a migration guide for v2 -> v3 planned?

### ISSUE THREAD

**Issue by mreinstein** [GoodBoyDigital/pixi.js#1572]
curious about the changes I'd need to upgrade my game to v3

**Comment by JiDW** [comment]
There is already a lot of console.log telling you what to do when you try to use PIXI v3 with an old code.

http://www.serenity-ff.com/images/screenshots/screenshot173415001.png

**Comment by englercj** [comment]
The plan was pretty much that, the deprecation file.

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/deprecation.js

**Comment by mreinstein** [comment]
very good, very good. thanks!

**Comment by mreinstein** [comment]
The only downside this I can see is that someone won't be able to weigh the pros and cons of updating. i.e., if I have a huge project it would be nice to have a sense of the work involved before diving into a full-on upgrade. Not a problem for me as my project is still small but I could see it being an issue for others.

**Comment by englercj** [comment]
The API changes are pretty minimal, and the things that have changed are in the backwards compat layer there. So ideally there would be almost nothing to change if you are OK with warnings in the console.

**Comment by mreinstein** [comment]
ah ok so it's not really major breaking changes then. with the move from 2.x to 3.x I assumed semver style breaking API changes.

**Comment by englercj** [comment]
@mreinstein It is semver style breaking change. If we made only 1 change (like renaming `DisplayObjectConainter` to `Container`, which we did) that would be a major version bump according to semver.

**Comment by drkibitz** [comment]
See these 2 specific breaking changes called out as such with errors:
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/deprecation.js#L14
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/deprecation.js#L24

**Comment by drkibitz** [comment]
Now that I'm looking at those errors, should probably get in getters as well ;)

**Comment by drkibitz** [comment]
another breaking change:
- Stage and Container are compatible but are not the same, e.g. backgroundColor is a renderer property.

**Comment by englercj** [comment]
@drkibitz [Yes](https://github.com/GoodBoyDigital/pixi.js/pull/1563#discussion_r26809657) :)
