### ISSUE TITLE
[V3-RC3] Tilling sprite have a wrong internal scale with WebGLRenderer

### ISSUE THREAD

**Issue by Greewi** [GoodBoyDigital/pixi.js#1573]
Hello,

When using a TillingSprite with a WebGLRenderer, the sprites are not correctly displayed. Each repetition occured at the correct position, but the texture itself is streched (and croped by the repetitions).

The display is correct with the CanvasRenderer.

You can see this behavior here : http://jsfiddle.net/99L7nwaw/4/

I suspect the method TilingSprite.generateTilingTexture, but it's just a blind guess.

**Comment by GoodBoyDigital** [comment]
should work like a champ now! thanks for sharing, the fiddle made it easy to diagnose and fix :+1:

**Comment by Nazariglez** [comment]
Hi!,

It's fine now, but if you use a texture with alpha, and create two TilingSprite with different textures with a WebGLRenderer, the second sprite is a mix of both textures. -> https://jsfiddle.net/99L7nwaw/5/

**Comment by GoodBoyDigital** [comment]
great catch! fixed now in the dev branch. :+1:
