### ISSUE TITLE
Collision between Sprites and Graphics

### ISSUE THREAD

**Issue by gplopes** [GoodBoyDigital/pixi.js#1576]
Hey guys, 
I'm a new js and pixi.js programmer and I've been struggling to do collision between sprites and graphics. I'm using this function and it works fine between sprites.

 /// Collision

        PIXI.Sprite.prototype.collision = function (enemies) {

            for (var i = 0; i < enemies.length; i++) {
                var enemy = enemies[i];
                var xdist = enemy.x - this.x;

                if (xdist > -enemy.width / 2 && xdist < enemy.width / 2) {
                    var ydist = enemy.y - this.y;
                    if (ydist > -enemy.height / 2 && ydist < enemy.height / 2) {

                        // HIT CODE
                        
                    }
                }
            }
        }

Should I add some extra option in my Graphics? 

        var circleTime = new PIXI.Graphics();
                circleTime.lineStyle(2, 0xFFFFFF, .1);
                circleTime.drawCircle(160, ($(window).height() - 200), 19, { antialias: true});

**Comment by GoodBoyDigital** [comment]
Hi there and welcome to the pixi world :)

To be honest pixi does not have any built in functionality for checking if elements are colliding as this falls outside of its responsibility. Pixi.js is basically only takes care of your rendering.

I would suggest using a physics engine such as the excellent p2.js (https://schteppe.github.io/p2.js/) as they integrate very nicely together.

hope that helps and good luck!

**Comment by gplopes** [comment]
@GoodBoyDigital it did. 
Thanks lot. :+1:
