### ISSUE TITLE
baseTexture.dirty() is not dirty enough with CanvasRenderer

### ISSUE THREAD

**Issue by edankwan** [GoodBoyDigital/pixi.js#1579]
If the baseTexture source dimension has changed, only update the width & height of the sprite and the do the baseTexture.dirty() is not good enough to update the image size with CanvasRenderer

Example:
http://jsfiddle.net/t0905jpn/

In this example, the first one is using CanvasRenderer(), the second one is using WebGLRenderer(). I set the sprite baseTexture canvas as width&height 1, after the image is loaded, I updated the canvas size and draw the image on the canvas. In order to update the size of the sprite, I use baseTexture.dirty() and change the sprite.width/height to the image size. However, it only works on WebGLRenderer.

Solution: uncomment the lines 27-28

**Comment by englercj** [comment]
If at all possible can you try the latest builds in v3 ([dev][d] branch)? I don't think v3 suffers from this issue.

[d]: https://github.com/GoodBoyDigital/pixi.js/tree/dev/bin

**Comment by GoodBoyDigital** [comment]
hello! this should work fine now in v3

```sprite.texture.update();``` instead of ```baseTexture.dirty()``` though. enjoy! :+1:
