### ISSUE TITLE
[V3] Thoughts on brfs

### ISSUE THREAD

**Issue by mattdesl** [GoodBoyDigital/pixi.js#1581]
We are using brfs a fair bit in our own projects and I personally find it "heavy handed." The main purpose of brfs is to make existing Node programs compatible with Browserify without any source modifications. It was never really designed to be the most user-friendly way of grabbing UTF8 strings in browser/Node.

Here's my thoughts:

- it's a bit of a beast for newbies since all the docs deal with NodeJS
- it leads to a lot of boilerplate and repetition (error prone)
- if you forget `"utf8"` it returns a Buffer which will make your bundle a fair bit larger and can break code that expects a string

I've been toying with the idea of making a module specifically for this purpose in Node / Browser. Maybe Pixi would also benefit from it? It would look like this (name pending): 

```js
var contents = require('file-contents')('./foo.txt')
console.log(typeof contents) // -> 'string'
```

It would use [static-module](https://www.npmjs.com/package/static-module) so the mechanism would be the same as brfs. It would come in the form of a NodeJS module (dumb wrapper on `readFileSync`) and another module for the browserify transform. 

Alternatively; since Pixi is only using brfs to load in shaders, you may benefit from a module specifically targeting that use-case. It might later grow to support compile-time minification, validation, or some Pixi-specific features. 

```js
var fragSourceStr = require('load-pixi-shader')('./blur.frag')
```

**Comment by englercj** [comment]
Double posted, closing for #1582.

**Comment by mattdesl** [comment]
Weird, not sure how that happened.

:+1:
