### ISSUE TITLE
Thoughts on brfs

### ISSUE THREAD

**Issue by mattdesl** [GoodBoyDigital/pixi.js#1582]
We are using brfs a fair bit in our own projects and I personally find it "heavy handed." The main purpose of brfs is to make existing Node programs compatible with Browserify without any source modifications. It was never really designed to be the most user-friendly way of grabbing UTF8 strings in browser/Node.

Here's my thoughts:

- it's a bit of a beast for newbies since all the docs deal with NodeJS
- it leads to a lot of boilerplate and repetition (error prone)
- if you forget `"utf8"` it returns a Buffer which will make your bundle a fair bit larger and can break code that expects a string

I've been toying with the idea of making a module specifically for this purpose in Node / Browser. Maybe Pixi would also benefit from it? It would look like this (name pending): 

```js
var contents = require('file-contents')('./foo.txt')
console.log(typeof contents) // -> 'string'
```

It would use [static-module](https://www.npmjs.com/package/static-module) so the mechanism would be the same as brfs. It would come in the form of a NodeJS module (dumb wrapper on `readFileSync`) and another module for the browserify transform. 

Alternatively; since Pixi is only using brfs to load in shaders, you may benefit from a module specifically targeting that use-case. It could later grow to support compile-time minification, validation, or some Pixi-specific features. 

```js
var fragSourceStr = require('load-pixi-shader')('./blur.frag')
```

(This could be like a bare-bones version of glslify #1460)

**Comment by englercj** [comment]
Good points, I thought brfs did inline replace the fs code with the loaded file?

**Comment by mattdesl** [comment]
Yeah; brfs does inline replace the code. The custom transform would do the same, so the above code would get compiled to:

```js
var contents = "some contents of a file";
console.log(typeof contents) // -> 'string'
```

I haven't found any transforms like this with Node/Browser support, but maybe they exist. This is something I am thinking about for my own projects, so I may build it independently of Pixi, but thought you guys might want to chime in.

**Comment by englercj** [comment]
@mattdesl So what you are trying to solve is syntax sugar for `fs.readFileSync()` to reduce potential misuse?

**Comment by mattdesl** [comment]
Yep, that's basically the goal. Pretty minor. ;)

**Comment by serprex** [comment]
Does PIXI ever plan to be usable in node? (be it for serverside rendering through node-canvas, or if people decide to have games run off browser but through node)

If yes, that's a reason to not rely on browserify so much (which would include avoiding a module that would add use-strict in the build phase)

**Comment by englercj** [comment]
@serprex We don't really have any plans, really, because we don't really have a use-case. It is something that is *easier* by using browserify, and especially by using brfs.

**Comment by drkibitz** [comment]
@serprex @englercj I plan to contribute more in the isomorphic arena. There's parts that are impossible, and parts that are completely possible with some changes. Just need to contribute ;)

In this regard, brfs is a pretty good solution for now.

**Comment by englercj** [comment]
Closing this since for now we will be sticking with brfs as it is currently the best solution for what we want to do.
