### ISSUE TITLE
PIXI.Text padding doesn't appear to work correctly on current dev branch

### ISSUE THREAD

**Issue by baseten** [GoodBoyDigital/pixi.js#1584]
Sorry, I appreciate dev might not be stable! Ordinarily I wouldn't want to use it, but I need a couple of the latest fixes in my project.

This is rendered with v3.3.0-rc3

http://jsfiddle.net/zk45377h/4/

This is rendered with dev, the bottom of the text canvas is trimmed much earlier

http://jsfiddle.net/uexztot4/13/

Diffing `Text.js` between the two, doesn't show up any major differences in the way the padding and canvas height is calculated, so I guess it is happening elsewhere.

**Comment by GoodBoyDigital** [comment]
how strange! this bug seems to have been introduced in the last day or so? Have we done any texture tweaks?

**Comment by englercj** [comment]
Regarding the revert, what was the breaking change? Moving the 'update' event to be in the frame setter?

Just curious, because there was a mix of things in there some of which should probably stay if it wasn't the breaking change.

**Comment by GoodBoyDigital** [comment]
I'm not 100% sure to be honest matey. At a glance it looked like it should have not made a difference, but reverting it did fix the above.. Was looking into the whole canvas update thing on Sunday evening so hopefully should have a fix for it soon. 

I will make sure to put the changes back in and test to see which one one was the culprit too

**Comment by englercj** [comment]
Super weird, looking forward to figuring out what that was. Right now, update doesn't happen if the user changes the frame which can cause the sprite to not update size (since it listens for update) which is why I made that change. Possibly related?

**Comment by GoodBoyDigital** [comment]
absolutely related i think! Definitely a good shout on the whole update flow - gonna make sure to peel that back and take a look. closing this one for now as it should be fixed. Cheers all! :+1:
