### ISSUE TITLE
npm install gets wrong version of resource-loader

### ISSUE THREAD

**Issue by rygine** [GoodBoyDigital/pixi.js#1585]
Using 3.0.0-rc3.

I've tried manually changing the version in package.json to something else, and for some reason, I continue to get 1.3.2, which does not have the json parsing middleware and throws an exception.

I'm coming from 3.0.0-rc1 which grabs the right version. what am I missing?

**Comment by englercj** [comment]
Good catch, RC3 should be using `1.3.0` which has bugs of its own. I need to release a new RC. I'll do that now.

**Comment by englercj** [comment]
RC4 now expects and properly uses 1.3.2 of asset loader.
