### ISSUE TITLE
Question: Which version to use?

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#1586]
I'm writing an article where in one example I use Pixi JS. The main focus is performance (animating/moving images). Should I use the latest version 2, latest version 3 (eg the latest release candidate), or the latest (version 3) from the dev branch? (Would it be OK to use the latter?)

**Comment by englercj** [comment]
Latest v3 from the dev branch would be the best to use. We will likely release a new RC this week.

**Comment by englercj** [comment]
Just released RC4, use that.

**Comment by tobireif** [comment]
When I get to the Pixi example I'll use the then latest RC. Thanks!
