### ISSUE TITLE
[V3-RC4] PIXI.Loader is undefined

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1588]
Hello,

Did I miss something  (like a new name for the asset loader) or is there a bug with the RC3 and RC4 ?

I can't call "new PIXI.Loader()" anymore.

**Comment by englercj** [comment]
https://twitter.com/rolnaaba/status/580372751073951744

https://github.com/GoodBoyDigital/pixi.js/issues/1565

Also mentioned it on other chat sources and IRC as well lol. Plugins moved into their namespaces. If you want to create your own loader it is in the `loaders` plugin: `PIXI.loaders.Loader`.  There is also a pre-made loader that pixi is nice enough to export for you at `PIXI.loader`.

**Comment by JiDW** [comment]
Ok then, thanks ! There is an IRC channel ? 
Anyway, it should be added to "deprecation.js" I guess.

**Comment by englercj** [comment]
https://gitter.im/GoodBoyDigital/pixi.js

Is a chat channel we use often.

**Comment by englercj** [comment]
Also the docs are up now, so it is easier to find what you need:

http://pixijs.github.io/docs/
