### ISSUE TITLE
from V2 to 3 performances issue due to stage to container

### ISSUE THREAD

**Issue by Inateno** [GoodBoyDigital/pixi.js#1589]
Hello,

I looked around to see if anyone submit this and it seem not, I made a simple benchmark on V2 and migrated it to V3 and performances goes from 59fps to 16.
Here is the piece of code

```javascript
        var ycar, ycar2, x, y;
        for ( var i = 0; i < 2000; ++i )
        {
            x = Math.random() * 10000 >> 0;
            y = Math.random() * 5000 >> 0;
            ycar = PIXI.Sprite.fromImage( "imgs/ycar_1.png" );
            ycar.scale.set( 0.5, 0.5 );
            ycar.position.x = x;
            ycar.position.y = y;
            ycar2 = PIXI.Sprite.fromImage( "imgs/ycar_2.png" );
            ycar2.position.x = x + 1024;
            ycar2.position.y = y + 48;
            container.addChild(ycar);
            container.addChild(ycar2);
        }
```
I move the objects inside/outside the fov with arrow keys but now I just have to move the container if I did things well (anyway objects or container change anything).

```javascript
    container.position.x += xdir * 30;
    container.position.y += ydir * 30;
```

So I don't know if the best way now is to render objects one by one or to do a verification if the object is inside the fov manually.

See ya

**Comment by GoodBoyDigital** [comment]
Wow! That's quite the drop! If you could provide the full benchmark (v2 and v3) iI would be keen to take a look to see where the issue lies.. Thanks!

**Comment by englercj** [comment]
Yeah that seems like a crazy perf drop! Most of our tests show v3 to be faster, I'm really curious to see the full test code!

**Comment by Inateno** [comment]
I just find a way to improve perf from 16 to 35-42 by putting sprite in a container, and this container in a global container here is what change in the loop:

```javascript
            ct = new PIXI.Container();
            ct.position.x = x;
            ct.position.y = y;
            ct.addChild( ycar );
            ct.addChild( ycar2 );
            map.addChild( ct );
```
I'm making the 3 versions and uploading them, I'll post when it's done

**Comment by Inateno** [comment]
V2 ~53-55 fps on chrome 41, 60 on Firefox and same on IE11:
http://inateno.com/protos/pixi_bench_v2/

V3 18fps on chrome (I found a way from 16fps to 18 but not enough...) and 26 on Firefox:
http://inateno.com/protos/pixi_bench_v3/

I use 2 images 2048*2048 and spare them randomly.
As you will notice, on V2 if you move all objects completely out of your fov you will go from 55 to 60 (because there is nothing to render) but on V3 this doesn't appear, I think it's a boundary problem ?

You'll maybe have different fps depends on your hardware, I have a pretty good one...

**Comment by GoodBoyDigital** [comment]
i see! They are very different experiments - the 'v2' version uses only one texture and benefits from sprite batching. The 'v3' example uses 2 textures, this specific setup forces pixi to render each sprite as a separate call.

**Comment by Inateno** [comment]
?? I use two texture in both example, the loop is the same only container change.

**Comment by GoodBoyDigital** [comment]
nope! the v2 version only renders using ycar_1

**Comment by Inateno** [comment]
ah my bad I do map.addChild( ycar, ycar2 ) I try with 2 lines.

**Comment by GoodBoyDigital** [comment]
v2 - one draw call using ycar_1 -> ![screen shot 2015-03-24 at 9 36 02 pm](https://cloud.githubusercontent.com/assets/3112434/6813533/e2d8710c-d26d-11e4-8496-9e7621d5914d.png)

v3 -> a seperate draw call alternating between ycar_1 and ycar_2 ->
![screen shot 2015-03-24 at 9 36 28 pm](https://cloud.githubusercontent.com/assets/3112434/6813544/045c4e0c-d26e-11e4-8108-620c6039dff5.png)

each 'i' shows a draw call.

**Comment by englercj** [comment]
If you look in the trace output of webgl inspector in chrome you can see how we have to call draw repeatedly. Mostly likely because the demo adds sprites with alternating textures, so we have to flush and draw each new texture.

**Comment by Inateno** [comment]
My bad the difference was 
```javascript
            map.addChild( ycar, ycar2 );
```
```javascript
            ct.addChild( ycar );
            ct.addChild( ycar2 );
```
And I forgot the first way doesn't work this way ><

So the way to improve the draw call if I use different texture is to push all "ycar" together then all "ycar2" this way webgl will render first all ycar1 then 2 and don't switch ?

I try some other way but I think we can close my issue, and sorry for the mistake.

**Comment by GoodBoyDigital** [comment]
no worries man! always good to flag this stuff as we pride ourselves on only getting faster.. not slower :)

cheers!

**Comment by Inateno** [comment]
@englercj I tried put all of ycar_1 in first, then all of the ycar_2 no fps change.
