### ISSUE TITLE
New home for Spine

### ISSUE THREAD

**Issue by englercj** [GoodBoyDigital/pixi.js#1591]
Hey all,

Mat and I have decided we want to split the spine implementation to a plugin module, outside of the main repository. It would live at https://github.com/pixijs/pixi-spine and be initially based upon the current spine implementation.

We are looking for someone passionate about spine in pixi who would take this plugin and drive it forward from now on. Anyone interested in working on that?

Thanks!

**Comment by drkibitz** [comment]
Sorry, haven't actually used the spine implementation in pixi for a project yet, but thought I'd give a :+1: for the direction ;)

**Comment by ivanpopelyshev** [comment]
Ok, let me try it. I can watch for pull requests and update it for new versions of pixi if its necessary.

**Comment by englercj** [comment]
I'll update this thread when I have the new plugin repo up and running.

**Comment by GoodBoyDigital** [comment]
You the man @ivanpopelyshev :+1:

**Comment by ivanpopelyshev** [comment]
Hey, Mat!
Nice to see you here :) Remember OGS2013?

**Comment by GoodBoyDigital** [comment]
Absolutely! Mr Bombermine :D Hope you are well!

**Comment by englercj** [comment]
I've setup the start of the new spine repo:

https://github.com/pixijs/pixi-spine

It is the v3 version of spine with the changes that @ivanpopelyshev has made recently merged in. Next steps are to remove spine from this repo in the v3 branch, and to publish the other spine implementation to be used here via npm.

**Comment by ivanpopelyshev** [comment]
Stupid question: tabs or spaces? This files have both.

**Comment by englercj** [comment]
I'll add an editorconfig, we prefer spaces.

**Comment by ivanpopelyshev** [comment]
Ok, I'll look at it today or tomorrow. Got a busy weekend :)

**Comment by englercj** [comment]
This repo has been updated to use pixi-spine now.
