### ISSUE TITLE
cacheAsBitmap : scale, undefined error and blink

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1595]
Hello,

I have 3 bugs with cacheAsBitmap.

1) One is common to both WebGl and Canvas render but I'm not sure if it is not fixable by design or if we can do something : 

When you set cacheAsBitmap to true on a container, you will see a "blink".

On webGL, your next frame will display the cached container on x:0 and y:0 and scale:1 inside the rendered container (ex stage).
It results in a visible "blink" if your container is not at x:0/y:0 or if it has a scale (or a "worldScale" from a parent)

On Canvas, you will just see a black rectangle.

2) When you set cacheAsBitmap to true on Canvas, you will get the following error : 
Uncaught TypeError: Cannot read property 'bind' of undefined => cacheAsBitmap.js:221 

3) On WebGL, the fact that it does not use the scale property or the scale of the parents produces a very blurry texture : 
(Here with a scale of 1.2)
cacheAsBitmap:false => http://www.serenity-ff.com/images/screenshots/screenshot162231001.png
cacheAsBitmap:true => http://www.serenity-ff.com/images/screenshots/screenshot162304001.png

Here is a jsFiddle to toy with the bugs (it sets cacheAsBitmap to true after 2 seconds) : http://jsfiddle.net/e9Lygkdx/2/

Regards.

**Comment by ayamflow** [comment]
I'm having the issue 2 as well.

**Comment by GoodBoyDigital** [comment]
righto! Today is a pixi day :) time to look into this one. Thanks for the fiddle @JiDW will make it much easier to fix. Watch this space...

**Comment by GoodBoyDigital** [comment]
smoothness sorted :+1:  now to fix that little flicker..

**Comment by GoodBoyDigital** [comment]
flicker sorted now too.. now to poke around with canvas. Almost done!

**Comment by GoodBoyDigital** [comment]
All sorted now on dev branch :+1: thanks all!

**Comment by ayamflow** [comment]
Well thank you!

**Comment by JiDW** [comment]
Thanks Mat !

However my bitmap was still blurry and I found that is was because the code use CONST.RESOLUTION to set the resolution of the texture. When you set cacheAsBitmap to true, shouldn't it always use the renderer resolution ?

Is there a difference between CONST.RESOLUTION and the renderer.resolution ?

**Comment by GoodBoyDigital** [comment]
No worries @JiDW !

have you tried setting CONST.RESOLUTION to 2 on start up? that should make all generated textures (text / renderTexture / cacheAsBitmap) use a resolution of 2

cheers!

**Comment by JiDW** [comment]
Yes, I've done that earlier and it works perfectly, thanks ! My question was more about the difference between this const and the renderer property.

**Comment by GoodBoyDigital** [comment]
the const is default value for any generated textures. For example if you make a renderTexture and don't specify a resolution the default will be CONST.RESOLUTION.

 I guess it might make sense to make the default resolution the resolution of the renderer provided though..

**Comment by elmoeleven** [comment]
@GoodBoyDigital, are you going to make the default resolution the resolution of the current renderer? Is that in the pipeline? Thanks!
