### ISSUE TITLE
[V3-RC4] stopPropagation function missing

### ISSUE THREAD

**Issue by benny00100** [GoodBoyDigital/pixi.js#1596]
The stop propagation function is missing in the event object. Refer to following example:

sprite.click = function(e) {
  e.stopPropagation():  
};

**Comment by englercj** [comment]
Looks like the `stopped` functionality is there but you have to set the property directly on the event data `e.stopped = true`?

We should add the fn back in though if it makes sense.

**Comment by benny00100** [comment]
Well, 

e.stopped = true 

works for me for now. So, thanks.

Adding the fn back in would make sense for me, too - though.

**Comment by GoodBoyDigital** [comment]
@englercj  Can we add the function to the event class? or would that mess with the whole NPM philosophy?

**Comment by englercj** [comment]
It should definitely be added to the [`eventData`](https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/interaction/InteractionManager.js#L61) object. That is where `stopped` lives, and is what is passed to users. It doesn't have anything to do with ee3.

**Comment by GoodBoyDigital** [comment]
stopPropagation added to eventData in the interaction Manager. enjoy! :+1:
