### ISSUE TITLE
Transparent WebGL renderer doesn't work with Multiply blend mode

### ISSUE THREAD

**Issue by spaceoddity** [GoodBoyDigital/pixi.js#1597]
When using a transparent WebGL renderer and sprites/graphics with blend mode multiply, nothing renders.

Example using PIXI.blendModes.ADD (everything looks okay)
http://jsfiddle.net/jcx4eunz/2/

Example using PIXI.blendModes.MULTIPLY (nothing renders)
http://jsfiddle.net/jcx4eunz/3/

**Comment by GoodBoyDigital** [comment]
pretty sure thats the expected result of a multiply on a transparent bg? Unfortunately there is no way to get the blend modes to blend properly with the stuff behind the canvas. This being the case Im closing for now.

**Comment by spaceoddity** [comment]
Actually, I wasn't trying to get the blend modes to interact with the stuff behind the canvas. I was just trying to have the things on the canvas blend with each other (and ignore the background of the renderer, because the background is transparent).

This is completely possible to do with a canvas with multiply blend mode. Here is an example:

https://jsfiddle.net/v95pz5h2/

In this example, the body is gray. There is a transparent canvas over the body. The canvas is set to multiply, and the rectangles are blending with each other (and ignoring the background).

But when one tries to do this with pixi, nothing renders at all...

It's possible with canvas, but not possible with WebGL/pixi?

(PS Thank you, I love pixi, it's wonderful!)
