### ISSUE TITLE
[V3] - Mouseover not triggering

### ISSUE THREAD

**Issue by FlorentBiffi** [GoodBoyDigital/pixi.js#1602]
Hi !
I'm currently using pixi v3 (rc4) and I encounter an issue with the mouseover callback. When I'm overing an object, leaving the stage then coming back in the same object, mouseover isn't triggered. I don't have this problem if I come back on an other object.

**Comment by GoodBoyDigital** [comment]
This should be cool now on v3. Cheers! :+1:
