### ISSUE TITLE
[V3-RC4] gaps in TilingSprite

### ISSUE THREAD

**Issue by Greewi** [GoodBoyDigital/pixi.js#1603]
Hello,

We have a new issue with the Tilling sprites. The first one we create is ok. But the following ones present a strange gap that seem increasing as we create new TillingSprite.

You can see the bug here : http://jsfiddle.net/3559hce2/1/

**Comment by GoodBoyDigital** [comment]
thanks for providing this fiddle! Will make it much easier to debug! :+1: Looking into this now..

**Comment by GoodBoyDigital** [comment]
All fixed now in dev branch. Thanks!
