### ISSUE TITLE
[3.0] Pixi.Text stroke problems on iOS

### ISSUE THREAD

**Issue by JaredSartin** [GoodBoyDigital/pixi.js#1604]
I am working on a mini game using Pixi 3. In my desktop environments, my font renders fine. On Mobile Safari, Chrome, and CocoonJS App it draws as a black box that goes from the top of the screen to the bottom - no white fill!

Here is the code:
``` js
			this.scoreText = new this.PIXI.Text(" 0 ", {
				font: "60px FlappyBird",
				fill: "#FFFFFF",
				align: "center",
				stroke: "#000000",
				strokeThickness: "10"
			});
			this.scoreText.anchor.x = 0.5;
			this.scoreText.position.x = 288;
			this.scoreText.position.y = 10;
```

Notes: I am using a webfont. The rendering of my score is just fine without the stroke. Happens only on mobile.

**Comment by JaredSartin** [comment]
... Solved, not fixed. Changing the strokeThickness to a number (10 instead of "10") makes it render properly on mobile now.

**Comment by englercj** [comment]
Stroke thickness is a number, not a string:

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/text/Text.js#L25

Passing in a string is an error.
