### ISSUE TITLE
[V3-RC4] Freezing movie clips when animationSpeed < 1

### ISSUE THREAD

**Issue by Greewi** [GoodBoyDigital/pixi.js#1606]
Hello,

When using movie clips with an animationSpeed smaller than 1 (for example 0.1), we notice that some (most on our systems) freeze. The onComplete callback is never called when this occure.

You can see the bug in action here : http://jsfiddle.net/jp08zvon/4/
To help you tracking the creation and the end of the animations, we have logged theses event in the console with the number of "living" clips.

**Comment by GoodBoyDigital** [comment]
All sorted in v3 now. thanks for sharing and providing an example! :+1:
