### ISSUE TITLE
[V3] InteractionManager mouse not updating with DOM overlay

### ISSUE THREAD

**Issue by ayamflow** [GoodBoyDigital/pixi.js#1608]
Hey there,
I noticed something funny (or is it?) with the interaction manager.

I'm working on a project with a pixi-powered canvas, and sometime some DOM content opens on top of it when the user clicks on a Sprite.
When this DOM content opens, the interaction manager  `update` function doesn't change the mouse position since the mouseove is captured by the DOM element instead of the canvas.

So if I close my DOM overlay and I click on another Sprite (I moved my mouse while the DOM overlay is closing) the click is called on the wrong place.
Probably because `processInteractive(this.mouse.global, ...)` uses mouse.global instead of the event coordinates, and mouse.global is updated in mousemove. See what I mean ? Should mouse.global be updated with any event ?

Don't have time for a test fiddle for now, I hoped you understand the issue like that. Let me know !
(Might be related to #1602)

**Comment by ayamflow** [comment]
Hey there, monkey patching the `onMouseDown` of InteractionManager do the trick for now:

```js
InteractionManager.prototype.onMouseDown = function (event)
{
    this.mouse.originalEvent = event;
    this.eventData.data = this.mouse;
    this.eventData.stopped = false;

    // Update internal mouse reference
    this.mapPositionToPoint( this.mouse.global, event.clientX, event.clientY);

    if (this.autoPreventDefault)
    {
        this.mouse.originalEvent.preventDefault();
    }

    this.processInteractive(this.mouse.global, this.renderer._lastObjectRendered, this.processMouseDown, true );
};

```

**Comment by GoodBoyDigital** [comment]
bit lat to this one :) but yes that problem makes sense to me, as does the solution. Thanks for sharing @ayamflow :+1:

**Comment by GoodBoyDigital** [comment]
patch applied to dev branch.. should be all good now.
