### ISSUE TITLE
Last commit (webgl tweaks) can produce a bug

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1610]
Hello,

This commit : https://github.com/GoodBoyDigital/pixi.js/commit/4b5cab7fabce38d39137b0f6585849c2e8cfec4a

can cause an issue here : 

```javascript
   this._updateTextureBound = function(e){
        this.updateTexture(e.target);
    }.bind(this);

    this._destroyTextureBound = function(e){
        this.destroyTexture(e.target);
    }.bind(this);
```

"e" can be the basetexture object in some cases. I suspect that it happens when Basetexture.source is null.

I'll try to produce a test case if the fix isn't obvious for you, @GoodBoyDigital

**Comment by Inateno** [comment]
I got the same issue, here is a simple test with only a container and a text

No update on text, no error
http://inateno.com/protos/pixi/text_bug/index.html
Set text on loop, got the error
http://inateno.com/protos/pixi/text_bug/withUpdate.html

I try to check for fix, also this demo work if I use the pixi.js from bin directory on the dev branch, but if I build a new with last files, I got the error.
It seem this come from the last push on WebGLRenderer:

```javascript
    texture.on('update', this.updateTexture, this);
    texture.on('dispose', this.destroyTexture, this);
```
replaced by _updateTexureBound as said @JiDW

**Comment by englercj** [comment]
Curious why this change was made @GoodBoyDigital, not sure what `e.target` is supposed to be?

**Comment by GoodBoyDigital** [comment]
this was an error on my side peeps! I accidentally committed some old changes.. Shame on me :/
All fixed now though in the dev branch now though :+1:
