### ISSUE TITLE
MovieClip in not steady tempo?

### ISSUE THREAD

**Issue by Mr-Eluzive** [GoodBoyDigital/pixi.js#1613]
Hi
I have to implement animation of objects on the map and I have gifs to do it. 
In pixi if I want have a animation object I have to create MovieClip object, right?
If I had a animation in steady tempo I would create a spritesheet with TexturePacker and set tempo what I wanted to MovieClip object but for example I have a animation like this: 
first_frame - 3s , second_frame - 0,1s, third_frame - 0,2s (attachment).
![animacja](https://cloud.githubusercontent.com/assets/9000139/6881072/407cadca-d550-11e4-8d4e-cbfe9f57b18c.gif)
Is there any smart solution for this? I mean any built-in solution because if not I have to create some kind of array to each other object and write the time interval into, probably.

**Comment by englercj** [comment]
No, we do not have robust animation class. But all the tools you need are there to create your own.

**Comment by Mr-Eluzive** [comment]
Ok so I'll try to write something and if it is a nice solution I'll share it.

**Comment by englercj** [comment]
Awesome! Would make a great v3 plugin!
