### ISSUE TITLE
touch event not fired from pixi

### ISSUE THREAD

**Issue by pavan4** [GoodBoyDigital/pixi.js#1615]
I am raising a touch event like this : 

    var type = 'end'; // or move, end
    var event = document.createEvent('TouchEvent');
    event.initTouchEvent();
    event.initEvent('touch' + type, true, true); 
    var point = {x: 10, y: 10 };
    event.touches = [{identifier: Date.now() + i,
								force: 1,
								pageX: point.x,
								pageY: point.y,
								screenX: point.x,
								screenY: point.y,
								clientX: point.x,
								clientY: point.y}];
    dispatchEvent(event);

I am able to catch it using

    window.addEventListener("touchend", endHandler, false);
    function endHandler(event) {
      console.log(event);
    }

But the event in pixi doesn't fire when I do this 

    button.touchend = function(data){
        console.log('event fired from pixi');
    }

What should I replace to get the event fired from pixi?

**Comment by englercj** [comment]
You are firing the event on window, but we are listening to events on the render element (the canvas). Dispatch the event on that element.

**Comment by pavan4** [comment]
is there any way I can dispatch it on the window and catch the element on top of it ?

**Comment by englercj** [comment]
Event bubble up the DOM, and the window is at the top. So that doesn't work. But if you dispatch the event on the canvas, it will bubble up to the window. Why do you have to dispatch on window?

**Comment by pavan4** [comment]
I am dispatching the event from js and I do not have any requirement to dispatch on window but I do not know how to dispatch it on canvas. Any example to raise a touch event will be helpful. (Sorry if this is a noob question)

**Comment by englercj** [comment]
`renderer.view.dispatchEvent(event)`

Should work fine, there is only one canvas that things can happen on right?

**Comment by pavan4** [comment]
It didn't work. The event is firing and I can catch it in the listener but the element doesn't react to the event. It worked only on safari on iOS with 

    x = 175;y=75;
    var touch = document.createTouch(window, window, 1, x, y, x, y);
    var touches = document.createTouchList(touch);
    var targetTouches = document.createTouchList(touch);
    var changedTouches = document.createTouchList(touch);
    var event = document.createEvent("TouchEvent");
    event.initTouchEvent('touchstart', true, true, window, null, x, y, x, y, false, false, false, false, touches, targetTouches, changedTouches, 1, 0);
    renderer.view.dispatchEvent(event);

This however doesn't work on Android (chrome) no idea why :/ 

But unfortunately the createTouch and createTouchList are not available for desktop even in mobile emulation enabled and the other method mentioned above doesn't fire the reaction in PIXI on desktop ... Any workarounds?

**Comment by GoodBoyDigital** [comment]
Hi there! looks like you may need to turn off ```autoPreventDefault```

```renderer..plugins.autoPreventDefault = false```

this will let the event bubble up out of pixi.
