### ISSUE TITLE
Use bitmap font texture from spritesheet

### ISSUE THREAD

**Issue by krzysztof-o** [GoodBoyDigital/pixi.js#1617]
To optimize number of draw calls I need to have all UI images (and bitmap font) on a single spritesheet.
Currently bitmapFontParser always forces you to load dedicated texture.

**Comment by JiDW** [comment]
That would be awesome !

**Comment by gprzybylowicz** [comment]
I like it!  Would be really helpful.

**Comment by JiDW** [comment]
I've done it this morning for my game. Thanks for the idea ! There is too much code related to my game to make it usable for everyone but here is what I've done : 

First of all, I've modified our .fnt exports to replace file="image.png" by frame="image.png"

1- Load .json spritesheets
2- Wait for the spritesheets to be loaded
3- Load .fnt Bitmap fonts
4- Hack https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/loaders/bitmapFontParser.js#L62
   * Check if file or frame is set. Follow a different parse for each
   * Get the texture from the texture cache (Texture.fromFrame())
   * Modify the texture rect by adding the x and y of the related frame
   * Optional : if you use retina textures, divide by the correct resolution (make sure to have "identical layout" checked inside TexturePacker's scaling variant.
   * Set the baseTexture to the one of your frame for data.chars.texture
5- Done !

It needs some polish and more work if you need to be able to use rotated spritesheet, but it's a start and it works.

**Comment by krzysztof-o** [comment]
I also managed to hack it, but I was thinking about nicer way :)
Next month I'll be migrating to v3 so I'll try to send a PR.
