### ISSUE TITLE
when using graphics arc, how to stop drawing continuously

### ISSUE THREAD

**Issue by NikkiKoole** [GoodBoyDigital/pixi.js#1622]
I am not fully sure if I am looking at a feature or a bug, but what I am trying todo is drawing 2 arcs (without a line in between them)

![screen shot 2015-03-31 at 6 02 16 pm](https://cloud.githubusercontent.com/assets/453055/6923122/275211be-d7d0-11e4-891a-08a96a9a8936.png)
so that straight line in between is NOT wanted ;)

```
var testGraphic = new PIXI.Graphics();
testGraphic.lineStyle(3, 0);
testGraphic.arc(100,100,50,(180-130)/57, (180+130)/57, true);
testGraphic.arc(100,100,50,(130)/57, (-130)/57, false);
stage.addChild(testGraphic);

```

Is there some function call I could do after the first arc fnCall ? with straight lines and clear coords one can off course use the moveTo function, but in this context I cannot.

here's a fiddle showing an example:
http://jsfiddle.net/332gdcna/11/

ps: this is on pixi v3 rc4

**Comment by englercj** [comment]
That looks like a bug to me!

**Comment by NikkiKoole** [comment]
I rebuild pixi.js (I was looking at a slightly older version from a week ago) https://github.com/photonstorm/phaser/commit/93dc67be71e1d6b5401572428dc4411f99e63d98

the problem is fixed now I think.

**Comment by englercj** [comment]
Ok, cool thanks for the update. Glad it is working for you now.
