### ISSUE TITLE
Displacement on graphics when cacheAsBitmap is true

### ISSUE THREAD

**Issue by fbrussa** [GoodBoyDigital/pixi.js#1624]
Hi, I'm starting to develop an application to build influence diagrams.
I doing some tests with pixi v3 found this behavior. It is probably a bug?

http://jsfiddle.net/7ku14f4g/1/

**Comment by GoodBoyDigital** [comment]
hi there! A bug indeed! Thanks for providing the fiddle made it much easier to fix :+1: 

This will work correctly now in the dev branch. Cheers!
