### ISSUE TITLE
Filename: pixi.min.js - Change to one including version number

### ISSUE THREAD

**Issue by adamdanielsdesign** [GoodBoyDigital/pixi.js#1625]
This is a change request to the filename used for the dist/bin version of pixi to that of one including the version number something similar to:

pixi.3.0.0.js
pixi.3.0.0.min.js

**Comment by englercj** [comment]
ehhh, we commit builds and I don't want to have an infinite number of build files in the project. You're welcome to name the file whatever you want when you download it for use in your project.

**Comment by adamdanielsdesign** [comment]
I agree for the aspect of having a number of builds laying around it'd be a hastle perhaps. Although my suggestion relates more towards issue requests. A lot of times they don't mention what version their using, if they did a recent pull or what branch they're using. Thus it requires that much more miscommunication to get on the same page with them.

If the version numbers were clearly marked then it might be an option to resolve this.

Also, there are some clear differences in usage from build to build I've seen. Especially with spine in version 2. The recent drawOrder fix changed references to known objects and resulted in a full rebuild of our abstraction engine.

**Comment by englercj** [comment]
pixi's version is exposed at runtime, and is easily found in both the compiled bundle or the package.json.

Which versions of dependencies is in the package.json. There are big differences in v2-v3 builds but we try not to do api breaking changes in non-major versions.

Our contributing guide (https://github.com/GoodBoyDigital/pixi.js/blob/dev/CONTRIBUTING.md) says you should include versions when making an issue.

I don't think renaming the build file solves any of those problems. People don't post it now, and they wont post it then either. If they post a live example, we can find the version with `PIXI.VERSION` which is easier to spot than the filename anyway.

**Comment by adamdanielsdesign** [comment]
Is there a patch number then?

**Comment by englercj** [comment]
https://github.com/GoodBoyDigital/pixi.js/blob/dev/package.json#L3

We follow [Semantic Versioning](http://semver.org) as closely as possible. Patch versions are backwards-compatible bug fixes, Minor versions are backwards-compatible feature additions, Major versions are backwards-incompatible changes.

Sometimes we break that philosophy but we try to have a good reason when we do.

**Comment by adamdanielsdesign** [comment]
ok, tx!
