### ISSUE TITLE
[v3 rc4] IE11 font XML error (potential solution)

### ISSUE THREAD

**Issue by RoryPicko** [GoodBoyDigital/pixi.js#1628]
When I try to load in a bitmapFont XML in IE11 PIXI tries to access 'resource.data.frames' but it is 'Permission Denied' and breaks the page with an Exception, adding the mimeType check skips the if statement before it reaches IE and then works as expected.

I think it's line 10 of loaders/spritesheetParser.js    (it was line 23317 is off the fully compiled pixi.3.0.0.js)

if (!resource.data || resource.data.mimeType == "XML File" || !resource.data.frames)

**Comment by GoodBoyDigital** [comment]
Sounds like one for you @englercj . IE is fun :)

**Comment by englercj** [comment]
ugh, IE. Do you have a repo page I can test on? Thanks!

**Comment by RoryPicko** [comment]
IE is always fun, like the mimeType being XML Document and not XML File in different versions! so this new fix is better 

if (!resource.data || (resource.data.mimeType && resource.data.mimeType.indexOf("XML") > -1) || !resource.data.frames)

i've created a version for you here
http://kokodev.co.uk/pixifontbugie/index.html  - example of error
http://kokodev.co.uk/pixifontbugie/fixed.html  - a page with my fix in

**Comment by RoryPicko** [comment]
ahh the issue may be deeper than that line, that fixes it for IE11 but in IE9 I get 
Unable to get value of the property 'toString':object is null or undefined

which is from the reqType(xhr) function as xhr is undefined. 
when loading a texturejson file the json response body is empty within the network panel even though it gets a 200 headers

**Comment by englercj** [comment]
Ok, just pushed a commit that should fix this. I added some helpers in v1.4.0 of the resource-loader that allows you to tell what the data is without weird duck typing. So now the parsers in pixi can check if the data is json, xml, etc safely and then operate.

It should clear up this issue, just know you will need to build your own from the latest `dev` branch and you *must* update the local install of resource-loader you might have to v1.4.0 (`npm update resource-loader --depth=0`). Then you can try it out.
