### ISSUE TITLE
[V3 RC4] Gap inside TilingSprite (Again)

### ISSUE THREAD

**Issue by Greewi** [GoodBoyDigital/pixi.js#1630]
Hello,

We still encounter a gap between tiles in tilingsprites as seen in this fiddle : http://jsfiddle.net/66bsa0tv/1/ (The texture used, http://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Nextgen_road.jpg/40px-Nextgen_road.jpg, dont have black borders)

**Comment by Greewi** [comment]
On our local version we fixed it by changing the lines : https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/extras/TilingSprite.js#L388-L389 

by :
```javascript
        tempSprite.worldTransform.tx = -0.5;
        tempSprite.worldTransform.ty = -0.5;
```

**Comment by Inateno** [comment]
I got this problem too but on the next part of the code (in the else)
In my case I had to change the next worldTransform to fix the gap

https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/extras/TilingSprite.js#L412
````javascript
  this._tileScaleOffset.x = 0;
````

I don't have a simple example but texture isn't power of two and isn't fromFrame, here is it
http://dreamirl.com/games/ola/img/1080/env/sky.png

Hoping this will help to fix properly this problem.

**Comment by alaa-eddine** [comment]
I confirm the bug.
for me it only occure when using a texture atlas, if I use separate images the it works just fine.

you can clearly see it here 

Pixi v3-rc4 the title bar is using texture atlas, the button bellow is using images 
http://labs.ezelia.com/pixi/tilingsprite-pixi3-rc4.png

Pixi v2.2.8 for comparison
http://labs.ezelia.com/pixi/tilingsprite-pixi2.2.8.png

**Comment by Inateno** [comment]
Also I checked right now and there is the same gap problem in canvas rendering.

**Comment by GoodBoyDigital** [comment]
hey peeps, just uploaded a new Tiling texture to the dev branch.. please let me know if it works ok for ya!

**Comment by alaa-eddine** [comment]
the gaps are fixed now, thank you :)
