### ISSUE TITLE
Framebuffer does not clean correctly in firefox on windows, board Intel HD 4000 / GeForce 7400

### ISSUE THREAD

**Issue by PixelsCommander** [GoodBoyDigital/pixi.js#1632]
This happens when dragging http://pixelscommander.com/polygon/htmlgl/demo/advanced-content-webgl.html in Firefox 36.0.4 Windows. It seems that the background is not cleaned (or rendered correctly) in the framebuffer when a DOM node is moved.

![webgl](https://cloud.githubusercontent.com/assets/798800/6984394/c9d18f20-d9fe-11e4-8f53-32504cd8ed0e.png)

It's a dual Intel HD 4000/Nvidia GT 635M. Using Intel generates these artifacts. Forcing NVidia crashed the browser during the demo page load.

Works fine in the same PC, Chrome 41, using Intel.

**Comment by PixelsCommander** [comment]
Video https://www.screenr.com/HA6N

**Comment by GoodBoyDigital** [comment]
Hi there is this issue present with pixi v3?

cheers!

**Comment by PixelsCommander** [comment]
This is reproducable with 2.2.5 . Will try v3.

**Comment by PixelsCommander** [comment]
Fixed in v3
