### ISSUE TITLE
[v3 RC4] renderer.resize() doesn't seem to be working

### ISSUE THREAD

**Issue by edankwan** [GoodBoyDigital/pixi.js#1634]
http://jsfiddle.net/c7vwmyxf/1/

Or do I need any set up on the Container/Renderer to make it behave like `Stage` in v2?

**Comment by adelciotto** [comment]
is this because a call to:
```javascript
 gl.viewport(0, 0, width, height)
```

 is missing?

**Comment by GoodBoyDigital** [comment]
my bad! All fixed now :+1:  thanks for sharing!
