### ISSUE TITLE
Question about mask in V3

### ISSUE THREAD

**Issue by jeremypetrequin** [GoodBoyDigital/pixi.js#1639]
Hello,

I've already used PIXI in several projects, firstly, i want to thank you for all this awesome work!
But for my current project, I need to do a mask with a complexe shape, that i can't draw with code. The perfect solution for me could be to have a PNG image as a mask, and render my texture only on the visible part of this PNG.

Something like that seems to be possible with the V3 (http://www.goodboydigital.com/client/goodboy/nebulon/)? But there's not a lot of documentation yet and the deadline for my project doesn't allow me to wait the official release..

Could someone help me a little bit with that?

**Comment by englercj** [comment]
You can use a sprite as a mask in v3, just assign a sprite to another sprites mask property.

**Comment by jeremypetrequin** [comment]
Hello,

thank for your response,

You mean that a mask will only use the visible pixels of the sprite, no matter what there are inside? Using alpha too I guess? If yes, seems to be very awesome!

But, i've just made a quick test, and it doesn't seem to work as expected:

````js
var textureLogo = PIXI.Texture.fromImage('img/logo-mask.png');
var logoMask = new PIXI.Sprite(textureLogo);

var textureTexture = PIXI.Texture.fromImage('img/logo-texture.jpg');
var logoTexture = new PIXI.Sprite(textureTexture);

canvasStage.addChild(logoMask);
logoTexture.mask = logoMask;
canvasStage.addChild(logoTexture);
canvasRenderer.render(canvasStage);
````

logo-mask.png is a PNG file where the shape is black and the rest is transparent.
If I comment the line ````logoTexture.mask = logoMask;```` the both images appear

I think I misunderstood something? 

(sorry for my english, and thanks again for help!)

**Comment by englercj** [comment]
Try waiting until the images load, then using the mask. Don't remember if it handles unloaded images properly.

**Comment by jeremypetrequin** [comment]
I already wait the end of loading before apply the mask. I've simplified a little bit the code for my post, but in fact, I use the new PIXI.loader to preload my assets, then I draw my stage.
Using ````Texture.fromFrame```` or ````Texture.fromImage```` the results are the same: when I apply the mask, the both images disappear, even in a big setTimeout to be sure i'm waiting enough time for loading.

**Comment by GoodBoyDigital** [comment]
hi there! are you using webGL? Alpha masking is only available in webGL at the mo. cheers!

**Comment by jeremypetrequin** [comment]
Hi!
I've found the solution thanks to your help, 
two things: 
 - first, I was using a black and transparent PNG, if I use the same with white instead of black it works,
I don't know if it's "normal" that black be considered as transparent?
 - secondly, it need a second "render" call, in a ````setTimeout(function() {}, 0)``` to be displayed.. weird

Thanks again to your help

**Comment by GoodBoyDigital** [comment]
good stuff! yes alpha masks use alpha / color to make life easy for people. So black and alpha of 0 will mask the item. Thanks!

**Comment by jeremypetrequin** [comment]
Ok!
Just a little precision about the second point, it doesn't need a setTimeout, just need two calls to render:
````javascript
canvasRenderer.render(canvasStage);
canvasRenderer.render(canvasStage);
````
and it's ok, but without the second, the mask doesn't display.. Don't know if it's "normal" again?

**Comment by Priyank30** [comment]
@GoodBoyDigital

This is the first time I am using pixijs in my any project and I found it is very easy (yet POWERFUL) to start with it. Previously I was using three.js library and I have spent almost a month to optimize my program and still struggling with performance and this library has fixed all performance issue one day however I have not fully implemented in my system but getting +ve feelings.

My program is totally based on 2d graphics and in first face I have started to implement complex polygons with holes. Sooner I came to know pixijs does not support non-zero winding rules or any direct api to add holes in polygon but can be done using PIXI.Sprite. I have achieve it anyhow but don't know whether there is better approach then below. 

            var renderer = PIXI.autoDetectRenderer(1200, 900);
			document.body.appendChild(renderer.view);
			
			// create the root of the scene graph
			var stage = new PIXI.Container();
			 
			//beneathObject1 & beneathObject2 are added to make sure an overlapping object with hole is working as expected.
			var beneathObject1 = new PIXI.Graphics(); 
			beneathObject1.beginFill(0XFFFFFF);	//White object	
			beneathObject1.drawRect(0, 0, 800, 800);	
			beneathObject1.endFill();			
			stage.addChild(beneathObject1);
			
			var beneathObject2 = new PIXI.Graphics(); 
			beneathObject2.beginFill(0X60b044);	//Green object	
			beneathObject2.drawRect(100, 100, 600, 600);
			beneathObject2.endFill();			
			stage.addChild(beneathObject2);
			
			//Adding hole into the shape
			var baseObject = new PIXI.Graphics();		
			baseObject.beginFill(0XF41A1A); //Red object		
			baseObject.drawRect(0, 0, 500, 500);	
			baseObject.endFill();	
			
			//Mask object is the polygon with holes. 
			var maskObject = new PIXI.Graphics();
			maskObject.beginFill(0XF41A1A); //Red object	
			maskObject.drawRect(0, 0, 500, 500);	
			maskObject.endFill();
						
			maskObject.beginFill(0X000000); //Objects(Black colored) which I want to remove
			maskObject.arc(100, 100, 25, 0, 2 * Math.PI);
			maskObject.arc(100, 200, 25, 0, 2 * Math.PI);
			maskObject.endFill();			
			
			var mask = new PIXI.Sprite(maskObject.generateTexture());			
			mask.position.x = 310;
			mask.position.y = 190;
			
			baseObject.mask = mask;
			
			stage.addChild(mask);			
			stage.addChild(baseObject);			
			
			renderer.render(stage);
			renderer.render(stage);

Output:
![output](https://cloud.githubusercontent.com/assets/2055200/7474253/c40a99ba-f35d-11e4-9691-c07253cc019b.png)


One last thing as @jeremypetrequin mentioned I have to call renderer.render(stage); twice to get correct output. Don't know why is that?

**Comment by clark-stevenson** [comment]
Just a quick question.

[The docs](https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/display/DisplayObject.js#L225) say Graphics. 

Can a mask be any DisplayObject or is it limited to say, Graphics | Sprite?

**Comment by englercj** [comment]
Right now it is Graphics | Sprite.

This line needs to be updated: https://github.com/GoodBoyDigital/pixi.js/blob/07e4e26f8fd404524a7ebaa73c210de3d8f2cf25/src/core/display/DisplayObject.js#L225
(and the `@property` line below that removed)

**Comment by SphinxC0re** [comment]
I just stumbled over this issue myself. I can't seem to get masking working at all. I'm using a sprite loaded from an Image to mask a rectangle created from a PIXI.Graphics object. This is my code:
```javascript
var bg_color = 0xCFD1CE;

var render_options = {
    antialias: true,
    backgroundColor: bg_color
};

this.renderer = new PIXI.CanvasRenderer(window.innerWidth, window.innerHeight, render_options);

document.body.appendChild(this.renderer.view);

var app = new PIXI.Container();

var variable = PIXI.Sprite.fromImage('img/testmask3.png');

setInterval(function()  {
    var rColor = Math.random() * 0xFFFFFF;
    app.removeChildren();
    var first = new PIXI.Graphics();
    first.beginFill(rColor).drawRect(0, 0, 640, 480).endFill();

    var second = new PIXI.Graphics().beginFill(0x000000).drawCircle(100, 100, 30)
    first.mask = variable;
    app.addChild(first);

    this.renderer.render(app);
}, 500);
```
I used these three testimages as masks:
1.
![testmask](https://cloud.githubusercontent.com/assets/3702016/11628626/2a2b90de-9cf3-11e5-87b5-56b44ea141b1.png)
2.
![testmask2](https://cloud.githubusercontent.com/assets/3702016/11628627/2a2ce074-9cf3-11e5-8c31-27e56182e296.png)
3.
![testmask3](https://cloud.githubusercontent.com/assets/3702016/11628625/2a2b3e90-9cf3-11e5-9915-ddc5214bea64.png)

**Comment by Bartzy** [comment]
@englercj I am getting the same issue as @SphinxC0re .

Using the WebGL renderer, latest Pixi.js source from master.
I verified that the mask is loaded and my code looks like:

```
    var object = new PIXI.Sprite.fromImage(this.getAssetPath(layer.image));

    object.width = layer.width;
    object.height = layer.height;
    object.x = layer.x;
    object.y = layer.y;

    var mask = PIXI.Sprite.fromImage(this.getAssetPath(layer.mask));
        
    object.mask = mask;

    container.addChild(object);
```

and of course I have ```renderer.render(container)``` running in a RAF callback.

Are we using the mask property wrong with PIXI.Sprite objects?

Thanks!

**Comment by Bartzy** [comment]
Update: If I specify the object.x and object.y as 0, then the mask works perfectly. As I increase the object's position in the X and/or Y axes, the object gets "cut" in its top and left boundaries.

**Comment by englercj** [comment]
Add the mask as a child of the object is is masking, so that it follows it around.

**Comment by Bartzy** [comment]
Thanks,

Just did that and indeed it is masking in the correct place, but it seems like it's smaller than it should be. The mask image is exactly the same size as the object's image, but the resulting masked object I get is smaller for some reason?

Also, what's the reasoning behind having the mask layer in the layer tree itself? For me it seems like a "mask" is just like any other layer property that changes its appearance.

Thanks again,
Bar.

**Comment by perfectbeeing** [comment]
Has support for canvas alpha masking ever been included? Is it possible? The project uses PIXI.js for server side rendering of video with heavy use of masking. Thank you so much!!

**Comment by englercj** [comment]
No alpha masking works using a gl shader, no canvas support.
