### ISSUE TITLE
updateGraphicsTint not called when getBounds is used before next frame

### ISSUE THREAD

**Issue by FlorianLudwig** [GoodBoyDigital/pixi.js#1643]
`PIXI.Graphics.prototype.getBounds` sets `this.dirty = false` 

But `PIXI.CanvasGraphics.renderGraphics` checks the dirty flag:
```javascript

    if(graphics.dirty)
    {
        this.updateGraphicsTint(graphics);
        graphics.dirty = false;
    }
```

To avoid similar problems the WebGL renderer maintains a `webGLDirty` flag. I suggest using it in the canvas renderer as well (and renaming it to `rendererDirty`).

**Comment by GoodBoyDigital** [comment]
Good catch! I ended up adding a boundsDirty property to graphics to handle this. Thanks for sharing! :+1:
