### ISSUE TITLE
[V3] Displacement Filter inside mask deform mask

### ISSUE THREAD

**Issue by jeremypetrequin** [GoodBoyDigital/pixi.js#1644]
Hi!

I'm currently trying to make a mask (with the new V3 masking method! :) ) on a sprite and then add a Displacement filter to this sprite,
the behavior I expect is that only the sprite should be deformed, inside the rounded mask,
the result is that the mask is deformed too..

see : http://codepen.io/jeremypetrequin/pen/vEwbdB?editors=001

I've tried with several calls to render or change order of instructions, but I can't have what I want..
Does someone know if it's possible?

(I know I could make this simple mask with a ````PIXI.Graphics```` but my real mask is way more complicated than that ;) )

And two others small things:
 - I think there's maybe a typo in https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/filters/displacement/DisplacementFilter.js#L13
the constructor needs a PIXI.Sprite and the comment says Texture
 - Is there somewhere to get some start of documentation and/or examples for the V3? Or do you have an idea about a release date maybe? :)

Thanks everybody!

**Comment by GoodBoyDigital** [comment]
Hi there! the way v3 works is that it always applies the filters as the last step of rendering an object.
If you nest your displacement object in masked container it should get you the effect you require:

http://codepen.io/anon/pen/ogrPyo

I also tweaked the documentation in the code to. The latest docs can be found here: http://pixijs.github.io/docs/

Cheers!
