### ISSUE TITLE
shader example(s) ?

### ISSUE THREAD

**Issue by mreinstein** [GoodBoyDigital/pixi.js#1646]
Recently I've been learning a bit about shaders and building some prototypes on shadertoy.com. I want to start integrating them with pixi. Is there some place with more info on how to write shaders that work within pixi?

I've looked in the typical places for how to go about writing shaders and using them with pixi.js but haven't found much. Here's where I've looked:

https://github.com/pixijs/examples

https://github.com/pixijs/docs

http://www.pixijs.com/examples/

**Comment by mreinstein** [comment]
on a somewhat related note, is there any information known about using glslify with pixi? 

https://github.com/stackgl/glslify

this seems mega awesome!  ^

**Comment by englercj** [comment]
Have you looked at any of filters in the filter plugin?

https://github.com/GoodBoyDigital/pixi.js/tree/dev/src/filters

**Comment by mreinstein** [comment]
I did start looking at those filters yes. But they are very light on details. For example vTexturecoordseems to be a built in uniform that is exposed to filters. But I'm not sure how. Are there others? Is there a specific way that I should update variables passed to the shaders, like global time elapsed? do I simply update filter.dirty = true in my requestanimationframe loop each step?

**Comment by mreinstein** [comment]
was just looking for more of a guide or information around how shaders tie into pixi

**Comment by englercj** [comment]
@mreinstein "How do shaders tie into pixi" is a bit fague, but generally when people say "shader" they want to do what our filters do, so I assume that is what you mean.

Filters extend AbstractFilter which uses [TextureShader](https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/core/renderers/webgl/shaders/TextureShader.js) for default vertex/fragment shaders. The attributes and uniforms there are the "built-in" ones.

As far as updating values, all you need to do is set the value. The library takes cares of everything else for you. For example, checkout the [ShockwaveFilter](https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/filters/shockwave/ShockwaveFilter.js), it uses elapsed time but there isn't anything special to set it.

If someone wants to write a guide I'm sure many people will appreciate it. In the meantime, is there a specific problem you are having, or a filter you have tried that isn't working?

**Comment by mreinstein** [comment]
ok I'll take a look at those particular files, thanks!

**Comment by mreinstein** [comment]
@ivanpopelyshev  and I are working on a pixi plugin to handle dynamic lighting for spine animations via normal maps. I'm looking at https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/filters/normal as a good starting point for this. Several questions:

in https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/filters/normal/NormalMapFilter.js :
* there are several references to "displacement map". I'm guessing this is because it was copy/pasted from displacement shader, and these references should all be "normal map" instead?
* in the constructor, it sets a uniform variable named `displacementMap` but then the accessors defined torwards the bottom of the file refer to `map`. I'm assuming this is a bug, and the accessors won't actually do anything since the fragment source refers to `displacementMap` ?
* there is mention on line 63 that the texture must be a power of 2. Is this true for normal maps too, or simply a copy/paste leftover from displacement map?
* is `mapDimensions` the pixel width/height values of the normal texture passed in, or in some other unit?
* can you elaborate more on what all of the uniform variables are? except for `mapDimensions` and `displacementMap`, it's not clear to me how to use these values

Sorry to slam you with a wall of questions here. My hope is that we'll be able to produce something usable in a short time with a minor bit of hand holding. Here's our current prototype:

https://github.com/mreinstein/pixi-spine-lighting

in building a commercial game, I'm finding that pixi is stellar all around, but the lacks crucial constructs  for lighting, and it's really painful. It's the one area that Unity really has us beat, IMO. I'm hoping this will be a start torwards solving this.

**Comment by englercj** [comment]
The NormalMapFilter doesn't work, it was an experiment that apparently snuck into the repo. I wouldn't look at it at all (except the shader as a guide). Look at [pixi-lights](https://github.com/pixijs/pixi-lights).

**Comment by mreinstein** [comment]
@englercj are there other filters that don't work and snuck in? Should I send a PR to remove them?

**Comment by englercj** [comment]
Not that I am aware of.

**Comment by mreinstein** [comment]
related to the shader examples, is there a specific filter that shows how to get the world space coordinates of the current fragment/pixel from within a fragment shader?

**Comment by englercj** [comment]
A couple shaders upload the worldTransform matrix of the object they are operating on. I would search here and in pixi-lights for `translationMatrix`.

**Comment by englercj** [comment]
Closing this since it seems answered.

**Comment by mreinstein** [comment]
yeah, sorry. I forgot to close it.

**Comment by mreinstein** [comment]
@englercj  so the default vertex shader sets `vTextureCoord` to be the fragment's window coordinates. I was asking about how to get world space coordinates; now I'm curious about how I get object space coords (i.e, if I have a sprite with a filter, and want 0,0  and 1,1 to be opposing corners of the sprite regardless of its' size).
