### ISSUE TITLE
GL ES 2 support

### ISSUE THREAD

**Issue by PixelsCommander** [GoodBoyDigital/pixi.js#1650]
Hi

We`ve tried to use Pixi to render UI for TV console and unfortunately failed since Pixi do not support GL ES 2 spec since v2.

Is there a chance to get support back or have compatibility mode? We may contribute, but need a bit of  direction.

**Comment by GoodBoyDigital** [comment]
Hi there! Not 100% sure what you mean i'm afraid? is webGL not based on ES2?

**Comment by PixelsCommander** [comment]
Basically we have QT 5.3 browser on ARM powered device with Nexus graphics system. I know for sure it supports https://www.khronos.org/opengles/2_X/ and Pixi v1 works fine there but Pixi v3 and v2 fails with some GL error.

Will drop error details on Monday when have access to hardware.

**Comment by englercj** [comment]
We would need the specific errors, WebGL 1.0 is OGL ES 2.0 and we use WebGL. We can't use something that isn't OGL ES 2.0, we have no choice :)

Likely there are features in WebGL that we are using that are not supported in the QT browser.

**Comment by GoodBoyDigital** [comment]
Good Stuff! Pretty sure we can solve any issues if once you provide the error details :+1:

**Comment by PixelsCommander** [comment]
Here is browser`s console log:

Apr 13 17:03:42 (none) kern.notice QTBROWSER: objects with out-of-line .property storage: 10488 (66%)
### 396927:03:33.904 nexus_graphics2d: missing call to NEXUS_Graphics2D_Checkpoint. blit is queued.
Apr 13 17:03:42 (none) kern.warn kernel: ### 396927:03:33.904 nexus_graphics2d: missing call to NEXUS_Graphics2D_Checkpoint. blit is queued.
Apr 13 17:03:43 (none) kern.notice QTBROWSER: [console] [http://127.0.0.1:8081/MWRPAppServer/demo/advanced-content-webgl.html#.VSvax2wdUb0:0] WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range
Apr 13 17:03:43 (none) kern.notice QTBROWSER: [console] [http://127.0.0.1:8081/MWRPAppServer/demo/advanced-content-webgl.html#.VSvax2wdUb0:0] WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range
!!!Error ### 396927:03:37.546 nexus_generic_driver: BERR_NOT_SUPPORTabnormal termination of an unprotected client 81061800 is not supportedED(0x8) at /opt/
vendor/broadcom/7430/Refsw12.4_7430_CADB/nexus/lib/ipc/bipc_server.c:254
*** 396927:03:19.869 refsw_server: closing client:0x45d140 with fd:39
*** 396927:03:19.869 bipc_server: bipc_server_destroy:0x461920 cleaning up object 0x461c70(39,39):brc_client(0x45d29c)
Apr 13 17:03:46 (none) kern.warn kernel: ### 396927:03:37.546 nexus_generic_driver: abnormal termination of an unprotected client 81061800 is not supported
Apr 13 17:03:56 (none) kern.notice UPNP_CLIENT: Mon Apr 13 15:03:56 2015 [ERROR]: Need to have control URL for UPnP IGD first
Apr 13 17:03:56 (none) kern.notice UPNP_CLIENT: Mon Apr 13 15:03:56 2015 [ERROR]: Need to have control URL for UPnP IGD first
Apr 13 17:03:56 (none) kern.notice UPNP_CLIENT: Mon Apr 13 15:03:56 2015 [ERROR]: Need to have control URL for UPnP IGD first
Apr 13 17:03:56 (none) kern.notice UPNP_CLIENT: Mon Apr 13 15:03:56 2015 [ERROR]: Need to have control URL for UPnP IGD first
Apr 13 17:03:56 (none) kern.notice UPNP_CLIENT: Mon Apr 13 15:03:56 2015 [ERROR]: Need to have control URL for UPnP IGD first

**Comment by PixelsCommander** [comment]
Is this providing some insight?

INVALID_VALUE: disableVertexAttribArray: index out of range [http://127.0.0.1:8081/MWRPAppServer/demo/advanced-content-webgl.html#.VSvax2wdUb0:0] WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range
!!!Error ### 396927:03:37.546 nexus_generic_driver: BERR_NOT_SUPPORTabnormal termination of an unprotected client 81061800 is not supportedED(0x8) at /opt/

**Comment by englercj** [comment]
I think these are the lines that are telling:

```
Apr 13 17:03:43 (none) kern.notice QTBROWSER: [console] [http://127.0.0.1:8081/MWRPAppServer/demo/advanced-content-webgl.html#.VSvax2wdUb0:0] WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range
Apr 13 17:03:43 (none) kern.notice QTBROWSER: [console] [http://127.0.0.1:8081/MWRPAppServer/demo/advanced-content-webgl.html#.VSvax2wdUb0:0] WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range
```

Wish it gave more specific logs of where that came from, is there anyway to remote debug with Chrome tools or reproduce the issue somewhere with a better debugger?

**Comment by PixelsCommander** [comment]
The error is caused by https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/renderers/webgl/utils/WebGLShaderManager.js#L109 during rendering. What is possible reason for it?

**Comment by GoodBoyDigital** [comment]
What is the value of the index? Is it -1? Thanks!

On Tuesday, 14 April 2015, Denis Radin <notifications@github.com> wrote:

> The error is caused by
> https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/renderers/webgl/utils/WebGLShaderManager.js#L109
> during rendering. What is possible reason for it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoodBoyDigital/pixi.js/issues/1650#issuecomment-92905668>
> .
>


-- 
Mat Groves

*Technical Partner*


 Telephone: 07708 114496 :: www.goodboydigital.com
 First Floor, Unit 9B, Queens Yard, White Post Lane, London, E9 5EN
 goodboy©. All Rights Reserved.

**Comment by PixelsCommander** [comment]
No, seems i=8 and i=9 are out of range...

WRPAppServer/bower_components/pixi/bin/pixi.dev.js:11234] i = 8
Apr 15 11:21:43 (none) kern.notice QTBROWSER: [console] [http://127.0.0.1:8081/MWRPAppServer/demo/advanced-content-webgl.html#.VS4toWwdUb0:0] WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range
Apr 15 11:21:43 (none) kern.notice QTBROWSER: [console] [http://127.0.0.1:8081/MWRPAppSeBKNI_P_GetTrackAllocEntry_resize: resizing from 4096->8192
rver/bower_compoBKNI_Malloc(linuxkernel) top users:
    blocks,   bytes, filename:line
nents/pixi/bin/p       804,   54672, ../magnum/basemodules/mem/bmem_system.c:306
ixi.dev.js:11236       651,   88536, magnum/commonutils/mrc/src/bmrc_monitor.c:972
] #6
Apr 15 11:       313,   30048, nexus/modules/core/src/nexus_memory.c:581
       312,   22464, refsw/nexus/base/src/nexus_base_scheduler.c:702
21:43 (none) kern.notice QTBROWSER: [console] [http://127.0.0.1:8081/MWRPAppServer/bower_components/pixi/bin/pixi.dev.js:11232] #5
Apr 15 11:21:43 (none) kern.notice QTBROWSER: [console] [http://127.0.0.1:8081/MWRPAppServer/bower_components/pixi/bin/pixi.dev.js:11234] i = 9
Apr 15 11:21:43 (none) kern.notice QTBROWSER: [console] [http://127.0.0.1:8081/MWRPAppServer/demo/advanced-content-webgl.html#.VS4toWwdUb0:0] WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range

**Comment by GoodBoyDigital** [comment]
nice! I think I know what it is now..
watch this space :)

**Comment by PixelsCommander** [comment]
:+1:

**Comment by GoodBoyDigital** [comment]
Righto, try now. Seems I was hardcoding the maxAttributes property to 10.. it now reads thatvalue from the WebGL. Let me know how it goes! :+1:

**Comment by GoodBoyDigital** [comment]
closing this as im pretty sure its fixed. Let me know if im wrong :)

**Comment by PixelsCommander** [comment]
This error is fixed however we still can not run Pixi on this device for some reason. Will create another issue after getting details.

**Comment by GoodBoyDigital** [comment]
:+1:
