### ISSUE TITLE
Managing a large number of (dynamic) images

### ISSUE THREAD

**Issue by ayamflow** [GoodBoyDigital/pixi.js#1653]
Howdy,

This is more of a question regarding performance in this specific use case.

I'm currently working on a project on PIXI that pulls images from a CMS and make a Sprite from them. It's based on a infinite scroll, and changing page reset all sprites (and it starts again). The images will be loaded by batches of ~10. Desktop, tablet & mobile.

Since it's based on an infinite scroll & a CMS we can not prepare spritesheets in advance, neither can we know how many images there will be. First tests showed that it works pretty good under 30-50 sprites but then degrades when the number grows (each Sprite contains different children & effects).

I was wondering 2 things:
- Should we manually manage the TextureCache to free up images used on the previous page to avoid bloating the memory? Since the images will be cached anyway.
- Is the texture from an invisible (`.visible = false`) Sprite sent to the GPU? I'm manually culling my Sprites.
- Any idea on other possible optimisation? I was thinking of trying to make a dynamic spritesheet for each image batch, or maybe some kind of Sprite pool; I have no idea if this would work under the hood.

Any tips would be greatly appreciated!

**Comment by GoodBoyDigital** [comment]
Yo! All good points man! 

The best way I have found to create a nice memory efficient scroller is to make sure to tidy up after yourself. Theres a few different ways to do this!

For this site (http://www.goodboydigital.com/project/mcdonalds-40-years-together/) which was an infinite scroller in every direction I found the best way was to create all the textures I would possibly need upfront  to cover the screen and override them manually. You can do this by using ```BaseTexture.updateSourceImage```

If you prefer to go with a different method Its important to make sure you remove unused textures from the GPU once you no longer need them. Pixi uploads an image to the GPU the first time its rendered. It then stays there forever until you either call ```myTexture.destroy(true)``` or ```baseTexture.dispose()```

Culling wise theres lots of different way to achieve that too. if a sprite is set to visible false it will not have its updateTransform function called or its render function called. But it will still exist in the parents children array.

Unless you are going to have 1000s of images you should not need to worry about making a dynamic sprite sheet as the effort required to make it would outweigh the performance increase for sure!

The ultimate key here is to manage the textures for the infinite part of you site a little more manually than the rest of the project and not fill the GPU up with an infinite amount of them :)

**Comment by ayamflow** [comment]
Ah, thanks for the detailed write-up!
Good to know that a dynamic spritesheet would be overkill, I didn't really want to dig into this stuff...

I remember the McDonalds thing, definitely an impressive piece of work! So I guess this was some kind of pool of sprites + textures ? I can see something like 20-30 items and their textures loading. I like the approach... I'll see how I can get this done!

I see that the `BaseTexture.updateSourceImage` doesn't call `baseTexture.dispose()`, should that be called ?

**Comment by GoodBoyDigital** [comment]
cheers man! na ```baseTexture.dispose()``` would not be required as ```BaseTexture.updateSourceImage``` overrides the GPU texture itself. So instead of destroy - create it simpley updates the existing GPU texture.

**Comment by ayamflow** [comment]
Noïce!! Will try and definitely come back to tell my experience. Stay tuned !

**Comment by GoodBoyDigital** [comment]
good luck man :+1:

**Comment by englercj** [comment]
Closing this now as it seems wrapped up.

**Comment by ayamflow** [comment]
@GoodBoyDigital Hiya! I've been toying a bit with it, I've got a nice pool of object that I clear & reuse when needed, working nice for now. Though I have one more question:

When the infinite scroll triggers, I preload all new images and then recycle my objects (and assign new texture sources). So I'm doing `object.texture.baseTexture.updateSourceImage(newPath)` but I'm thinking, since the images are preloaded, they are in the TextureCache and updating the source image will not free the image right?
I'm basically doing `object.texture = TextureCache[newPath]` I guess, which is not freeing the memory...

Can I do something like  `TextureCache[oldPath].destroy(true)` ? I guess if I need the texture again, it will fetch it from browser cache and upload it to the GPU, but I'm not too comfortable about all this dark magic stuff like you are :D

**Comment by ayamflow** [comment]
Also, two of the biggest improvements I was able to implement:
- For masks that don't change that often, use a `new PIXI.Sprite(mask.generateTexture(...))` since masks are really slow on mobile (at least with canvas renderer). I still show the real mask during animation.
- Filter a bit all those nasty `resize` events that mobiles tend to trigger on every scroll direction change (I check if the width changed + another project-specific check to be sure).
Those made a big difference, mostly on devices & iPad.

**Comment by gg4u** [comment]
@ayamada  would you like to elaborate on: 

> Filter a bit all those nasty resize events that mobiles tend to trigger on every scroll direction change (I check if the width changed + another project-specific check to be sure).
Those made a big difference, mostly on devices & iPad.

? 

I think it'd be useful, thanks!
