### ISSUE TITLE
Setting alpha on a SpriteBatch

### ISSUE THREAD

**Issue by davidfig** [GoodBoyDigital/pixi.js#1655]
I ran into a problem when trying to change the alpha on a SpriteBatch. Outside of SpriteBatch.alpha = 0, nothing happens. Changing the alpha on individual Sprites within the SpriteBatch worked fine. It appears  the Sprite's parent's alpha is not used in alpha calculation (perhaps because updateTransform is not called on the SpriteBatch?).

I fixed this by changing WebGLFastSpriteBatch.prototype.renderSprite to add an alpha calculation: 

    var alpha = sprite.alpha * sprite.parent.worldAlpha;

and then changed the colors on all the vertices to alpha (instead of sprite.alpha).

I haven't tested this behavior on the canvas renderer.

**Comment by englercj** [comment]
Have you tried this in v3 with ParticleContainer?

**Comment by davidfig** [comment]
Not yet, but I will.

**Comment by davidfig** [comment]
I tested it with the v.3 ParticleContainer and it has the same bug.

**Comment by englercj** [comment]
@davidfig Is this WebGL only you have this issue, or canvas as well?

**Comment by davidfig** [comment]
Haven't tested canvas. I'll give it try over the next couple of days.

**Comment by GoodBoyDigital** [comment]
All fixed up now on the dev branch. Thanks for sharing @davidfig :+1:
