### ISSUE TITLE
WebGL `Graphics.generateTexture` is all blurry. (v3)

### ISSUE THREAD

**Issue by jordwalke** [GoodBoyDigital/pixi.js#1656]
If I pass `true` to the last arg of `autoDetectRenderer`, then converting graphics objects to sprites does not do anything strange. However, if I flip the flag to `false` (so it uses `WebGL`) then all the generated sprites are the entire size of the drawing screen (perhaps?) and blurry.

This might have something to do with the fact that I noticed that `autoResize: true` is required on the `autoDetectRenderer` when you have a resolution > 1 - even if you supply the correct height/width. (Or that could be a totally unrelated bug!)

**Comment by GoodBoyDigital** [comment]
hi there @jordwalke. If you could provide a fiddle demonstrating your issue that would be ace. Cheers!

**Comment by englercj** [comment]
Ping for a repro case. Would be very helpful to track down this issue.

**Comment by jordwalke** [comment]
I just tried flipping some args around and couldn't repro on the latest Pixi. I'll reopen if I see it again.

**Comment by englercj** [comment]
Even better, thanks!
