### ISSUE TITLE
A way to create border-images.

### ISSUE THREAD

**Issue by jordwalke** [GoodBoyDigital/pixi.js#1657]
In CSS, there is a very handy way to create borders from images (sprites). There is a similar API on iOS views. Basically, you define the width of the border on all sides of the images, then when the image stretches, the edges are not scaled, they are preserved perfectly, but the center (the region not belonging to any edge) is either tiled or stretched depending on how you've configured it. Is there something simliar for pixi?

**Comment by woutercommandeur** [comment]
I believe you're looking for something like: https://github.com/SebastianNette/PIXI.NinePatch

**Comment by jordwalke** [comment]
Looks like exactly what I was searching for.

**Comment by jordwalke** [comment]
Should this be supported by TilingSprite? We would only need to be able to tile a certain region *inside* a single sprite resource, instead of tiling the entire sprite. Reopening to ask Pixi devs if this is relatively easy to add to `TilingSprite`.

**Comment by englercj** [comment]
I think this is out of scope for being directly in TilingSprite. But it is likely with some clever use of TilingSprite you could achieve a similar effect.

**Comment by jordwalke** [comment]
I was hoping there was a way to upload one single texture and have an intelligent shader know how to pull out only a certain repeatable rect within it, but also painting the border that is outside of that repeatable rect. Does this sound doable? (Thanks for your patience, I don't know much about GLSL).

**Comment by englercj** [comment]
Most things are possible, but I'm not experienced enough with glsl to come up with something for that. But that doesn't sound like something I would want the TilingSprite to do.

**Comment by jordwalke** [comment]
Okay, fair point. I'm curious why that seems beyond the scope of tiling sprite, since tiling behavior is simply a special case of border-image where the repeat rect is the entire sprite. I'll play around with it, maybe make a plugin. Thanks for all the great work!
