### ISSUE TITLE
Throw error -> [object object]

### ISSUE THREAD

**Issue by Inateno** [GoodBoyDigital/pixi.js#1658]
Sometimes the code throw error with "this" causing an [object object] in console and it's not very useful.

Unfortunately we cannot do throw new Error( "message", this ) instead of +, but maybe we should add a console.log or console.error before the throw to get more information about the error ?

An example:
In Sprite.fromFrame
throw new Error('The frameId "' + frameId + '" does not exist in the texture cache ' + this);

**Comment by GoodBoyDigital** [comment]
good shout @Inateno. that error message has been bugging me for ages! Will make sure to tweak

**Comment by GoodBoyDigital** [comment]
all done :) thanks @Inateno
