### ISSUE TITLE
[V3 RC4] TilingSprite not rendering with CanvasRenderer

### ISSUE THREAD

**Issue by alaa-eddine** [GoodBoyDigital/pixi.js#1659]
TilingSprite is not working in Canvas renderer

in TilingSprite.prototype._renderCanvas method

this piece of code seems wrong 

```javascript
    if (!this.__tilePattern ||  this._refreshTexture)
    {
        this.generateTilingTexture(false);

        if (this._tilingTexture)
        {
            this.__tilePattern = context.createPattern(this._tilingTexture.baseTexture.source, 'repeat');
        }
        else
        {
            return;
        }
    }
```

because generateTilingTexture need a renderer as first parameter but false is passed instead

**Comment by PcPenguin** [comment]
Is each parameter connected to each function? is your Tile set to thew correct UI i am as confused as you!!

**Comment by krzysztof-o** [comment]
I'm experiencing the same error in the latest dev version.

**Comment by GoodBoyDigital** [comment]
watch this space ladies and gents..

**Comment by GoodBoyDigital** [comment]
hey peeps, just uploaded a new Tiling texture to the dev branch.. please let me know if it works ok for ya!

**Comment by alaa-eddine** [comment]
it's working now :)
thank you for the fix
