### ISSUE TITLE
Pixijs doesn't like Sprites over 96pixels (v3)

### ISSUE THREAD

**Issue by jordwalke** [GoodBoyDigital/pixi.js#1664]
I am using the @2x/@3x resolution suffixes to indicate the resolution density.

I have a `img.png` at 32px/32px. This is what should be rendered on non-retina screens.
I have the same image saved as `img@2x.png` at 64px/64px.
I have the same image saved as `img@3x.png` at 96px/96px.

Any image equal or larger than 96px/96px renders as a black box. If I rescale the @3x image down to 95px/95px it works fine. 97px/97px is also broken.

Whenever it renders as a black box, I get the following errors:

> WebGL: drawElements: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering or is not 'texture complete'. Or the texture is Float or Half Float type with linear filtering while OES_float_linear or OES_half_float_linear extension is not enabled.

**Comment by GoodBoyDigital** [comment]
hi there! An interesting one indeed! Would mind providing a fiddle to show the error. Makes our debugging lives way easier :D thanks!

**Comment by jordwalke** [comment]
I think it's hard to reproduce in a fiddle because you have an image with `@3x` available to load: but here's the steps:

    var renderer = PIXI.autoDetectRenderer(paddedWidth, paddedHeight, {
      view: null,
      transparent: true,
      antialias:false,
      preserveDrawingBuffer:false,
      resolution: window.devicePixelRatio,
      autoResize: true,
      clearBeforeRender: false
    }, false);
    document.body.appendChild(renderer.view);
    var pictureIcon = new PIXI.Sprite.fromImage("images/picture_icon@3x.png", false);
    var topContainer = new PIXI.Container();
    topContainer.addChild(pictureIcon);
    renderer.render(topContainer);


Then load the page on an iPhone 6+, *or* load it in chrome, but set your profile to mock an iPhone 6+.

**Comment by GoodBoyDigital** [comment]
This has now been fixed! An interesting little issue that was caused by passing a non-whole number to pixi's isPowerOfTwo check. Thanks for sharing!

**Comment by jordwalke** [comment]
:+1:
