### ISSUE TITLE
Feature proposal : cached texts

### ISSUE THREAD

**Issue by JiDW** [GoodBoyDigital/pixi.js#1669]
Hello,

This is something we did for our game and I wonder if it should stay a home-made feature, a plugin, or if it could be merged into PIXI.

PIXI.Text.updateText() is very slow because it needs to create a canvas and write something inside it in order to use the canvas as a base texture.

Because of this, it is not usable for an often modified text, like a score count for example. With PIXI, you can use BitmapText to do that efficiently, but you are limited by the number of BitmapFont you have generated because you want to have a bitmapfont for every font size you need, to avoid pixelated texts.

So PIXI.Text is still very useful, but PIXI.Text.updateText() is so slow that it can makes the render of a complex game UI laggy on smartphones. For example, our game have multiple page : http://www.serenity-ff.com/images/screenshots/screenshot173214001.png

When you click to go to another page, we recreate the sprites and texts. On some smartphones (ex: nexus 4) it is enough to get a 1200ms-1600ms freeze. When you want to animate the transition between your pages, it is not acceptable.

The idea is to not generate a new texture when you try to create twice the same text with the same style. What we did it is to create every PIXI.Text base textures with a _pixiId generated from the text and the style of the PIXI.Text object.

We had to deal with setText and setStyle on an existing object but it was not a big deal.

This feature allowed us to preload the texts at the start of the game, making the creation of a PIXI.Text as fast as a PIXI.Sprite, while still being able to use setText, setStyle and other PIXI.Text related methods.

It even improve the performances of creating texts not directly related to each others but already displayed somewhere else in the game with the same style.

Another use case is when you have a menu with mouseover interactivity, like changing the fill color of the text. Once the two states (inactive/over) are generated and in the cache, the mouseover effect will be very fast. (You can of course preload the two styles)

The only drawback we didn't manage yet but can be done easily is to prevent this behavior from happening if you want to use PIXI.Text for a often modified text, even if it is not a good thing performance-wise, like a score because it will keep in memory every generated texture if you do not destroy them manually. We plan to add a parameter to make this behavior optional.

What do you think of this feature ?
At this moment the code is not clean, meaning is has references to our game, but we are wondering if it could be interesting to share and if yes, how ?
Should it be a plugin overloading PIXI.Text ? Should it be a pull request into the core component of PIXI.Text ?

Regards.

**Comment by GoodBoyDigital** [comment]
Hi there @JiDW 

I would say that something like this is certainly useful, but maybe not something that belongs in the core as its more of an application optimisation. The great thing about v3 though is you could create a plugin and we could add it to the pixi organisation if you fancied?

**Comment by englercj** [comment]
This sounds like

**Comment by englercj** [comment]
I agree something like this should be made, but I don't think it needs to be in core. Let us know if you need help setting up a plugin.

**Comment by JiDW** [comment]
Working on it today. While I'm reading the git documentation, do you have a link to redirect me to some explanations about the plugin system of PIXI ? Some kind of setup advices would be greatly appreciated !

Following your comments, I guess I should build something like a CocoonText plugin, because it is mostly revelant inside cocoonjs and it is not the only thing about text not working properly within cocoonjs.

For example, the resolution property doesn't work because CocoonJS can't use "context.scale" on the text canvas and you have to multiply the font size by the resolution you want in order to get high resolution texts.

**Comment by englercj** [comment]
@JiDW [pixi-spine][ps] is a good plugin to model after, and my generator can help you scaffold a project [generator-browserify][gb]

[ps]: https://github.com/pixijs/pixi-spine
[gb]: https://github.com/englercj/generator-browserify

**Comment by JiDW** [comment]
Thanks ! I tried to copy pixi-spine for my plugin and I think I succeeded but I can't test it because I don't understand how to use a plugin.

When you build pixi-spine, it produce a file that can't be called directly after PIXI so I guess there is a missing step but I can't find a documentation.

**Comment by JiDW** [comment]
Fixed. Here is the plugin : https://github.com/JiDW/pixi-cocoontext

I hope I did things the rigth way. let me know if there is changes to make.
