### ISSUE TITLE
3.0 a good time for a move?

### ISSUE THREAD

**Issue by drkibitz** [GoodBoyDigital/pixi.js#1671]
I'm sure there have been discussions about this I'm missed, or have even happened offline.

Probably no better time than 3.0 to move the repo, to github.com/pixijs/pixi, and change npm package name to 'pixi', (I can give you the name). It would be a clean switch, major version, breaking changes, etc. etc.

**Comment by englercj** [comment]
/agree

@GoodBoyDigital Was waiting to hear back from someone at GitHub to ensure we stayed on some "top something something" lists after the move happened.

**Comment by perara** [comment]
It took me approx 10 minutes to migrate from v2 to v3.
And this was mostly warnings about Container refactor and Text's settext.

Good work guys!

**Comment by englercj** [comment]
To be clear @drkibitz is talking about moving the repository to the pixijs organization and out of GoodBoy's personal project space.

**Comment by perara** [comment]
I see, Well then!

**Comment by drkibitz** [comment]
@englercj 

I added you as a package owner to:
https://www.npmjs.com/package/pixi

and deprecated the project:
https://github.com/drkibitz/node-pixi

**Comment by drkibitz** [comment]
Here's some of my thoughts...

1. After assurance from Github that everything will be ok, **move** "GoodBoyDigital/pixi.js" to "pixijs/pixi"
   - Github will take care of all redirects etc. from the old location at GoodBoyDigital/pixi.js, as long as you **move** the repo. Do not fork it, or create a new one and push to it.
   - Moving the repo and relying on Github redirects means that GoodBoyDigital/pixi.js can no longer exist, otherwise it would conflict with and prevent the Github managed redirections to pixijs/pixi.
2. Publish package to https://www.npmjs.com/package/pixii
   - This package can be started out at 3.0
   - The pixi.js package can remain v2, but can still have a v3 of which would only contain a README to point to new package. If you want to be really nice, it can even depend on the new package, export it, and throw a warning to say the same thing as the README.
3. Make some major pushes to all community outlets possible, about the move along with the new version, and the reasons behind the move and the architecture.
   - My reason behind the move would be that it is part of putting our best foot forward while moving toward a modular and pluggable architecture. Having everything in a centralized Github organization (namespace) helps mitigate confusion, and simplifies source access management. Naming the library `pixi` is just a simplification of the current name, saves a few keystrokes, and matches the name of the global object that the library exposes. The organization is already called "pixijs", the core will probably be called "pixi-core", so "pixi" just makes sense for a package that glues things together for you. The reason for this architecture is something that we've already had long discussions over that I'm not going to summarize here.

**Comment by drkibitz** [comment]
@GoodBoyDigital To help, thought I'd reference a project that recently changed it's name and org:
https://github.com/nwjs/nw.js

As the README says, it was previously known as node-webkit, and was under the author's (Roger Wang) user organization. In that location, the project grew exponentially, and now under the new organization and name, it continues to grow.

Pinging @rogerwang, the author of NW.js (aka node-webkit), to see if he would like to share his experience in making a major move like this, why, and how things went from the perspective of a project steward.

**Comment by drkibitz** [comment]
Here is the Github redirect for this project in action ;)
https://github.com/rogerwang/node-webkit

**Comment by englercj** [comment]
@drkibitz To be clear, the thing stopping us from moving right now is not the redirect stuff but that the pixi repo is listed on some "top X" lists on github based on traffic and what not. Those stats *do not* move with the repo and will be lost. We are working with GitHub to get those back in place if we move.

**Comment by englercj** [comment]
Going to close this since we should be moving as soon as we clear up some details with GitHub, thanks all!

**Comment by mattstyles** [comment]
Yes, 6to5 recently changed to babel too, _I think_ without too much undue stress
