### ISSUE TITLE
Temporarily disable PIXI.Ticker && PIXI.InteractionManager loops

### ISSUE THREAD

**Issue by gordyr** [GoodBoyDigital/pixi.js#1672]
We are using PIXI to power all heavy duty (mobile style) animations for a photo focussed next generation social network,  as well as for the backbone of our webgl shader based photo editor.

For the purpose of this question i'll explain the simplest work flow that we have....

User scrolls down their newsfeed, all HTML rendered.  They see a post which contains photos and decide to select a photo.

When they do so we switch from traditional HTML to PIXI.  The photo then expands to fill the screen with a lovely animation all powered by webgl... the user can then scroll left and right through the photos so on and so fourth.  Creating and destroying PIXI textures (of the users photos) as required.

Very simple but very effective, and silky smooth thanks to PIXI/WebGL.

Now.... creating a PIXI renderer has a startup cost associated with it.  It's only several milliseconds but its enough to interfere with user responsiveness when a photo is selected.  Therefore we create a single renderer at page load time and attach it to the dom whenever we need... removing it again once we are done.

This works perfectly and everything feels instantaneous.

However we have noticed that ```PIXI.Ticker``` and ```PIXI.InteractionManager``` are constantly looping in the background as soon as we create the ```PIXI.autoDetectRenderer```.  And before we need it.

Since we only use PIXI to power certain user interactions this is very undesirable.  We would like to be able to stop and start these loops at will.  Currently they are eating CPU cycles in the background which we would like to avoid.

We have managed to stop the ```PIXI.Ticker``` loop by setting:

```PIXI.extras.Ticker.active = false;```

Straight after we load PIXI itself. 

However we cannot seem to find a simple way to halt the looping of the ```PIXI.InteractionManager```

Is there any way to easily do so? If not this looks very easy to implement and I would like to request it as a feature for version 3.  Perhaps something like  ```renderer.deactivate()``` and ```renderer.activate()``` functions or something along those lines.

Thanks guys.

**Comment by gordyr** [comment]
Okay I've just realised I can call ```renderer.destroyPlugins()``` then when we want to use it we can call ```renderer.initPlugins()``` to reactivate them.

This works great but feels a bit unnecessary when we just want to temporarily halt the background loops.

Any thoughts?

**Comment by gordyr** [comment]
Okay I've found a workaround which is to do the following:

1. Pre-initialize our renderer on page load and instantly kill the ```InteractionManager``` by calling:

```renderer.plugins.interaction.destroy()```

2. When we need it we simply reattach it to the renderer:

```render.plugins.interaction = new PIXI.interaction.InteractionManager(renderer)```


This appears to work fine but seems a bit verbose.  It would be great to be able to simply halt the loop itself rather than completely kill the plugin.

**Comment by drkibitz** [comment]
I just contributed some changes to Ticker, with more waiting that addresses this. Now that I see that InteractionManager is doing the same thing, I think a good idea would be to use the ticker within InteractionManager

**Comment by drkibitz** [comment]
Maybe should move ticker to it's own namespace.

I've got an open PR that you can feel free to comment on.
https://github.com/GoodBoyDigital/pixi.js/pull/1682

**Comment by drkibitz** [comment]
@gordyr with my PR in dev branch, you can do this:
```js
var ticker = PIXI.ticker.shared;
// Set this to prevent starting this ticker when listeners are added to it
// By default this is true only on the PIXI.ticker.shared instance
ticker.autoStart = false;
// Call this to ensure the ticker is stopped right now
ticker.stop();
// Call this when you are ready for it a running ticker
ticker.start();
```

**Comment by drkibitz** [comment]
@gordyr should mention that InteractionManager was also changed to use the the shared ticker.

**Comment by GoodBoyDigital** [comment]
@drkibitz is this cool to close based on your latest pr? thanks!

**Comment by drkibitz** [comment]
@GoodBoyDigital I'm cool with closing it. There should be enough in place now to prevent automatically starting raf loops if wanted. I would like some feedback from @gordyr though.

**Comment by gordyr** [comment]
Apologies for getting back to you so late.  @drkibitz your PR looks good to me and is a far better solution based on a quick look through your code.

We will try it in use tomorrow and I'll feedback if there are any issues, but I can't foresee any.  

Good stuff :)

**Comment by gordyr** [comment]
Just to let you know.... it works perfectly.  And is far more elegant.  Cheers
