### ISSUE TITLE
Alpha parameter of Graphics.beginPath() function not working when point count > 4

### ISSUE THREAD

**Issue by hmilyyang** [GoodBoyDigital/pixi.js#1678]
According to source code of pixi v2, there may be a bug in function "WebGLMaskManager.prototype.bindGraphics":

gl.uniform1f(shader.uniforms.alpha._location, graphics.worldAlpha);

should be

gl.uniform1f(shader.uniforms.alpha._location, graphics.worldAlpha * webGLData.alpha);

**Comment by englercj** [comment]
Is this problem happening in the latest v3 build?

**Comment by hmilyyang** [comment]
It happens in latest v3, but not happen in v2.

**Comment by englercj** [comment]
This should be fixed now with #1770.
