### ISSUE TITLE
Are there any implementations for font atlases and SDF support for Pixi?

### ISSUE THREAD

**Issue by PixelsCommander** [GoodBoyDigital/pixi.js#1679]
At the moment Pixi does not optimize fonts rendering. Are there any plugins or solutions to use characters atlases? And even more challenging what about SDF?

May be any plans or ideas on that?

**Comment by GoodBoyDigital** [comment]
Hi there! Pixi does indeed support bitmap fonts which is pretty much what you are after. SDF is on the todo list too but not currently implemented. Hope that helps! Thanks :+1:

**Comment by PixelsCommander** [comment]
Does it use font atlas or uploads labels to GPU one by one?

2015-04-18 15:23 GMT+02:00 Mat Groves <notifications@github.com>:

**Comment by GoodBoyDigital** [comment]
it uploads a sprite sheet of all characters. Then constructs letters using that sheet, so just the one texture upload at startup.

**Comment by PixelsCommander** [comment]
Great, thank you
