### ISSUE TITLE
WebGL mask has wrong position

### ISSUE THREAD

**Issue by ayamflow** [GoodBoyDigital/pixi.js#1690]
Since yesterday's `npm install` all my masks have wrong position, only when being masked.
This only applies for Sprite-based mask, I haven't tried Graphics-based and/or canvasRenderer.

If I comment `sprite.mask = theMask` the mask appear at the correct position but if I activate the mask, the visible content is offset by `height * 0.5` on the Y axis (but what is shown is correct).

I reverted my pixi dep to 42fa2ad31967d5ae31eb10f7dad88b6a3d7eef6b and the problem doesn't appear. Any idea on top of you head? If not I'll try to setup a simple example this week.

**Comment by GoodBoyDigital** [comment]
hey man, do you have a fiddle I could take a peek at? will aim to fix this one today. cheers!

**Comment by GoodBoyDigital** [comment]
sorted in dev branch init :+1:

**Comment by ayamflow** [comment]
Ahah nice ! Couldn't reprouce it in fiddle
