### ISSUE TITLE
Rope seems to use baseTexture instead of respecting the textureFrame boundaries using fromFrame

### ISSUE THREAD

**Issue by Friksel** [GoodBoyDigital/pixi.js#1691]
After a lot of testing it seems like Pixi Rope is not working with spritesheets-frames as textureinput: Texture.fromFrame. Pixi uses the full baseTexture scale to display and warp the individual points instead of the boundaries of the frame. So what I see is not only the texture inside the frame, but the full baseTexture getting warped with the points.

The same code is working fine using individual imagefiles (with Texture.fromImage). 
After a lot of trying out different things, I can't figure out anything anymore to tryout next.  I could be mistaken here or missing something important, but it seems to me like a bug 'cause I would expect the same code working with Texture.fromImage should also work using Texture.fromFrame. A texture is a texture I'd say.

Here's the part of the code I'm using:

```
        var points, rope;
        var segments = 14;
        var imgWidth = 980; // px frame
        var length = imgWidth / segments; 


        // DEFINE POINTS
        points = [];
        for (var i = 0; i < segments; i++) {
            points.push(new px.Point(i * length, 0));
        }


        // DEFINE ROPE
        rope = new px.Rope(px.Texture.fromFrame(snakesettings.imgID), points);  // DOESN'T WORK: USES FULL BASETEXTURE FOR SOME REASON
//  BEFORE THIS WAS WORKING FINE WITH SEPERATE IMAGE FILES:  px.Rope(px.Texture.fromImage(snakesettings.imgID), points);

        stage.addChild(rope);
```

**Comment by GoodBoyDigital** [comment]
Hey there @Friksel ! Using sprite frames could be possible but is not currently implemented in pixi. For now its best to use separate images. There would be no real advantage / performance boost from using images in a sprite sheet for a rope as each one is a seperate draw call anyways. hope that helps!

**Comment by Friksel** [comment]
Wow, that's quick @GoodBoyDigital ! Thanks for your response. Reason I'm using spritesheets is for lowering the file-requests. I have more graphics inside one animation and I'm used to put them all into one spritesheet per animation for performance reasons. So for this reason It would be great if this would be possible in the future, although I understand your priorities ofcoarse.

Love pixi anyhow! Great framework and it always put a smile on my face!

**Comment by englercj** [comment]
You can also load a single image, and draw each frame to a canvas and use that as a texture if loading 1 image is important to you.
