### ISSUE TITLE
WebGL rendering textures from a spritesheet incorrectly

### ISSUE THREAD

**Issue by thesquib** [GoodBoyDigital/pixi.js#1692]
On the latest dev 15c062e3cd3766bec3771c46fe173119af123eeb 
When the WebGL renderer is enabled, the sprites from a spritesheet are not quite aligned and there is bleed from the adjacent sprites. It appears to work fine when a CanvasRenderer is used. I'm creating a spritesheet manually in code from a base texture. 

See the jsfiddle for the code, although it doesn't work in jsfiddle for some reason, I have it running in Chrome
https://jsfiddle.net/ycn1jspk/3/

**Comment by englercj** [comment]
Update your fiddle with the latest version of pixi, and using http so it works:

http://jsfiddle.net/ycn1jspk/4/

**Comment by englercj** [comment]
I was right, if you change your base texture creation to use nearest scaling it works fine:

```js
var baseTexture = PIXI.Texture.fromCanvas(canvas, PIXI.SCALE_MODES.NEAREST);
```

Working fiddle:
http://jsfiddle.net/ycn1jspk/5/

**Comment by thesquib** [comment]
Thanks Chad
