### ISSUE TITLE
[V3] MovieClip.currentFrame should be renamed

### ISSUE THREAD

**Issue by gprzybylowicz** [GoodBoyDigital/pixi.js#1694]
currentFrame is really confusing name because this variable is not current frame! I think there should be another var to counting up time, and another getter/method/var to return current frame.

example:
```
this.totalTime += this.animationSpeed * deltaTime;
var floor = Math.floor(this.totatTime);
this.currentFrame = floor % this._textures.length
```

**Comment by drkibitz** [comment]
+1, this bit me as well even with the comment saying it does not have to be whole number.

**Comment by englercj** [comment]
Closing since #1696 was merged.
