### ISSUE TITLE
[V3 RC4] Help migrating, getLocalPosition is not a function?

### ISSUE THREAD

**Issue by manelis** [GoodBoyDigital/pixi.js#1699]
Hello, 

First of all sorry for asking here, but seeing there is no forum and I can't find documentation for 3.0 yet, seems to be a good place to ask.

I have a somewhat complex project built on pixi and performance is not briliant right now due to a huge number of objects and thought it would be a good time to try change to 3.0, to see how it improves. Mostly went fine, fixed all the deprecated warnings on the console, however, some functions do not work. Most important of all to have a working build of this is the interaction.

In any of the mouse callbacks I cant get the position and says getLocalPosition is not a function. This is the working 2.2.7 code for mouse move as an exemple:

on start:

```javascript
      dragMask.mousemove = dragMask.touchmove = function(data) {
        if(jsmap.smoothing)
          return;
        if(!zoom_on_prev_frame)
          jsmap.cameraMouseMove(data);
        else
          jsmap.cameraMouseUp(data);

      };
```

and the cameraMouseMove where it throws the error:

```javascript
    cameraMouseMove: function(data){

      if(jsmap.state == jsmap.map_state){
        globalMousePosition = data.getLocalPosition(pixiWindow);
        if (map.dragging) {
          map.position.x = map.initx + globalMousePosition.x - map.initlocalx;
          map.position.y = map.inity + globalMousePosition.y - map.initlocaly;
          jsmap.updateQuadtree();
          jsmap.fixOrdersPosition();
        }
      }

      else if(jsmap.state == jsmap.city_state){
        globalMousePosition = data.getLocalPosition(pixiWindow);
        if (city_view.dragging) {
          city_view.position.x = city_view.initx + globalMousePosition.x - city_view.initlocalx;
          city_view.position.y = city_view.inity + globalMousePosition.y - city_view.initlocaly;
        }
      }
    },
```

pixiWindow is now a Container (previously a DisplayObjectContainer).

Other less important things giving the same error are setStyle on a PIXI.Text and new PIXI.MovieClip.

Thank you for the help.

**Comment by englercj** [comment]
`event.data` is the InteractionData object, which has getLocalPosition.

**Comment by manelis** [comment]
Ok, thank you for the quick awnser. Already also found the setStyle, however I also cant seem to find the new PIXI.MovieClip. Already tried with and without the new, with and without arguments and with and without the PIXI. 

this is how it is being used and working in v2.2.7:

```javascript
    addMovieClip: function(map, x, y, xoffset, yoffset, textures){
      var tex = [];
      for(var i = 0; i < textures.length; i++){
        if(!jsmap.textures.hasOwnProperty(textures[i]))
          jsmap.textures[textures[i]] = new PIXI.Texture.fromImage(textures[i]);
        tex.push(jsmap.textures[textures[i]]);
      }

      var xpos = jsmap.getMapXPos(x, y);
      var ypos = jsmap.getMapYPos(x, y);
      var clip = new PIXI.MovieClip(tex);
      clip.position.x = xpos + xoffset;
      clip.position.y = ypos + yoffset;
      clip.xCoord = x;
      clip.yCoord = y;
      clip.gotoAndPlay(0);
      clip.animationSpeed = 0.25;
      map.addChild(clip);
      clip.visible = false;
      jsmap.quadtree[x][y].push(clip);
    },
```

Everything else is already working fine with 3.0. Will give feedback later to the performance after this is fixed. Thank you again.

**Comment by manelis** [comment]
ok, found it. PIXI.extras.MovieClip.

**Comment by englercj** [comment]
Most things in v3 will log where it has moved to if you are using the latest `dev` version the deprecation logs are pretty comprehensive.
