### ISSUE TITLE
Sprites disappear with certain filters?

### ISSUE THREAD

**Issue by Shadowstep33** [GoodBoyDigital/pixi.js#1705]
Hello,

There is a condition that I'm not fully sure of that makes sprites disappear. When I have a blur filter on a DOC, it works correctly for most of the time. After I play the game I am making for a little bit, the blur filter makes sprites disappear from the DOC. To test this, in the console I tried setting the DOC's filter to null, and everything appears again. 

I noticed this same thing happen with a ColorMatrix filter, except that consistently makes the sprites children disappear. I'm not sure if these two problems are related.

The code I use for blur:

	        var blur_filter = new PIXI.BlurFilter();
	        blur_filter.blur = 5;		
	        container.filters = [blur_filter];

As I mentioned, it works most of the time but there is some sort of condition/interaction where if there is a blur filter on container, all of containers children sprites become hidden (but they still have alpha = 1 and visible = true).

Would appreciate any help, as it is a bit of an eye sore and an obvious bug in gameplay.

Thanks,
Shadowstep33

**Comment by englercj** [comment]
Hmm, interesting. Can you get a minimal example that displays the issue so we can investigate?

**Comment by Shadowstep33** [comment]
Sure thing!

http://jsfiddle.net/ny19tak0/

If you uncomment the line that reads 

skill_sprite.filters = [filter];

then you can see some strange things happen. It isn't happening exactly how it does in my game, but the child sprite still has some issues (in this example, only half of it disappears for some reason; in the game I am working on, the full sprites are disappearing);

**Comment by englercj** [comment]
Oh, this is a v2 issue! Does this still happen in v3 at all?

**Comment by Shadowstep33** [comment]
Wait, v3 is released :O ?!?!

**Comment by englercj** [comment]
So it is!

http://www.goodboydigital.com/pixi-js-v3/
https://github.com/GoodBoyDigital/pixi.js/releases/tag/v3.0.0

**Comment by Shadowstep33** [comment]
Mmmm tastey :) Going to play with it ASAP. I'll go ahead and close this for now but if I see the same bug I'll re-open. Are the docs at http://www.goodboydigital.com/pixijs/docs/ updated to v3 or can I find those elsewhere?

**Comment by englercj** [comment]
Everything is on github now:

https://github.com/pixijs/docs
http://pixijs.github.io/docs/

**Comment by Shadowstep33** [comment]
Thank you! Just did a little dance of excitement :)
