### ISSUE TITLE
Simple Loader doesn't work

### ISSUE THREAD

**Issue by Manu33** [GoodBoyDigital/pixi.js#1709]
Hi all, 

Following the docs in Class: Loader

var loader = new PIXI.loader();
loader.add('bunny',"data/bunny.png");
loader.once('complete',onAssetsLoaded);
loader.load();

Give to me : 

TypeError: Object is not a constructor (evaluating 'new PIXI.loader()')

**Comment by JiDW** [comment]
```javascript
var loader = PIXI.loader();
loader.add('bunny',"data/bunny.png");
loader.once('complete',onAssetsLoaded);
loader.load();
```
or

```javascript
var loader = new PIXI.loaders.Loader();
loader.add('bunny',"data/bunny.png");
loader.once('complete',onAssetsLoaded);
loader.load();
```

PIXI creates one loader for you (PIXI.loader) already ready for use. To create a new one, you must not forget the namespace "loaders"

**Comment by krzysztof-o** [comment]
@JiDW you have type in the first line of your example. It should be:
```javascript
var loader = PIXI.loader;
```

**Comment by JiDW** [comment]
Yes sorry, thanks.

**Comment by Manu33** [comment]
Thank you, ok so the docs is false. Thank you. Please correct the docs (docs/PIXI.loaders.Loader.html)

**Comment by englercj** [comment]
Docs fixed, and issue solved!
