### ISSUE TITLE
Cannot dynamically change renderer resolution.

### ISSUE THREAD

**Issue by wojciak** [GoodBoyDigital/pixi.js#1712]
Hello :)

With pixi v2.x I had a simple "auto-performance" scaling engine. When I detected low fps for some time I did a simple trick (renderer is an instance of PIXI.CanvasRenderer or PIXI.WebGLRenderer)

renderer.resolution = 0.5; // or any value that I figured out would be ok to achieve good fps
renderer.resize();
interactionmanger.something // it updated the event map properly

and this triggered a nice resize with more or less pixelated textures.

Now in pixi v3.0.1 I can't seem to do it anymore. 
The .resolution property works as expected when initailizing the renderer, but once I change it and trigger .resize() everything goes to hell :)

Is there a way to dynamically change the resolution?

**Comment by alaa-eddine** [comment]
have you tried to use .resize(width, height) ?

**Comment by wojciak** [comment]
Yes, but i need to check if I'm not multiplying width and height by the resolution prior to resizing.

Will update :)

**Comment by wojciak** [comment]
It doesn't work either. Additionally I get something like this:
Error: WebGL: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)

**Comment by wojciak** [comment]
I've added one line to WebGLRenderer.prototype.resize and it now works:
this.gl.viewport(0, 0, this.width, this.height);

**Comment by englercj** [comment]
Added a fix in dev, will go out with v3.0.2 :)

**Comment by wojciak** [comment]
Hi guys - bumping this up. In 3.0.2 the "this.gl.viewport(0, 0, this.width, this.height);" part is in the wrong place. When it's located like this:

if(this.currentRenderTarget === this.renderTarget) {
        this.renderTarget.activate();
        this.gl.viewport(0, 0, this.width, this.height);
    }

It works like a charm ;] - perfect resizing with no flicker
