### ISSUE TITLE
requirejs get's overridden by pixi's require (v3)

### ISSUE THREAD

**Issue by naranjamecanica** [GoodBoyDigital/pixi.js#1713]
I'm loading the bin version of pixi v3 using requirejs and the first line in the this files overrides the require function in global scope. Putting a scope arround it using:

    (function () {
        var require = ...
    }());

prevents the overriding.

And thanks btw for the new kick-ass version! :+1:

**Comment by englercj** [comment]
Yeha this happens because we expose pixi.js via browserify's "expose" method. That allows plugins to do `require('pixi.js')` and it works because we have exposed PIXI.

Will have to think about how plugin need to interact with pixi if we don't use expose...

**Comment by naranjamecanica** [comment]
Is there an disadvantage for the plugins when you wrap the whole build pixi script in an closure like above?

**Comment by englercj** [comment]
If we wrap the whole build in the closure, plugins won't be able to do `require('pixi.js')` because `require` won't exist (or will be something other than what it is looking for).

I'm still thinking about the best way to do this, likely it is to use standalone and find out how to make plugins work...

**Comment by englercj** [comment]
I think I have fixed it by just using `standalone` and always exporting to global (in addition to any commonjs/amd things that happen).

If plugins rely on that global export, they too can use standalone and always for all environments. Closing this for now since it will be fixed in v3.0.2.

**Comment by naranjamecanica** [comment]
Just to let you know: the current version works well in my requirejs setup, thanks :+1:
