### ISSUE TITLE
Tilemaps

### ISSUE THREAD

**Issue by krazyjakee** [GoodBoyDigital/pixi.js#1714]
This issue existed before and was solved: https://github.com/GoodBoyDigital/pixi.js/issues/48

I thought I'd start a fresh issue now that v3 has arrived.

Is tilemap support on the roadmap?

**Comment by englercj** [comment]
Nope, tilemaps are not something we will put into core pixi.js. It is really more of a game feature, and its implementation will be specific to a game engine or application and doesn't make sense to be in our thin rendering layer.

That being said, nothing is stopping anyone from making a v3 plugin for it. It just will never be in core.

**Comment by krazyjakee** [comment]
Doh, I think I was in the grapefruit headspace. Thanks.

**Comment by englercj** [comment]
Ha, no problem!
