### ISSUE TITLE
PIXI.Text font family is incorrect on Android

### ISSUE THREAD

**Issue by ayamflow** [GoodBoyDigital/pixi.js#1716]
On Android 4.4+ (tested on Nexus 4, Nexus 7, Moto X), the font rendering of `PIXI.Text` is incorrect, it always fallback to the default one (Arial).

Tested on the official [example page](http://pixijs.github.io/examples/index.html?s=basics&f=text.js&title=Text&v=v3.0.1).

In my use case, I tried to load the fonts in different ways, including [fontfaceonload](https://github.com/zachleat/fontfaceonload) and via [resource-loader](https://github.com/englercj/resource-loader/). In the example page it uses the WebFont loader but apparently it doesn't change anything. I also tested with a few native fonts without luck!

**Comment by englercj** [comment]
Weird, is this only on Android that this happens? Does this happen with native canvas draw methods as well or only on pixi?

**Comment by ayamflow** [comment]
Good point, I'll try to add a fiddle with that.
I've been witnessing that for a while now but didn't give it much time, but now that the examples are updated I am sure it's not my code only :)

**Comment by mattdesl** [comment]
It could be a race condition with font loading. I've seen "flash of unstyled text" using canvas fillText, and if it's cached the first time around (I believe it is in Pixi) your sprite ends up being the unstyled (native) fonts.

Try putting a long timeout before creating text elements to see if that does anything.

**Comment by ayamflow** [comment]
The sprites are created already a while after the initial preloading. Thing is, refreshing doesn't fix the issue and the font is properly loaded in the network tab.

**Comment by englercj** [comment]
I'm curious if this is an Android browser bug, if so you would see this behavior even when using raw canvas commands and not using pixi at all.

If you see it work properly in raw canvas, but not pixi text. Then it is a bug in ours and we can look into it. Just update this thread when you get a chance to check it out.

Thanks!

**Comment by ayamflow** [comment]
[Demo here](http://ayamflow.fr/pixi/android-text/). Works on Android.
[Also old demo on PIXI](http://www.goodboydigital.com/pixijs/examples/10/). Works on android too.

**Comment by ayamflow** [comment]
Poking @englercj since I'm not sure you saw the update ;) Not to pressure on you, just FYI!

**Comment by ayamflow** [comment]
Well, seems like it works now on my project, but still not in the demo!

**Comment by englercj** [comment]
This works for me on my android devices.

If you end up having issues again feel free to open another issue.
