### ISSUE TITLE
PIXI.ColorMatrixFilter is undefined

### ISSUE THREAD

**Issue by dmitriigaidarji** [GoodBoyDigital/pixi.js#1722]
Processing this code from the docs:
```
var colorMatrix = new PIXI.ColorMatrixFilter();
```
drops error: 
```
TypeError: 'undefined' is not a constructor (evaluating 'new PIXI.ColorMatrixFilter()')
```
I built the library with all the modules ( didn't exclude anything ). What am i doing wrong?

**Comment by englercj** [comment]
You are looking to use the `filters` plugin: `PIXI.filters.ColorMatrixFilter()`. :)
