### ISSUE TITLE
V3 : how to get view width/height ?

### ISSUE THREAD

**Issue by alaa-eddine** [GoodBoyDigital/pixi.js#1726]
Hi,

in PIXI 3 reference to the current renderer was removed, and I want to get width/height of the current viewport.

I tried by using the root container width and height but those are not the viewport width/height.
is there a way to get width/height of renderer or viewport in PIXI 3 ?

**Comment by wojciak** [comment]
You could just do:

```
var renderer = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight, this.options);
```

renderer.width
renderer.height

**Comment by alaa-eddine** [comment]
I know it's possible if I have access to renderer instance :)
but in my case it's an extension to PIXI, and I need the dimensions without knowing about renderer instance.

**Comment by englercj** [comment]
The viewport is controlled by the renderer, you need a reference to it to get the width/height of the viewport. Also checking the size of the canvas element will give you the same result.

**Comment by alaa-eddine** [comment]
this is actually the workaround I'm using (getting size from canvas element) .
I was just wondering if there was a "cleaner" way :) 

Thank you anyway

**Comment by englercj** [comment]
The cleanest way is to use the renderer, I would adjust your framework to expose it.

**Comment by alaa-eddine** [comment]
actually I was trying to make it as transparent as possible for the user, but maybe I'll add a init() method which will initialize the framework stuff.

btw is there a page where we can publish PIXI libraries/plugins ? mine is a themable GUI system for PIXI and Phaser, and I'll release it soon, just fixing some compatibility issues and creating examples and will publish it.

**Comment by englercj** [comment]
This might be appropriate:

https://github.com/GoodBoyDigital/pixi.js/wiki/Pixi-v3-Plugins
