### ISSUE TITLE
Cannot dynamically change renderer resolution cd :)

### ISSUE THREAD

**Issue by wojciak** [GoodBoyDigital/pixi.js#1727]
ref #1712 

Hi guys - bumping this up. In 3.0.2 the "this.gl.viewport(0, 0, this.width, this.height);" part is in the wrong place. When it's located like this:

if(this.currentRenderTarget === this.renderTarget) {
this.renderTarget.activate();
this.gl.viewport(0, 0, this.width, this.height);
}

It works like a charm ;] - perfect resizing with no flicker

**Comment by englercj** [comment]
Sorry about that, committed to the latest dev!

**Comment by wojciak** [comment]
Thanks! :+1:
