### ISSUE TITLE
Blur Filter

### ISSUE THREAD

**Issue by davidfig** [GoodBoyDigital/pixi.js#1728]
The v.3 BlurFilter looks very different from the v.2 one. It looks less blurry and more like the image is displayed multiple times and slightly offset. Is it just me?

**Comment by Shadowstep33** [comment]
I noticed this as well

**Comment by englercj** [comment]
It is definitely different: #1654.

Have you tried playing around with the `blur` and `passes` params to try and get your desired effect?

**Comment by davidfig** [comment]
Yes, I played with both blur and passes to try to get the desired blur. At low blur, it gives a nice soft edge, but as you increase the blur distance, it starts to look like the image is multiplied and slightly offset. (I also noticed this multiplied image in the v.3 blur example: http://pixijs.github.io/examples/index.html?s=filters&f=blur-filter.js&title=Blur&v=v3.0.2)

I'm using the blur filter to generate smoke using blurred circles and I need very soft edges for the effect to work--like the Feather filter from Adobe Illustrator. It's one of the few things that broke with the move to v.3. I'll continue to play with it and see if I can get it working again. 

Otherwise I'm loving v.3 :)

**Comment by englercj** [comment]
You can also use the `BlurXFilter()` and `BlurYFilter()` like the old `BlurFilter` wrapped previously for you:

```js
smoke.filters = [new PIXI.filters.BlurXFilter(), new PIXI.filters.BlurYFilter()];
```

And that should have the same behavior as v2.

**Comment by Danetag** [comment]
Hmm, applying ``BlurXFilter()`` and ``BlurYFilter()`` like the old ``BlurFilter`` doesn't seem to work...

**Comment by davidfig** [comment]
Thanks, switching to the old style filter worked better
