### ISSUE TITLE
[V3] All ParticleContainer children get the same texture (bug or feature?)

### ISSUE THREAD

**Issue by manelis** [GoodBoyDigital/pixi.js#1730]
Giving the new particle container and considering my sprites only need to change position, I tried changing one of the containers to particle container. The problem is that every sprite stays with the same texture (probably the first one that is load). Is this as intended or a bug? It seems from the bunnymark example that it is able to handle multiple textures.

Only change I made (already tried all the flags, but I only need the position one)

```javascript
      //map_military = new PIXI.Container();
      map_military = new PIXI.ParticleContainer(jsmap.hexagon_count, [true, true, true, true, true]);
```

Code to add a sprite:

```javascript
    addSprite: function(map, path, x, y, xoffset, yoffset) {
      if(!jsmap.textures.hasOwnProperty(path))
        jsmap.textures[path] = new PIXI.Texture.fromImage(path);
      var sprite = new PIXI.Sprite(jsmap.textures[path]);
      sprite.position.x = jsmap.getMapXPos(x, y) + xoffset;
      sprite.position.y = jsmap.getMapYPos(x, y) + yoffset;
      map.addChild(sprite);
      sprite.visible = false;
      jsmap.quadtree[x][y].push(sprite);
      return sprite;
    },
```

before:

![before](https://cloud.githubusercontent.com/assets/9083381/7348657/3ddfe764-eceb-11e4-9427-9091f1b73d8a.jpg)

after:

![after](https://cloud.githubusercontent.com/assets/9083381/7348630/07715ea6-eceb-11e4-9b53-66165e591ac9.jpg)

Also, another thing, is it possible to be able to toggle visiblity on a object in a particle container?

**Comment by englercj** [comment]
There can only be one *base texture* in a particle container. The benchmark uses multiple textures that all reference a single base texture ([this spritesheet](http://www.goodboydigital.com/pixijs/bunnymark/bunnys.png)).

Also the second param is an object, not an array:

```js
map_military = new PIXI.ParticleContainer(null, { position: true });
```

And in fact, the default is only position. So if that is all you need, you don't need to pass anything:

```js
map_military = new PIXI.ParticleContainer();
```

All children of a particle container *must* share the same base texture.

**Comment by manelis** [comment]
Thank you.

What about toggling visibility of children of a particle container, is it not possible?

btw, the array was from the benchmark code:

http://www.goodboydigital.com/pixijs/bunnymark/js/bunnyBenchMark.js

**Comment by englercj** [comment]
@manelis Yes the benchmark was written a long time ago, before we even did an RC. It has since changed. Always check the source :)

**Comment by manelis** [comment]
Thank you again, and sorry, considering that it seems that you missed that, what about the visibility?

**Comment by englercj** [comment]
Pretty sure `.visible` doesn't do anything to a child of a particle container, you can ensure that alpha gets uploaded and set alpha to 0 though to hide children.

```js
map_military = new PIXI.ParticleContainer(null, { position: true, alpha: true });
```

Which is fastest depends on how often you show/hide objects, and how many you will have hidden at a single time. I would just play with it.

**Comment by manelis** [comment]
The question is more about the performance.You can see the context on the above images.What I do right now is every time the user moves the camera or zooms, i calculate what hexagons get in and out of the screen and show/hide them accordingly. This greatly improved the performance earlier in the project, using 2.1 with DisplayObjectContainers, so I assumed that stops pixi from accessing them when rendering.

Now, setting alpha and etc to 0 wouldnt be slower, or that also indirectly disables the object? The problem is that this needs to be able to handle prety large maps (and that is why I wanted to try to use the particle manager to improve performance) and if that makes the object render, even if empty, probably would end up slower than my current method, no?

**Comment by englercj** [comment]
So the big difference between Container and ParticleContainer is on WebGL.

Container iterates children, updates transforms, then renders each child.

ParticleContainer doesn't do any of that. It uploads non-changing data statically to the GPU then dynamically updates the properties you specify, and just draws everything via a shader. That is why it is so much faster, is because almost all the work is done on the GPU and not in JS on the CPU.

It also means there is no such thing as "skipping" a child like you can do in Container with `visible`. The only way to "skip" it is to remove it. But, if you don't have a ton of hidden sprites, maybe it is OK for the shader to run on them and just not draw anything which is why I suggested `alpha = 0`.

I suggest playing with it, seeing if alpha = 0 meets your needs and if not then trying to remove the child. If that still seems to have too much overhead then your case is probably too dynamic to get benefits from ParticleContainer and you can just use a normal Container.

**Comment by manelis** [comment]
I have checked and what I needed to change for something that is not certain that will be better is not worth the effort right now, specially that would make it harder to add new sprites, but will be something to try if the performance ends up being a even bigger problem in the future.

Thank you (and any other developers) again for the help and for a great framework that is making my life easier right now :)
