### ISSUE TITLE
e.data.getLocalPosition() weird behaviour

### ISSUE THREAD

**Issue by wojciak** [GoodBoyDigital/pixi.js#1734]
Hi,

Lets say that I have a sprite at [0,0], when my mouse cursor is 100px on the right from the sprite then e.data.getLocalPosition(sprite) should return [100,0]. Instead it returns [100,~26]

Is this the expected behaviour? (Pixi 3)

**Comment by wojciak** [comment]
I think I've found it:

In: https://github.com/GoodBoyDigital/pixi.js/blob/master/src/interaction/InteractionData.js

Changing:
point.x = a11 * id * global.x + -a01 * id * **global.y** + (a12 * a01 - a02 * a11) * id;
point.y = a00 * id * global.y + -a10 * id * **global.x** + (-a12 * a00 + a02 * a10) * id;

to:
point.x = a11 * id * global.x + -a01 * id * **global.x** + (a12 * a01 - a02 * a11) * id;
point.y = a00 * id * global.y + -a10 * id * **global.y** + (-a12 * a00 + a02 * a10) * id;

Seems to fix the issue ;]

**Comment by englercj** [comment]
merged
