### ISSUE TITLE
[v3] BlurX/Y make alpha not working

### ISSUE THREAD

**Issue by Danetag** [GoodBoyDigital/pixi.js#1742]
Yo!

I've been trying to use the blurFilter for 2 days. I managed to use BlurX/Y Filter instead of the new one, which is not working correctly yet. 

Anyway, the blur is working. But if I try to play with the opacity of its parent's container, the alpha doesn't work as long as the container contains a child with a blurFitler applied. 

What's going on?

**Comment by englercj** [comment]
Do you happen to have a running example we can take a look at?

**Comment by Danetag** [comment]
In a class extending PIXI.Sprite:

``
this.spriteBG = new PIXI.Sprite(PIXI.utils.TextureCache[this.options.id]);
this.spriteBG.cacheAsBitmap = true;
this.addChild(this.spriteBG);

// Blur
this.spriteBGBlured = new PIXI.Sprite(PIXI.utils.TextureCache[this.options.id]);

var blurX = new PIXI.filters.BlurXFilter();
var blurY = new PIXI.filters.BlurYFilter();

blurX.blur = this.BLUR_VALUE;
blurX.passes = this.BLUR_PASSES;
blurY.blur =  this.BLUR_VALUE;
blurY.passes = this.BLUR_PASSES;

this.spriteBGBlured.filters = [blurX, blurY];
			
this.addChild(this.spriteBGBlured);
``

Then, if I play with the alpha, there's no effect. I think it comes from the shader of the blurFilter which overrides the alpha of the container

``
this.alpha = 0.2; //not working
``

**Comment by englercj** [comment]
We reverted back to the old blur filter that uses X/Y in v3.0.3. Hopefully that clears this up, sorry about that.
