### ISSUE TITLE
Error when calling CanvasRenderer.destroy

### ISSUE THREAD

**Issue by jeremypetrequin** [GoodBoyDigital/pixi.js#1744]
Hello,

I think there could be an issue with the CanvasRenderer destroy method, it throw the error 
````
Uncaught TypeError: this.maskManager.destroy is not a function
````
At line : https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/renderers/canvas/CanvasRenderer.js#L189

The method destroy() doesn't exist in the CanvasMaskManager. 
The WebglRenderer doesn't call this.maskManager.destroy() in her destroy method, maybe just do the same if the method is not usefull?

**Comment by englercj** [comment]
WebGL totally calls destroy for the mask manager:

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/renderers/webgl/WebGLRenderer.js#L476

There should be a stub of destroy in CanvasMaskManager.

**Comment by jeremypetrequin** [comment]
yes totally missed that line in the WebGL renderer, sorry :) !

**Comment by englercj** [comment]
Will go out with the next release (v3.0.4)
