### ISSUE TITLE
Int colors in PIXI.Text does not work

### ISSUE THREAD

**Issue by martende** [GoodBoyDigital/pixi.js#1745]
v3.0 pixi code

    var sScore = new PIXI.Text(score,{font: '30px _sans',fill:0xff0000});

produces black text, but string "#f00" works. 

And docu says that fill can be Number

@param [style.fill='black'] {String|Number} A canvas fillstyle that will be used on the text e.g 'red', '#00FF00'

Code or docu contains error.

**Comment by englercj** [comment]
Definitely should accept a number, I'll be sure to look into this!
