### ISSUE TITLE
Texture.scaleMode not doing anything

### ISSUE THREAD

**Issue by Metamist** [GoodBoyDigital/pixi.js#1747]
When doing
```javascript
var tex = PIXI.Texture.fromImage("images/terrain.png");
tex.scaleMode = PIXI.SCALE_MODES.NEAREST;
```
Nothing happens, however, if you were to modify the baseTexture's scaleMode instead, it works fine.
```javascript
tex.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;
```

Looking through the pixi.js code, the updateTexture function of the WebGLRenderer is what actually uses the scaleMode variable, but the texture passed into the updateTexture function is the baseTexture, not the texture I defined.
Is this a bug or is this how it's intended to work?

**Comment by englercj** [comment]
`Texture` doesn't have a `scaleMode` property, `BaseTexture` does ;)

**Comment by Metamist** [comment]
Ah, right, thanks. When searching around about nearest neighbor scaling, all I could fine was "use scaleMode on the texture or PIXI.SCALE_MODES.DEFAULT" So I assumed it would be on the texture and not BaseTexture.
