### ISSUE TITLE
Support for Text Kerning/Letterspacing

### ISSUE THREAD

**Issue by vanillabass** [GoodBoyDigital/pixi.js#1748]
This would be great =)

**Comment by englercj** [comment]
Pretty sure we do, what isn't working for you?

**Comment by vanillabass** [comment]
Can't seem to adjust the space between letters to make spacing tighter.

**Comment by berezmax** [comment]
+ keep up 
I would do something like splitText (https://greensock.com/SplitText) But for this you need to know the parameters of fonts.

**Comment by englercj** [comment]
Are you using abitmap text or normal text object?

**Comment by vanillabass** [comment]
Normal text object

**Comment by englercj** [comment]
Normal text is just text drawn to a native canvas element, aside from the normal kerning of the font used you can't change the letter spacing:

http://stackoverflow.com/questions/8952909/letter-spacing-in-canvas-element

You can do this in bitmapfonts though.

**Comment by Izaias** [comment]
Is it too late to share a workaround I had to come up with for a project http://codepen.io/Izaias/pen/ZbbLOJ
