### ISSUE TITLE
TilingSprite incorrect scaling in 3.02

### ISSUE THREAD

**Issue by weepy** [GoodBoyDigital/pixi.js#1751]
Heya, I noticed that the tiling sprite doesn't seem to quite correctly rendered. It appears to repeat 1px too early.

Here's a test : https://jsfiddle.net/ya9b73qk/

I noticed that if you set tiles.scale to be (1+size)/size it's more correct, but of course you get some pretty bad aliasing then ... 

J

**Comment by englercj** [comment]
Duplicate of #1683?

**Comment by weepy** [comment]
I suspect its similar underlying but has different symptoms.

**Comment by englercj** [comment]
Closing, fixed this with #1683!
