### ISSUE TITLE
Unable to set Texture scalemode when using loader [V3]

### ISSUE THREAD

**Issue by naranjamecanica** [GoodBoyDigital/pixi.js#1757]
The textureParse middleware of the resource automatically creates an BaseTexture object.

If I later use 

    PIXI.Sprite.fromImage(file, null, PIXI.SCALE_MODES.NEAREST)

The texture on the sprite does not have nearest applied, bet the default one.

Related to: #1724

**Comment by englercj** [comment]
Correct, that is the drawback of using the convience functions `.fromImage()` you lose control of the underlying objects.

But you can just change the scale mode at any time:

```js
var spr = PIXI.Sprite.fromImage(file);
spr.texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;
```

Or just make sure to update the base texture when it is loaded:

```js
PIXI.loader.add('image', 'derp.png').load(function (loader, resources) {
    // now anything using this base texture will be scaled correctly.
    resources.image.texture.baseTexture.scaleMode = PIXI.SCALE_MODES.NEAREST;
});
```

**Comment by naranjamecanica** [comment]
Ah, ok, didn't now that, give that a try :+1: 

Would it be an idea to give options to the loader for the middleware?

**Comment by englercj** [comment]
Yes it might make sense, but right now there is no way to pass options to a pixi middleware. The loader uses standard middleware style (`.use(middleware(options))`) but PIXI calls the `.use()` necessary to add all the middleware automatically for you, and there is no way to hook into it.

If we add options to the texture middleware the only way to pass them in would be to create your own loader instance based off the base `resource-loader` class and setup middleware yourself. If you can think of an elegant way to pass the options into `PIXI.Loader` having people make a custom pixi loader for options is an OK compromise. Maybe an object where the key is the middleware name and the value is the options to pass in? I'd be willing to discuss a PR for that.

**Comment by naranjamecanica** [comment]
Would give some extra benefits in using the standard loader. Right now the updating of the texture on a later time works perfectly. I'll give it a shot when I have more time on my hands in a couple weeks. Thanks.

**Comment by englercj** [comment]
Anytime!
