### ISSUE TITLE
videoTexture err

### ISSUE THREAD

**Issue by qlogcn** [GoodBoyDigital/pixi.js#1758]
Uncaught TypeError: Cannot read property 'hasLoaded' of undefined

**Comment by saschagehlich** [comment]
Please post some example code to reproduce this issue

**Comment by englercj** [comment]
Please be sure to read our contributing guide, there is not enough information here for us to act on.

https://github.com/GoodBoyDigital/pixi.js/blob/master/CONTRIBUTING.md

**Comment by qlogcn** [comment]
Thank you for your help.
However, this can only hear sound.
No image

err: Uncaught TypeError: Cannot read property 'hasLoaded' of undefined


<!DOCTYPE html>
<html>
<head>
    <title>Video</title>
    <meta charset="utf-8"/>
    <style type="text/css"> body{background:#ddd;padding:0; margin:0;overflow-y: hidden;}</style>
</head>
<body >
    <script type="text/javascript" src='pixi.v3.min.js'></script>
  
<script type="text/javascript">
    var renderer = new PIXI.WebGLRenderer(800, 600);

    document.body.appendChild(renderer.view);

    var stage = new PIXI.Container();

    var texture = PIXI.VideoBaseTexture.fromUrl('testVideo.mp4');

    // var texture = PIXI.Texture.fromImage("logo.png");

    var bunny = new PIXI.Sprite(texture);

    bunny.position.x = 0;
    bunny.position.y = 0;

    bunny.width = 400;
    bunny.height = 300;
  
    stage.addChild(bunny);

    requestAnimationFrame(animate);
    function animate() {
        renderer.render(stage);
        requestAnimationFrame(animate);
    }
</script>
</body>

</html>

**Comment by englercj** [comment]
That is because you are trying to pass a base texture into a sprite, which doesn't work. A `Texture` is created from a `BaseTexture` and a `Sprite` is created from a `Texture`. Either of these will work instead:

```js
var texture = PIXI.Texture.fromVideoUrl('testVideo.mp4');

// OR:

var baseTexture = PIXI.VideoBaseTexture.fromUrl('testVideo.mp4');
var texture = new PIXI.Texture(baseTexture);
```

**Comment by qlogcn** [comment]
thank you very much. ^_^

**Comment by qlogcn** [comment]
I suggest increasing the texture of checks to prevent assignment errors.
The termination of the program
For example:
if (! (this.texture instanceof PIXI.Texture)) {
this.texture = PIXI.Texture.emptyTexture;
throw new Error ('. Pixi.js Error This is not the right type of texture');
}

**Comment by qlogcn** [comment]
Wrong answer.It should be.

if (! (this.texture instanceof PIXI.Texture)) {
this.texture = PIXI.Texture.emptyTexture;
console.warn ('. Pixi.js warn  This is not the right type of texture');
}
