### ISSUE TITLE
When can we use filter in canvas with V3+?

### ISSUE THREAD

**Issue by zhkuang** [GoodBoyDigital/pixi.js#1764]
When can we use filter in canvas with V3+?

**Comment by photonstorm** [comment]
Filters are essentially just shaders. Shaders are for WebGL only. Or did you mean something else?

**Comment by englercj** [comment]
If the question is when will filters work on canvas, the answer is unfortunately never. Specifically for the reason that @photonstorm just pointed out. Shader are a WebGL feature :(

Sorry!

**Comment by zhkuang** [comment]
@englercj   I use a method to implement, but not sure if there are any potential problems.

// work in canvas model
function getGraySprite(sprite) {
	
	var canvas = document.createElement('canvas');
	var image = sprite.texture.baseTexture.source;

	canvas.width = image.width;
	canvas.height = image.height;

	if (canvas.getContext) {

		var context = canvas.getContext("2d");
		context.drawImage(image, 0, 0);
		var canvasData = context.getImageData(0, 0, canvas.width, canvas.height);

		for (var x = 0; x < canvasData.width; x++) {
			for (var y = 0; y < canvasData.height; y++) {

				// Index of the pixel in the array
				var idx = (x + y * canvasData.width) * 4;
				var r = canvasData.data[idx + 0];
				var g = canvasData.data[idx + 1];
				var b = canvasData.data[idx + 2];
				var a = canvasData.data[idx + 3];

				if (a == 0) {
					continue;
				}

				var gray = .299 * r + .587 * g + .114 * b;

				canvasData.data[idx + 0] = gray; // Red channel
				canvasData.data[idx + 1] = gray; // Green channel
				canvasData.data[idx + 2] = gray; // Blue channel
				canvasData.data[idx + 3] = a; // Alpha channel
			}
		}
		context.putImageData(canvasData, 0, 0);

		var tempTexture = new PIXI.Texture.fromCanvas(canvas);
		var sprite = new PIXI.Sprite(tempTexture);
		return sprite;
	}
}

**Comment by englercj** [comment]
I'm glad that works for your case but in general pixel manipulate on the CPU is just *way* too slow. We will not able to do much with filters in canvas unfortunately. You will have to polyfill where your app needs it and find a solution that is performant enough for your cases.
