### ISSUE TITLE
Unable to load spritesheet assets by string name using Sprite.fromFrame

### ISSUE THREAD

**Issue by patrickfabrizius** [GoodBoyDigital/pixi.js#1767]
Hi,
First of all, thanks for all the great work you guys put down in PIXI - love it!

I have tried hard to find updated docs for my problem and even looked around a fair bit in the source files, to no avail. When trying to create a sprite from a spritesheet using String.fromName('bqueen') i get the following error: 

Uncaught Error: The frameId "bqueen" does not exist in the texture cache (Sprite.js:545)

I have tried using the (official) spritesheet example on http://www.goodboydigital.com/pixijs/examples/2/ as a reference, which loads spritesheet frames by their string name, however the demo is using an outdated version of PIXI so everything looks quite different. 

If i output the contents of the texturecache in the console, it looks like this from the demo: 

![pixi-spritesheet-demo-console](https://cloud.githubusercontent.com/assets/6759985/7535676/e291d8a4-f587-11e4-903a-00975d60ded1.png)

And when doing the same in my application it looks like this: 

![pixi-spritesheet-mine-console](https://cloud.githubusercontent.com/assets/6759985/7535675/deebf55e-f587-11e4-84fc-fad5b7ed9065.png)

If i use Sprite.fromFrame(0) instead, the sprite is loaded. Given that the contents of the TextureCache object looks different it seems that something has changed in version 3. 
The format of my JSON file is identical in syntax to the one in the demo, except for the "meta" part (was created with http://www.leshylabs.com/apps/sstool/ , i had to add the element "image" manually. But since it works using integer reference, it seems unlikely the problem is with my JSON.

**Comment by englercj** [comment]
Usually the integer keys come if you export using the "JSON Array" format in Texture packer instead of the "JSON Hash" format. That is likely what is happening here.

Can you share the json file you are loading, or even better can you give me a running example that I can debug?

**Comment by patrickfabrizius** [comment]
Oh, you are corrent - regenerating the spritesheet in "JSON hash" instead works fine! Seems the JSON files wasn't identical after all, sorry about that .. 

Thanks! :)

**Comment by englercj** [comment]
Np! :)
