### ISSUE TITLE
Script error in IE9

### ISSUE THREAD

**Issue by Manu33** [GoodBoyDigital/pixi.js#1771]
Hi all,

Simple script 

    var renderer = new PIXI.CanvasRenderer(700, 550);

give me a lot of error repeating :

SCRIPT16389: Erreur non spécifiée. (unspecified error)
pixi_test.html, Ligne 1 Caractère 1

Also, i cannot make my game works on IE9 with the new pixi v3 version...

Another code : 

    var renderer = new PIXI.WebGLRenderer(700, 550,{transparent:true});
    var stage = new PIXI.Container();
    $(renderer.view).appendTo("body");

Give me :

SCRIPT5009: « ArrayBuffer » est indéfini (is not defined)
pixi_test.html, Ligne 12 Caractère 1

Any idea ?

**Comment by englercj** [comment]
IE9 doesn't support WebGL, so creating a WebGLRenderer will never work there. However, We have tested the canvas renderer on IE9 quite a bit, and have even shipped a thing or two.

Can you show me a running example of something that breaks for you? Everything I have runs fine on IE9 (using canvas).

**Comment by Manu33** [comment]
I have trying severals things...but i have always some problems. Now problem seems to come from the loader. Theses bugs come only on IE9 and not other IE, chrome, firefox safari or mobile device

    var load0 = PIXI.loader;
    load0.add('essai',"essai.json");
    load0.once('complete',onas0);
    load0.load();
    
    function onas0()
    {
	   var mov=[];
	   for (var j=0;j<8;j++)
		mov.push(PIXI.Texture.fromFrame(""+j));

The essai.json file

    {"frames": {
    "0":
    {
	"frame": {"x":0,"y":0,"w":37,"h":41},
	"rotated": false,
	"trimmed": false,
	"spriteSourceSize": {"x":0,"y":0,"w":37,"h":41},
	"sourceSize": {"w":37,"h":41},
	"pivot": {"x":0.5,"y":0.5}
    },
    "1":
    ...


Give error : SCRIPT5022: The frameId "0" does not exist in the texture cache

**Comment by englercj** [comment]
Are you 100% sure you are using v3.0.3? There were some IE9 bugs in the loader fixed in that version.

**Comment by Manu33** [comment]
I have tried with pixi.min  and pixi.js version 3.0.3 : 

    Journal : Pixi.js 3.0.3 - Canvas - http://www.pixijs.com/ 
    Journal : la 
    Journal : ici 
    SCRIPT5022: The frameId "0" does not exist in the texture cache 
    pixi_test.html, Ligne 548 Caractère 3


On another script i have tested on IE9, it seems the complete event is never fired. I think there's severals problems with IE9 and pixi 3, with pixi 2 i haven't these problem with the same script (adapted to pixi 2)

**Comment by englercj** [comment]
Can you give me a running example so I can debug it?

**Comment by englercj** [comment]
This should be working in latest versions of pixi, if not please opena  new issue with a running test case for debugging.

**Comment by Manu33** [comment]
Hi, i’m sorry because i’m very busy in this time, i try quickly 3.0.5 and YES ! This works now :-)

Thank you
