### ISSUE TITLE
Pixi.js v3 Documentation

### ISSUE THREAD

**Issue by GoodBoyDigital** [GoodBoyDigital/pixi.js#1774]
Hello Pixi Pushers!

It has come to our attention that the Pixi v3 docs could do with a serious bit of love. Both in terms of skinning and ensuring that they are typo free and all 100% correct. 

We will get round to it eventually but we (me and @englercj ) are both very busy at the moment working on cool new features. We would absolutely love it if any of you keen bean Pixi heads out there would like to help us out with this task! 

Also please feel free to drop any suggestions on how you think the v3 docs could be improved here too. 

Cheers all!

**Comment by aholla** [comment]
Hey guys, I just wanted to chip in and add that personally I hate the new Template/DocStrap thing. 

The old docs pages was far more productive, I can open the page and can almost see all the classes, I could also hit "ctrl + f" and type to find my class. Then with the class selected I can see a nice list on all the public methods and click if i need to know more. I can click to view the source etc etc.

The new system requires clicking a button, and then scrolling up and down in a tiny drop down looking for somethign that might be what im looking for. I select it and the page reloaded, I have to click the drop down again and scroll through the list again if it was not the correct item. Then when it comes to viewing the content I have to scroll up and down the page looking for all the methods, there is no source. It is horrible!

But you probably know this. Please go back to the old system :)

p.s. Looking at the docs for createJS, they're using the old system you were but with some nice styling: http://createjs.com/Docs/EaselJS/classes/.

**Comment by JiDW** [comment]
Could not get a look at it earlier, while I agree with aholla on the current docs style, instead of going back to the old format, we could style the new one to our needs. I'll make a try on sunday.

**Comment by GoodBoyDigital** [comment]
Totally agree @aholla..
@JiDW if you could, that would make you my hero :+1:

**Comment by englercj** [comment]
@aholla Yeah the old template/theme was a lot better, we definitely agree. Just to be clear though we will not be reverting back to YUIDoc, we just need to make a template/theme for jsdoc that makes everyone happy :)

One we found recently that may be a good starting point is [jaguarjs-jsdoc][0] ([demo][1]).

[0]: https://github.com/davidshimjs/jaguarjs-jsdoc
[1]: http://davidshimjs.github.io/jaguarjs/doc/

**Comment by aholla** [comment]
Yeah that jaguar theme is much better, if you could turn off the auto-scrolling/Jumping of the navigation bar when you select an item I think it would do :)

**Comment by englercj** [comment]
Here are some that look nice as well (not a jsdoc themes, but good doc inspiration):

http://typedoc.io/api/
https://mandrillapp.com/api/docs/
https://docs.angularjs.org/api

**Comment by aholla** [comment]
I really like the angular one, it's nice and smimple. Not sure about the others.

**Comment by JiDW** [comment]
pull request created to change to jaguar.js. 

There isn't a lot of theme for jsdoc, it seems to be the best available. I think we should use jaguar.js for a couple of days and report issues or ideas here.

**Comment by englercj** [comment]
Merged! http://pixijs.github.io/docs/

**Comment by JiDW** [comment]
I've just find out that the new doc doesn't list the interactive property under PIXI.DisplayObject and its possible interactive events like tap, click, etc.

They are not default property of DisplayObject but it makes the documentation useless if you want to understand how to deal with events.

**Comment by englercj** [comment]
Interactive target is missing all those docs:

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/interaction/interactiveTarget.js

**Comment by englercj** [comment]
Closing this as the new doc template seems to be awesome!
