### ISSUE TITLE
Pixi 3 loader won't load json from a data URI

### ISSUE THREAD

**Issue by martin-stone** [GoodBoyDigital/pixi.js#1781]
In Pixi 2 we could load json spritesheets from a data URI:

https://jsfiddle.net/oy8rpdvr/ (draws a red square from a spritesheet)

In Pixi 3 trying to do the same... 

https://jsfiddle.net/xah346ps/1/

... results in ... 

> Uncaught Error: The frameId "Symbol1" does not exist in the texture cache

Is there any intention of reinstating this functionality?

**Comment by englercj** [comment]
Data urls should still work fine in pixi 3, this is a bug and I will look into it as soon as I have some time.

Thanks for the repro cases!

**Comment by englercj** [comment]
This has been fixed in resource-loader v1.6.0, and pixi has been bumped to use that version.

The next pixi release will include this fix (v3.0.6)
