### ISSUE TITLE
Bind function not defined in PhantomJS

### ISSUE THREAD

**Issue by martin-stone** [GoodBoyDigital/pixi.js#1785]
We have some automated tests for our game which we run with grunt-contrib-jasmine. This uses PhantomJS 1.9, which doesn't support Function.prototype.bind(). 

I've created a little Grunt project that exhibits the problem. (Drop a pixi.js file alongside the other files if you want to try it out):

https://gist.github.com/martin-stone/cf99855f4a61f491dbf4

When run, we get a failure due to "this._loadResource.bind(this)" (bind is undefined).

If we paste in the Function.prototype.bind polyfill from MDN at the top of pixi.js, it starts working.

Could PIXI include a polyfill for this?

**Comment by englercj** [comment]
We could, the reason we don't right now is because all of our supported browsers implement the necessary functionality:

http://kangax.github.io/compat-table/es5/#Function.prototype.bind

Feel free to put in a PR to add it to [our packaged polyfills](https://github.com/GoodBoyDigital/pixi.js/tree/master/src/polyfill).

**Comment by wojciak** [comment]
I use this https://www.npmjs.com/package/polyfill-function-prototype-bind and add IT to karma files, afaik phantomjs is the only browser that doesn't support bind

**Comment by martin-stone** [comment]
Yes, on reflection it seems wrong to pollute Pixi with a polyfill for this. In fact, grunt-contrib-jasmine has a polyfill already, but for some reason it isn't in place when the offending line is executed. We'll add a workaround to our code.

**Comment by englercj** [comment]
Closing then since this seems decided.
