### ISSUE TITLE
Anti-aliasing on iPad 2

### ISSUE THREAD

**Issue by jwdunn1** [GoodBoyDigital/pixi.js#1786]
Using iPad2, visit http://jsfiddle.net/intrinsica/vf062L6c/
Text is rendered almost unreadable.
Graphics rectangle appears with "cross-hair" artifacts on corners and at intersections with other rects.
This issue was introduced with PIXI v3 and is related to anti-aliasing.
Screen shot from iPad2 attached...
![textrectissue](https://cloud.githubusercontent.com/assets/4262131/7606165/454d8af2-f90b-11e4-8f78-69ceb2cb1902.PNG)

**Comment by GoodBoyDigital** [comment]
Ah yes! This is because ios devices do not support Antialiasing natively. So FXAA is being used instead.
If you add an object to behind the text then it does improve. http://jsfiddle.net/x54kahqp/
But if the quality is still not good enough I would recommend removing the antialiasing for ipad.

**Comment by jwdunn1** [comment]
Thanks for shedding light on this. I didn't quite understand all of this from the release notes. Now it makes sense. Looks like I'll have to detect the device and switch accordingly.
