### ISSUE TITLE
Bower browserify problem version 3.x

### ISSUE THREAD

**Issue by Barnzy** [GoodBoyDigital/pixi.js#1798]
Hi,

Recently upgraded my app to use version 3.x of Pixi from version 2.x.I use Bower to manage my client side dependencies and installed the latest version of Pixi on Bower (3.0.5).

I also use a [debowerify](https://github.com/eugeneware/debowerify) transform during my Grunt browserify step to grab all Bower packages and build them through browserify. It hits a stumbling block in pixi/bin:

```javascript
Error: Cannot find module './polyfill' from 'pixi/bin'
``` 

Having a look, it appears to be the first import line in bin/pixi.js. Line 4:

```javascript
require('./polyfill');
``` 

Assuming it will have the same problem with all the other imports as it's supposed to be looking in src/ for those imports. However, my build process has no idea of where to look for these and assumes the imports will be relative to where they are being imported. Your Gulp build on the other hand, does know where to look so.

So, I went into my bower_components folder and ran npm install, followed by gulp build and it complained that the gulp/tasks folder doesn't exist and it was correct. Turns out bower install didn't include any of the Gulp tasks.

Is my only solution to clone the Pixi Git repo and manage it manually as opposed to Bower for now?

Ultimately it would be awesome if the src inside Bower came pre-packaged (built) or was build-able (without any setup), through a vanilla Grunt browserify task.

**Comment by Barnzy** [comment]
Having cloned the Pixi repo and completed a Gulp build, it appears to have produced the same files in bin with import still being a problem.

Looks like I will have to modify my build in someway to look inside src folder for the import statements. Unless I'm going about this the wrong way.

**Comment by Barnzy** [comment]
Ignore my ramblings. Found the npm pixi.js location now. :-)

**Comment by englercj** [comment]
Just so you know, the reason this was happening is because you were trying to `require()` the built output. Don't do that.

If you are using browserify, you should `require()` the `src/index.js` file because that is the [main entry point](https://github.com/GoodBoyDigital/pixi.js/blob/master/package.json#L10). Otherwise you will try to run transforms over our built file and that will not work.
