### ISSUE TITLE
NormalMapFilter error in PIXI 3.0

### ISSUE THREAD

**Issue by jagi** [GoodBoyDigital/pixi.js#1799]
Hi I've tried using NormalMap filter but I get following errors in the console:

```
Pixi.js Error: Could not initialize shader.
gl.VALIDATE_STATUS false
gl.getError() 0
Pixi.js Warning: gl.getProgramInfoLog() Varyings with the same name but different type, or statically used varyings in fragment shader are not declared in vertex shader: vColor
WebGL: INVALID_VALUE: getUniformLocation: no object or object deleted
WebGL: INVALID_VALUE: getAttribLocation: no object or object deleted
WebGL: INVALID_OPERATION: drawElements: no valid shader program in use
WebGL: too many errors, no more errors will be reported to the console for this context.
```

I thought that the problem is maybe on my side, so I've modified your [example](http://www.goodboydigital.com/pixijs/examples/20/) to work with PIXI 3.0 and it throws the same errors.

Here is the reproduction of your example that should work with PIXI 3.0 https://github.com/jagi/pixijs-normalmap-error

**Comment by englercj** [comment]
Sorry about that, got it fixed in the latest dev. Will go out with the next patch.

**Comment by jagi** [comment]
Great! :) No problem, you are doing great job! Thanks!
When can we expect the patch to be published?

**Comment by englercj** [comment]
I have been trying to do a patch a week, and I *just* did one. So probably next weekend, though I can do it sooner if it is critical.

**Comment by jagi** [comment]
No no I will just wait :) and will focus on different things right now. Thanks!
