### ISSUE TITLE
cacheAsBitmap alpha applied twice?

### ISSUE THREAD

**Issue by FletcherD** [GoodBoyDigital/pixi.js#1800]
I set cacheAsBitmap = true on some Graphics objects that were rendered with 0.5 alpha in order to improve the rendering speed. After doing this I saw that the objects were rendered a lot lighter... like they had been cached to a bitmap with 0.5 alpha, then that bitmap rendered with 0.5 alpha again. By setting the alpha to 0.7 (~sqrt 0.5), I was able to make the object look like it did before.

**Comment by englercj** [comment]
Does this happen only in a particular renderer, or does it happen in both?

Can you create a jsfiddle reproduction case?

**Comment by FletcherD** [comment]
I've only tried this in the WebGL renderer.
I was able to create a reproduction case, it uses sprites but the result is the same: https://jsfiddle.net/fletcher00/cd6jahh8/5/

The two sprites are exactly the same, with alpha 0.5; after one second, cacheAsBitmap it turned on for the second sprite, and it gets dimmer.

The reason for the 1s timeout is that I just noticed if an object is set to cacheAsBitmap=true the same frame it is created, before it has been rendered, it will sometimes be cached as totally blank instead. I'll ask about that separately in the forum.

**Comment by englercj** [comment]
Thanks for the test case, I will look at this soon.

As for this:

> The reason for the 1s timeout is that I just noticed if an object is set to cacheAsBitmap=true the same frame it is created, before it has been rendered, it will sometimes be cached as totally blank instead. I'll ask about that separately in the forum.

That is because you are running cacheAsBitmap before the texture has loaded, so it caches a blank image because that is what it is. You need the image to load since cacheAsBitmap just caches what is there.

**Comment by FletcherD** [comment]
You're right! I didn't even think to make sure the loader was actually done loading the textures before continuing, and that solved it. Thanks for the quick reply. https://jsfiddle.net/cd6jahh8/9/
