### ISSUE TITLE
Masking with ParticleContainer not working

### ISSUE THREAD

**Issue by zeus123** [GoodBoyDigital/pixi.js#1801]
I want to apply masking on ParticleContainer or sprites inside ParticleContainer but it seems none of two works.
can we use particle container and masking together?

**Comment by englercj** [comment]
You can't that is the trade off of using the particle container:

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/particles/ParticleContainer.js#L4-L8

```
/**
 * The ParticleContainer class is a really fast version of the Container built solely for speed,
 * so use when you need a lot of sprites or particles. The tradeoff of the ParticleContainer is that advanced
 * functionality will not work. ParticleContainer implements only the basic object transform (position, scale, rotation).
 * Any other functionality like tinting, masking, etc will not work on sprites in this batch.
```
