### ISSUE TITLE
resolution not working on mobile Firefox and Android Browser

### ISSUE THREAD

**Issue by PianoScore** [GoodBoyDigital/pixi.js#1808]
I've posted  this problem in forum
http://www.html5gamedevs.com/topic/14527-pixeldeviceratio-support/

metatag
````metatag
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
````

javascript
````javascript
           //detect devicePixelRatio
            var dpr = window.devicePixelRatio || 1;
           
           //detect device screen width ( using jQuery)
            var renderer = PIXI.autoDetectRenderer($(window).width(),1080*$(window).width()/1920,{backgroundColor:0xFFFFFF,resolution:dpr});

            $("#pixitest").append(t.renderer.view);

           var container=new PIXI.Container();
           //fit container to screen width
            container.scale.x=t.container.scale.y=$(window).width()/1920

            PIXI.loader
                .add('pianobody','./img/pianobody.png') /*This image size is 1920 x 1080 */
                .load(function(loader,resources){
                    container.addChild(resources.pianobody.texture);
               animate();
                })                    

function animate(){
     renderer.render(container);
     requestAnimationFrame(animate);
}
````

**Comment by englercj** [comment]
That code didn't run at all, and there were a bunch of things that just made no sense (the height calculation for the renderer, the scale of the container, etc).

So, I cleaned it up a bit to get it rendering properly. Would you mind looking at this jsFiddle and seeing if you still see weird issues and if so I will use this as my test-bed for trying to figure out the problem:

http://jsfiddle.net/5emxydyh/1/

**Comment by PianoScore** [comment]
Thank you.
Your code exactly work.

But what shoud I do to fit container for several device screen width ?

**Comment by englercj** [comment]
You can set the container width/height to the size of the renderer:

```js
container.width = renderer.width;
container.height = renderer.height;
```

**Comment by englercj** [comment]
You can set the container to the size of the renderer:

```js
container.width = renderer.width / renderer.resolution;
container.height = renderer.height / renderer.resolution;
```

**Comment by PianoScore** [comment]
By this way , container size will be fit to renderer width and height.
But In this case , image  is overflowed from screen.
Because canvas size is increased by devicePixelRatio.

http://www.pianoscore.jp/playpiano/sample1.html
````
            var renderer;
            var container;
            function showPianoBody(){
                var dpr = window.devicePixelRatio || 1;
                renderer = PIXI.autoDetectRenderer($(window).width(),$(window).height(),{backgroundColor:0xFFFFFF,resolution:dpr});
                $("#pixitest").append(renderer.view);
                container=new PIXI.Container();   
                
                PIXI.loader
                    .add('pianobody','./img/pianobody.png')
                    .load(function(loader,resources){
                        var pianobody=new PIXI.Sprite(resources.pianobody.texture)
                        container.addChild(pianobody);
                        container.width=renderer.width/renderer.resolution;
                        container.height=renderer.height/renderer.resolution;
                        animate();
                    });
                    
            }
````
way to fit device width but image is poor
http://www.pianoscore.jp/playpiano/sample2.html
````
            var renderer;
            var container;
            function showPianoBody(){
                var dpr = window.devicePixelRatio || 1;
                var devicewidth = $(window).width();
                var deviceheight=1080 * (devicewidth / 1920)
                renderer = PIXI.autoDetectRenderer(devicewidth / dpr, deviceheight/dpr,{backgroundColor:0xFFFFFF,resolution:dpr});
                $("#pixitest").append(renderer.view);
                container=new PIXI.Container();   
                PIXI.loader
                    .add('pianobody','./img/pianobody.png')
                    .load(function(loader,resources){
                        var pianobody=new PIXI.Sprite(resources.pianobody.texture)
                        container.addChild(pianobody);
                        container.width=renderer.width/renderer.resolution;
                        container.height=renderer.height/renderer.resolution;                        
                        animate();
                    });
                    
            }
````

 If I pinch out screen , high quality image showed In the sample1 
I want to show as sample2 and more high quality image.

**Comment by englercj** [comment]
Seems to work in this fiddle:

http://jsfiddle.net/5emxydyh/2/

The image correctly fills the entire viewport regardless of the value I set to `dpr`. I'm not sure what issue you are encountering?

**Comment by PianoScore** [comment]
There is no problem in DPR is 1. 
Problem caused when DPR is larger than 1.

Please see my problem screen shot.
(using chrome device elumation)
![default](https://cloud.githubusercontent.com/assets/11884415/7669290/f4071aba-fca6-11e4-869d-c44afc8a2019.PNG)

**Comment by englercj** [comment]
Of course it does that, because it scales up for the pixel ration. Settings the DPR value higher doesn't make your viewport have more pixels.

When the DPR of a device *actually is* 2 it should look fine.

**Comment by PianoScore** [comment]
So what is best solution do you think?
My purpose is to show this piano as above 2nd screen shot in any devices(PC , iPhone , iPad ,Android tabs etc.)

**Comment by englercj** [comment]
Both my jsfiddle and your "sample1" are working exactly how they should be. The reason you see bleeding is because you are on a device with a DPR of 1, but telling pixi it is 2+. That is why you see bleeding.

It should look fine when using the native DPR of the device it is on.

**Comment by PianoScore** [comment]
OK.Thank you

**Comment by JiDW** [comment]
Hello,

To be able to debug resolution related stuff on a simulated environment you can scale your stage container to fit inside your screen like this : 

```javascript
var ratio = ratio = canvas.width/320; //or whatever your stage scale is. this is for mobile here. it may be 0, depends of your project
var resolution = window.devicePixelRatio;

stage.scale.x = ratio; //fullscreen scale for a mobile game
stage.scale.y = ratio;

if(debug)
{
	stage.scale.y = ratio/resolution;
	stage.scale.x = ratio/resolution;
}
```

Regards.
