### ISSUE TITLE
FrameID does not exist in texture cache?

### ISSUE THREAD

**Issue by Shadowstep33** [GoodBoyDigital/pixi.js#1810]
When I load up the application I am working on in IE 11, I get this error everytime I try to execute this code:

```
construction_ghost = PIXI.Sprite.fromFrame(result);
```

I am using pixi 3.0.2. Everything works as expected in Chrome. Out of curiosity, is there a way I can catch this error and use fromImage instead?

**Comment by englercj** [comment]
This was an issue in the loader that was fixed in later versions (v1.5.5 of loader, v3.0.3 of pixi IIRC).

**Comment by Shadowstep33** [comment]
Good to know, thanks!
