### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by serprex** [GoodBoyDigital/pixi.js#1811]
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/renderers/webgl/shaders/TextureShader.js#L18

new Float32Array should be passed an Array, as is it creates a single array [0] when not polyfilled as Array

**Comment by englercj** [comment]
Oops! Nice catch!

It works since we only assign to this matrix and don't try to access anything, but could definitely cause problems.
