### ISSUE TITLE
Sprite.destroy can sometimes error due to sprite.children being undefined

### ISSUE THREAD

**Issue by khalilravanna** [GoodBoyDigital/pixi.js#1813]
Specific steps to repro I have in my code:

1) Create sprite via `PIXI.Sprite.fromFrame`
2) Call `sprite.destroy()` (`Sprite.prototype.destroy`)
3) This calls `Container.prototype.destroy`
4) Which calls `Container.prototype.removeChildren`
5) Which references `this.children.length` even though `this.children` is `undefined`

Will look a little further to see if it's something specifically to do with `PIXI.Sprite.fromFrame` because I haven't seen this error up until today with my code which calls destroy all over the place.

Edit: It looks like it's nothing to do with `PIXI.Sprite.fromFrame` as that just calls `new Sprite()`. It looks like this could easily resolved by just not calling `Container.prototype.removeChildren` if `!this.children` or escape out of `removeChildren` for the same check. I'll go ahead and open a PR for this now.

**Comment by englercj** [comment]
Hmm, a Container (which Sprite inherits from) should always have a `children` property, unless it had been previously destroyed...

Do you have a repro test case I can look at?

**Comment by khalilravanna** [comment]
> unless it had been previously destroyed

Aha it would make sense that it's an error in my code somewhere :) but I couldn't find any glaring deletion of the children happening on my end in my initial search. I'll have to look into places where I might be calling `destroy` more than once.

That being said, it seems odd that calling `destroy` on a sprite that has already been destroyed would cause an error instead of being a noop.

**Comment by englercj** [comment]
Well destroy clears the internal variables, that's all. It is up to user code to then lose your reference of the sprite. If you call destroy, then keep your reference around not only will GC never clean it up, but you may get errors like this.

**Comment by khalilravanna** [comment]
Ok that's totally valid. Thanks for the quick response!
