### ISSUE TITLE
Mesh not working

### ISSUE THREAD

**Issue by fifobuffers** [GoodBoyDigital/pixi.js#1815]
Not throwing any errors, but not showing the image that is being displaced, older version seem to work, here's a sample using your demo code but tweaked for the new version (Container instead DisplayObjectContainer, requestAnimationFrame instead of requestAnimFrame, Stage as Container instead of Stage): 
I ended up pulling the .js from your demo and it works, but using the latest .js from the site does not show the mesh.
http://staging34.com/pixiTests/demo-sample.html

**Comment by englercj** [comment]
Yes this is a bug in v3.0.5 and was fixed in the latest dev. I will be doing a release today that includes the fixes.

**Comment by englercj** [comment]
Just released 3.0.6, this should be fixed now!
