### ISSUE TITLE
Firefox OS 2.x object from different WebGL context (or older generation of this one) passed as argument

### ISSUE THREAD

**Issue by wojciak** [GoodBoyDigital/pixi.js#1816]
Environment:
FirefoxOS 2.0.x - Firefox Browser
Devices: Mozilla Flame, Alcathel One Touch Fire E (6015x)

Expected result:
After minimizing the browser and then returning to it the textures should render properly.

Actual result:
After minimizing the browser and the returning to it the canvas is black and webgl errors present.

Steps to reproduce:
1. Open any sample with pixijs 3.0.x on the given devices/browser. 
2. Make sure the sample works
3. Minimize the browser
4. Maximize the browser
5. Watch console

```
Error: WebGL: drawElements: no VBO bound to enabled vertex attrib index 0!
Error: WebGL: bindTexture: object from different WebGL context (or older generation of this one) passed as argument
Error: WebGL: drawElements: no VBO bound to enabled vertex attrib index 0! 
Error: WebGL: bindTexture: object from different WebGL context (or older generation of this one) passed as argumen
Error: WebGL: drawElements: no VBO bound to enabled vertex attrib index 0!
```

**Comment by englercj** [comment]
Hmm, very strange. Does this repro on the emulator? (I don't own a device.)

**Comment by wojciak** [comment]
I'll test it and let you know.

2015-05-18 16:33 GMT+02:00 Chad Engler <notifications@github.com>:

**Comment by wojciak** [comment]
Unfortunately this doesn't occur in the simulator

**Comment by wojciak** [comment]
A little update:
1. After reading webgl lostContext / restoreContext docs I'm almost sure that we need to have a new context when resuming, by adding this_.createContext() to the handleContextRestored callback I've managed to move forward a bit.
2. After that in _createContext() we have "canvas.getContext('webgl', contextOptions) || canvas.getContext('experimental-webgl', contextOptions)". This will throw an error always for experimental-webgl implementations, as we can't try do get a "webgl" context after an "experimental-webgl" context was got - this will throw an error. We should probably store the contextType that we're using.
3. After this I'm left with 1 error "Error: WebGL: drawElements: no VBO bound to enabled vertex attrib index 0!" in:

```
// now draw those suckas!
gl.drawElements(gl.TRIANGLES, size * 6, gl.UNSIGNED_SHORT, startIndex * 6 * 2); 
```

**Comment by englercj** [comment]
It was literally your bug that made us not recreate the context on restore:

https://github.com/GoodBoyDigital/pixi.js/issues/1788

Also, the [context-lost-restored tests](https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance/context/context-lost-restored.html) by the Krohnos Group do not recreate context on restore.

**Comment by wojciak** [comment]
Yeah, but the problem was in another place - it was trying to restore a wrong type of context (I'm no expert on webgl, that's why I'm trying to learn from you guys). Nevertheless the issue goes deeper I think as I'm unable to grab the textures after rebuilding the context.

I'll run the tests on the devices and see if they work. If not - it's canvas fallback for the platform for now.

As for the details they explicitly say that no old resources can be Used after the context is restored, and I don't think we're clearing that right now https://www.khronos.org/webgl/wiki/HandlingContextLost#Handling_Lost_Context_in_WebGL

**Comment by englercj** [comment]
> As for the details they explicitly say that no old resources can be Used after the context is restored, and I don't think we're clearing that right now 

There is an issue with this I think since the context Id doesn't change between restores, so the resources likely don't get uploaded again properly. That might be what you are experiencing.

**Comment by wojciak** [comment]
A little update. Got to the point where I recreate the context properly, bump the id etc, but I'm still stuck on 
```
gl.drawElements(this.gl.TRIANGLES, size * 6, this.gl.UNSIGNED_SHORT, startIndex * 6 * 2);
```
that gives 
```
Error: WebGL: drawElements: no VBO bound to enabled vertex attrib index 0!"
```
Is there something I'm missing? I don't want to fallback to the canvas renderer ;]

**Comment by wojciak** [comment]
Dropping this as of:
https://bugzilla.mozilla.org/show_bug.cgi?id=1009553
