### ISSUE TITLE
Native Android browser "invisible" canvas

### ISSUE THREAD

**Issue by wojciak** [GoodBoyDigital/pixi.js#1818]
Hi,

I've noticed that when using a native android browser the canvas in our games becomes invisible (Pixi 3.0.5). I've went to test out the v3 announcement demos and one demo is working which is quite odd for me :)

Examples that reproduce the issue: 
- http://www.goodboydigital.com/pixijs/bloom/
- http://www.goodboydigital.com/pixijs/bunnymark/

An example that works is the alpha mask one (no alpha mask, but the texture rendering seems good):
- http://www.goodboydigital.com/pixijs/masky/ 

When I put the pixi version from bloom or bunny mark into "masky" it stops working also. 

Environment:
Android 4.1.2, 4.2.2, 4.4.2

**Comment by wojciak** [comment]
P.s. The renderer that's being used is "Canvas"

**Comment by wojciak** [comment]
*Bump* 

Tried everything alpha-related and still no joy.

**Comment by englercj** [comment]
I haven't forgotten @wojciak, I just don't do much pixi work during the week. I will get to this when I have the time. Thanks.

**Comment by wojciak** [comment]
Turned out not to be related to latest pixi builds. This was an internal issue on my side. Closing.
