### ISSUE TITLE
How does one make a sequence of images a character animation?

### ISSUE THREAD

**Issue by hassanshaikley** [GoodBoyDigital/pixi.js#1827]
I have a running animation in 4 frames. 

Do I have to constantly addChild and removeChild at the right location? That seems like overkill. Does anyone have any idea?

**Comment by wojciak** [comment]
You use the movieClip object: http://www.goodboydigital.com/pixijs/docs/classes/MovieClip.html
Example: http://www.goodboydigital.com/pixijs/examples/3/

**Comment by hassanshaikley** [comment]
Sweet! Thank you!

By the way I am having some issues with TilingSprite

function Background() {
  var texture = PIXI.Texture.fromImage("cobblestone_ground.png");
  PIXI.TilingSprite.call(this, texture, 300, 100);
  this.position.x = 0;
  this.position.y = 370;
  this.tilePosition.x = 0;
  this.tilePosition.y = 0 ;
  this.viewportX = 0;

};

This isn't repeating! Any idea why?

**Comment by hassanshaikley** [comment]
I am trying to get structure to be glued to cobblestone ground! So that their X values are dependent!

However cobblestone ground just stays in the same place(on the screen, setViewportX doesn't do anythin!)

Do you know why?

Also let me know if asking you all of this is inappropriate!


function Background() {
  var texture = PIXI.Texture.fromImage("cobblestone_ground.png");
  
  PIXI.TilingSprite.call(this, texture, 4000, 100);
  this.position.x = 0;
  this.position.y = 370;
  this.tilePosition.x = 50;
  this.tilePosition.y = 0 ;
  this.viewportX = 1000;
 

  var structure = new PIXI.Sprite(PIXI.Texture.fromImage("spire.png"));
  structure.position.y = -100;
  this.addChild(structure);

};

**Comment by wojciak** [comment]
Please create a separate topic for that, or better yet create a topic at
http://html5gamedevs.com. GH is mostly a bug tracker :)

2015-05-20 12:11 GMT+02:00 Hassan Shaikley <notifications@github.com>:

**Comment by hassanshaikley** [comment]
Got it! Thank you : D
