### ISSUE TITLE
PixiDoc - Difference between Members and Properties.

### ISSUE THREAD

**Issue by FlorianBELLAZOUZ** [GoodBoyDigital/pixi.js#1828]
Hi ! 

What is the difference that you do between members and properties in the documentation ?!

Eg: http://pixijs.github.io/docs/PIXI.Container.html

**Comment by englercj** [comment]
It was listing the properties of the mask member, this was just a typo in the doc comments:

https://github.com/GoodBoyDigital/pixi.js/blob/07e4e26f8fd404524a7ebaa73c210de3d8f2cf25/src/core/display/DisplayObject.js#L225-L226

I have fixed it and will regenerate the docs later.
