### ISSUE TITLE
Can not build using bower [v3]

### ISSUE THREAD

**Issue by naranjamecanica** [GoodBoyDigital/pixi.js#1832]
I'm using bower to get and track the latest dev version. Because the builds in the bin directory are not always up to date I want to build it myself. Right now the gulp/tasks folder of is missing, the utils folder does exist. Is this intentional?

**Comment by englercj** [comment]
Yes, the idea behind the bower/npm packages is that they are distributables. Bundles in `bin` if you want to use those directly, and source in `src` if you want to use browserify.

Really all you should get in that package is `bin`, `src`, and `package.json`. Anything else is something we should filter out. Thanks for reminded me to update that!

**Comment by naranjamecanica** [comment]
Is it possible to have another bower file filter in the dev branch so if install that one, you can actually build it?

**Comment by englercj** [comment]
Including tests scripts, build scripts and other repo data in a registry package is an antipattern. I *really* don't want to do that.

Instead can't you just clone the repo if it is for development? Does bower have something like "npm link" for these cases?

**Comment by drkibitz** [comment]
npm can also install from git, or better yet ... a tarball. github itself provides every commit, tag, and branch as tarball which is a fast install via npm.

**Comment by drkibitz** [comment]
@englercj thanks, totally agree with your "antipattern" comment there.

**Comment by drkibitz** [comment]
@englercj while I'm commenting, I strongly suggest just using the `"files": []` field in package.json rather than `.npmignore` (which IMO is an antipattern :wink:)

**Comment by drkibitz** [comment]
Things to include:
- bin
- src
- README.md
- LICENSE
- package.json

A couple of those may be included by default, can't remember which ATM.

**Comment by englercj** [comment]
> while I'm commenting, I strongly suggest just using the "files": [] field in package.json 

Yeah for some reason in my head I had updated it, but this ticket reminded me that I didn't :P
