### ISSUE TITLE
Blurry text (and images) on v3

### ISSUE THREAD

**Issue by uorbe001** [GoodBoyDigital/pixi.js#1835]
After we updated pixi to v3, we started noticing blurry text and images. I'm trying to find out what is wrong, but I'm having a hard time figuring it out. I wrote this fiddle where I can see obviously blurry text on a retina display and I've been told it is blurry on a lower resolution screen: http://jsfiddle.net/cLgo0b7w/4/

![screen shot 2015-05-21 at 09 50 15](https://cloud.githubusercontent.com/assets/610728/7743901/3462cbd6-ff9f-11e4-8c8f-ddb3e20dd482.png)

Initially I thought the issue was that we are not using the @2x resolution  images, but that shouldn't affect the text, should it? I'm testing it on a retina macbook pro, but I'm pestering other people to look at it on other resolutions to see if it looks decent, and they tell me it is blurry. At this point, I think it must be something we are doing wrong, but I'm unable to see what it is. Any help would be appreciated :grin: 

UPDATE: It just occurred to me to test on different browsers, Chrome, Chrome Cannary and Firefox look pretty much the same as that screenshot I uploaded to me, but Safari looks *differently wrong*:
![screen shot 2015-05-21 at 10 30 39](https://cloud.githubusercontent.com/assets/610728/7744541/942dc43a-ffa4-11e4-99bf-b2338be7c4fd.png)

**Comment by englercj** [comment]
At resolution 1 it seems to be crisp for me, I'll have to look at it ion my retina device to check other resolutions. I'll try to get to it this weekend.

**Comment by JiDW** [comment]
Could you try to use this plugin to check if you have the same issue please ? If yes, I'll know what it is.

https://github.com/JiDW/pixi-cocoontext

(You do not need CocoonJS, don't worry)

**Comment by uorbe001** [comment]
@englercj my `devicePixelRatio` is 2. I also tested on a retina ipad and I get a similar output to the one on OSX's safari. Is there any info I can give you to help debug this? (in our real code we are using the autoDetectRenderer, so it should be using the WebGL renderer, but I used the canvas renderer on this fiddle to try to rule that out as a problem).

@JiDW I'll try that thanks, but I'd rather use the built-in text, as it is not only a problem with the text (images are also affected) and I suspect they are related. (Also, there's a ton of existing code we'd have to change to use cocoontext)

**Comment by JiDW** [comment]
Yes it's just for testing purpose. If cocoontext let you have correct texts, then I'll know that it is because of context.scale. At first I created this plugin because of this issue.

**Comment by JiDW** [comment]
http://jsfiddle.net/3L5ron29/ here it is with the plugin. Do you have the same issue ?

**Comment by uorbe001** [comment]
Yes, I still see the same blurry text on Chrome/Firefox:
![screen shot 2015-05-22 at 10 39 30](https://cloud.githubusercontent.com/assets/610728/7766976/fed21bea-006e-11e5-8449-e8a8c8c6fdc0.png)

And this is on safari:
![screen shot 2015-05-22 at 10 39 34](https://cloud.githubusercontent.com/assets/610728/7766981/0762f93c-006f-11e5-990c-271e7325c822.png)

**Comment by JiDW** [comment]
Ok thanks. Last test : http://jsfiddle.net/3L5ron29/1/

**Comment by uorbe001** [comment]
@JiDW that does look crisp! Do you know what the issue is then?

**Comment by JiDW** [comment]
Yes, The first test didn't work because of a bug in my plugin (not correctly uses renderer resolution).

It is what I suspected. To create a higher text resolution, PIXI create a x1 sized canvas and then call this line : 

```javascript
this.context.scale( this.resolution, this.resolution);
```

It works fine on Chrome desktop because of a superior font engine but from what I understand, on mobile the fonts are rendered in a not scalable way, meaning that PIXI just upscales a bitmap.

What I do in my plugin and that you can recreate in your own app if you don't want to use a plugin is to comment the line I pasted here and take a look at how I multiply every styles by the resolution I want in order to get a correct texture =>

https://github.com/JiDW/pixi-cocoontext/blob/master/src/CocoonText/index.js#L218

**Comment by JiDW** [comment]
Hey, that may be another thing. Following the "bug" in my plugin, I remembered that you have to set PIXI.RESOLUTION too.

Does this fiddle works for you ? 

http://jsfiddle.net/cLgo0b7w/5/

**Comment by uorbe001** [comment]
@JiDW lol, yes it does. I agree with your issue, it makes little sense that they aren't linked. So I guess we just need to set the PIXI.RESOLUTION to fix the issue..

**Comment by JiDW** [comment]
Ok good. so context.scale is a cocoonjs issue only. Always good to verify. Thanks for your testing reports !

**Comment by uorbe001** [comment]
I'm was experiencing some blurriness on text after setting the `PIXI.RESOLUTION` (in our real codebase), but I just found out what's causing it. It turns out we were creating the Renderer before some content on screen, so it ended up with an incorrect resolution. Looks better now, so I'm going to close this issue in favor of #1841. 

thanks for the help!

**Comment by uorbe001** [comment]
[This last fiddle](http://jsfiddle.net/cLgo0b7w/5/) looks nice on retina devices, but I know have a designer crying about his beautiful designs being destroyed with blurriness on non-retina devices.

I've managed to replicate this blurriness on that same fiddle with chrome's "device mode" selecting any device with `window.devicePixelRatio == 1`, but I'm unable to find out what the issue is. This is what it looks like:

![screen shot 2015-06-05 at 10 12 59](https://cloud.githubusercontent.com/assets/610728/8001997/8498c88a-0b6b-11e5-9f8c-26c905f0df3d.png)

Is this normal? Am I missing some other option that we need to set on PIXI?

**Comment by JiDW** [comment]
Did you zoom the last screenshot ? Because it is definitely not a 20px text.

**Comment by uorbe001** [comment]
No, but I took it from a retina device with Chrome's device mode, that might have scaled it up. I have no devices with `devicePixelRatio == 1` to take the screenshot with, but I can ask someone else to do it

**Comment by JiDW** [comment]
Ok I see. The only way to truly test a pixel ratio related bug is on a device with that said pixel ratio. Everything else is emulated and will result in strange behavior.

In your game, can you confirm that your rendered container is not scaled in any ways ? Because that's what people often do to make it fullscreen.

**Comment by uorbe001** [comment]
Here's an unadulterated screenshot from a device with devicePixelRatio=1 (macbook air): 
![screen shot 2015-06-05 at 10 45 09](https://cloud.githubusercontent.com/assets/610728/8002560/34888628-0b70-11e5-9622-d12d72f32e3f.png)
It does look blurry to me, and it is a lot worse with other type fonts (I can write a fiddle with one of the really bad ones).

@JiDW yes, we are not scaling the container at any point, we have some nodes that are being scaled for animations and that sort of things, but neither the container nor most nodes are being scaled. We are creating the canvas/renderer exactly the same way as the fiddle, and just appending it to the document.body.

**Comment by JiDW** [comment]
To me is does not look blurry. Please note that native fonts will be displayed outside of a canvas will be rendered from a SVG-like file and will receive enhancements from the browser and OS to makes it look sharp and clean.

An easy way to enhance your texts could be to render them in a higher resolution and let pixi downscale them. However it means more virtual memory.

Try this fiddle : http://jsfiddle.net/cLgo0b7w/6/

**Comment by uorbe001** [comment]
I made a couple of fiddles with one of the worst font types we are using to test your change on the fiddle, this is without the resolution parameter you passed (on a device with devicePixelRatio == 1): http://jsfiddle.net/cLgo0b7w/8/
![screen shot 2015-06-05 at 11 56 30](https://cloud.githubusercontent.com/assets/610728/8003833/10829b14-0b7b-11e5-9934-e109ff34dac8.png)

This one, has the resolution parameter on the text constructor: http://jsfiddle.net/cLgo0b7w/7/
![screen shot 2015-06-05 at 11 56 17](https://cloud.githubusercontent.com/assets/610728/8003841/1db8a56c-0b7b-11e5-9955-cf28739ea74a.png)

They both look good on a device with devicePixelRatio == 2: 
![screen shot 2015-06-05 at 12 06 34](https://cloud.githubusercontent.com/assets/610728/8003867/598252d2-0b7b-11e5-80ff-9d292eb0ef6c.png)

The version with the resolution parameter seems to be better, but it seems odd that we'd have to pass that parameter, is this how Text is intended to use? (we are also having issues with images being blurry, but it might be a different problem like the browser downscaling the images or something like that)

**Comment by uorbe001** [comment]
I think I just found the problem with our code, we had antialiasing enabled, and some devices were using FXAA antialiasing, which was causing the blurriness. If someone else has this problem, try disabling it.

**Comment by robertpataki** [comment]
@uorbe001 PIXI.RESOLUTION = _this.screenData.resolution; seems to be solving the issue, thanks!

**Comment by yreenchan** [comment]
So，how can i solve this problem? @uorbe001

**Comment by hdennen** [comment]
I realize this is closed now but in case anyone else finds this here's what worked for me. I took the generatedStyle from @JiDW 's comment here: https://github.com/pixijs/pixi.js/issues/1835#issuecomment-104594047 and multiplied the relevant numbers by resolution AND 2. Then I set the scale to (0.5, 0.5) which effectively doubles the density from what I understand. Since WebGL is apparently just scaling bitmaps, this works.

**Comment by pambi** [comment]
@hdennen, Hi can you explain the process in detail? Did you use plugin? What are the relevant numbers? Can you show your code?

**Comment by hdennen** [comment]
@pambi No plugins, it's fairly straight forward. I just overrode the font size, padding, and anything else having to do with sizing in a custom class that extends PixiText. Also added a setter so I could do the doubling if font size changed later. Here's an illustrative gist: https://gist.github.com/hdennen/ab26103f0037b95d4b96308231b4376e

**Comment by pambi** [comment]
@hdennen Thanks :)
