### ISSUE TITLE
processInteractive and undefined displayObject

### ISSUE THREAD

**Issue by YopSolo** [GoodBoyDigital/pixi.js#1838]
Sometime
InteractionManager.prototype.onMouseUp = function (event)
{
    this.mouse.originalEvent = event;
    this.eventData.data = this.mouse;
    this.eventData.stopped = false;

    // Update internal mouse reference
    this.mapPositionToPoint( this.mouse.global, event.clientX, event.clientY);

    this.processInteractive(this.mouse.global, this.renderer._lastObjectRendered, this.processMouseUp, true );
};

can return an undefined displayObject witch lead to an unhandled error in processInteractive

**Comment by englercj** [comment]
Potentially a duplication of #1817?
