### ISSUE TITLE
pausing renderer

### ISSUE THREAD

**Issue by weepy** [GoodBoyDigital/pixi.js#1842]
Heya, I'm running multiple PIXI renderers in my browser, but only have one active at a time. However I noticed that this._tick and the InteractionManager seem to poll even though I'm not calling update. 
Is there a way to pause these ? I'm worried about performance of having many instances on a low power device .

Thanks

**Comment by JiDW** [comment]
Yes you can call .stop()

http://pixijs.github.io/docs/PIXI.ticker.html

**Comment by englercj** [comment]
Closing this, @JiDW nailed it.
