### ISSUE TITLE
WebGlRenderer does not draw multiple lines well.

### ISSUE THREAD

**Issue by chirotaq** [GoodBoyDigital/pixi.js#1843]
Using the webgl renderer to draw multiple lines, results in some parts of the lines being drawn where they are not intended.  This seems similar to the fixed issue #1076 concerning the drawing of circles.

Changing to a canvas renderer will fix the issue, but I would rather use webgl.

Using pixi.js 3.0.6 in chrome. (https://cdn.rawgit.com/GoodBoyDigital/pixi.js/v3.0.6/bin/pixi.js)
https://jsfiddle.net/1hcczsvc/1/

**Comment by englercj** [comment]
What issue are you seeing? When I looked at the jsfiddle the lines were crisp, parallel and separate. Is that not intended?

**Comment by chirotaq** [comment]
![renderer_differences](https://cloud.githubusercontent.com/assets/12562595/7776071/db626156-007d-11e5-869c-1d221ba0f476.jpg)

**Comment by JiDW** [comment]
I see them parallel with WebGL too. Both on my Chrome desktop and Android.

**Comment by englercj** [comment]
The image you posted for canvas is what I see for WebGL as well.

Chrome 42, Windows 8.1

**Comment by chirotaq** [comment]
I've tried it on two different computers and have seen my result.  A third computer produces what you are reporting.  Is there anything I can do to debug more?

**Comment by JiDW** [comment]
Maybe more infos on hardware and software specs.

Browser version, OS version, GC model, etc

**Comment by chirotaq** [comment]
Win 7 Pro, service pack 1.
Intel i7-2600 
Intel HD Graphics 2000
Chrome Version 42.0.2311.152 m

**Comment by chirotaq** [comment]
The third computer I tried that worked properly had Intel HD Graphics 4000.  Could that be it?

**Comment by englercj** [comment]
Most likely, I'm not 100% sure how to fix it though.

**Comment by drkibitz** [comment]
Looked on 2 machines
1. ASUS Laptop 2008: Win 7, NVIDIA GeForce 9800GX2
2. Macbook Pro 2014: NVIDIA GeForce GT 750M

On both I see what looks like the canvas example.

**Comment by chirotaq** [comment]
I just realized I didn't check the driver for the GC.  It seems to be outdated (work computer).  I do not have admin rights, so give me a bit to get it updated.  I'm hoping that will fix it.  >.<

**Comment by chirotaq** [comment]
Sorry for the delay.  I finally had the graphics driver updated and do not see any issues.  Sorry for not catching that earlier and thanks for helping me out.
