### ISSUE TITLE
Typescript Support For v3

### ISSUE THREAD

**Issue by tommyZZM** [GoodBoyDigital/pixi.js#1845]
have a official d.ts for pixi v3?

**Comment by drkibitz** [comment]
See: https://github.com/pixijs/pixi-typescript

Pretty sure @englercj is maintaining it, I won't speak for him, but he seems pretty busy :wink:

**Comment by englercj** [comment]
@clark-stevenson and myself are the ones working on it:

https://github.com/pixijs/pixi-typescript/tree/v3.x

He does a great job of keeping it up to date!

**Comment by tommyZZM** [comment]
thanks
