### ISSUE TITLE
Allow removal of plugins

### ISSUE THREAD

**Issue by yotamlaufer** [GoodBoyDigital/pixi.js#1849]
I would like to disable the InteractionManager plugin completely as I use my own.
It seems that when the InteractionManager is enabled, which is the default case if I'm not mistaken, it also activates the Ticker, which I don't use as I managed render cycles myself.

It will be nice to have convenience method for the removal of plugins. Thanks.

**Comment by englercj** [comment]
You can exclude plugins completely from the build:

https://github.com/GoodBoyDigital/pixi.js#how-to-build

**Comment by yotamlaufer** [comment]
@englercj I hacked the removal of the InteractionManager by reversing the logic used to add the plugin and it seems to work. But this is obviously very dirty.

```javascript
function removePlugin(name, renderer) {
    var plugin = renderer.plugins[name];
    if (plugin) {
        plugin.destroy();
    }
    delete renderer.plugins[name];
}
```

**Comment by englercj** [comment]
Was doing a custom build not working for you?

**Comment by yotamlaufer** [comment]
It failed. I admit that I didn't put to much effort into it as I'm rushing to a deadline. I got this error when doing `npm install`

```
Error: ENOENT, no such file or directory '/Users/yotamlaufer/Work/player/player/public/src/bower_components/pixi/gulp/tasks'
```

I used bower to install PIXI, so maybe it requires a `git clone` instead.

**Comment by englercj** [comment]
To do a custom build you need to clone (or download the repo tar), you can't do it from a distributable package.

**Comment by yotamlaufer** [comment]
That's what I thought. No time for this right now, but good to know. Thanks!
