### ISSUE TITLE
Nearest-neighbor scaling issues with canvasrenderer

### ISSUE THREAD

**Issue by zOadT** [GoodBoyDigital/pixi.js#1850]
Hello everyone,

using the Canvas renderer can lead to different results as the WebGL renderer if you use nearest neighbor scaling:

If your resize the renderer you need to manually set the imageSmoothing-property to false. Also it seems like you need to set the default scale mode after you initialize the renderer. In WebGL both works a expected.

Here is a small fiddle: https://jsfiddle.net/0zj88jse/

I hope this issue doesn't already exists, I didn't found it. If it already exists I am sorry

**Comment by englercj** [comment]
Interesting, thanks for the report.

**Comment by GoodBoyDigital** [comment]
that is really strange! thanks for sharing this one!

**Comment by GoodBoyDigital** [comment]
All fixed! Added a little patch to the resize function in the canvas renderer to account for this behaviour.
