### ISSUE TITLE
Can't use .getLocalPosition() on PIXI.Container mouse event

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [GoodBoyDigital/pixi.js#1865]
If I create a new `PIXI.Container`, then attach to it a mouse or touch event (`mousedown`, `touchstart`, `mousemove`...), and then I try to call `InteractionData.getLocalPosition()`, I get the following error:
```
Uncaught TypeError: Cannot read property 'worldTransform' of undefined
```
This likely a bug since the function exists for this combination (`Container` + mouse event), but can't be called.

[Live demo](http://jsfiddle.net/zcqfg91s/) (open your console)

**Comment by RoryPicko** [comment]
you have to pass the DisplayObjectContainer object to the function that you want the relative position from

**Comment by GeoffreyFrogeye** [comment]
My bad...
Thanks anyway!
