### ISSUE TITLE
drawPolygon very slow with fill in WebGL

### ISSUE THREAD

**Issue by GBagley** [GoodBoyDigital/pixi.js#1869]
Hi,

In WebGL renderer, using drawPolygon along with a beginFill is really, really slow (<= 1 frame per second) drawing about 1000 relatively simple polygons to 1 Graphics object. Also pegs my 'GPU Load' (in GPU-Z) to 100%.

If I remove the fill, then it performs very well. OR, if I switch to the canvas renderer (including fill) it also does pretty well. So there is something about Polygons with fill in WebGL renderer that is having trouble. If you have any ideas, please let me know. 

(using PIXI 3.0)

**Comment by GoodBoyDigital** [comment]
If you could provide an example that would be ace! Cheers :+1:

**Comment by GBagley** [comment]
Here's a test case that shows what I'm seeing:
http://jsfiddle.net/y6y4t6hd/

(sorry for embedding all the polygons in there...was the easiest way to get them in there)

So this has the Stats FPS counter on the top left. I get around 1-3 FPS using WebGL and with a beginFill. If you switch to the canvas renderer, then I'm getting closer to 40 FPS. Or commenting out the beginFill line, I get around 30 FPS (in WebGL).

**Comment by wayfu** [comment]
does it improve the FPS if you introduce an endFill call? (as in 1. beginFill, 2. drawPolygon, 3. endFill)

**Comment by GBagley** [comment]
Nope, adding endFill doesn't seem to change things.

**Comment by GoodBoyDigital** [comment]
wow, thats a lot of polygons!

have you tried breaking the object in to smaller graphics instances?


On Fri, Jun 5, 2015 at 12:12 AM, GBagley <notifications@github.com> wrote:

> Nope, adding endFill doesn't seem to change things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoodBoyDigital/pixi.js/issues/1869#issuecomment-109087010>
> .
>



-- 
Mat Groves

*Technical Partner*


 Telephone: 07708 114496 :: www.goodboydigital.com
 First Floor, Unit 9B, Queens Yard, White Post Lane, London, E9 5EN
 goodboy©. All Rights Reserved.

**Comment by GBagley** [comment]
Yes. I tried using a separate graphics instance for each polygon also. Made it a bit worse I think. Not noticeably better.

Yes, it is a lot of polygons. This is just a test case. I actually have closer to 40k total polygons to draw, for now :)

Normally, I haven't had issues with high volume of other shape types. I'm drawing over 100k rectangles using drawRect, with no issues at all.

**Comment by englercj** [comment]
Rectangles are trivial, polygons have to be triangulated and drawn using multiple triangles :)

**Comment by GBagley** [comment]
Sure, I understand that. The issue in this particular case is the huge discrepancy in canvas vs. webgl performance for filled polygons. Seems there is something about how the webgl renderer handles polygon fill that is much less efficient than it could be. (Unfilled polygons have no problem)

I had also tried running the points through a poly line simplifier first (Simplify.js) to reduce the number of points. Helped a little bit not nearly enough.

**Comment by englercj** [comment]
> The issue in this particular case is the huge discrepancy in canvas vs. webgl performance for filled polygons.

We draw polygons on canvas using native draw methods, which are often gpu accelerated. In WebGL we triangulate on the cpu, then pass that data to the gpu for drawing. This is likely to be much slower.

> Seems there is something about how the webgl renderer handles polygon fill that is much less efficient than it could be.

Likely true, if you find some optimizations please put in a PR!

> (Unfilled polygons have no problem)

We don't have to triangulate those, and the drawing algorithm is way simpler.

**Comment by wayfu** [comment]
aren't the triangulations cached in the indices? or do you re-calc them every frame?

**Comment by GoodBoyDigital** [comment]
they should be cached. Im surprised how slow they run to be honest. Will check the code, maybe somthing has changed..

**Comment by englercj** [comment]
We changed to earcut instead of PolyK, but I would be blown away if this got slower because of that. earcut is way faster than PolyK.

**Comment by GoodBoyDigital** [comment]
true, It shouldn't be that - it should only do the tessellation once.. will take a looksie..

**Comment by manelis** [comment]
Make a texture with it and then draw a sprite:

```javascript
    drawHexagon: function(map, color, x, y){  
      var xpos = jsmap.getMapXPos(x, y);
      var ypos = jsmap.getMapYPos(x, y);
      var texture = null;
      if(!jsmap.textures.hasOwnProperty(color)){
        var gfx = new PIXI.Graphics();
        gfx.moveTo(xpos + 61, ypos);
        gfx.beginFill(color, 1.0);
        gfx.drawPolygon([xpos + 187, ypos, xpos + 250, ypos + 86, xpos + 187, ypos + 171, xpos + 61, ypos + 171, xpos, ypos + 86, xpos + 61, ypos]);
        gfx.endFill();
        jsmap.textures[color] = gfx.generateTexture();
      }
      var sprite = new PIXI.Sprite(jsmap.textures[color]);
      sprite.position.x = xpos;
      sprite.position.y = ypos;
      map.addChild(sprite);
      return sprite;
    },
```

It helps a lot in my situation.

**Comment by GBagley** [comment]
Good suggestion! Yes, that does seem to solve (or at least workaround) the issue. Thanks. Here's an updated fiddle with a use_sprites toggle. Using a separate tex/sprite for each polygon -- back up to full FPS:
http://jsfiddle.net/y6y4t6hd/1/

**Comment by GBagley** [comment]
Spoke too soon. The Sprite option works well for 1k polys, but doesn't scale up past 10k polys very well.

**Comment by manelis** [comment]
But did drawing 10k polygons scale better before? If it did, then i will also change back when this is fixed.

**Comment by GoodBoyDigital** [comment]
Did a little messing around and made the threshold for complex polygons higher. Should be better now!

http://jsfiddle.net/77zc0qnn/

enjoy!

**Comment by GBagley** [comment]
Perfect. Getting a full 60 FPS up until about 300k polys now, which is way more than I need, and only minor slowdown with even more (up until the page crashes). Thanks for the quick update on this one! Much appreciated.
