### ISSUE TITLE
Video loop using video texture

### ISSUE THREAD

**Issue by pavan4** [GoodBoyDigital/pixi.js#1872]
I used the sample for rendering a video as a sprite  from here : https://github.com/GoodBoyDigital/pixi.js/tree/v2.x/examples/example%2025%20-%20Video 

I would like to knwo How could I run the video in a loop. I would also like to reset the playback i.e., start the video from the beginning by attaching the call to an event. Is it possible to do this? I could not get this information from the documentation.

If anyone could point me towards a guide I will be grateful

**Comment by photonstorm** [comment]
Just set the loop property of the video to 'loop' (true works as well in browsers I've tested, but technically it should be the string 'loop').

You need to do this before it plays though.

Also remember that most browsers at the moment utterly fail to provide seamless looping. Chrome is absolutely terrible when it comes to looping videos. IE11 ironically is the best. FF somewhere in the middle.

**Comment by pavan4** [comment]
Sorry for the noob question but do you mean through pixi ?

something like : 

      var texture = PIXI.VideoTexture.fromUrl("test.mp4");
      var moveSprite = new PIXI.Sprite(texture);
      moveSprite.anchor.x = 0.5;
      moveSprite.anchor.y = 0.5;
      moveSprite.alpha = alpha;
      moveSprite.loop = 'loop';

Also how can I reset the video midway during playback ?

**Comment by englercj** [comment]
There is no video texture, there is a video base texture though.

You are probably wanting to do this:

```
var texture = PIXI.Texture.fromVideoUrl("test.mp4");
var moveSprite = new PIXI.Sprite(texture);

var video = texture.baseTexture.source;

// the `video` var is an HTML video element. You can do whatever you want with it.
video.currentTime = 0; // reset
```

If you need to setup the video element yourself before putting it in a texture, you can use `PIXI.Texture.fromVideo(videoElement)`

**Comment by pavan4** [comment]
I am a bit lost here (noob). Sorry again but I am not sure what you mean.

To explain I have two scenes and I am rendering either of the scene on the stage based on event.

One scene is running video and the other an interactive image.

I am following the example to render the video : 


     var stage = new PIXI.Stage(0xffffff);
     var renderer = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight);
     document.body.appendChild(renderer.view);
     requestAnimFrame(animate);
     var texture = PIXI.VideoTexture.fromUrl("testVideo.mp4");
     var moveSprite = new PIXI.Sprite(texture);
     stage.addChild(moveSprite); 
     function animate() {
        requestAnimFrame(animate);
        renderer.render(stage);
     }

I did not add the code for scene change in the above though. But based on your code sample how can I integrate this into the code.

**Comment by englercj** [comment]
```js
 var stage = new PIXI.Stage(0xffffff);
 var renderer = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight);
 document.body.appendChild(renderer.view);
 requestAnimFrame(animate);
 var texture = PIXI.VideoTexture.fromUrl("testVideo.mp4");
 var moveSprite = new PIXI.Sprite(texture);
 stage.addChild(moveSprite); 
 function animate() {
    requestAnimFrame(animate);
    renderer.render(stage);
 }

// you can access the video element like this:
texture.source;

// you can do to it, anything you can do to an HTML5 video element. Such as, seeking, pausing, playing, looping, etc.
```

This code you pasted is for v2, you should upgrade to v3 if you have a chance.

**Comment by pavan4** [comment]
I did this to loop the video ... might be a stupid idea but I am stuck here : 
    
    function animate() {
    var video = texture.baseTexture.source;
    //console.log(video.currentTime ,'sdfasd' ,  video.duration ); 
    if(video.currentTime == video.duration){
          video.currentTime = 0; // reset
    }
    requestAnimFrame(animate);
    renderer.render(stage);
    }

The time is reset to 0 but the loop never resumes. Am I doing something very stupid?

**Comment by pavan4** [comment]
Thanks a lot that worked.
