### ISSUE TITLE
version number?

### ISSUE THREAD

**Issue by laughingturtle** [GoodBoyDigital/pixi.js#1873]
It would be super useful to be able to see the version number at the top of the pixi.js file or pixi.min.js file.  The version I've downloaded does not have that.

**Comment by englercj** [comment]
Yeah, been meaning to add the license header back in and haven't had time. Good call out.

In the meantime you can run `PIXI.VERSION` in the console and it will outpu the version, or search the file for "VERSION" and you will see it.

**Comment by drkibitz** [comment]
Just to note, the package.json is included in every v3 build. It's not at the top in a comment header, but it is within the source, devDependencies and all. The version is exposed as PIXI.VERSION directly from the required package.json.
