### ISSUE TITLE
Cannot use a same item inside other "camera"

### ISSUE THREAD

**Issue by Inateno** [GoodBoyDigital/pixi.js#1875]
Hey guys,

A new problem appear to me today :D
I created a "camera" object, something very simple that inherit from PIXI.Container.

My current problem is I cannot see the same scene through 2 camera, and this is due to PIXI DisplayObject architecture (child got parent and parent got child, if you move your DisplayObject inside an other one, the previous parent lost his child).

Of course, a "container" shoudn't use a child from an other container. I have the solution to create 2 renderer, but imo it's a nasty solution.
(in my case I want use a camera for the background, this one can see only background stuff, and the other one can see everything).

Waiting for a better solution I duplicated instance for my background stuff (not a lot, only 4 with a very simple logic).

Any suggestion ? :)
Cya, hf coding

**Comment by englercj** [comment]
You can use a render texture for the second camera to share objects.

**Comment by Inateno** [comment]
Mmmh didn't tried that, I try this. Thanks
