### ISSUE TITLE
Does PIXI store spriteSheet json after it's been processed

### ISSUE THREAD

**Issue by RoryPicko** [GoodBoyDigital/pixi.js#1878]
I'm looking to implement something whereby I can completely clear all resources of a SpriteSheet.

for example I load in a sprite sheet (spritesheet.json) that contains 'sprite.png' and 'sprite2.png' I am then looking to destroy the base texture of the spritesheet, the  the generated textures from the sheet and the json (if stored), It would be a lot easier if i could access the spritesheet.json which could then be looped through to determine which textures in the texture cache need to be deleted

destroySpritesFromSheet('spritesheet.json');

So that I don't have to individually destroy the textures by name as some sprite sheets have loads of textures and that would be a tedious task

**Comment by JiDW** [comment]
For what I know, PIXI doesn't store the json data; but thanks to javascript it would be very easy to load this json file into a javascript object and use it to clean your cache.

And if you don't want to reload this json for whatever reasons, I guess you could loop on PIXI.utils.TextureCache and check if texture.baseTexture.source.url is your spritesheet.png

**Comment by RoryPicko** [comment]
sweet, thanks @JiDW :+1:

**Comment by englercj** [comment]
If you are using the loader then it has the json data in there. If you load a spriteSheet resource then after loading the `.textures` property is an array of textures for the spritesheet, and the `.data` property is the spritesheet json data. The base texture is obviously the same accross all the elements in the `.textures` array.
