### ISSUE TITLE
The Run pixie run can't run well on the android

### ISSUE THREAD

**Issue by LyonZhang** [GoodBoyDigital/pixi.js#1880]
Dear GoodBoyDigital,

I am playing and developing a Run pixie run game, but I found we can't run the game in my browser on android.
There is a very strange cover on the top of the game(it seem is bgcolor of body).
What can I do on the pixi or the program to fix it?

You can download the browser from http://mb.qq.com/.
Many thanks.

![image_1433878965 798513](https://cloud.githubusercontent.com/assets/12819292/8067819/cadfb19a-0f22-11e5-9055-238cf833f37c.jpg)
![image_1433878959 808073](https://cloud.githubusercontent.com/assets/12819292/8067820/cae99412-0f22-11e5-9364-fa08fc0b976b.jpg)

**Comment by englercj** [comment]
This was built an old version of pixi.js, closing this for now.

**Comment by jdnichollsc** [comment]
Any tutorial about this scaling with Phaser please? @englercj

**Comment by englercj** [comment]
This isn't the forum for that. There are tons of tutorials on scaling phaser:

http://phaser.io/docs/2.5.0/Phaser.ScaleManager.html
http://phaser.io/shop/books/scale-manager-guide
