### ISSUE TITLE
Valve used Pixi for the summer sale

### ISSUE THREAD

**Issue by PierBover** [GoodBoyDigital/pixi.js#1890]
This is not an issue but I don't know where else to put it :)

Valve is using Pixi!
http://steamcommunity.com/minigame/towerattack/

**Comment by englercj** [comment]
This is amazing, thanks so much for sharing!

**Comment by PierBover** [comment]
I was curious to see what the big Valve was using... and lo and behold! They are using Pixi!

**Comment by JiDW** [comment]
Yes that's very cool ! Congratulation to Mat, Chad and the others contributors for this fantastic engine. I'm glad to see a company like valve acknowledge PIXI's awesomeness.

**Comment by pwolfert** [comment]
Yeah, that's pretty awesome!  Good job, guys.  It really is a wonderful engine.

**Comment by krzysztof-o** [comment]
Congrats to all contributors, well done everyone! OSS FTW!

**Comment by englercj** [comment]
woot!

**Comment by PierBover** [comment]
I know this is offtopic... but how do you guys communicate? Do you have a Pixi google group? A Slack chat?

**Comment by englercj** [comment]
https://gitter.im/GoodBoyDigital/pixi.js :)
