### ISSUE TITLE
pixi.js v3 strange behavior for touchevents

### ISSUE THREAD

**Issue by pavan4** [GoodBoyDigital/pixi.js#1891]
I was running my app with pixi v2.2.8 perfectly. 

I tried to upgrade and this happened : 

When I use the custom touch events like this 

```javascript
    var event = document.createEvent('Event');
    event.initEvent('touchmove', true, true);
    var obj = {};
    var temp = [];
    obj = {identifier: ind,
          pageX: x,
          pageY: y,
          screenX: x,
          screenY: y,
          clientX: x,
          clientY: y
    };
    temp.push(obj);
    event.touches = temp;
    renderer.view.dispatchEvent(event);
```

This worked like a charm when I set the x and y I could create touch events . With v3 I have this weird problem that when I use a physical touch all the events are raised but when I raise a custom event using the code above PIXI seems to eat away most of the events. Also, I added this : 

```javascript
	document.addEventListener("touchmove", function(event) {
		console.log('eventLog');
	});
```
I am able top catch all the custom events. 

I have to rapidly fire with x and y changing and only 3 out of 100 events are being rendered. Is there a setting I am missing? 

If my question is unclear please let me know.

**Comment by endel** [comment]
Is this related to https://github.com/GoodBoyDigital/pixi.js/issues/1837 and https://github.com/GoodBoyDigital/pixi.js/issues/1884 too?

There is a patch/pull-request for this here: https://github.com/GoodBoyDigital/pixi.js/pull/1894

**Comment by pavan4** [comment]
Unfortunately no. I alraedy made the changes on my local version to gt rid of the touchevents on all elements. My problem is all the events are not being fired. If I fire 100 touch events only 3 or 4 are dispatched.

**Comment by pavan4** [comment]
This might be the reason I think.

I have overlapping objects and the touch event is raised on the object that is on the top. But the object below is visible as well and I want the event to be fired on the object below as well. 

This worked with v2.2 but not in 3. Is there any way to call the event or propagate it to the elements below?

**Comment by pavan4** [comment]
I have read through similar issues. Some expect the event to be stop propagation and some expect to bubble down. Is there any way to control this ? I want it to propagate to other events.

Here : https://github.com/GoodBoyDigital/pixi.js/issues/1765b , https://github.com/GoodBoyDigital/pixi.js/issues/1763 and also https://github.com/GoodBoyDigital/pixi.js/issues/1725 

Sorry if this is a noob question.

**Comment by pavan4** [comment]
https://github.com/GoodBoyDigital/pixi.js/issues/1920 This fixed it.

```javascript 
// InteractionManager.prototype.processInteractive
if(hitTest || displayObject.forceHitTest) {...}

// Any sprite I need to perform hit tests
sprite.forceHitTest = true;```
