### ISSUE TITLE
renderTexture seems broken

### ISSUE THREAD

**Issue by gmeter** [GoodBoyDigital/pixi.js#1893]
I'm using the latest pixi.

    var renderer = PIXI.autoDetectRenderer(width, height);
    var stage = new PIXI.Container();

    var renderTexture = new PIXI.RenderTexture(234, 199); 

			var color_sprite = PIXI.Sprite.fromImage("images/colormap.gif"); 
			color_sprite.position.x = 234/2; color_sprite.position.y = 199/2; 
			color_sprite.anchor.x = 0.5; color_sprite.anchor.y = 0.5; 

    /* I wait till the image is loaded before calling the following */

    renderTexture.render(color_sprite);

I get the following error in the console

TypeError: this.renderer.renderDisplayObject is not a function

The error refers to the following line:
   ` this.renderer.renderDisplayObject(displayObject, context);`

from:
    ` RenderTexture.prototype.renderCanvas = function (displayObject, matrix, clear, updateTransform)`

**Comment by englercj** [comment]
Try adding the sprite to the stage and rendering the stage instead.

**Comment by gmeter** [comment]
I tried that and got the same error, plus an additional error of 'h' not being set...

I am trying to implement  a color-picker feature. 

I thought to use the getpixel(x,y) function of renderTexture to read a pixel value from a specific sprite. 

Any other ways of achieving that?

**Comment by adelciotto** [comment]
don't you need to pass in the renderer to a render texture?

```javascript
var rt = new PIXI.RenderTexture(renderer, 300, 200, ..);
```

**Comment by englercj** [comment]
Ha of course, I missed that in the code posted.

**Comment by adelciotto** [comment]
Haha yeah, easy to miss.

So @gmeter, passing in the renderer should remove that error as it won't be undefined anymore.

A shorter example:

```javascript
var renderer = PIXI.autoDetectRenderer(400, 240);
var stage = new PIXI.Container();
document.body.appendChild(renderer.view);

var bunny = PIXI.Sprite.fromImage("http://www.goodboydigital.com/pixijs/examples/1/bunny.png"); 
var rt = new PIXI.RenderTexture(renderer, 32, 32);

var rtSprite = new PIXI.Sprite(rt);
rtSprite.position.set(400/2, 240/2);
rtSprite.anchor.set(0.5, 0.5);
stage.addChild(rtSprite);

function animate() {
  rt.render(bunny);
  requestAnimationFrame(animate);
  renderer.render(stage);
}

animate();
```

**Comment by englercj** [comment]
Closing, seems answered.
