### ISSUE TITLE
Configuration Option to turn off console declaration

### ISSUE THREAD

**Issue by mcnuttandrew** [GoodBoyDigital/pixi.js#1900]
In the console (on what appears to be all browsers) Pixi gives off a notification that Pixi is active and what rendering system is being used. Eg:

   Pixi.js 3.0.6 - ✰ WebGL ✰      http://www.pixijs.com/    ♥♥♥ 

I think it would be cool if this could be turned off by an option somewhere

**Comment by JiDW** [comment]
Hello, you can already do that, but be carefull for your face :D 

```javascript
/**
     * Logs out the version and renderer information for this running instance of PIXI.
     * If you don't want to see this message you can set `PIXI.utils._saidHello = true;`
     * so the library thinks it already said it. Keep in mind that doing that will forever
     * makes you a jerk face.
     *
     * @param {string} type - The string renderer type to log.
     * @constant
     * @static
     */
     sayHello: function (type)
```

**Comment by englercj** [comment]
True facts, Jerky McJerkhead.

**Comment by mcnuttandrew** [comment]
What about doing this makes a person a jerk?

**Comment by JiDW** [comment]
It helps to let people know about PIXI, if you do not advertise it in another way.
Say, for exemple, I'm a web dev and I discover an impressive game or website so I press F12 to look at the code, and I see the hello message from PIXI.

So of course you can do it, and nobody will blame you for that, but it would be nice to let PIXI get some credit if you use it.

**Comment by englercj** [comment]
@mcnuttandrew Companies like Valve have used Pixi for projects and kept the log in, there is rarely a reason to take it out. The only real case is to make your own log that includes Pixi's info, or to pretend you didn't use PIXI at all, which is a jerk move. The log is a simple way for you to give back to the project that is powering your app by increasing its visibility. 

If you feel it is necessary feel free to turn it off, we made it easy to do on purpose. But I reserve the right to look down my nose at you. ;)

**Comment by mcnuttandrew** [comment]
I'm not trying to hide the fact that I'm using it, I just don't like the clutter in the console when i'm trying to do other things on a relatively small screen. But i feel y'all, those are super good reasons, thanks for the energetic replies

**Comment by photonstorm** [comment]
Disable it during development and then when you publish throw it back in again. Simple.

**Comment by rzoller** [comment]
I consider this is still an unresolved issue because as far as I can tell, using `PIXI.utils._saidHello = true;` is an undocumented hack, and not a proper way to disable the console message.

I'm all in favor of properly acknowledging FOSS use, but IMHO, and at the risk of being called a jerk, the proper way of doing that is to include the license, for which I've created a separate issue #2427. As other people have mentioned, the console message is funny at first, but quickly becomes an annoyance. Now, imagine if all the other libraries you have in your project were doing the same...

**Comment by akbr** [comment]
I agree with @rzoller here. I love Pixi, and am pleased to credit it prominently in my projects.

However, in development, the console message is annoying. And throwing in extra code to silence isn't a very elegant solution.

**Comment by englercj** [comment]
The log message is opt out. The code to opt out is `PIXI.utils._saidHello = true;` this will likely not change in the near future.

**Comment by photonstorm** [comment]
While I agree it should be kept, I also agree it is a bit odd having it
under a private var. it makes it appear like a hack, even though it clearly
isn't.

The issue of having to add a single line of code to your app is a
non-issue. It's 10 seconds work, tops, and then can be part of your
standard template.

The issue of 'what if other libs did it' is also a non-issue, because they
don't.



On Thursday, 31 March 2016, Chad Engler <notifications@github.com> wrote:

> The log message is opt out. The code to opt out is PIXI.utils._saidHello
> = true; this will likely not change in the near future.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/pixijs/pixi.js/issues/1900#issuecomment-204025077>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by bigtimebuddy** [comment]
We did change our minds. The public API for this is [PIXI.utils.skipHello()](http://pixijs.download/release/docs/PIXI.utils.html#.skipHello).

**Comment by j-funk** [comment]
Not having console messages in my integration tests is very nice!

**Comment by Larkenx** [comment]
I am happy to advertise PIXI.js for folks to see what my game is made of...but honestly, something about the hearts wrapping when my console is a small width bugs me like nothing else
![image](https://user-images.githubusercontent.com/12945799/39963606-9cd651ee-563e-11e8-9105-2b99e31d752b.png)

**Comment by carlsmith** [comment]
The banner is always messed up in my browser `:(`

![image](https://user-images.githubusercontent.com/7561668/52593089-02b96580-2e40-11e9-8f04-d624974165c2.png)

It happens with v4 and v5, and I have `<meta charset=utf-8/>` at the top of the HEAD element.

Either way, using the banner in production makes sense, but honestly, it annoys me after a while in development (I use a 13 inch laptop with a 1440x900 display). If PIXI ever gets a debug mode, the default should probably be changed to only show the banner in production (which also makes it less likely to be disabled in development and forgotten about).

Chrome 71
macOS Mojave 10.14.2
PIXI v4.8.5, v5.0.0-rc

**Comment by themoonrat** [comment]
The answer is above.... you have to call `PIXI.utils.skipHello();` before you create the renderer

**Comment by carlsmith** [comment]
That doesn't fix the fact that the banner is garbled, and there's no way to disable it in development, but display it in production, so your claim that "it works" is personal and subjective.

**Comment by Larkenx** [comment]
you can just simply check the origin host name and see if it’s local host. If so, then use the skipHello function.

**Comment by carlsmith** [comment]
Thanks @Larkenx. I just thought of using `location.host.startsWith("localhost:")`, came here to mention it as an option, and saw you'd already thought of it.

To be honest, I'm a bit perplexed by your downvote. Do you understand that themoonrat had responded to my comment with a solution to a problem that nobody had expressed, basically dismissing my actual issue without reading the comment properly?

**Comment by carlsmith** [comment]
I reported a minor bug (garbled banner), and included a screenshot and version numbers for my OS, browser and the two versions of PIXI I tested it with. I also casually mentioned how nice it would be to be able to automate the banner's visibility in production.

Themoonrat replied to my comment, but clearly had not read it.

> The answer is above.... you have to call `PIXI.utils.skipHello();` before you create the renderer.

I thought it was a little but rude, but nothing to worry about, so I explained (factually and without rudeness) that his reply doesn't address either of my points:

> There is no "answer above" that explains why the banner is garbled on my machine.
> That aside, the problem with `PIXI.utils.skipHello` is that it provides no way to disable the banner in development, but display it in production, so it gets disabled and left like that.

You downvoted that??

**Comment by carlsmith** [comment]
To be honest, I'm a bit perplexed by your downvote.

I reported a minor bug (garbled banner), and included a screenshot and version numbers for my OS, browser and the two versions of PIXI I tested it with. I also casually mentioned how nice it would be to be able to automate the banner's visibility in production.

Themoonrat replied to my comment, but clearly had not read it.

> The answer is above.... you have to call `PIXI.utils.skipHello();` before you create the renderer.

I thought it was a little but rude, but nothing to worry about, so I explained (factually and without rudeness) that his reply doesn't address either of my points:

> There is no "answer above" that explains why the banner is garbled on my machine.
> That aside, the problem with `PIXI.utils.skipHello` is that it provides no way to disable the banner in development, but display it in production, so it gets disabled and left like that.

You downvoted that??

**Comment by carlsmith** [comment]
It's no big deal. If it was just a misunderstanding, that's cool. I just don't want to upset people without knowing why really. Best wishes, whatever it was.

**Comment by bigtimebuddy** [comment]
The garbled output is a bug and should probably be a new issue @carlsmith, not sure why that’s happening of the top of my head. Would appreciate you starting a new issue rather than commenting on this closed one, since the original issue is solved.

**Comment by carlsmith** [comment]
Thanks @bigtimebuddy. Will do.

**Comment by carlsmith** [comment]
I think I figured out the garbled output. I didn't want to open an issue, because I thought it was just my machine, then a couple of days after you said to, I finally figured it out.

It doesn't happen on CodePen (in the same browser). I'm pretty sure now that it's just the bash one liner I often use to run a local, Ruby, static file server.

Sorry for the noise, guys.
