### ISSUE TITLE
Should I add children to sprites instead of creating containers for performance?

### ISSUE THREAD

**Issue by RoryPicko** [GoodBoyDigital/pixi.js#1903]
I've been seeing a few GitHub issues within this repository lately about adding sprites/graphics/text inside other sprites/graphics/text lately (which I didn't think you could do, coming from a flash/AS3 background) asif each sprite/graphics/text also acts as a container, is this method faster for rendering?

for example I created a toggle button (checkbox) with this structure
-container (container)
     ---on state (sprite)
     ---background (sprite)

and then I add a mouse event to the container to toggle the visibility of the onstate sprite.
whereas from what i've read recently i can do this
-background (sprite)
     ---on state (sprite)

This is the simplest example I could think of but I'm using the container method multiple times across many menus

Does the method without the container make any considerable difference in rendering performance? shy of reducing the computation loops by 1, which in my experience on mobile platforms, rendering is the bottleneck for performance.

**Comment by englercj** [comment]
> if each sprite/graphics/text also acts as a container, is this method faster for rendering?

They are containers, they act exactly like containers, no difference.

> Does the method without the container make any considerable difference in rendering performance? 

Not really, wide scene graphs are better than deep ones but the difference between one or two sprites really just doesn't matter.
