### ISSUE TITLE
[v3] ParticleContainer throws an error on destroy() method

### ISSUE THREAD

**Issue by jwdunn1** [GoodBoyDigital/pixi.js#1911]
Here's a minimal repro: http://jsfiddle.net/intrinsica/z6m87dmw/
1) open the browser console
2) click anywhere on the black stage to destroy the ParticleContainer.
3) Error report in console: Uncaught TypeError: this._buffers.destroy is not a function

**Comment by adelciotto** [comment]
The actual element in the array is not being indexed.

this: 
```javascript
for (var i = 0; i < this._buffers.length; ++i) {
    this._buffers.destroy();
}
```

should be:
```javascript
for (var i = 0; i < this._buffers.length; ++i) {
    this._buffers[i].destroy();
}
```
