### ISSUE TITLE
Interactive parent gives strange behavior to interactive children if other children overlap it

### ISSUE THREAD

**Issue by alanthai** [GoodBoyDigital/pixi.js#1920]
A child `child1` that is interactive will trigger a "click" response if it is clicked anywhere in its hit box.

However, if a parent is set to interactive AND the parent has another child `child2` that is ON TOP OF `child1`, then `child1`'s click event will not trigger if you click on `child2`.
 
Similar issue to the one below:
#1670 

Example:
http://jsfiddle.net/nzexvjfa/1/

Clicking on the `bunny` will not trigger `circle`'s click. Clicking on `circle` but not `bunny` will trigger the click. If `bunny` is added to `stage` after `container` was added, then clicking anywhere on `circle` will also trigger a click

Tested on v3.0.6

**Comment by alanthai** [comment]
Sorry I think it's the same issue as #1901

**Comment by endel** [comment]
It seems that the only problem in your example is that you're using `clicked` instead of `click` on the container. That's because it's not being triggered.

**Comment by alanthai** [comment]
Sorry small mistake. Change `clicked` to `click`. You still get the same problem with the parent-child interaction. The main problem is still clicking something over top of the `circle` is still not registering a click. Are you getting the same problem?

**Comment by alanthai** [comment]
Until this is fixed, I did a quick fix on InteractionManager
https://github.com/GoodBoyDigital/pixi.js/blob/v3.0.6/src/interaction/InteractionManager.js#L381

```
// InteractionManager.prototype.processInteractive
if(hitTest || displayObject.forceHitTest) {...}

// Any sprite I need to perform hit tests
sprite.forceHitTest = true;
```

**Comment by englercj** [comment]
So I don't understand where the idea of clicking an interactive item should trigger items below it is coming from. That is not how DOM interactions work, and I don't think that is how the interaction manager should work. Why would we want it to work that way? I don't understand.

**Comment by alanthai** [comment]
It might just be me, but I found it strange for this reason:

if `parent.interactive = false`, and you click on `child1` where `child1.interactive = true`, then clicking on `child2` (which is on top of `child1`) would fire an event for `child1` being clicked.

Now if you set `parent.interactive = true`, this scenario no longer works.

To me this behavior feels inconsistent.

**Comment by englercj** [comment]
> if parent.interactive = false, and you click on child1 where child1.interactive = true, then clicking on child2 (which is on top of child1) would fire an event for child1 being clicked.

In this scenario are both child2 and child1 interactive, but not the parent? Because if so, that is a bug. child2 being interactive should not somehow send events to items it is blocking.

**Comment by variousauthors** [comment]
Another similar issue is that child elements of parents with defaultCursor cannot themselves have defaultCursor. I [modified the fiddle][0] above so you can see this: when I mouseover the circle there is a crosshair, when I mouse over the bunny I expect a grabby hand. Instead the parent cursor wins. Is this the expected behaviour?

[0]: http://jsfiddle.net/nzexvjfa/5/

**Comment by englercj** [comment]
No, children are considered "on top" so that is not desired behavior.

**Comment by variousauthors** [comment]
So, should I open an issue for that? In the game I'm currently working on, I have a situation where I would like a parent to have a different cursor behaviour than its smaller child. My intention is to break up the hierarchy and fake it for now.

**Comment by englercj** [comment]
Yes, please open a diferent issue.

**Comment by Sirk** [comment]
> So I don't understand where the idea of clicking an interactive item should trigger items below it is coming from. That is not how DOM interactions work, and I don't think that is how the interaction manager should work. Why would we want it to work that way? I don't understand.

That's not totally true. At a DOM level, you can both attach a click on a parent and on a child. If you for exemple listen to click event on a div, and too listen to a click event in a span inside it, you will fire the both two events. 

The event on the span inside will not be triggered only if you call event.stopPropagation() inside the div event callback.

I'm in a situation right now where I need some interaction at my main stage level, and inside child elements. If my stage has interactive = true, nothing is catched by the childrens events.

The best logic scenario would be to me : if a parent DisplayObject listen some events, the childrens of this parent can't catch those events only if the parent event callback call event.stopPropagation(). If you don't, the event bubbles right to the childs if the hitTest is true.
