### ISSUE TITLE
Multiple views that share memory?

### ISSUE THREAD

**Issue by GBagley** [GoodBoyDigital/pixi.js#1927]
Hi,

Wondering if it's possible to have multiple views of a scene that share gpu/graphics memory. The idea is that I have a dense scene and want to split it into 2 (or more) views of the same scene, just with different graphics elements being shown/hidden in each. All the graphics/geometry/buffers would be shared between both views, just the hidden properties on objects would be different.

I know this is possible in OpenGL (not positive about WebGL), but haven't figured out how to go about it within pixi. Multiple WebGLRenderers? Something to do with contexts? Maybe drawing the first view of the scene, then flipping the visible properties to set up the 2nd scene, offsetting the container and rendering again (in the same frame) for the 2nd view of the scene (but without clearing between renders)? Would appreciate any hints/insight you might have. Thanks!

**Comment by englercj** [comment]
Have you tried to use a RenderTexture to achieve the effect you are describing? If you use two WebGLRenderers, they cannot share resources (because they have separate contexts).

**Comment by GBagley** [comment]
Thanks. I hadn't see RenderTexture before. Haven't been able to get it to work yet though...could you take a look and let me know what I'm doing wrong? Have tried using RenderTexture with both sprites and containers (containing graphics objects) but not getting anything rendered.

http://jsfiddle.net/hneojaq6/

**Comment by englercj** [comment]
I dont see any code there to actually use the texture you created. RenderTexture is just a texture, so you need to create a sprite that uses it to draw it:

```js
var renderTexture = new PIXI.RenderTexture(renderer, width, height);

var sprite = new PIXI.Sprite(renderTexture);

stage.addChild(sprite);

renderer.render(stage);
```

Make sense?

**Comment by Arm08102525** [comment]
#1927

**Comment by GBagley** [comment]
Oh, I see. The RenderTexture lets you render graphics objects to a texture target rather than the screen, and then you add that texture back into the scene with a different position. Great. Will give that a try:

(updated fiddle: http://jsfiddle.net/1mv2suj7/ )

**Comment by englercj** [comment]
Exactly!

**Comment by Arm08102525** [comment]
#1927

**Comment by englercj** [comment]
Seems like this is answered, closing.
