### ISSUE TITLE
Mesh Renderer for V 2.2.9

### ISSUE THREAD

**Issue by SeminYun** [GoodBoyDigital/pixi.js#1929]
Hi. 

Can i use Mesh renderer for V.2.2.9

because I wanna use Spine Mesh(FFD) for my Project with PIXI.js 

i 'm using long time with v.2.x  so i can't change to V.3.0x 

i'm waiting long time for spine mesh.

and i heard it can use in v.3.0.6 

how can i use that ability with V.2.2.9

please help.

thx

**Comment by englercj** [comment]
`v2.x` is supported for maintenance only (critical or blocker bugs). The default answer is "upgrade to v3". The upgrade process really isn't all that difficult, I was able to upgrade the Phaser game engine in less than an hour and that is a really large project. Have you tried?

**Comment by SeminYun** [comment]
I See ^^/ 
I will try soon.. ..
thx a lot..

**Comment by englercj** [comment]
Closing this since we won't be back porting mesh into v2.
