### ISSUE TITLE
Can't build on Windows 8

### ISSUE THREAD

**Issue by ex** [GoodBoyDigital/pixi.js#1935]
Installing gulp on Windows 8 is failing with error:
```
C:\Users\Administ>npm install -g gulp
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "node" "C:\\Users\\Administ\\AppData\\Roaming\\npm\\node_modules\\
npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! node v0.12.5
npm ERR! npm  v2.12.0

npm ERR! undefined is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administ\npm-debug.log
```
I know this is more a npm or gulp issue, but I was wondering if somebody made the build work on Windows. I can build fine on OSX

**Comment by englercj** [comment]
I develop on Windows, and it works for me. Unsure what is going on without npm-debug.log; but either way definitely not a pixi.js issue.

**Comment by ex** [comment]
Thanks, updating to npm@next fixed the problem, running cmd as administrator:
```
npm cache clear
npm install -g npm@next
npm install -g gulp
```

**Comment by englercj** [comment]
Yeah looks like npm v2.12.0 is broken for windows :(
