### ISSUE TITLE
Can CanvasRendered.roundPixels be set from options passed to consctuctor?

### ISSUE THREAD

**Issue by tiriana** [GoodBoyDigital/pixi.js#1936]
My question is about this line:
https://github.com/GoodBoyDigital/pixi.js/blob/master/bin/pixi.js#L12384
We would like to be able to set it while creating renderer. Could this be set from ```options``` ?
```this.roundPixels = !!options.roundPixels;``` for instance?

**Comment by englercj** [comment]
Sure, feel free to put in a PR!

**Comment by englercj** [comment]
#1945 has been merged.
