### ISSUE TITLE
Exclude from build is not working

### ISSUE THREAD

**Issue by stbaer** [GoodBoyDigital/pixi.js#1946]
For example `gulp build --exclude spine` throws `Error: Cannot find module '../../src/spine'` (tried with latest dev).

**Comment by englercj** [comment]
Spine isn't packaged with pixi.js, so that will throw because it doesn't exist. Valid values are:

```
extras
filters
interaction
loaders
mesh
```

**Comment by stbaer** [comment]
Yes, bad example, I took it from the Readme. But e.g. filters or anything else is also not working for me.

**Comment by stbaer** [comment]
Hm, I just realized that its actually working with only one dash for exclude.

```sh
gulp build -exclude filters
```

instead of 

```sh
gulp build --exclude filters
```

So probably just the Readme needs to be updated...

**Comment by englercj** [comment]
@stbaer It works because the cli parser reads it as `gulp build -e filters -x -c -l -u -d- e` so technically it works since `-e filters` is valid.

I've fixed the long form `--exclude` in the latest code in `dev`. Sorry about that!

**Comment by stbaer** [comment]
Nice, thank you!
