### ISSUE TITLE
interactionData.getLocalPosition(container) bug

### ISSUE THREAD

**Issue by bQvle** [GoodBoyDigital/pixi.js#1947]
This is supposed to return the mouse position relative to the container,

And it works as intended, until you rotate the container. then It returns strange values that doesn't make sense in relation with the container.

I would expect that LocalPosition would return the same value, if you click the top of an object. and then rotate the object 90 degrees and click the right side.  because i want the localPosition of the click in the container.

Example (at rotations other than 90 degrees the numbers is even more random)

![example](http://i.imgur.com/mVTo4mN.jpg)

**Comment by DanielVyskoc** [comment]
Same problem here #1896
I also explained how it could be solved

**Comment by englercj** [comment]
Going to track this with #1896
