### ISSUE TITLE
RenderTexture.resize bug

### ISSUE THREAD

**Issue by bQvle** [GoodBoyDigital/pixi.js#1948]
Every time i call RenderTexture.resize, it clears the whole texture.

I assume that's not intended (when there's an option, to choose if you want to resize the baseTexture or not).

**Comment by englercj** [comment]
Hmm, what behavior do you expect to happen? Remember the base texture in a RenderTexture is just a stub to make sure the texture buffer is drawn correctly.

**Comment by bQvle** [comment]
I was hoping, I would be able to resize the RenderTexture, while keeping the part that was already rendered. 

I'm drawing a dynamic spritesheet, and its a bit harsh to start off with a blank 2048x2048 texture.

**Comment by englercj** [comment]
I'm not sure I understand, tbh. Can you give me a code example to illustrate what you are trying to do?

No other texture/buffer objects act the way you are describing, maybe there is a different way to accomplish the goal to are trying to reach.

**Comment by bQvle** [comment]
I wrote this script, to render a Container onto a spritesheet, and make a Sprite that uses that texture instead. I do this because the container is to heavy to be handled in realtime (gives me alot of draw calls).

While i got your attention, I'm also trying to make the PIXI.Mesh.Rope tilable, but if my uvs exceed 1 it just streatches the last pixel.  I looked in the src, and noticed that it had to be "Power of two", to enable gl.REPEAT.  but i still get the same result.

Sorry for the sidejump...

heres the Spritesheet script. (currently it just creates the rendertexture at 2048x2048, because i cant resize it).


/// <reference path="pixi.js" />
/// <reference path="../Default.html" />

        var sprites = [];
        var pendingSprites = [];
        var spritesheet = {
            //texture: new PIXI.RenderTexture(null, 0,0),
            height: 0,
            width: 0,
            currentX: 0,
            currentY: 0,
            nextY: 0,
            maxX: 0,
            resolution : { x: 2048, y: 2048},
            positionContainer: new PIXI.Container(),
    
            init: function () {
        
                this.texture = new PIXI.RenderTexture(scene.renderer, this.resolution.x, this.resolution.y);
                this.canvas = this.texture.getCanvas();
                this.ctx = this.canvas.getContext("2d");
                this.preview = new PIXI.Sprite(this.texture);
                this.preview.scale.set(0.3);
                this.preview.position.x = 200;
                scene.stage.addChild(this.preview);

                setInterval(this.renderPending, 200);
        
    
            },

            add: function (container, width, height) {

                var that = {};
                that.height = height;
                that.width = width;
                that.rawContainer = container;
                that.container = new PIXI.Container();

                sprites.push(that);
                pendingSprites.push(that);

                return that;
            },

            renderPending: function () {
        
                for (var i = 0; i < pendingSprites.length; i++) {
                    spritesheet.render(pendingSprites[i]);
            
                }


    
            },

            render: function (sprite) {
                //readycheck
                if (!this.readyCheck(sprite.rawContainer))
                    return;

                //Remove from pending
                var index = pendingSprites.indexOf(sprite);
                pendingSprites.splice(index, 1);

                //set ref
                var container = sprite.rawContainer;
                var width = sprite.width;
                var height = sprite.height;

        

                //var container = new PIXI.Container(); //delete


                //Check if next row
                if (width + this.currentX > this.resolution.x) {
                    if (width + this.currentX > this.maxX)
                        this.maxX = Math.ceil(width + this.currentX);
                    this.currentX = 0;
                    this.currentY = this.nextY;
                    this.nextY = 0;
                }

                //update sprite data
                sprite.startX = this.currentX;
                sprite.startY = this.currentY;



                //Update nextY
                if (height + this.currentY > this.nextY)
                    this.nextY = Math.ceil(height + this.currentY);

                //position sprte for render
                this.positionContainer.addChild(container);
                container.position.x = this.currentX;
                container.position.y = this.currentY;
                container.rotation = 0;
                this.currentX += Math.ceil(width);

                //resize rendertexture
                //console.log(this.maxX + "," + this.nextY);
                //this.texture.resize(this.maxX, this.nextY, true);
                //this.texture.width = this.maxX;
                //this.texture.height = this.nextY;


                //render to spritesheet
                this.texture.render(this.positionContainer);
                this.texture.requiresUpdate = true;


                //Generate texture
                //console.log(sprite.startX + "," + sprite.starY)
                var _texture = new PIXI.Texture(this.texture.baseTexture, new PIXI.Rectangle(sprite.startX, sprite.startY, sprite.width, sprite.height));
                var _sprite = new PIXI.Sprite(_texture);
                _sprite.anchor.set(0.5);
                sprite.container.addChild(_sprite);
        

                //console.log(this.currentX + "," + this.currentY + "(" + this.preview.texture.width + "," + this.preview.texture.height + ")");

                //clear position container
                this.positionContainer.removeChild(container);
                this.preview.displayObjectUpdateTransform();
        

                //Dispose raw container
                container.destroy();
  
            },

            remove : function (id) {
                //this.texture.clearRect(0, 0, 500, 500);  
            },

            readyCheck: function (container) {
                //container = new PIXI.Container();
                var ready = true;
                for (var i = 0; i < container.children.length; i++) {
                    if (container.children[i].texture && container.children[i].texture.baseTexture)
                        if (!container.children[i].texture.baseTexture.hasLoaded) 
                            ready = false;

                    if (container.children[i].children) {
                        var childrenready = this.readyCheck(container.children[i]);
                        if (!childrenready)
                            ready = false;
                    }
                }
                return ready;
            }
        }

**Comment by englercj** [comment]
> While i got your attention, I'm also trying to make the PIXI.Mesh.Rope tilable, but if my uvs exceed 1 it just streatches the last pixel. I looked in the src, and noticed that it had to be "Power of two", to enable gl.REPEAT. but i still get the same result.

I would open a second issue about this, jsut to keep things on track.

-----

As for the script you posted. It looks like what you are trying to do is build a sprite sheet based on multiple sprites, but you don't keep sprites around to be rerendered when resizing.

That is going to be really difficult, to achieve; and in fact won't be possible with a since RenderTexture. Ideally you will keep references to the sprites that are the tiles so when you need to redraw you can just redraw them all after resizing. Basically, keep the position container filled with the sprites of the spritesheet. That will let you just render that container to the texture each time you need update it.

If you absolutely cannot keep the sprites in a data structure within this spritesheet, then alternatively you can accomplish what you are trying to do with 2 textures. You would draw to texture A, when it is time to resize you resize (and therefore clear) texture B. Draw texture A onto texture B, then draw the new objects to texture B. Once it is time to resize again you resize texture A, draw B to it, then use A as the active texture.

**Comment by bQvle** [comment]
thanks, i think i will do it that way (two textures), because it might cause spikes if it has to redraw all the containers. (apparently they are heavy to render).

I will open an issue on the Rope thing,

thanks.

**Comment by englercj** [comment]
@bQvle Awesome, I hope it works out for you!
