### ISSUE TITLE
click button to add graphic z-index problem

### ISSUE THREAD

**Issue by supermrji** [GoodBoyDigital/pixi.js#1954]
createBox();

    var line = function() {
        var _lineContainer = new PIXI.Container();
        //stage is main Container
        stage.addChild(_lineContainer);

        function _drawLine() {
            var _graphics = new PIXI.Graphics();
            _graphics.lineStyle(5, _lines[num].color);
            _graphics.moveTo(0, +_pos[1]);
            _lineContainer.addChild(_graphics);
        }
        return {
            draw: function() {
                _drawLine();
            }
        }
    }

I set a `click` event to add a Graphics line ,
why `_drawLine`'s Graphics behind createBox

**Comment by englercj** [comment]
No way to tell from just this code, but things are drawn in order, with later children drawn on top.

**Comment by supermrji** [comment]
createBox();

var line = function() {
    var _lineContainer = new PIXI.Container();
    //stage is main Container
    

    function _drawLine() {
        var _graphics = new PIXI.Graphics();
        _graphics.lineStyle(5, _lines[num].color);
        _graphics.moveTo(0, +_pos[1]);
        _lineContainer.addChild(_graphics);
    }
    return {
        draw: function() {
            _drawLine();
            stage.addChild(_lineContainer);
        }
    }
}

Move `stage.addChild(_lineContainer);` to draw 
This code solve my problem
Thanks
