### ISSUE TITLE
moveto lineto polygon bug,  pixi thinks shape is closed by default.

### ISSUE THREAD

**Issue by whizzkid** [GoodBoyDigital/pixi.js#1956]
while updating my project to pixi3 i noticed some of my graphs were drawn incorrectly.

when drawing the y and x axes, i get a triangle instead of 2 lines..

http://jsfiddle.net/whizzkid74/5kf67grb/

pixi automatically sets closed=true to the polygon shape.  no checking if beginning or ending coordinate are the same after you add points to it (using lineTo)

**Comment by englercj** [comment]
Duplicate #1932 #1844
