### ISSUE TITLE
Tileable Rope

### ISSUE THREAD

**Issue by bQvle** [GoodBoyDigital/pixi.js#1958]
I'm trying to make a tileable version of PIXI.Mesh.Rope.
So that it will repeat a tiled texture along the path. (a road etc.)

But when my UVS exceed 1, it just streaches the last pixel.
I see that the texture has to be "Power of Two" for gl.REPEAT to be enabled, but my texture is 64x64, so that should not be the problem.

I thought of checking the distance between points, and set the uv offset based on that. but i cant get past  (x:1, y:0),(x:1, y:1).

**Comment by englercj** [comment]
Can you create a jsfiddle example the demonstrates what you are trying to do, it makes it a lot easier to iterate on :)

Thanks!

**Comment by bQvle** [comment]
Hi,

Yes heres the fiddle
http://jsfiddle.net/qkk1nwjn/

I haven't done anything yet, other then forsing the UV's to be twice the texture uv for each point/polygon. else its just a copy of PIXI.Mesh.Rope.



If this works the rest should be easy.

**Comment by bQvle** [comment]
NEVERMIND!.... sorry im an idiot...

When i resized my texture in photoshop i didnt notice it was on %.. and not px... so i resized it to 64% not 64px.......

I spend way to much time on such a stupid mistake! :)

My bad....

**Comment by englercj** [comment]
So it was just non-power-of-two and was clamping :P

Glad you got it working!

**Comment by bQvle** [comment]
Yes... i feel so stupid now :)

thanks for listening!

**Comment by bQvle** [comment]
@englercj Here's the final result.

http://jsfiddle.net/qkk1nwjn/1/

If you want you can add it to the library. i don't know if it needs to be a feature of rope though.
