### ISSUE TITLE
Moving displayObjects between containers

### ISSUE THREAD

**Issue by bQvle** [GoodBoyDigital/pixi.js#1967]
I need to move a sprite from one container to another,
Which has different rotation and scale.

But i want to preserve its original world transform. (so it stays at the same location, same size, same rotation).

How would i go about this?

I'm not a math genius, but my guess is that i need to "reverse" the DisplayObject.updateTransform function, and then iterate all the way back to the top parent, and the apply the matrix'es alle the way up to my "target container". apply the x, y, scale and rotation, and addChild on the new parent.
(which I doubt I'm capable off)

Is there a build in, or better way to do it?

**Comment by bQvle** [comment]
The best I've got so far is using worldTransform.apply and applyInverse to get the position right.
The scale i can get by looping back and forth in the hierarchy.
The rotation i haven't solved.

**Comment by englercj** [comment]
Can the container move freely? If so you can copy the values from the other container so the containers are in the same place.

**Comment by bQvle** [comment]
Everything can move/rotate/scale freely. in both child and parent.

It might be easier to understand if i show you. I'm making a level-designer, and I'm currently trying to get all the basic stuff working. (selecting sprites, moving sprites, transforming sprites). 

I want to be able to manipulate multiple sprites at once, thats why i move all the selected sprites to a transform container, apply the transformation to that, and move them back to their original parent.

You can see it here: http://tankwar.io/test/test2.html
Zoom and pan: mouse3 and scroll
drag to select as normal, and rotate in the corners of transform selection.

It works if you only select one sprite, and dont flip the scale. (when only selecting one, the transform selection is aligned 100% to it) but if you flip it, it will start messing up the rotation aswell.

If you select multiple trolls that are rotated, it will continue messing up each transform.

When you start (dragging the handels, moving the container, rotating the container) all the selected sprites is moved to the "transform container(the one you see)". the transform is executed on the container, when releasing the mousebutton, they are moved back to their orignal location.

here is the code I currently have for moving sprites between containers

        function moveChild(child, parent) {
            child.displayObjectUpdateTransform();
            parent.displayObjectUpdateTransform();

            var zero = new PIXI.Point(0, 0);
            var forward = new PIXI.Point(1, 0);
            
            //child angle in parent (faulty)
            child.worldTransform.apply(forward, forward);
            child.worldTransform.apply(zero, zero);
            parent.worldTransform.applyInverse(forward, forward);
            parent.worldTransform.applyInverse(zero, zero);
            child.rotation = Math.atan2(forward.y - zero.y, forward.x - zero.x);


            //update position
            zero.set(0, 0);
            child.worldTransform.apply(zero, child.position);
            parent.worldTransform.applyInverse(child.position, child.position);

            
            //reverse transform for child 
            var _parent = child.parent;
            while (_parent) {
                child.scale.x *= _parent.scale.x;
                child.scale.y *= _parent.scale.y;
                _parent = _parent.parent;
            }

            //get parent hierachy
            var parents = [];
            _parent = parent;
            while (_parent) {
                parents.splice(0, 0, _parent);
                _parent = _parent.parent;
            }

            //reapply transforms
            for (var i = 0; i < parents.length; i++) {
                _parent = parents[i];
                console.log(_parent.scale.x);
                child.scale.x /= _parent.scale.x;
                child.scale.y /= _parent.scale.y;
            }
            
            parent.addChild(child);
        }

**Comment by englercj** [comment]
I think moving objects between containers for the purposes of easily updating multiple transforms will likely be harder than it is worth.

IMO the easiest way to accomplish this would be when to update each selected item with the delta of change that is happening. For example, when I select 3 trolls I just store each as a selected item. Then when I drag to move instead of updating one container with the delta of the mouse move I update all 3 selected trolls.

This keeps the scene the same when transforming, and all you need to do is change your input handler to update all selected items in a loop instead of updating a single transform parent.

**Comment by bQvle** [comment]
That was my first attempt, but that's getting pretty complicated aswell, yes movement would be easy, but not rotation and scalling, because they would need to rotate/scale around the selection origin (anchor in this case). I'd also have to compensate for scale and rotation of the items parent aswell, otherwise X can be multiple directions.

So it would basicly requre the same calculations as moving it to the transform container would.
Later i will need the "moveChild" function anyways, because i'll make a "layer/gameobject" hierarchy.

what i would need though was something like "apply" and "applyInverse" that returned x,y,scale and rotation of an entire object.

**Comment by englercj** [comment]
> because they would need to rotate/scale around the selection origin

Ah, I see, that is a great point. I didn't notice they rotate around the parent pivot not their own.

How about this: Before you move the child cache it's `worldTransform`. Move it to the other container, do stuff to it, then when you go to move it back you can compare the `worldTransform` it has now with what it had previously. That will give you the delta of each component (pos, scale, rot). You can use those deltas to modify the component properties (.position, .scale, .rotation) to where they should be now since they have changed.

Does that make sense?

**Comment by bQvle** [comment]
hmm kind of, though I'm having trouble understanding the matrix, and how to convert, a,b,c,d,tx,ty into actual rotation and scale.

but you want to move them raw without manipulating any data, then compare the matrixes after it has returned to the original container.
then they would glitch visually while transforming.

And it wouldn't solve my case when i actually implement the layer handeling.

**Comment by bQvle** [comment]
Hmmm, thinking about it!

Isn't this actually physically in-achievable.

I mean, if you take a sprite and put it into a box, rotate the sprite 45 degrees,
and scale the box on the y axis.

then the sprite would have to become non-rectangular to stay the same shape?

**Comment by englercj** [comment]
> but you want to move them raw without manipulating any data, then compare the matrixes after it has returned to the original container. then they would glitch visually while transforming.

What I am saying is store the `worldTransform` before dragging. When manipulation is complete, but before you move them back to the other parent do the comparison, update, and transfer at the same time.

Well, rotation changes everything but you can see how the matrix is composed here:

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/display/DisplayObject.js#L275

**Comment by bQvle** [comment]
yeah, but actually i think, its doing (sort of) as well as it can now.

The problem is, when appending a scaled sprite to another container with another rotation, you cant get the same result. that would require the sprite to become non-rectangular. its can only inherit the x and y scales. 

they would become even more distorted if you scale the selection on one axis only. and the result when putting it back to its original parent would have to eather scale in x an y, it cant do the streach that was possible with the Transform-containers rotation. (without putting it in another container to compensate for that).

I looked at unity3d to see how they handled it, and it wasn't possible there either. when scalling a gameobject on x and y, all the children is just scalled locally.

I think i just have to settle at some point, and then the user will proberly learn whats possible when transforming groups of sprites.

If you scale on both x and y its no problem, and if the sprites has the same orientation as the bounding box, its no problem eather.

This should also work when moving between layers, because the layers is just un-transformable containers positioned at 0,0. (primarily for handling grouping of z-index and having a better overview).

When its loaded into the game, it will only use the container as render-order while building the scene.
and keep everything in 2 containers (one rendered bellow, roads, rocks etc.. and one above, treetops, enterable buildings etc.)
