### ISSUE TITLE
NoiseFilter display bug on iOS

### ISSUE THREAD

**Issue by sokeroner** [GoodBoyDigital/pixi.js#1970]
Hi !

I found an issue with the noise filter on iOS devices (tested on iOS 8).
In fact, there is a display bug :

Code Example : [http://jsfiddle.net/oky5cv3j/1/](http://jsfiddle.net/oky5cv3j/1/)
Result : 

![pixi-noise-bug](https://cloud.githubusercontent.com/assets/923990/8633556/45f7a4aa-27ce-11e5-881c-f81b2820cc7c.jpg)

The NoiseFilter is inspired by the [glfx.js noise shader](https://github.com/evanw/glfx.js/blob/master/src/filters/adjust/noise.js), but this filter work well on iOS devices.

Example : [http://evanw.github.io/glfx.js/demo/](http://evanw.github.io/glfx.js/demo/) (select noise filter)
Result :

![glfx](https://cloud.githubusercontent.com/assets/923990/8633558/4d36e99c-27ce-11e5-8591-7dc45c111c52.jpg)

Any idea to fix it ?

Regards,

**Comment by englercj** [comment]
Out of curiosity try changing `precision mediump float;` to `precision highp float;` and see if that changes anything.

**Comment by sokeroner** [comment]
Yeah !
This change fixes the issue.

**Comment by englercj** [comment]
Nice!
