### ISSUE TITLE
Adding ColorMatrixFilter support to Canvas/2d rendering

### ISSUE THREAD

**Issue by pongstylin** [GoodBoyDigital/pixi.js#1971]
Now just in case you try to say "no way, it would be too slow!", I just want to point out that it is little different from how we are supporting Canvas/2d tinting support today.  In my own project, I use ColorMatrixFilter a lot, and it has been a pain to get a "good enough" effect in Canvas/2d when the webgl version looks awesome.  So after realizing that most of the infrastructure is in the pixi code base already to support tinting, I adapted it so that I can get ColorMatrixFilter support as well.  Of course, it doesn't try to support other filter types, but ColorMatrixFilter is very powerful and worth supporting.  I'd be happy to contribute code somehow (I'm not super familiar with the process for that).  But I wanted to first raise it to your attention.  Maybe it is easy for you to add since tinting is similar.  Maybe there are other things to consider.  I'd just like to make this feature part of the main product so that I don't have to deal with merging my changes with new versions of PIXI as I upgrade.  Thoughts?

**Comment by englercj** [comment]
filters are not supported on canvas, the only way to do this would be to use GetImageData, manipulate it and draw it back to canvas. The filter we have written for webgl wouldn't be the code that runs for the canvas version so it would be the creation of an entirely new system built soley for emulating shader effects on canvas. That is way out of the scope of pixi.js

**Comment by pongstylin** [comment]
But tinting uses the getImageData technique as well. That's what I mean by saying the system or infrastructure is already in place. It is not much different. If it required a lot of effort, I would not have attempted it, much less pulled it off in a day. So if this is beyond scope, why wasn't tinting?

**Comment by englercj** [comment]
Because tinting is done once on change and cached. Filters are dynamic. They have arbitrary code, they have parameters that change, they can be applied to arbitrary objects, they may have multiple passes, they may have multiple render targets,  etc. 

Comparing filters to tint isn't a fair comparison. There is a huge difference between implementing a single cached pixel manipulation on a texture and building a system for running shader-like code on an array of pixels on the cpu. Tinting is stupid slow, but luckily almost never changes and so we can pretend it is a one time cost. That isn't true for nearly all filters. 

If you got color matrix filter working how you want on canvas for your app, that's awesome. But if we did it in core we would need to support all major use cases of all filters which is almost always highly dynamic,  rapidly changing data (see noise, displacement, lighting, etc). Try running getImageData, manipulating the pixels, and putting it back every frame for multiple objects. There is no way to make that scale on the cpu. The only way to reliably do it is to make it work for the application specific way you need it to, which is out of the scope of pixi.

**Comment by pongstylin** [comment]
Before I continue, I want to thank you for discussing this with me.  I don't want a context where I am in one camp and you are in another camp, and we are battling out our differing views until one wins and one loses.  My real goal is to discuss the obstacles, to have a constructive conversation, to dig deep into the problems inherent to trying to accomplish ColorMatrixFilter support in 2d canvas rendering and then speculate on how we might overcome them.  At the end of the conversation, we may mutually decide if it is worth it or not.

You've touched on several things, but for the sake of moving the conversation along briskly, I'll make some broad statements that address most of them and respond to the rest if they come up again as a significant issue.

1) I'm not sure what to make of "major use cases".  I assume that some sort of analysis was made to determine what they are, like assessing a sampling of maybe 100 projects in the wild to determine common trends.  Otherwise, this is subjective and arbitrarily determined.  It also suggests that the most common use cases are considered to prioritize efforts so that you get the most bang for your buck.  But this doesn't necessarily mean edge cases should never be supported.  It's just lower in priority.  And if some nice fella wants to come along and improve the capabilities of the product for free, all power to him.  This is assuming the product is not hurt by the changes in some way.

2) So if "major use cases" isn't the driver of a product's scope.  Then, what is?  Well, two of PIXI's major selling points (to me at least) is its speed and its ability to fallback from WebGL to Canvas as necessary.  So I understand that anything about PIXI that is slow makes it look bad.  But if the fallback from WebGL to Canvas is useless because of missing functionality, it also makes PIXI look bad.  So I don't think my suggestion is truly out of scope.  I think it is just difficult to meet our sometimes-conflicting design goals.

3) So the real question is if the product is hurt in any way if ColorMatrixFilter support is added to 2d canvas.  I suggest that there are 4 types of projects in relation to this change:
a) Projects that don't use ColorMatrixFilter. (obviously not affected)
b) Projects that have required ColorMatrixFilters and restrict themselves to WebGL.  (not affected)
c) Projects that have optional ColorMatrixFilters and 2d context, but use filters heavily and would be slowed down unacceptably in 2d context. (adversely affected)
d) Projects that have required ColorMatrixFilters and 2d context, but use filters lightly or otherwise cached effectively. (positively affected)

It is hard to say if (c) is more common than (d).  But commonality just factors into priority, right?  Assuming (c) projects are even a real thing, they should always be tested against the latest pixi version before release.  If they are really slowed down too much, then some mechanism can be provided to disable filters in 2d context.  I do know that projects in (d) is a real thing.  I have a board game that has proven to perform well in slow browsers (firefox) and slow devices (apple and android phones) using very dynamic ColorMatrixFilters in 2d context.

So these are my thoughts for catering to every use case, as opposed to just the major use cases.  But this is assuming that any coding difficulties can be solved creatively (i.e. detecting when filters get dirty, caching, and utilization).

**Comment by englercj** [comment]
Thanks for the well thought out response. I think where we are having differences is that you are confusing "supporting color matrix" on canvas with "supporting filters on canvas". Those two statements are very very different.

I think the other thing we are miscommunicating on is that there is a difference between "support filters on canvas in pixi's core library" and "write a plugin to add filter support to canvas".

When I say "most use-cases" I mean most use cases of filters. Look at the filters we have:

https://github.com/GoodBoyDigital/pixi.js/tree/master/src/filters

Very, very few of them are run once and done. Almost all of them are dynamically changing which means that is what we would have to support in pixi. I am not comfortable putting in a feature that we know will have poor performance. That doesn't mean there is any reason not to build it into a plugin that you can use in your app and share with the community. Keeping the core as lite as I can makes it easier to maintain, and easier for people to only get what they need.

If you want to abstract your code into a plugin, please do it and add it to this list:

https://github.com/GoodBoyDigital/pixi.js/wiki/Pixi-v3-Plugins

I'm sure you are not the only one who would want this feature for certain apps. Hopefully this makes sense.

**Comment by pongstylin** [comment]
Some of the differences you describe was evident.  I did hammer the term "ColorMatrixFilter" over and over again in my last post to stress that I wasn't suggesting that we support all filter types in canvas.  My initial argument was that ColorMatrixFilter, given how powerful it is, may be worthwhile to support individually (in the core) like tinting being a common need.  But I also appreciate that it may seem oddly unique and confusing to support that but not other filters in canvas.  Filters do come in many shapes and sizes and trying to recreate them all "manually" for 2d canvas as well as in shaders for webgl seems quite redundant.

So what I'm saying is, I can live with it being a plugin.  But that takes me back to my original need: I don't love the idea of spending time merging my changes into future versions of pixi as it grows.  If I create a plugin, will it need to be updated for the lifetime of PIXI v3? (I understand that v4 may require an update)  Perhaps there is a guide (best practices) for ensuring it won't need updates for the lifetime of v3?

**Comment by englercj** [comment]
> My initial argument was that ColorMatrixFilter, given how powerful it is, may be worthwhile to support individually (in the core) like tinting being a common need

I misunderstood this, I thought you wanted us to support filters in general.

> If I create a plugin, will it need to be updated for the lifetime of PIXI v3?

Hopefully not, we try to follow semver as much as is reasonible especially with breaking changes. I try really hard to not have breaking changes. Likely you will not have to update the plugin very often or at all through the v3 lifetime.

**Comment by englercj** [comment]
Closing this for now.
