### ISSUE TITLE
Sprite tint does not work with ParticleContainer

### ISSUE THREAD

**Issue by karimbeyrouti** [GoodBoyDigital/pixi.js#1972]
Not sure if this is broken ( looking at souce it is not in optimised Particle* code ) however example http://pixijs.github.io/examples/index.html?s=demos&f=batch.js&title=Particle%20Container has tinting code for ParticleContainer sprites.

**Comment by sergebat** [comment]
Current docs for the ParticleContainer suggests it is not supported:
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/particles/ParticleContainer.js#L4-L8

"Any other functionality like tinting, masking, etc will not work on sprites in this batch."

So, unless something new is coming up, it is example that needs fixing to remove this line. :)

**Comment by englercj** [comment]
This is not a feature supported in ParticleContainers, if you need to use tint then use a normal Container.

**Comment by karimbeyrouti** [comment]
Thought as much. Thank you for the update.
