### ISSUE TITLE
BitmapText.font property is not documented

### ISSUE THREAD

**Issue by sergebat** [GoodBoyDigital/pixi.js#1973]
BitmapText.font property works great (and part of .d.ts as expected), but not documented at the moment:
http://pixijs.github.io/docs/PIXI.extras.BitmapText.html

Its use is clear from the constructor doc, but I thought I'd mention it anyway (as for a second I thought I'd have to re-create BitmapText instance just to change the font size :) ).

**Comment by englercj** [comment]
It is documented in code, likely the docs just need to be regenerated.

https://github.com/GoodBoyDigital/pixi.js/blob/master/src/extras/BitmapText.js#L156

**Comment by sergebat** [comment]
> It is documented in code, likely the docs just need to be regenerated.

Just FYI. Same issue with many filters - such as http://pixijs.github.io/docs/filters_blur_BlurFilter.js.html (doc is in the code, but not in the generated doc). Their doc is particularly confusing, as no properties are documented at all:
http://pixijs.github.io/docs/PIXI.filters.BlurFilter.html

Given that SRC in the doc itself is reflected correctly, maybe this is something with the doc tool setup?
