### ISSUE TITLE
ERASE for PIXI.BLEND_MODE 

### ISSUE THREAD

**Issue by dakom** [GoodBoyDigital/pixi.js#1976]
Would be so awesome if such a blend mode existed (esp for WebGL).... ;)

**Comment by englercj** [comment]
Is this a blend mode that canvas supports? Can you link some spec/support docs for ERASE? I'm not familiar with this blendMode.

**Comment by wayfu** [comment]
destination-out looks like a good candidate.

**Comment by dakom** [comment]
Ah, I'm unfamiliar with Canvas/WebGL... porting a project from Flash/Starling which had ERASE blendmode for RenderTexture- http://doc.starling-framework.org/current/starling/display/BlendMode.html#ERASE

**Comment by wayfu** [comment]
this post may be of interest to you: http://www.html5gamedevs.com/topic/10849-is-it-possible-to-subtract-a-graphics-shape-from-another-shape/?p=89926

also here's the source code from starling that sets up their blendFunc parameters:
https://github.com/Gamua/Starling-Framework/blob/8e61b55c32e0ec2ed7b3e4a4c8bdc39747e3862d/starling/src/starling/display/BlendMode.as

@englercj comparing this to the pixi blendmodes, it looks like you guys are using a mix of premul and non-premul blendings. may be something to spend a bit of time on evaluating; as far as i know PNG is never premultiplied...

**Comment by wayfu** [comment]
Just tried the starling normal settings and they do look wrong with my test cases.

**Comment by englercj** [comment]
> comparing this to the pixi blendmodes, it looks like you guys are using a mix of premul and non-premul blendings. may be something to spend a bit of time on evaluating; as far as i know PNG is never premultiplied..

You should open a new issue with a running example showing the incorrect modes, as well as an exmaple of what they should be. I'd be happy to fix it up!

**Comment by wayfu** [comment]
I don't think they're incorrect really, I tested them against the starling modes and pixi's looked better/more correct in my cases.

**Comment by englercj** [comment]
@wayfu Ah, ok I guess I misread that :P

**Comment by englercj** [comment]
Closing this since it is going off topic, and we only support native blend modes.
