### ISSUE TITLE
Using a constantly updating canvas as a Texture

### ISSUE THREAD

**Issue by AndreasDilaveris** [GoodBoyDigital/pixi.js#1980]
Hi guys,

First off thanks for an amazing opensource product.  Using it is a learning experience in and of itself. 

I am trying to achieve the following: Create gradients with alpha on a canvas ( that will change on animationFrame) apply them to a Texture and then to a Sprite - then apply this Sprite as another Sprite's mask.  An example goal would be a gradient wipe, but obviously not limited to just this effect.  

I'm looking for the most optimum way to apply this - canvas sourced, animated Texture, to a Sprite. 
Do I have to constantly use .fromCanvas? Is there something cleverer?

Also doing something like the above; will I be able to take advantage of webgl?

Hope that makes sense.  I'm a few days into pixi use and I'm already hooked.

Thanks

**Comment by englercj** [comment]
You only need to use fromCanvas() once. Then just let pixi know the texture needs to be updated:

```js
var texture = PIXI.Texture.fromCanvas(canvas);

// update the texture when you redraw the canvas
texture.update();
```

Just note that it will be a GPU upload each time you update, doing this for many textures or for long periods of time may incurr some performance hits.

**Comment by AndreasDilaveris** [comment]
Thank you for the reply that's very helpful.
Are complex masks based on canvases not considered a good technique?  My knowledge of webgl and GPU performance is sub-basic so I'm not sure what constitutes 'many textures'.  Say 25fps update of 1024x768 canvas (masks) x15 ? I shouldn't even really be asking, I should just be building,  but maybe someone else will find that info useful too?

Again thanks for the response and answer

Andreas

**Comment by englercj** [comment]
Each time you call `.update()` we have to upload a new texture to the GPU, which can be expensive. YMMV, but just be aware that is can cause performance issues. Nothing is better than testing :)
