### ISSUE TITLE
Fullscreen-Mode with pixi.js

### ISSUE THREAD

**Issue by damian82** [GoodBoyDigital/pixi.js#1984]
Is it possible that native fullscreen-modes of browsers are not supported in pixi.js? I didn't find an example nor a manual, where fullscreen mode is used.

    canvas = document.getElementById("canvas");
    stage = new PIXI.Stage(0x000000);
    renderer = PIXI.autoDetectRenderer(1024, 768, canvas);

When I now want to call fullscreen. The browser actually turns to fullscreen mode but just shows a black screen. 

    if(canvas.webkitRequestFullScreen) {
        canvas.webkitRequestFullScreen();
    }
    else {
        canvas.mozRequestFullScreen();
    }
    
When I use the context environment to draw (and not the pixi renderer), everything works fine

    var ctx = canvas.getContext("2d");

So my question is: Is it possible to activate fullscreen mode with pixi renderer and if yes: what element do I have to make fullscreen and what elements do I have to attach to it?

**Comment by englercj** [comment]
Does this only happen with the WebGL renderer? Does using the CanvasRenderer work as expected?

**Comment by damian82** [comment]
Thanks for your reply. When I use 
    renderer = PIXI.CanvasRenderer(1024, 768, canvas);
or 
    renderer = PIXI.WebGLRenderer(1024, 768, canvas);
the screen stays black. And when I turn off WebGL manually in firefox and use the autodetect
    renderer = PIXI.autoDetectRenderer(1024, 768, canvas);
no sprites are drawn (but the background is white)

Do you have any idea due to what this is? Is there probably an issue i didnt pay enough attention to?

**Comment by englercj** [comment]
There must be something weird happening in your application, check the developer console.

I made a quick test page and it worked perfectly:

```js
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />

        <title>Testing</title>
    </head>
    <body>
<script src="bin/pixi.js"></script>

<script>
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

// create a texture from an image path
var square = new PIXI.Graphics();
square.beginFill(0xFFFF00);
square.drawRect(100, 100, 100, 100);
stage.addChild(square);

// start animating
animate();
function animate() {
    requestAnimationFrame(animate);

    // render the container
    renderer.render(stage);
}

renderer.view.addEventListener('click', function () {
    renderer.view.webkitRequestFullscreen();
});

</script>


    </body>
</html>
```

**Comment by damian82** [comment]
Thanks for your time. 

I saw that you applied the fullscreen on the renderer.view which I haven't tried. I will have a look at it tomorrow.

**Comment by englercj** [comment]
`renderer.view` is the canvas element the renderer is drawing to.

**Comment by englercj** [comment]
Oh, now i see the error in your code. The third param to a renderer is not a canvas element it is the options argument.

http://pixijs.github.io/docs/PIXI.html#.autoDetectRenderer

You are getting your problems because you are trying to fullscreen a canvas that pixi isn't using, so of course it has no values.

**Comment by damian82** [comment]
Oh yeah, this solved the problem. Thank you so much!
