### ISSUE TITLE
Time Series with Graphics 

### ISSUE THREAD

**Issue by iskdjim** [GoodBoyDigital/pixi.js#1991]
hi,
i am working on a time series chart an i use the Graphics Class to draw lines. (moveTo, LineTo)
now i would like some interaction with the lines, for example click events or mouse over.

The graphic object has such funcitions, but as i read it is important to define a hitarea.
How do i define such a hitArea for lines?

thanks

**Comment by englercj** [comment]
`hitArea` can be any shape, including a polygon.

**Comment by iskdjim** [comment]
yeah...but for a polygon i need more point datas i think...?

if i have 4 points:
p1(0,0)
p2(40,100)
p3(50,150)
p4(100,200)

i draw lines like this

moveTo(0,0)
lineTo(40,100)
lineTo(50,150)
lineTo(100,200)

then i set linestyle(5, color)

i now i have the drawn lines.

but how to i get out of this data points a hit area for each line...?

**Comment by englercj** [comment]
Construct a polygon that traces the lines :)

**Comment by iskdjim** [comment]
sounds good, thx. in de documentation i read that the draw polygon funciton needs a path array.
what exectly is this array. an array auf points? sorry for the "stupid" question..cant find the exact explaination

**Comment by englercj** [comment]
You don't need to draw a polygon, you need to create a `PIXI.Polygon` object and assign it to `.hitArea`.

**Comment by iskdjim** [comment]
ok, so if i want a hitarea for line p1(50,100), p2(50,200) i have to generate for example 4 points out of it do draw a polygon rectangle? or is it in some way possible, to make a polygone only with the 2 points and a line width? like i do it with the lineto function and linestyle.
do you understand what i mean?

**Comment by englercj** [comment]
> i have to generate for example 4 points out of it do draw a polygon rectangle

Yes!

> or is it in some way possible, to make a polygone only with the 2 points and a line width?

No!

> do you understand what i mean?

Yes!

**Comment by iskdjim** [comment]
oh thats bad ;), horizontal and vertikal lines would be no problem, but a diagonal will make some problems with the "width" and the exact points.

anyway, thanks for your help and time

**Comment by englercj** [comment]
Anytime!
