### ISSUE TITLE
Loaded images added to TextureCache with url

### ISSUE THREAD

**Issue by ahumphreys87** [GoodBoyDigital/pixi.js#1994]
I'm currently moving from Phaser to Pixi and I've noticed a difference in the loaders. In Phaser you are able to load an image from cache using the `name` you give to the asset during load - in Pixi the Texture is stored in TextureCache with `url` as the key.

Is there a reason this is not `name`? looking at the code it seems `name` defaults to `url` if it is not supplied - I think this would give users the best of both worlds?

I might have missed something but I think its a matter of changing: https://github.com/GoodBoyDigital/pixi.js/blob/master/src/loaders/textureParser.js#L12

to:

```
core.utils.TextureCache[resource.name] = resource.texture;
```

**Comment by englercj** [comment]
The texture cache is an internal mechanism to power the convenience methods of `.fromImage()`.

The loader "cache" is the resources object on the loader. It is keyed by the name you pass in.

```js
PIXI.loader.add('derp', 'file.png').load(function (loader, resources) {
    // the resources object is the loader's "cache", keyed by the loaded name.
    // resources === loader.resources === PIXI.loader.resources
});

**Comment by ahumphreys87** [comment]
@englercj so to use these resources from `PIXI.Sprite.fromImage` I need to pass the url? Wouldn't it make more sense to key the TextureCache by name, falling back to url if name is not present?

**Comment by englercj** [comment]
That isn't what `.fromImage()` is:

http://pixijs.github.io/docs/PIXI.Texture.html#.fromImage

The first parameter is a URL, it is for creating a texture from a url. If you don't want to use a url then don't use that API.

In fact, if you are using the loader it already creates a texture for you; just use it:

```js
PIXI.loader.add('derp', 'file.png').load(function (loader, resources) {
    console.log(resources.derp.texture);
});
```

**Comment by ahumphreys87** [comment]
Ok thanks, i think this is probably just me getting confused when switching from phaser's api.

I expected to be able to:

```
PIXI.loader.add('derp', 'file.png').load(function () {
    var mySprite = PIXI.Sprite.fromImage('derp');
});
```

**Comment by englercj** [comment]
@ahumphreys87 Nope! :)

That isn't what that API was created for, or should be used for. Just use the loader resources, you will create less objects that way anyway.
