### ISSUE TITLE
Renderer not defined when point checking.

### ISSUE THREAD

**Issue by TomSlezakowski** [GoodBoyDigital/pixi.js#1998]
Line : 28730

Seem's like the renderer isn't being passed into this function, fires out an error :(

`var ray = math3d.getRayFromScreen(point, renderer);`

**Comment by englercj** [comment]
I don't know what `math3d` is...

There are also not 28k lines in the pixi output, so I'm not sure you are at the right place.

**Comment by TomSlezakowski** [comment]
Oh sorry, this is suppose to be for the dev-flip branch!

**Comment by englercj** [comment]
Ah, that branch is highly in flux and isn't yet released. If you use it, you should build it yourself.

Looks like what you mentioned is actually fixed in the source just the build isn't updated:

https://github.com/GoodBoyDigital/pixi.js/blob/dev-flip/src/flip/index.js#L304-L308
