### ISSUE TITLE
Blurry text when using resolution flag

### ISSUE THREAD

**Issue by doskallemaskin** [GoodBoyDigital/pixi.js#2000]
When using resolution flag to scale content of a webpage, the texts get blurry. See js fiddle: http://jsfiddle.net/mz7mb70e/

Wouldn't it be better to instead of scaling by the resolution, increasing the font size by the resolution factor? Or is there a font option as with the @x2 @x4 images?

**Comment by englercj** [comment]
Either pass in the resolution parameter to the `PIXI.Text` [constructor](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/text/Text.js#L42), or change `PIXI.RESOLUTION` to the value you need.

Updated fiddle:
http://jsfiddle.net/mz7mb70e/1/

Unifying these params is being tracked here: #1841
