### ISSUE TITLE
how do I pass an array of vectors to a fragment shader?

### ISSUE THREAD

**Issue by mreinstein** [GoodBoyDigital/pixi.js#2004]
I'm not getting the values I'd expect when passing things in. I suspect I'm not declaring things right, somewhere...

my fragment shader:

```
precision mediump float;
uniform vec2 position[4];

void main(void) {
   // do something with 3rd vector, position[2]
  gl_FragColor.rg = position[2];
}
```

my filter:

```coffeescript
class MyFilter extends PIXI.AbstractFilter
  constructor: ->
    uniforms =
      position:    { type: '2fv', value: new Float32Array(8) }
    super null, frag, uniforms
```

my calling code:
```coffeescript
idx = 0
mycars = [ ... ]  # holds 4 car objects
for car in mycars
  myFilter.uniforms.position.value[idx*2] = car.pos.x
  myFilter.uniforms.position.value[idx*2+1] = car.pos.y
  idx++
```

For some reason this doesnt seem to work. Any ideas what I'm doing wrong?

**Comment by mreinstein** [comment]
I've also tried passing data directly into the uniform, which works:

```
uniforms =
      position:    { type: '2fv', value: [ 20, 30,  40, 40,  100, 20,  200, 90  ] }
```
 but I still can't seem to update the values at runtime.

**Comment by englercj** [comment]
Hmm, that code should work fine. The uniforms should be [synced for you](https://github.com/GoodBoyDigital/pixi.js/blob/master/src/core/renderers/webgl/managers/FilterManager.js#L287). Any chance of getting a running example?

**Comment by mreinstein** [comment]
Okay, well the fact that you're confident the syntax looks right gives me some confidence that it's probably a bug elsewhere in my code. I'll close this and keep investigating. If it turns out to be anything on the pixi side I'll re-open.

Thanks for your help!
