### ISSUE TITLE
InteractionManager Proposal

### ISSUE THREAD

**Issue by drkibitz** [GoodBoyDigital/pixi.js#241]
I can't remember if I brought this up somewhere else, if I did, sorry for the reiteration. I have tried to create this issue to be a more standard proposal conveying my thoughts on pixi.js's InteractionManager.

Currently it does allow for interactivity, which is pretty much what a name like InteractionManager means. What this doesn't mean is that it should be coupled with DOM events and cross platform compatibility. It should instead take a more *hands-off* approach to handling interactivity from different input devices.

### PIXI.Stage (refactor)

The Stage can be simplified by removing much of the current InteractionManager logic it contains, but it may instead provide direct access to methods such as:

- `PIXI.Stage.prototype.getDisplayObjectAtPoint(x, y)`
- `PIXI.Stage.prototype.getInteractiveDisplayObjectAtPoint(x, y)`

Doing this, the logic within the stage can be much more focused on pixi.js's display list, and optimization. Such as what display object should dispatch events, etc..

### PIXI.InteractionManager (refactor)

The InteractionManager does not need to contain the platform compatibility code that it does now, and can be much more decoupled from everything, which means basically it becomes completely optional. This doesn't mean the cross platform code can't be moved to another optional module. A new API may look more like this:

- `new PIXI.InteractionManager(stage, view)`

  >stage is optional, set InteractionManager.prototype.stage to value passed
  >view is optional, set InteractionManager.prototype.view to value passed
- `PIXI.InteractionManager.prototype.handleStart([interaction], stage, view)`

  >stage and view are optional. Default to properties that may be set, throw error if no valid references.
- `PIXI.InteractionManager.prototype.handleMove([interaction], stage, view)`

  >stage and view are optional. Default to properties that may be set, throw error if no valid references.
- `PIXI.InteractionManager.prototype.handleEnd([interaction], stage, view)`

  >stage and view are optional. Default to properties that may be set, throw error if no valid references.
- `PIXI.InteractionManager.prototype.handleCancel([interaction], stage, view)`

  >stage and view are optional. Default to properties that may be set, throw error if no valid references.

The `[interaction]` argument is specified as an array to handle simultaneous interactions. Each interaction object should adhere to an interface of something like this:
```javascript
{
    id: 123,        // For tracking the total interaction between 'start', 'move', 'end', and 'cancel' 
    timeStamp: 123, // To check whether to handle or drop this event
    pageX: 123,     // Converted to PIXI.Stage coordinate space (relative to renderer.view), then used to get the pixi interactive target
    pageY: 123      // Converted to PIXI.Stage coordinate space (relative to renderer.view), then used to get the pixi interactive target
}
```

### PIXI.Interaction (new)

There can be a helper `PIXI.Interaction` that provides methods like:

- `PIXI.Interaction.fromMouseEvent(event)` returns Array of objects
- `PIXI.Interaction.fromTouchEvent(event)` returns Array of objects 
- `PIXI.Interaction.fromPointerEvent(event)` returns Array of objects
- `PIXI.Interaction.fromAutoDetectEvent(event)` as a really *nice-to-have*

### Interaction Events

The InteractionManager can then tell display objects to dispatch events for 'click', 'start', 'move', 'end', and 'cancel' respectively.
The event passed to a listener added to a display object could look like this:
```javascript
{
    type: 'start',   // 'click', 'start', 'move', 'end', 'cancel'
    interaction: {}, // interaction passed
    target: {},      // The PIXI.DisplayObject interacted with
    stageX: 123,     // The PIXI.Stage x coordinate the interaction was converted to
    stageY: 123,     // The PIXI.Stage y coordinate the interaction was converted to
    x: 456,          // The event.target coordinate the interaction was converted to
    y: 456           // The event.target coordinate the interaction was converted to
}
```

**This I'm not certain of. It would be much easier, and maybe a more simple approach to just let the manager dispatch these events, and leave the display list to handle what is actually interactive.**

## Usage

Please review the following gist:
https://gist.github.com/drkibitz/6127080

## Conclusion

pixi.js is a great rendering engine, but I don't believe a rendering engine should try to handle DOM events directly. It should instead provide an API that allows an efficient, abstracted, and standard approach to interactivity that any platform's specific event implementation can hook into.

**Comment by sbondor** [comment]
@englercj Why reinvent the wheel when there are good mouse/interaction functionality designed in other libraries? 
Take a look for instance at Qt library's implementation (QWidget is like a DisplayObject):
http://qt-project.org/doc/qt-4.8/qwidget.html#mouseMoveEvent 
http://qt-project.org/doc/qt-4.8/qmouseevent.html

**Comment by GoodBoyDigital** [comment]
Closing this for now. InteractionManager has been rebuilt for v3 and  is now optional as it is 100% separate from the core. Thanks all!

**Comment by drkibitz** [comment]
Hello, got an alert upon closing this issue so thought I'd look at the progress of the dev branch. I see the direction taken within the `interaction/` directory, and very impressed with the amount of work going into the next version of this lib, great job! I have to be honest though, the interaction direction is a bit confusing out of the gate.

Also just saw a typo here:
https://github.com/GoodBoyDigital/pixi.js/blob/dev/src/interaction/interactiveTarget.js#L6

Sorry, this was just quick perusal, no time for any official contribution at this time, but hopefully in the future. Good luck on v3!
