### ISSUE TITLE
Expose spine object

### ISSUE THREAD

**Issue by GorshSerginio** [GoodBoyDigital/pixi.js#258]
Right now spine object (the one from spine runtimes) is private inside PIXI library.
Sometimes it's needed to change existing animations programmatically in runtime (for example an animation could depend on the distance to interacted object).
The way it can be done is described here: http://esotericsoftware.com/spine-using-runtimes/#animation-changes
For that case we need an access to spine runtimes objects. The easiest way to do that is to make spine object a field of PIXI:
```javascript
...
var spine = {};
...
PIXI.spine = spine;
```
But I'm not sure, that that's the best way since there is already a PIXI.Spine object.
Maybe you've got some better ideas?

**Comment by englercj** [comment]
spine runtime is exposed in v3
