### ISSUE TITLE
Node pixi.js (modular and browserified)

### ISSUE THREAD

**Issue by drkibitz** [GoodBoyDigital/pixi.js#307]
See branch here: https://github.com/drkibitz/node-pixi

- The branch does not contain final builds of the browserified bundle. To get these and test the examples, simply check out that branch and run `grunt` to make the bundles and distribute to examples as normal. **You need Firefox installed for the unit tests to pass.**
- After this run `grunt connect` as normal to see the examples run as expected. **There were no modifications made to any example.**

**Comment by englercj** [comment]
This has finally happened :)

**Comment by ddennis** [comment]
If we don't want to compile the lib, is this still the recommend way of using pixi with browserify?

    npm install --save GoodBoyDigital/pixi.js 

/Dennis

**Comment by englercj** [comment]
you can just do `npm i -S pixi.js` no need to try and pull it from github.

**Comment by ddennis** [comment]
Hi 

Sorry - i didn't know pixi was officily on npm. I kept getting https://www.npmjs.com/package/pixi which is deprecated.

Thanks for your time 

/Dennis
