### ISSUE TITLE
Texture cache collision (assets incorrectly shared)

### ISSUE THREAD

**Issue by ryanmcnz** [GoodBoyDigital/pixi.js#312]
When having multiple Spine objects in the Pixi stage that each contain separate assets, they have texture cache conflicts with said assets that share the same names in their skin/JSON hash file.
My suggested fix for this is implementing the use of IDs in the texture cache, eg. perhaps using a UUID rather than just using the image name.

Here is a simple example I made using the AssetLoader, to show this issue:
http://www.mediafire.com/download/eq81sgt15ls5lnj/asset_spine_test.zip

This contains two cannons made in Spine that are purposely in separate files.
These have the same bone names and image names in their skin...but use different texture files, JavaScript objects, etc.

Technically their assets shouldn't clash in the cache.
An example of where this could be an issue is if I had a dog and a human, but they both contained an image reference in their skin called "head", this issue would then occur.

To load these in, I've created two sets of objects with different names in JavaScript, to show that it isn't a conflict with something such as only having one AssetLoader or recycling other objects.

When loading this example, it has a random occurrence of either showing the two cannons correctly with their different textures, or randomly showing two cannons that look the same (aka duplicating assets between them for no reason).

My solution to this issue was to give all my spine skins heavily unique image names such as:
"cannon1_img_head", instead of "head".

**Comment by englercj** [comment]
This works differently in v3 now with the new loader system.

**Comment by PainKKKiller** [comment]
I use pixi.js  v4.5.2, I have a lot of spritesheets containing sequences of frames with names 001.png, 002.png ... etc, and I have a lot of warnings in my console which looks like this:
`bundle.js:19178 Texture added to the cache with an id [001.png] that already had an entry`
so I suppose this issue still isn't resolved?

**Comment by englercj** [comment]
Can you open a new issue with a running example of the problem you are having please?

**Comment by PainKKKiller** [comment]
Ok, I'll try to do a reproducible example

**Comment by gle6da** [comment]
Hey, the problem still here. Created new issue here: https://github.com/pixijs/pixi.js/issues/4156
