### ISSUE TITLE
Interactions don't work until you render stage twice

### ISSUE THREAD

**Issue by pjanik** [GoodBoyDigital/pixi.js#346]
Hi,

please take a look at this example:
http://jsfiddle.net/jL7Ce/

Looking at source and docs, I would expect that my mousedown handler should be executed when I click a circle. However unless you set ```renderTwice``` to true, it won't work.

Also I'm a bit unsure about these lines:
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/InteractionManager.js#L145-L149

This assumption there we need at least 33ms between updates can work fine during the animation, however consider such scenario:

1. render stage
2. remove all sprites, create a new set of interactive sprites
3. render stage again

The Interaction Manager update should be performed, but if there is less than 33ms between 1. and 3., it won't happen. This seems to cause problems in our app, where rendering can be triggered by user actions, initialization code etc. and we don't always use animation.

**Comment by englercj** [comment]
Interactions and the stage (any particular DO) will be decoupled in v3.

**Comment by GoodBoyDigital** [comment]
this should work like a champ in v3 now. One render and you should be good to go :+1:
