### ISSUE TITLE
SpriteSheet Bug - Rotated Sprites do not display correctly.

### ISSUE THREAD

**Issue by kidkarma** [GoodBoyDigital/pixi.js#387]
When I generate a Sprite sheet from Flash or TexturePacker, there is an option to rotate graphics so they fit better. The JSON document gives the objects a property "rotated": true.
The Spritesheet loader should be able to recognize this property, and correct the rotation, but it doesn't. Graphics are displayed on screen as rotated.

**Comment by englercj** [comment]
Want this to happen, I think I can get it to work with just the vertex shader.

**Comment by GoodBoyDigital** [comment]
closing in favor of #1335
