### ISSUE TITLE
Access to Scaling Spine JSON Data

### ISSUE THREAD

**Issue by choppingblock** [GoodBoyDigital/pixi.js#402]
The spine runtimes support the ability to scale the animation data, allowing us to scale the bone positions, image sizes, and animation translations on load.

Really handy if we want to load alternate resolution artwork. 

http://esotericsoftware.com/spine-using-runtimes/#scaling

**Comment by englercj** [comment]
Closing this now, spine implementation is totally exposed in v3. Shouldn't be an issue anymore.

**Comment by yysdsyl** [comment]
test
