### ISSUE TITLE
Standard JavaScript / HTML colors

### ISSUE THREAD

**Issue by J4G-** [GoodBoyDigital/pixi.js#458]
I know this is super low priority, but for someone trying Pixi.js for the first time, it's a little bit confusing when they try to set the stage color and realize that the colors must be in the format 0x00ff3f. Nearly every other plugin uses the standard CSS representation of hex colors, "#00ff3f". It would also be fantastic to be able to use the format "Rgb(0,0,0)". Just a small thing, but I don't think it would be super complicated to change.

**Comment by englercj** [comment]
Closing this since we use numbers to represent colors everywhere in PIXI now. Use another module to convert if you need it.
