### ISSUE TITLE
Question : Movie Clip and Animations

### ISSUE THREAD

**Issue by Dhumez-Sebastien** [GoodBoyDigital/pixi.js#471]
Hi (it's me again and again... ^^)

I work with some Movie Clip and i've some remarks.

I've see the animation is based on FPS. If the FPS is slow the anim is really... really slow ^^

Something else, maybe in futur it's possible to param Movie clip to begin a Clip at frame 1 for exemple?

I do this : 

```js
if (this._animable && this.timeAnim < Date.now() - 1000 / this.animSpeed) {

                this.currentFrame++;

                if (this.currentFrame >= this.maxFrame)
                    this.currentFrame = 1;

                this.currentAnim.gotoAndStop(this.currentFrame);

                this.timeAnim = Date.now();
            }
```

**Comment by englercj** [comment]
Going to track this in #1376.
