### ISSUE TITLE
DropShadowFilter and GlowFilter

### ISSUE THREAD

**Issue by master4523** [GoodBoyDigital/pixi.js#484]
Would it be possibe to add some filters similar to DropShadowFilter(1) and GlowFilter(2) from Flash?

Ref:
(1) http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filters/DropShadowFilter.html
(2) http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filters/GlowFilter.html

**Comment by englercj** [comment]
Bloom filter is in v3 :)
