### ISSUE TITLE
wordwrap broken?

### ISSUE THREAD

**Issue by SebastianNette** [GoodBoyDigital/pixi.js#502]
Hi Guys,

I just updated my pixi files on my apps and now the wordwrap is not working anymore.
http://jsfiddle.net/MbU3Z/

Can you please fix it? ;)

Also, could you add an option to simply cut the text if it exceeds the wrapwidth?
I'm currently doing this:

text.setText(text.wordWrap(text.text).split('\n')[0]);
text.updateText();

But that way I would do the wordwrap twice. Since pixi is doing the wordwrap anyway, maybe add a parameter like "cut" which is 0 (false) by default, and you can set the number of max lines that you want to actually display. Maybe optional with "..." at the end ;)

**Comment by englercj** [comment]
Pretty sure this is fixed in latest dev.
