### ISSUE TITLE
JSON format used when loading sprite sheets is not documented.

### ISSUE THREAD

**Issue by iirelu** [GoodBoyDigital/pixi.js#515]
[The documentation on SpriteSheetLoader](http://www.goodboydigital.com/pixijs/docs/classes/SpriteSheetLoader.html) reads like an advertisement and doesn't give any examples or explanation as to what the JSON format looks like.

I don't want to use a freeware program for creating sprite sheets and would prefer to just do it by hand, but I can't find any documentation on how to do that.

**Comment by englercj** [comment]
Loader works differently now (in v3), you can do any format you want using proper middleware. The one we ship with is specific to TexturePacker but feel free to write you own.
