### ISSUE TITLE
Text Returning Incorrect Sizes

### ISSUE THREAD

**Issue by MikkoH** [GoodBoyDigital/pixi.js#530]
So we're just having some issues with Text returning incorrect values for width and height on our site.

From everything I can see ```ctx.measureText``` is returning incorrect values (For us this could be even 20px).

I'm going to try to write some tests to see if writing a div and reading its width and height is better. Like ```determineFontHeight``` in Text is doing. (obviously this method is less efficient)

However I noticed a slight issue with ```determineFontHeight``` as I was looking at this.

Currently ```determineFontHeight``` is using ```offsetHeight```:
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/text/Text.js#L221

I believe it should be using clientHeight instead:
https://developer.mozilla.org/en-US/docs/Web/API/Element.clientHeight

offsetHeight includes borders and padding so if you have a general CSS rule for divs where borders or padding is set then your line height will be much larger than it should:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.offsetHeight

Thoughts?

**Comment by GoodBoyDigital** [comment]
Howdy! I just added a padding property to style that should fix these issues if they pop up. The padding won't affect the position of the text itself it will simply give a bit more rendering room.
