### ISSUE TITLE
is it possible to add a tint to BitmapText ?

### ISSUE THREAD

**Issue by alexfoxy** [GoodBoyDigital/pixi.js#542]
Looking for a way to change the colour of bitmap text easily! Is adding a tint to BitmapText possible?

**Comment by meekgeek** [comment]
I'm a little confused.  Version 2.2.7 is using DisplayObjectContainer.  Seems to be broken for me.

 ```javascript
var bitmapFontText = new PIXI.BitmapText("A Vision For Hollywood", {font: "fontname", align: "center"});

bitmapFontText.tint = 0x063699;
```

**Comment by meekgeek** [comment]
On a bit of a side note:  Can this have anything to do with bmGlyph?  I mean, is there a setting I should be aware of?  Took me a while to figure out to publish the fonts in Sparrow format.  Other formats gave me errors.

**Comment by englercj** [comment]
I'll make sure this works for v3.

**Comment by englercj** [comment]
Can you check this in v3, code looks like it should work fine.

**Comment by englercj** [comment]
Confirmed that this does work in v3.
