### ISSUE TITLE
getting hold of a bitmapfont's texture

### ISSUE THREAD

**Issue by weepy** [GoodBoyDigital/pixi.js#550]
hi

I'm trying to draw lots of labels (rectangles plus text) using a bitmap font and ideally I'd like to use part of the bitmap font's texture as a 4x4 white rectangle as the rectangle background.

I'm having difficulty trying to figure out how to do this ? 

Any ideas welcome ^_^

**Comment by GoodBoyDigital** [comment]
Hey @englercj is this possible in v3?

**Comment by englercj** [comment]
Sure it is! You can get the base texture from the asset loader when you load it, or look in `BitmapText.fonts` for your fonts character textures and you can get the base texture from those as well. What is giving you trouble?

**Comment by englercj** [comment]
Closing this since it seems answered.
