### ISSUE TITLE
RenderTexture can't be used as textures for TilingSprite in WebGL only

### ISSUE THREAD

**Issue by photonstorm** [GoodBoyDigital/pixi.js#590]
It dies in the generateTilingTexture function on this part:

`canvasBuffer.context.drawImage(texture.baseTexture.source,`

As there is no baseTexture.source defined for a WebGL RenderTexture. Works fine in canvas.

**Comment by GoodBoyDigital** [comment]
all fixed in v3 :+1:

**Comment by alaa-eddine** [comment]
sorry to ask on a closed issue, but is there any workaround for this in Pixi v2 ? 
I need the compatibility with Pixijs 2
