### ISSUE TITLE
Sprite.touchstart seems not to be working on WP8

### ISSUE THREAD

**Issue by Juljoin** [GoodBoyDigital/pixi.js#592]
Hello,

The touchstart event isn't triggered on Windows Phone devices. The workaround is to use the mousedown event.

I coded a little example for further clarification: www.deuse.fr/touchstart
When using it on my windows phone 8 the # of mousdown increase with each touch.
On android and apple devices the # of touchstart increase with each touch. 

If you need more information, feel free to contact me.

Have a nice day

**Comment by GoodBoyDigital** [comment]
Closing this one as its a year old :) and we just rebuilt the interaction manager for v3! better late than never right! :)

**Comment by Juljoin** [comment]
Thanks for the update :). Keep up the good job!
