### ISSUE TITLE
Graphics.cacheAsBitmap clobbers children

### ISSUE THREAD

**Issue by ryedin** [GoodBoyDigital/pixi.js#602]
TEST Case:

```
var rect1 = new PIXI.Graphics();
rect1.beginFill(0xFF0000);
rect1.drawRect(0, 0, 400, 400);

rect2 = new PIXI.Graphics();
rect2.beginFill(0x000000);
rect2.drawRect(100, 100, 200, 200);

rect1.addChild(rect2);

//add to stage, render, etc.

rect1.cacheAsBitmap = true;
```

Expected Results:
Well, not _exactly_ sure what to expect here, to be honest. At a minimum I was expecting rect1 to be a composite texture (a red rectangle with a smaller black one inside). I understand the process of caching the texture is a destructive one in terms of losing the ability to modify children's transforms discretely from the parent (although some syntactic sugar to detect when a 're-sampling' of the composite texture should be created would be wunderbar).

Actual Results:
A single red rectangle is rendered.

**Comment by GoodBoyDigital** [comment]
This has been fixed in v3. Thanks! :+1:
