### ISSUE TITLE
tap / click events not working on kindle fire

### ISSUE THREAD

**Issue by SebastianNette** [GoodBoyDigital/pixi.js#607]
Hi guys,

I am testing my game atm and noticed that the tap event is never fired on my kindle fire if I also use touchmove. 
My stage has 2 events.

1. mousemove / touchmove
2. click / tap

Is there a problem using tap and touchmove at the same time?
The mouse events do work fine tho.

I'll ask a friend to test my game on their ipad/iphone but I guess there will be the same issue.

On a sidenote: My game runs at 56-59 fps on silk o.O You really did a great job improving pixi.

Events were assigned like this:

      // movement
      this.stage.mousemove = this.stage.touchmove = function(e) {
        if(scope.gameready) {
          if(e.global.x < 0 || e.global.y < 0) {
            return;
          }
          scope.target = e.global.clone();
        }
      };
      
      // attack
      this.stage.click = this.stage.tap = function(e) {
        if(scope.gameready && !scope.game.paused && !scope.pauseButton.active) {
          if(e.global.x > 0 && e.global.y > 0) {
          	scope.target = e.global.clone();
        	scope.pointer.rotation = Math.atan2(scope.hero.sprite.position.y - scope.target.y, scope.hero.sprite.position.x - scope.target.x);
          }
          scope.hero.attack(scope.target, scope.pointer.rotation);
        }
      };

**Comment by GoodBoyDigital** [comment]
howdy, closing this for now due to inactivity...
