### ISSUE TITLE
GraphicsContainer as the alpha mask for another GraphicsContainer?

### ISSUE THREAD

**Issue by ryanmcnz** [GoodBoyDigital/pixi.js#639]
Hi. I've got a feature request, a thirst that shape-based stencil masks cannot quench :)

It would be brilliant if we could use the texture output of a GraphicsContainer on each render step (it could contain anything such as a shape, transparent PNG graphics, a spine animation, etc) as the alpha mask for another GraphicsContainer.

Kinda like this:
targetGraphicsContainer.setDynamicMask( sourceGraphicsContainer );

As a result, each time Pixi.js renders a new frame it would use the output from sourceGraphicsContainer as an alpha mask for the output from targetGraphicsContainer.

I feel that this could be a great feature for Pixi.js.

**Comment by bokanist** [comment]
I need that too, is there any solution to use the alpha from a PNG on a JPG texture ?

**Comment by GoodBoyDigital** [comment]
In v3 a sprite can also be used as a Mask now. :+1:

**Comment by ryanmcnz** [comment]
@GoodBoyDigital Brilliant work! I'm really starting to like the sound of the changes in v3. Looking forward to using it :)
