### ISSUE TITLE
Event informing about DO visual creation & CacheAsBitmap on Cocoon

### ISSUE THREAD

**Issue by cinkonaap** [GoodBoyDigital/pixi.js#662]
Hey,

today I encountered a problem that some functions operating on my visuals were called to early, and it happened to break my program ( without any error ). 

```javascript
this.viewComponent.navigator.show( e.getBody() );
this._currentMediatorName = mediatorClass.NAME;
this.facade.registerMediator( new mediatorClass(undefined, this.viewComponent.navigator.currentView) );
```

Mediator was starting some TweenMax animation on viewComponent too early, so what I did is something that Flash is offering, namely I added at the end of the ( in that case ) DisplayObjectContainer functions : _renderWebGL and _renderCanvas line:

```javascript
this.dispatchEvent( { type : 'FRAME_CONSTRUCTED' } );
```

So I could wait with registering my mediator on that event callback.

I think it should be considered. This won't happen on your PC browser, but it happened to me on Cocoons Android and iOS.

**Comment by GoodBoyDigital** [comment]
as this issue is nearly a year old I think now is a good time to close it.. unless someone objects :D
