### ISSUE TITLE
Improper Cropping with Filters + Trimmed Textures in 1.5.2

### ISSUE THREAD

**Issue by JHawkley** [GoodBoyDigital/pixi.js#679]
I have run into a problem when applying filters to sprites using TexturePacker trimmed sprite sheets.  Many of my sprites end up being improperly cropped after a filter, any filter, is applied.

Take a look at the following screenshots:
http://imgur.com/a/4EYEC

Circled in red, the character's extended hand is cropped out slightly after the filter is applied.  In a few other sprites, the error can be much more pronounced.  The sprite exhibits no odd behavior until a filter is applied.

Any idea if this is a bug or a problem I've introduced through my own code?  This is the first time I have dipped my toe in filters.

**Comment by englercj** [comment]
I think this is fixed in v3, confirm @GoodBoyDigital?

**Comment by GoodBoyDigital** [comment]
Pretty sure this is all good now in v3. Closing for now.. thanks for sharing @JHawkley !
