### ISSUE TITLE
Removing movieclip inside onComplete callback

### ISSUE THREAD

**Issue by yisk** [GoodBoyDigital/pixi.js#712]
A bug looks like https://github.com/GoodBoyDigital/pixi.js/issues/235, but not sure because I dont know coffeescript.

When I write something like this
```javascript
stage.addChild(movieclip);
movieclip.onComplete = function(){ stage.removeChild(this) }
```
I can get an error ```Cannot read property 'updateTransform' of undefined```
The problem is caused by changing length of ```stage.children``` in this cycle
```
PIXI.Stage.prototype.updateTransform = function() {
    this.worldAlpha = 1;
    for(var i=0,j=this.children.length; i<j; i++) {
        this.children[i].updateTransform();
    }
...
```
When PIXI calls ```updateTransform()``` of my "completed" movieclip, ```movieclip.onComplete()``` fires immediately and changes ```stage.children``` array. To close the issue, you should rethink this algorithm.
For now I use this workaround, just to pull out array changing from cycle.
```
movieclip.onComplete = function() {
    setTimeout(function(t) {
        stage.removeChild(t);
    }, 15, this);
};
```

**Comment by GoodBoyDigital** [comment]
This should no longer be an issue in v3. cheers!
