### ISSUE TITLE
Graphical glitches when using a RenderTexture with a TilingSprite

### ISSUE THREAD

**Issue by 4ian** [GoodBoyDigital/pixi.js#741]
Hi,

When rendering a TilingSprite with a RenderTexture, I encounter a glitch: (A bit like if the texture wasn't set to be repeated)  ![glitch](https://cloud.githubusercontent.com/assets/1280130/2915761/df8b415e-d6b1-11e3-8478-8bafc3e3515a.png)
When using Google Chrome, only the green window background is shown.

To reproduce the issue, open index.html in folder "example 9 - Tiling Texture". After line 

    var texture = PIXI.Texture.fromImage("p2.jpeg");

Add these lines:

	// use an intermediate render texture (could be used to resize the texture to a power of 2 for example)
	var renderTexture = new PIXI.RenderTexture(256, 256);
	var doc = new PIXI.DisplayObjectContainer();
	var sprite = new PIXI.Sprite(texture);
	doc.addChild(sprite);
	renderTexture.render(doc);

And finally change 

	var tilingSprite = new PIXI.TilingSprite(texture, window.innerWidth, window.innerHeight);

to

	var tilingSprite = new PIXI.TilingSprite(renderTexture, window.innerWidth, window.innerHeight);

(Note that this step is used to use the renderTexture as the texture for the TilingSprite, but strangely in Firefox the glitch is appearing even with texture instead of renderTexture).

I successfully used TilingSprite with previous versions of Pixi.js so I think that the problem must be somewhere in the library and not in the way I'm using TilingSprite. :)
The issue occurs with both master and dev branch as of today, at least with Firefox 30 (see the attached screenshot) and Chrome 34 (Only the background is rendered) (both webGL enabled).

**Comment by GoodBoyDigital** [comment]
should be all gravy in v3. :+1:

**Comment by 4ian** [comment]
:+1:
