### ISSUE TITLE
TilingSprite doesn't work properly with Texture from .generateTexture()

### ISSUE THREAD

**Issue by FNevesFMQ** [GoodBoyDigital/pixi.js#749]
Hello,

I was trying to use a generated texture on a TilingSprite, but when I add it to stage this error pops up:

_Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': No function was found that matched the signature provided._

About code, I'm creating sprites from my single images (dimensions: 144x137) and then adding it to a container (this.spritesContainer). When finished, that container dimensions are 144x685 and then I just defined:

```javascript
this.batchedTexture = this.spritesContainer.generateTexture();
this.finalSprite = new PIXI.TilingSprite(this.batchedTexture, 144, 411);
this.addChild(this.finalSprite);
```

I also tried using PIXI.RenderTexture instead but the result was the same.
Any suggestions if this a real issue or my bad?

Regards.

**Comment by GoodBoyDigital** [comment]
Hey all! This should work like a champ in v3 :+1:
