### ISSUE TITLE
Filters act as though their container is the entire stage

### ISSUE THREAD

**Issue by ryanmcnz** [GoodBoyDigital/pixi.js#768]
For example if I apply a DisplacementFilter or a AlphaMaskFilter to a DisplayObjectContainer, I'd expect the filter output to match where that container is on the stage.

A scenario of where this could be used is a DisplayObjectContainer with a wobbly jelly monster in it, at a position of 50,50. This container would use the DisplacementFilter, but for the correct visuals the filter output should be matching the containers position.

What actually happens is, if a container has a particular position or scale...neither of these seem to effect the filter:
- The filter remains at a position of 0,0. So if you are trying to have a DisplayObjectContainer at a position of 50,50 with the filter appearing at that same position...the filter is unable to match the position of the container it is applied to.
- The filter remains at a scaled size of 1,1. So if you are trying to have a DisplayObjectContainer with a scaled size of 2,2 (200%) with the filter using the same scaling...the filter is unable to match the scaled size of the container it is applied to.

This seems rather limiting.
I noticed that example 15 (the filter example) bypasses this issue by default because the rendered content is stretched to the window size.

How this came about:
I was investigating #639, specifically the fact that Pixi.js already contains a filter called "AlphaMaskFilter", which seemed like it could achieve what I was attempting for that issue.
This filter is not in the filter examples and the documentation for it is incorrect...it talks about the DisplacementFilter instead.

Any input on this is helpful as it will be useful for understanding what intentions I should have when using filters :)

**Comment by englercj** [comment]
We are adding local-space as an option for filters in v3.

**Comment by ryanmcnz** [comment]
@englercj Sounds good, looking forward to it! :)

**Comment by GoodBoyDigital** [comment]
v3 now uses a sprite as a displacement map source. Works much more intuitively now! enjoy :+1:
