### ISSUE TITLE
Accessing json loaded via AssetLoader

### ISSUE THREAD

**Issue by beeglebug** [GoodBoyDigital/pixi.js#776]
I would like to load multiple JSON files with the same assetloader I am using for my images, but there doesn't seem to be a way of getting at any of the json if it isn't a spine animation or texture atlas.

Is there any reason why we can't have a PIXI.JsonCache to match the AnimCache and TextureCache?

**Comment by englercj** [comment]
Loaders were rewritten in v3, but this was fixed in v2 as well.
