### ISSUE TITLE
touchmove not called until last added object is touched and moved

### ISSUE THREAD

**Issue by UncleAcid** [GoodBoyDigital/pixi.js#785]
I have an object that contains a Sprite and I set that sprite to be interactive and set all the interaction callbacks however when I add a few of them to my scene I must touch the last added one before the other's will send the touchmove event (touchstart, and touched are still being called).

The mouse events are called fine when played in a browser, this issue arises when I play on my iOS devices.

* Not included here is the positioning and adding to the screen code, it is being added and positioned fine; I only included the relevant interaction code*

MySprite 

    NameSpace.MySprite = function()
    {
        this.selected = this.selected.bind(this);
        this.dragged = this.dragged.bind(this);
        this.deselected = this.deselected.bind(this);

        this.sprite = PIXI.Sprite.fromFrame("sprite01.png");
        this.sprite.interactive = true;
        this.sprite.mousedown = this.sprite.touchstart = this.selected;
        this.sprite.mousemove = this.sprite.touchmove = this.dragged;
        this.sprite.mouseup = this.sprite.mouseupoutside = this.sprite.touchendoutside =     this.sprite.touchend = this.deselected;
    }
    NameSpace.MySprite.prototype.constructor = NameSpace.MySprite;

    NameSpace.MySprite.prototype.selected = function(data)
    {
        this.data = data;
        this.dragging = true;
    };
    NameSpace.MySprite.prototype.dragged = function()
    {
        if(this.dragging)
        {
            this.destinationX = this.data.getLocalPosition(this.container).x;
        }
    };
    NameSpace.MySprite.prototype.deselected = function()
    {
        this.destinationX = this.sprite.position.x;
        this.dragging = false;
        this.data = null;
    };

Create MySprites

    this.sprites = [];

    var sprite = null;
    for(var i = 0, spriteCount = 5; i < spriteCount; i++)
    {
        sprite = new NameSpace.MySprite();
        this.sprites.push(sprite);
    }

**Comment by GoodBoyDigital** [comment]
closing this one as pretty sure this issue has been resolved in v3. let me know if i'm wrong :+1:  cheers all!
