### ISSUE TITLE
Spine Events not supported

### ISSUE THREAD

**Issue by AndreiBarsan** [GoodBoyDigital/pixi.js#787]
I have created some animations which make use of Spine events. It's useful to e.g. add an event whenever a character's foot touches the ground, in order to precisely time stuff like dust effects and footstep sound effects. Events can help elegantly solve a lot of things which would otherwise require nasty hacks.

However, looking over the source code, I see no evidence of spine event timelines existing in pixi's Spine. The official runtime (https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-js/spine.js) **does** support them.

**Comment by englercj** [comment]
Tracking this at pixijs/pixi-spine#15.
