### ISSUE TITLE
Current worldX and worldY properties 

### ISSUE THREAD

**Issue by kittykatattack** [GoodBoyDigital/pixi.js#796]
This is a feature request :)

For accurate collision detection and reaction between sprites in different containers, it's important to know their `worldX` and `worldY` positions.

The current version of Pixi, 1.5.3, lets you access these values like this:
```
worldX = sprite.worldTransform.tx
worldY = sprite.worldTransform.ty
```
But there's a problem with these values. They're calculated each frame by `updateTransform`. They're not calculated when the sprite's x and y position changes. That means if you use `worldTransform.tx` and `worldTransform.tx` for collision detection and reaction, you will be using the values from the previous frame.

I'd like to request access to `worldX` and `worldY` values that are accurate as soon as the sprite's x and y values change. 
 
If there's a way to access these values in Pixi currently, please let me know :)

**Comment by GoodBoyDigital** [comment]
Hi there! This has now been added to v3. ```getGlobalPosition``` will return the world position of the displayObject. enjoy! :+1:

**Comment by kittykatattack** [comment]
Thanks again for adding this, guys, it's just what I needed!!
