### ISSUE TITLE
`setTextures` for MovieClips

### ISSUE THREAD

**Issue by kittykatattack** [GoodBoyDigital/pixi.js#823]
Hello :)

I noticed that there's no `setTextures` method for MovieClips that's equivalent to `setTexture` for ordinary sprites.
Should `setTextures` be added?

At the moment I'm using code like this to change a MovieClip's textures:

    movieClipSprite.textures = newArrayOfTextures

This works with the CanvasRenderer, but the WebGLRender is not picking up the change.
Could that be because texture changes need to notify the WebGL rendering engine?
Would a `setTextures` method help in this case?

**Comment by GoodBoyDigital** [comment]
done and done! this has now been added to v3. Thanks for the suggestion @kittykatattack :+1:
