### ISSUE TITLE
Background of canvas is black when white is specified in firefox 30.0

### ISSUE THREAD

**Issue by EricLesch** [GoodBoyDigital/pixi.js#826]
Codepen: http://codepen.io/anon/pen/Lxzrh?editors=101

Screenshot: 
![screenshot 13](https://cloud.githubusercontent.com/assets/1515192/3426125/415d7230-001a-11e4-8f71-8661612aa561.png)

Only broken for the WebGL Renderer. The Canvas Renderer works fine.

**Comment by GoodBoyDigital** [comment]
Closing this one as it seems like it may be a specific device/browser issue rather than pixi.
