### ISSUE TITLE
Setting hitArea requires sprite.texture.width

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#829]
Summary: Setting hitArea requires eg sprite.texture.width; perhaps expecting dimensions of the (potentially scaled) sprite would be more intuitive.

(Just an API detail, not a bug report.)
(Pixi JS version 1.5.3)
The context is at http://goo.gl/l0TCus .

This code yields the correctly sized clickable area:

    this.hitArea = new PIXI.Circle(0, 0, (this.texture.width / 2));

The below code yields a clickable area that's smaller than the rendered sprite (perhaps because the sprite is scaled 100px -> 60px).

    this.hitArea = new PIXI.Circle(0, 0, this.width / 2);

Should this latter code work? I think it would be more intuitive for the user if Pixi would expect half the width of the (potentially scaled) sprite instead of expecting half the width of the texture itself.
Or, instead of breaking backwards-compatibility, some info and example code could be added to the docs.

**Comment by GoodBoyDigital** [comment]
Hi @tobireif, as the hit area is transformed along with the sprite this is expected behavior. cheers!

**Comment by tobireif** [comment]
Hi @GoodBoyDigital , thanks for the explanation!
