### ISSUE TITLE
Left click triggers .click handler, but right-click does so as well.

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#830]
I assigned an event handler using .click . When I left-click on the sprite it works as intended. But when I right-click on it, the same action happens.
(Pixi JS version 1.5.3, Firefox, Mac OS. In Chrome, two right-clicks in two different locations inside the hitArea are required.)

(A related Pixi JS example: http://www.goodboydigital.com/pixijs/examples/6/ . Left-click -> console "CLICK!", and ditto for right-click.)

Instead, I'd expect the action to not happen on right-click (as is standard in HTML). In addition, Pixi could provide something like .rightClick  -  eg .click for catching leftClick, plus .middleClick, and .rightClick.

**Comment by GoodBoyDigital** [comment]
Hi @tobireif !

v3 should now have ```rightclick``` and ```click``` events for all you clicky needs. cheers! :+1:

**Comment by tobireif** [comment]
Thanks @GoodBoyDigital ! ⊙‿⊙

In a Pixi web app which uses Pixi 2, it behaves like this:
    left-click on a hitArea -> click/touchstart event.
    right-click on a hitArea -> no click/touchstart event, just the browser's
      standard right-click menu.
I hope that this will still work as above in Pixi 3.

The example
http://www.goodboydigital.com/pixijs/examples/6/
still exhibits the behavior I described in the report:
Left-click -> console "CLICK!", and ditto for right-click. If that's not the intended behavior, perhaps example #6 could be fixed (so that it only reacts only to left-click / touch not right-click).
