### ISSUE TITLE
context.globalCompositeOperation not reset properly

### ISSUE THREAD

**Issue by Nonofr** [GoodBoyDigital/pixi.js#837]
When using RenderTexture and blendModes with canvasRenderer, context.globalCompositeOperation is not reset properly in some cases, causing very big glitches. For example, in PIXI.Sprite.prototype._renderCanvas: 

    if(this.blendMode !== renderSession.currentBlendMode)
    {
        renderSession.currentBlendMode = this.blendMode;
        context.globalCompositeOperation = PIXI.blendModesCanvas[renderSession.currentBlendMode];
    }

this.blendMode equals renderSession.currentBlendMode but  context.globalCompositeOperation does NOT equals PIXI.blendModesCanvas[renderSession.currentBlendMode];

**Comment by GoodBoyDigital** [comment]
pretty sure this has been licked in v3. Closing for now. Thanks @Nonofr :+1:
