### ISSUE TITLE
A bug in the interactive

### ISSUE THREAD

**Issue by korner-brazers** [GoodBoyDigital/pixi.js#860]
Noticed a bug when using interactivity and multiple scenes, if you create a few scenes and render switch on one of them stops working it interactive.

In earlier versions, it was okay, but now stopped working.

Here is a good example:http://bumbird.com/pixi/index.html

**Comment by englercj** [comment]
Stage is removed in v3 and interaction manager is being rewritten (decoupled from renderer). Closing this now.
