### ISSUE TITLE
Add ability to cache spritesheet frame IDs as full url-s

### ISSUE THREAD

**Issue by vpmedia** [GoodBoyDigital/pixi.js#861]
Referenced ticket:
* https://github.com/GoodBoyDigital/pixi.js/issues/312

... and a feature request:
* http://www.html5gamedevs.com/topic/5445-best-way-to-load-texture-atlases-with-the-same-frame-names-possible-pr/

Method needed to patch in file **src/pixi/loaders/JsonLoader.js**:

> PIXI.JsonLoader.prototype.onJSONLoaded = function () {

Relevant modified code part:

    var cacheId;
    for (var i in frameData)
    {
        if(PIXI.IS_USE_FULL_QUALIFIED_FRAME_NAMES) {
            cacheId = textureUrl + "/" + i;
        } else {
            cacheId = i;
        }
        var rect = frameData[i].frame;
        console.warn("Caching Frame: " + cacheId + ": " + rect);

        if (rect)
        {
            PIXI.TextureCache[cacheId] = new PIXI.Texture(this.texture, {
                x: rect.x,
                y: rect.y,
                width: rect.w,
                height: rect.h
            });

            PIXI.TextureCache[cacheId].crop = new PIXI.Rectangle(rect.x, rect.y, rect.w, rect.h);

            //  Check to see if the sprite is trimmed
            if (frameData[i].trimmed)
            {
                var actualSize = frameData[i].sourceSize;
                var realSize = frameData[i].spriteSourceSize;
                PIXI.TextureCache[cacheId].trim = new PIXI.Rectangle(realSize.x, realSize.y, actualSize.w, actualSize.h);
            }
        }
    }

Please take a look at the new 'PIXI.IS_USE_FULL_QUALIFIED_FRAME_NAMES' flag.
I'm not entirely sure that this is the right way because i don't have reviewed the whole source code yet, please give some feedback.

Cheers!

**Comment by englercj** [comment]
This happens in v3.
