### ISSUE TITLE
Smooth vs slightly jagged text rendering

### ISSUE THREAD

**Issue by tobireif** [GoodBoyDigital/pixi.js#886]
In my web app I'm getting nicely anti-aliased text rendering.
(It looks slightly blurred / out of focus, but that's better than jagged, at least for me.)

When I add a drop shadow
```
  dropShadow: true,
  dropShadowColor: "#00ff00",
  dropShadowAngle: Math.PI/4,
  dropShadowDistance: 3
```
the text becomes slightly jagged.

Some info: Firefox, Mac OS, text.anchor = new PIXI.Point(0.5, 0.5), embedded font. I saved two code snapshots, one with smooth text, and one which has slightly jagged text (where only the above text shadow code has been added). I can send you the two zips, just drop me a line (my email address is at http://tobireif.com/ ).

When I tried to reproduce the behaviour in a small example, I noticed that in the cases I tested there, setting the anchor of the text makes the rendering smooth. The codepen: http://codepen.io/anon/pen/mwsuF .

It would be great if the text would always be rendered smoothly. (eg there could be an option which applies to just text rendering.)

**Comment by GoodBoyDigital** [comment]
v3 lets you round pixels on a sprite. should fix this issue! cheers! :+1:

**Comment by tobireif** [comment]
I think I want the "smooth" rendering (not crisp), so I'd make sure to avoid round/integer pixel values, I guess?
