### ISSUE TITLE
blurring roundedRects doesn't work

### ISSUE THREAD

**Issue by NikkiKoole** [GoodBoyDigital/pixi.js#895]
when I draw some normal rectangles and blur them like 
```
graphics = new PIXI.Graphics()
graphics.lineStyle(3, 0xffffff, 1.0)
graphics.beginFill(0x000001, 1)
graphics.drawRect(200,200,100,100)
graphics.drawRect(200,350,100,100)
graphics.drawRect(200,500,100,100)
graphics.drawRect(200,650,100,100)
graphics.endFill()
blurFilter = new PIXI.BlurFilter()
graphics.filters = [blurFilter]
stage.addChild(graphics)
```
I get 
![screen shot 2014-07-28 at 5 02 05 pm](https://cloud.githubusercontent.com/assets/453055/3722244/28c24944-1668-11e4-9ead-e70270b7ab0a.png)

when I do the same with a couple of roundedRectangles like
```
graphics = new PIXI.Graphics()

graphics.lineStyle(3, 0xffffff, 1.0)
graphics.beginFill(0x000001, 1)

graphics.drawRoundedRect(200,200,100,100,40)
graphics.drawRoundedRect(200,350,100,100,40)
graphics.drawRoundedRect(200,500,100,100,40)
graphics.drawRoundedRect(200,650,100,100,40)

graphics.endFill()


blurFilter = new PIXI.BlurFilter()
graphics.filters = [blurFilter]
stage.addChild(graphics)
```
I get 
![screen shot 2014-07-28 at 5 03 37 pm](https://cloud.githubusercontent.com/assets/453055/3722273/629343bc-1668-11e4-851a-f7e4d667e8c0.png)

when I don't apply the filter these roundedRects are drawn like
![screen shot 2014-07-28 at 5 04 20 pm](https://cloud.githubusercontent.com/assets/453055/3722282/796f5f08-1668-11e4-8232-487e1ed8c76d.png)

**Comment by GoodBoyDigital** [comment]
pretty sure this should be fine in v3. closing for now! Thanks for sharing @NikkiKoole :+1:
