### ISSUE TITLE
BaseTexture source.src assignment ordering

### ISSUE THREAD

**Issue by serprex** [GoodBoyDigital/pixi.js#918]
https://github.com/GoodBoyDigital/pixi.js/blob/master/src/pixi/textures/BaseTexture.js#L239 (modified line reference to match changed source)

The src of BaseTexture's source should not be set until after the constructor is called. This will ensure onerror is fired & should allow simplifying onload handling. Is there a reason src is set beforehand?

If this change is welcome I'm willing to make a pull request after doing it myself

**Comment by serprex** [comment]
Note this was handled perhaps in a better way through

https://github.com/GoodBoyDigital/pixi.js/pull/1193

& the need to move src assignment after the constructor is removed in that case

**Comment by englercj** [comment]
#1193 was merged as well, as was this change. So it should be double good :D
