### ISSUE TITLE
Touch move only working when touch start event handler present

### ISSUE THREAD

**Issue by GillesVermeulen** [GoodBoyDigital/pixi.js#933]
I recently updated one of our games to Pixi v1.6.1. In one of its scenes, the player has to move the cursor to guide the character. We also support touch, so touchmove was used too. (The scene I'm talking about: http://kaatje.ketnet.be/html/Schapenherder (-> still old Pixi version))

After the update, the touchmove event was not firing anymore. Upon examining the Pixi source code, it became clear that touchmove events are no longer firing for objects that do not have a touchstart listener.

```javascript
if(item.touchmove && item.__touchData && item.__touchData[touchEvent.identifier]) item.touchmove(touchData);
```
(from InteractionManager.js, line 607 in master version)

___item.__touchData___ is only defined on touchstart. So if there is no touchstart event -> no __touchData -> no touchmove event firing.

After adding a trivial touchstart listener, the problem was fixed.

Is there a way to prevent the need for a touchstart listener? At least this should be made clearer in the documentation.

**Comment by aholla** [comment]
I was just coming here to report this :)

**Comment by englercj** [comment]
I am pretty sure this is fixed in v3 interactions, but adding @GoodBoyDigital since he worked with it most recently.

**Comment by GoodBoyDigital** [comment]
fixed in v3! woop! :+1:
