### ISSUE TITLE
Mouse/Touch Event bug with multiple stages one renderer

### ISSUE THREAD

**Issue by wellcaffeinated** [GoodBoyDigital/pixi.js#950]
I've found that stages lose interaction management when several are used with one renderer.

Steps to reproduce:
1. Create a renderer
2. Create a few stages with interaction enabled
3. Add event callbacks to the stages
4. Render first stage (eg with anim frame)
5. use events
6. Render next stage 
7. use events
8. Render first stage again... events won't work

Here is a js fiddle demonstrating the bug: http://jsfiddle.net/wellcaffeinated/27fsywLn/

I'd love any advice for a workaround in the meantime... it's delaying my progress on a project... any help would be appreciated :)

**Comment by GoodBoyDigital** [comment]
Stage is outta here for v3. This issue should no longer persist. Cheers all! :+1:
