### ISSUE TITLE
How to deal with typescript definitions? 

### ISSUE THREAD

**Issue by clark-stevenson** [GoodBoyDigital/pixi.js#958]
@GoodBoyDigital 
@photonstorm 

After cobbling together PIXI definitions for phaser, and fighting against outdated, or partial updates from other sources. I worked on a definition for a while which becomes the basis of the phaser.d.ts file. It is upto date as of lastnight's dev. 

https://github.com/clark-stevenson/PIXI.d.ts

I have not made a pull request, because I do not know if you want it a part of the official project and if you do, where does it go?

But this leads me to having problems with phaser.  Phaser has its own definitions but it is a collection of external functionality.  Lewsters ISO plugin definition should not be maintained by Phaser but its going to have to be if people want it (I seen a couple of requests).  Also people will make a pull request for /phaser/pixi.d.ts which needs to end up back in /pixi/pixi.d.ts and when you consider dev/ master/ builds, this is a nightmare. There is even a p2.d.ts brewing.

So I wondered, should Rich just make a /phaser-ts/ repo or something, and we can throw them all in there?

**Comment by englercj** [comment]
Honestly I don't think the definition should live in the core repo *unless* it can be generated at build time. I feel like there is definitely a space for a tool that looks uses esprima/jsdoc parser and generates a ts definition.

**Comment by clark-stevenson** [comment]
Sure. 

For anyone else, phaser maintains the most up-to-date version of the definitions for pixi at this current time
https://github.com/photonstorm/phaser/tree/dev/typescript

@photonstorm 

Just a quick question. On recent forum posts I am getting the impression that pixi may be branching out in a way that is incompatible with phaser 2? In this case, I am not sure when I should stop maintaining pixi and start maintaining phaser's commit history of pixi instead.

**Comment by photonstorm** [comment]
@clark-stevenson let's worry about that when it happens. I'll try to avoid it for as long as possible.

**Comment by Nimrodxx** [comment]
Clearly there are TypeScript definition files for pixi.js but they just can't be found in this repo. The definition files in https://github.com/photonstorm/phaser/tree/master/typescript seem up to date so please refer to that repo in the README.MD. 

Furthermore the definition files should be pushed to the definitely typed repo(https://github.com/borisyankov/DefinitelyTyped), which is a collection definition files of the most common used libraries. I'll ask if they want to push the files to that global repo.

**Comment by clark-stevenson** [comment]
It is my opinion that we have a solid pixi.d.ts in spite of DT and not because of it.  I found it impossible to maintain both pixi and phaser dev branches while fighting against piecemeal updates from DT.  So we ended up with our own.

Pixi.d.ts here just is a nice bonus for non Phaser devs.  Rather than something which fights for compatibility with Phaser.d.ts which happened all the time when I tried to use community versions.

I think it is better to be where it is but my needs are no more important than @Nimrodxx 

Pixi3 and Phaser3 is a different ball park. No idea where it will go. Rich gets spammed with d.ts file updates and he does not really need it.  Neither does the pixi dudes.  So maybe the best place for these IS DT but ultimately I will be maintain my own until someone can make a automated build version from JSDoc :P

**Comment by GoodBoyDigital** [comment]
Hey @clark-stevenson !  Thanks for all you have done maintaining a phaser / pixi typescript definition. You have made them accessible to all the type scripters out there which is really cool :+1: 

If you do fancy maintaining a pixi typescript definition file we could look to set up a new repo in here. 
https://github.com/pixijs?

It would be the perfect home for it. Let me know and we can get something set up and add you as a collaborator. Many thanks and keep up the great work!

**Comment by englercj** [comment]
@GoodBoyDigital Good point, a pixi.d.ts repo under the org would be perfect for that if @clark-stevenson is interested in maintaining it.

**Comment by clark-stevenson** [comment]
@GoodBoyDigital  No problem at all! The framework is really awesome so thank you! :+1: 

Over the coming weeks, I will be working through the examples for pixi3 and getting that accessibility problem sorted, as soon as I have something decent I will hit this ticket again and we can take it from there.

**Comment by GoodBoyDigital** [comment]
wonderful! nice one @clark-stevenson :+1:

**Comment by Nimrodxx** [comment]
Thanks guys this will help a lot of TypeScript developers :+1:

**Comment by englercj** [comment]
Just setup this: https://github.com/pixijs/pixi-typescript

Which has the v2 definitions from phaser pulled into it. There is a v2.x branch we can continue to maintain the defs on, and we can update master with the new v3 definitions when ready.

**Comment by adireddy** [comment]
@englercj @GoodBoyDigital 
Guys, Totally off topic but I would love to transfer my Haxe externs to pixijs organisation if you are ok with it as long as I have  full rights to keep it up to date.
https://github.com/adireddy/haxe-pixi
Let me know. Thanks.

**Comment by englercj** [comment]
Sure, transfer ownership and I'll setup the permissions.

**Comment by adireddy** [comment]
It says I need admin rights to pixijs to transfer.

**Comment by GoodBoyDigital** [comment]
@adireddy nice man! well up for this :+1:

**Comment by adireddy** [comment]
Transfer done :+1:

**Comment by clark-stevenson** [comment]
@englercj thank you! :+1:

**Comment by englercj** [comment]
Repos, teams, and permissions are setup. Invites to the teams are sent.

Thanks all!

**Comment by GoodBoyDigital** [comment]
nice one @englercj!

**Comment by adireddy** [comment]
Travis CI says I need admin rights to enable pixi-haxe repo https://travis-ci.org/profile/pixijs.

Is there any way to give me full admin rights only to that repo?

**Comment by englercj** [comment]
Done.

**Comment by adireddy** [comment]
Works now :+1: Thx.
