### ISSUE TITLE
WebGLRenderer.destroy() blows up in Firefox

### ISSUE THREAD

**Issue by EricLesch** [GoodBoyDigital/pixi.js#961]
This line in WebGLRenderer.destroy blows up in Firefox

this.view.removeEventListener('webglcontextlost', this.contextLost);

this.contextLost seems to have been set to false after having been previously bound to the event as a function, making it a boolean so Firefox throws the error:

"Argument 2 of EventTarget.removeEventListener is not an object."

Also, this seems like it would create an observer leak in other browsers even though they don't complain since the event is never properly unbound.

Let me know if you want a fiddle to duplicate that for you.

Thanks,
Eric

**Comment by englercj** [comment]
This should be fixed now, those functions have been rewritten.
