### ISSUE TITLE
WebGL line rendering problem with small values

### ISSUE THREAD

**Issue by gaelduplessix** [GoodBoyDigital/pixi.js#975]
WebGL renderer fails to render a path with small coordinates.

http://jsfiddle.net/LyDx9/6/

In this example I render a simple path, then the same path scaled down 10 times (in a scaled-up container so it appears the same size). The scaled version is destroyed when rendered with WebGL renderer. (the vertical displacement is due to issue #711).

I can't explain exactly what causes the bug, indeed when you change the scaling factor to 9 for example, the path is rendered correctly, which seems pretty weird...

**Comment by gaelduplessix** [comment]
Any thoughts on this ?

**Comment by englercj** [comment]
Fixed by #975.
