### ISSUE TITLE
TilingSprite Jittering in Firefox

### ISSUE THREAD

**Issue by sumeetkpatel** [GoodBoyDigital/pixi.js#977]
Using a large TilingSprite while scaling and pivoting, jitter(?) is observed and the texture is often improperly aligned.

Appears to affect CanvasRender only, and mainly Firefox.
More notes in the html source.

The example below uses the system clock to animate so should behave the same in any browser.
https://collusionapp.com/tests/tiling/tile.html

![recording](https://cloud.githubusercontent.com/assets/4479653/4329071/870a6a9e-3f90-11e4-8597-751866d9800e.gif)
Pictured: Looking at the bottom right of the container, Chrome-Good (left), Firefox-Bad (right).

**Comment by englercj** [comment]
I think this has to do with the rounding is TilingSprite scaling. Closing to track there in #1302

**Comment by sumeetkpatel** [comment]
Could you elaborate?

**Comment by englercj** [comment]
Sorry, linked the wrong issue. I meant #1295 seems like the same issue.
