### ISSUE TITLE
Stage interactionManagers create a referential loop when renderer is destroyed, preventing GC of the view.

### ISSUE THREAD

**Issue by agamemnus** [GoodBoyDigital/pixi.js#986]
Problem:
The interactionManager is bound with a renderer's view, so it is insufficient to just allow Javascript to garbage collect. A self-referencing loop is formed which won't garbage-collect views (and stages?) unless .interactionManager.removeEvents () is called on the stage beforehand.

Solution:
The interactionManager's target should be removed when a renderer's destroy() is called.

**Comment by englercj** [comment]
Stage was removed in v3, and interaction manager decoupled.
